package com.instagram.api.schemas;

import X.0oU;
import X.DbY;
import X.Dbb;
import X.SWT;
import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.catalyst.modules.netinfo.NetInfoModule;
import java.util.LinkedHashMap;
import java.util.Map;

public enum BillingWizardName implements Parcelable {
    UNRECOGNIZED("BillingWizardName_unspecified"),
    ACTIVATE_AND_VERIFY_CREDIT_CARD("ACTIVATE_AND_VERIFY_CREDIT_CARD"),
    ACTIVATE_CARD_CREDENTIAL_SUB_CONFIG("ACTIVATE_CARD_CREDENTIAL_SUB_CONFIG"),
    ACTIVATE_CREDIT_CARD("ACTIVATE_CREDIT_CARD"),
    ACTIVATE_CREDIT_CARD_SUB_CONFIG("ACTIVATE_CREDIT_CARD_SUB_CONFIG"),
    ADD_BM_PAYMENT_METHOD("ADD_BM_PAYMENT_METHOD"),
    ADD_COUPON("ADD_COUPON"),
    ADD_COUPON_SUB_CONFIG("ADD_COUPON_SUB_CONFIG"),
    ADD_CREDIT_CARD("ADD_CREDIT_CARD"),
    ADD_CREDIT_CARD_SUB("ADD_CREDIT_CARD_SUB"),
    ADD_FUNDS("ADD_FUNDS"),
    ADD_PM("ADD_PM"),
    ADD_PM_BM("ADD_PM_BM"),
    ADD_PM_NUX("ADD_PM_NUX"),
    ADD_PM_PUX("ADD_PM_PUX"),
    ADD_PM_WABA("ADD_PM_WABA"),
    ADD_PM_WITH_ACCOUNT_SELECTION("ADD_PM_WITH_ACCOUNT_SELECTION"),
    ADD_RECURRING_LPM_SUB_CONFIG("ADD_RECURRING_LPM_SUB_CONFIG"),
    ASSIGN_AD_CREDITS("ASSIGN_AD_CREDITS"),
    ASSIGN_AD_CREDITS_SUB_CONFIG("ASSIGN_AD_CREDITS_SUB_CONFIG"),
    ASSIGN_SHARED_STORED_BALANCE_TO_ACCOUNT("ASSIGN_SHARED_STORED_BALANCE_TO_ACCOUNT"),
    ASSIGN_SHARED_STORED_BALANCE_TO_ACCOUNT_SUB_CONFIG("ASSIGN_SHARED_STORED_BALANCE_TO_ACCOUNT_SUB_CONFIG"),
    AUTO("AUTO"),
    AUTO_RELOAD("AUTO_RELOAD"),
    BUSINESS_INFO_SUB("BUSINESS_INFO_SUB"),
    BUSINESS_VERIFICATION("BUSINESS_VERIFICATION"),
    BUSINESS_VERIFICATION_WITH_TAX("BUSINESS_VERIFICATION_WITH_TAX"),
    BV_SUB_CONFIG("BV_SUB_CONFIG"),
    BV_WITH_TAX_SUB_CONFIG("BV_WITH_TAX_SUB_CONFIG"),
    CHANGE_COUNTRY_CURRENCY("CHANGE_COUNTRY_CURRENCY"),
    CHECK_AND_VERIFY_RISK_RESTRICTIONS("CHECK_AND_VERIFY_RISK_RESTRICTIONS"),
    COLLECT_ACCOUNT_INFO("COLLECT_ACCOUNT_INFO"),
    CREATE_BM_AD_ACCOUNT("CREATE_BM_AD_ACCOUNT"),
    CREATE_SHARED_STORED_BALANCE("CREATE_SHARED_STORED_BALANCE"),
    CREATE_WHATSAPP_BUSINESS_ACCOUNT("CREATE_WHATSAPP_BUSINESS_ACCOUNT"),
    DEACTIVATE_AD_ACCOUNT("DEACTIVATE_AD_ACCOUNT"),
    DELETE_MI_SHARING("DELETE_MI_SHARING"),
    DIRECT_DEBIT("DIRECT_DEBIT"),
    DOWNLOAD_PROFORMA("DOWNLOAD_PROFORMA"),
    EDIT_CREDIT_CARD("EDIT_CREDIT_CARD"),
    EDIT_MI_SHARING("EDIT_MI_SHARING"),
    EDIT_PRIMARY_PM("EDIT_PRIMARY_PM"),
    ENTER_SECURE_BILLING("ENTER_SECURE_BILLING"),
    E_MANDATE_MIGRATION("E_MANDATE_MIGRATION"),
    FINANCIAL_DOCUMENT_UPLOAD("FINANCIAL_DOCUMENT_UPLOAD"),
    FLEX_AUTO_CHARGE("FLEX_AUTO_CHARGE"),
    FLEX_AUTO_ENROLL_WELCOME("FLEX_AUTO_ENROLL_WELCOME"),
    FLEX_BILLING_ONBOARDING("FLEX_BILLING_ONBOARDING"),
    FLEX_CHANGE_PAYMENT_TERMS("FLEX_CHANGE_PAYMENT_TERMS"),
    FLEX_CONNECT_PLAID("FLEX_CONNECT_PLAID"),
    FLEX_DISCONNECT_PLAID("FLEX_DISCONNECT_PLAID"),
    FLEX_ON_BOARDING_PAY_NOW("FLEX_ON_BOARDING_PAY_NOW"),
    FLEX_RISK_BASED_UNENROLL("FLEX_RISK_BASED_UNENROLL"),
    GET_MISSING_CREDIT_CARD_INFO("GET_MISSING_CREDIT_CARD_INFO"),
    IAP_ADD_FUNDS("IAP_ADD_FUNDS"),
    IAP_ADD_FUNDS_INIT("IAP_ADD_FUNDS_INIT"),
    IAP_ADD_FUNDS_INIT_V2("IAP_ADD_FUNDS_INIT_V2"),
    IAP_COLLECT_INFO("IAP_COLLECT_INFO"),
    ID_VERIFICATION("ID_VERIFICATION"),
    INDIA_EMANDATE_INCREASE("INDIA_EMANDATE_INCREASE"),
    INDIA_MIGRATION("INDIA_MIGRATION"),
    INTRO_AUTOMATIC_BILLING("INTRO_AUTOMATIC_BILLING"),
    MAKE_PRIMARY("MAKE_PRIMARY"),
    MAKE_PRIMARY_SUB_CONFIG("MAKE_PRIMARY_SUB_CONFIG"),
    MANAGE_BILLING_DATE_THRESHOLD("MANAGE_BILLING_DATE_THRESHOLD"),
    MI_ADD_PM("MI_ADD_PM"),
    MI_ASSIGN_FINANCE_EDITOR("MI_ASSIGN_FINANCE_EDITOR"),
    MI_AUTO_PAYMENT("MI_AUTO_PAYMENT"),
    MI_EDIT_BILLING_INFO("MI_EDIT_BILLING_INFO"),
    MI_EDIT_BILLING_INFO_SUB_CONFIG("MI_EDIT_BILLING_INFO_SUB_CONFIG"),
    MI_EDIT_CREDIT_SHARING_V2("MI_EDIT_CREDIT_SHARING_V2"),
    MI_EDIT_INVOICE_DETAILS("MI_EDIT_INVOICE_DETAILS"),
    MI_ONBOARDING("MI_ONBOARDING"),
    MI_PAY_NOW("MI_PAY_NOW"),
    MI_SELECT_ACCOUNTS("MI_SELECT_ACCOUNTS"),
    MI_TO_SELF_SERVE("MI_TO_SELF_SERVE"),
    NONE(NetInfoModule.CONNECTION_TYPE_NONE_DEPRECATED),
    NON_RECURRING_PAYMENT_METHOD("NON_RECURRING_PAYMENT_METHOD"),
    PAYMENT_SUPPORT("PAYMENT_SUPPORT"),
    PAYMENT_THRESHOLD("PAYMENT_THRESHOLD"),
    PAY_NOW("PAY_NOW"),
    PAY_NOW_INVOICE_REPAYMENT("PAY_NOW_INVOICE_REPAYMENT"),
    PAY_NOW_SUBCONFIG("PAY_NOW_SUBCONFIG"),
    PLAID_REAUTH("PLAID_REAUTH"),
    PRELOAD("PRELOAD"),
    PRELOADED_ADD_PM("PRELOADED_ADD_PM"),
    PREPAY_JAIL("PREPAY_JAIL"),
    REACTIVATE_AD_ACCOUNT("REACTIVATE_AD_ACCOUNT"),
    REACTIVATE_AD_ACCOUNT_DEPRECATED("REACTIVATE_AD_ACCOUNT_DEPRECATED"),
    RECEIVE_CREDIT_CARD("RECEIVE_CREDIT_CARD"),
    REJECT_CREDIT_CARD("REJECT_CREDIT_CARD"),
    REMOVE_ASL("REMOVE_ASL"),
    REMOVE_PM("REMOVE_PM"),
    REMOVE_PM_BM("REMOVE_PM_BM"),
    REQUEST_CREDIT_INCREASE("REQUEST_CREDIT_INCREASE"),
    REQUEST_CREDIT_INCREASE_SUB_CONFIG("REQUEST_CREDIT_INCREASE_SUB_CONFIG"),
    REQUEST_REFUND("REQUEST_REFUND"),
    REQUEST_SHARED_STORED_BALANCE_REFUND("REQUEST_SHARED_STORED_BALANCE_REFUND"),
    REQUIRED_WIZARD_BILLING_WRITE("REQUIRED_WIZARD_BILLING_WRITE"),
    RESET_SPEND("RESET_SPEND"),
    RESOLVE_DYNAMIC_DESCSRIPTOR_FRICTION("RESOLVE_DYNAMIC_DESCSRIPTOR_FRICTION"),
    RESOLVE_PREAUTH_FRICTION("RESOLVE_PREAUTH_FRICTION"),
    RESOLVE_SDC_FRICTION("RESOLVE_SDC_FRICTION"),
    REVOKE_CC_SHARING("REVOKE_CC_SHARING"),
    RISK_VERIFY_CREDENTIAL("RISK_VERIFY_CREDENTIAL"),
    RISK_VERIFY_CREDENTIAL_SUB_CONFIG("RISK_VERIFY_CREDENTIAL_SUB_CONFIG"),
    SAVE_CARD_CREDENTIAL("SAVE_CARD_CREDENTIAL"),
    SECURE_BUSINESS_REFUND("SECURE_BUSINESS_REFUND"),
    SELECT_PAYMENT_METHOD("SELECT_PAYMENT_METHOD"),
    SELF_GRANT_MANAGE_AD_ACCOUNT("SELF_GRANT_MANAGE_AD_ACCOUNT"),
    SELF_SERVE_TO_MI_PAY_NOW("SELF_SERVE_TO_MI_PAY_NOW"),
    SEND_REAUTH("SEND_REAUTH"),
    SHARE_CREDIT_CARD("SHARE_CREDIT_CARD"),
    SHARE_MONTHLY_INVOICING("SHARE_MONTHLY_INVOICING"),
    SPEND_MORE("SPEND_MORE"),
    STATUS("STATUS"),
    SUBSCRIBE_NOW("SUBSCRIBE_NOW"),
    TURN_ON_AUTOPAY("TURN_ON_AUTOPAY"),
    TURN_ON_AUTOPAY_WITH_ADD_PAYMENT_METHOD("TURN_ON_AUTOPAY_WITH_ADD_PAYMENT_METHOD"),
    TURN_ON_AUTOPAY_WITH_PAYMENT_METHOD_SELECTION("TURN_ON_AUTOPAY_WITH_PAYMENT_METHOD_SELECTION"),
    UNBLOCK_SOLUTIONS("UNBLOCK_SOLUTIONS"),
    UPDATE_ACCOUNT_SPEND_LIMIT("UPDATE_ACCOUNT_SPEND_LIMIT"),
    UPSELL_POSTPAY_AUTO_BILLING("UPSELL_POSTPAY_AUTO_BILLING"),
    VERIFY_COUNTRY("VERIFY_COUNTRY"),
    VERIFY_CREDIT_CARD_CVV("VERIFY_CREDIT_CARD_CVV"),
    VERIFY_DIRECT_DEBIT("VERIFY_DIRECT_DEBIT"),
    VERIFY_PAYMENT_METHOD_BANK("VERIFY_PAYMENT_METHOD_BANK"),
    WABA_EDIT_PM("WABA_EDIT_PM"),
    WIZARD_COMPONENT_PLAYGROUND("WIZARD_COMPONENT_PLAYGROUND"),
    XFAC("XFAC");
    
    public static final Map A01 = null;
    public static final Parcelable.Creator CREATOR = null;
    public final String A00;

    public final int describeContents() {
        return 0;
    }

    /* access modifiers changed from: public */
    static {
        int i;
        BillingWizardName[] billingWizardNameArr;
        A02 = 0oU.A00(billingWizardNameArr);
        LinkedHashMap linkedHashMap = new LinkedHashMap(DbY.A00(r4));
        for (BillingWizardName billingWizardName : values()) {
            linkedHashMap.put(billingWizardName.A00, billingWizardName);
        }
        A01 = linkedHashMap;
        CREATOR = new SWT(61);
    }

    public final String toString() {
        return this.A00;
    }

    /* access modifiers changed from: public */
    BillingWizardName(String str) {
        this.A00 = str;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        Dbb.A0q(parcel, this);
    }
}
