package com.instagram.api.schemas;

import X.0oU;
import X.DbY;
import X.Dbb;
import X.SWT;
import android.os.Parcel;
import android.os.Parcelable;
import java.util.LinkedHashMap;
import java.util.Map;

public enum CallToActionType implements Parcelable {
    UNRECOGNIZED("CallToActionType_unspecified"),
    ACTIVATE_OFFER("ACTIVATE_OFFER"),
    ADD_TO_CART("ADD_TO_CART"),
    APPLY_NOW("APPLY_NOW"),
    ASK_ABOUT_SERVICES("ASK_ABOUT_SERVICES"),
    ASK_FOR_MORE_INFO("ASK_FOR_MORE_INFO"),
    AUDIO_CALL("AUDIO_CALL"),
    BET_NOW("BET_NOW"),
    BLOOD_DONATIONS("BLOOD_DONATIONS"),
    BOOK_A_CONSULTATION("BOOK_A_CONSULTATION"),
    BOOK_NOW("BOOK_NOW"),
    BOOK_TEST_DRIVE("BOOK_TEST_DRIVE"),
    BOOK_TRAVEL("BOOK_TRAVEL"),
    BUY("BUY"),
    BUY_NOW("BUY_NOW"),
    BUY_TICKETS("BUY_TICKETS"),
    BUY_VIA_MESSAGE("BUY_VIA_MESSAGE"),
    CALL("CALL"),
    CALL_ME("CALL_ME"),
    CALL_NOW("CALL_NOW"),
    CHAT_ON_WHATSAPP("CHAT_ON_WHATSAPP"),
    CHAT_WITH_US("CHAT_WITH_US"),
    CHECK_AVAILABILITY("CHECK_AVAILABILITY"),
    CIVIC_ACTION("CIVIC_ACTION"),
    CLAIM_OFFER("CLAIM_OFFER"),
    CONFIRM("CONFIRM"),
    CONTACT("CONTACT"),
    CONTACT_US("CONTACT_US"),
    DIAL_CODE("DIAL_CODE"),
    DONATE("DONATE"),
    DONATE_NOW("DONATE_NOW"),
    DOWNLOAD("DOWNLOAD"),
    EMAIL_NOW("EMAIL_NOW"),
    EVENT_RSVP("EVENT_RSVP"),
    EXPLORE_MORE("EXPLORE_MORE"),
    FIND_A_GROUP("FIND_A_GROUP"),
    FIND_YOUR_GROUPS("FIND_YOUR_GROUPS"),
    FOLLOW_NEWS_STORYLINE("FOLLOW_NEWS_STORYLINE"),
    FOLLOW_PAGE("FOLLOW_PAGE"),
    FOLLOW_USER("FOLLOW_USER"),
    GET_A_QUOTE("GET_A_QUOTE"),
    GET_DIRECTIONS("GET_DIRECTIONS"),
    GET_EVENT_TICKETS("GET_EVENT_TICKETS"),
    GET_MOBILE_APP("GET_MOBILE_APP"),
    GET_OFFER("GET_OFFER"),
    GET_OFFER_VIEW("GET_OFFER_VIEW"),
    GET_PROMOTIONS("GET_PROMOTIONS"),
    GET_QUOTE("GET_QUOTE"),
    GET_SHOWTIMES("GET_SHOWTIMES"),
    GET_STARTED("GET_STARTED"),
    GIVE_FREE_RIDES("GIVE_FREE_RIDES"),
    GO_LIVE("GO_LIVE"),
    INQUIRE_NOW("INQUIRE_NOW"),
    INSTAGRAM_MESSAGE("INSTAGRAM_MESSAGE"),
    INSTALL_APP("INSTALL_APP"),
    INSTALL_FREE_MOBILE_APP("INSTALL_FREE_MOBILE_APP"),
    INSTALL_MOBILE_APP("INSTALL_MOBILE_APP"),
    INTERESTED("INTERESTED"),
    JOBS_APPLY_NOW("JOBS_APPLY_NOW"),
    JOIN_CHANNEL("JOIN_CHANNEL"),
    JOIN_GROUP("JOIN_GROUP"),
    LEARN_MORE("LEARN_MORE"),
    LIKE_PAGE("LIKE_PAGE"),
    LINK_CARD("LINK_CARD"),
    LISTEN_MUSIC("LISTEN_MUSIC"),
    LISTEN_NOW("LISTEN_NOW"),
    LOYALTY_LEARN_MORE("LOYALTY_LEARN_MORE"),
    MAKE_AN_APPOINTMENT("MAKE_AN_APPOINTMENT"),
    MESSAGE_PAGE("MESSAGE_PAGE"),
    MESSAGE_USER("MESSAGE_USER"),
    MISSED_CALL("MISSED_CALL"),
    MOBILE_DOWNLOAD("MOBILE_DOWNLOAD"),
    MOMENTS("MOMENTS"),
    NO_BUTTON("NO_BUTTON"),
    OPEN_INSTANT_APP("OPEN_INSTANT_APP"),
    OPEN_LINK("OPEN_LINK"),
    OPEN_MESSENGER_EXT("OPEN_MESSENGER_EXT"),
    OPEN_MOVIES("OPEN_MOVIES"),
    ORDER_NOW("ORDER_NOW"),
    PAY_OR_REQUEST("PAY_OR_REQUEST"),
    PAY_TO_ACCESS("PAY_TO_ACCESS"),
    PLAY("PLAY"),
    PLAY_GAME("PLAY_GAME"),
    PLAY_GAME_ON_FACEBOOK("PLAY_GAME_ON_FACEBOOK"),
    PRE_REGISTER("PRE_REGISTER"),
    PURCHASE_GIFT_CARDS("PURCHASE_GIFT_CARDS"),
    RAISE_MONEY("RAISE_MONEY"),
    RECORD_NOW("RECORD_NOW"),
    REFER_FRIENDS("REFER_FRIENDS"),
    REGISTER_NOW("REGISTER_NOW"),
    REMIND_ME("REMIND_ME"),
    REQUEST_TIME("REQUEST_TIME"),
    SAVE("SAVE"),
    SAVE_OFFER("SAVE_OFFER"),
    SAY_THANKS("SAY_THANKS"),
    SEARCH("SEARCH"),
    SEARCH_MORE("SEARCH_MORE"),
    SEE_DETAILS("SEE_DETAILS"),
    SEE_MENU("SEE_MENU"),
    SEE_MORE("SEE_MORE"),
    SEE_OFFER("SEE_OFFER"),
    SELL_NOW("SELL_NOW"),
    SEND_A_GIFT("SEND_A_GIFT"),
    SEND_GIFT("SEND_GIFT"),
    SEND_GIFT_MONEY("SEND_GIFT_MONEY"),
    SEND_INVITES("SEND_INVITES"),
    SEND_TIP("SEND_TIP"),
    SEND_UPDATES("SEND_UPDATES"),
    SHARE("SHARE"),
    SHOP_NOW("SHOP_NOW"),
    SIGN_UP("SIGN_UP"),
    SOTTO_SUBSCRIBE("SOTTO_SUBSCRIBE"),
    START_ORDER("START_ORDER"),
    SUBSCRIBE("SUBSCRIBE"),
    SWIPE_UP_PRODUCT("SWIPE_UP_PRODUCT"),
    SWIPE_UP_SHOP("SWIPE_UP_SHOP"),
    TRY_IN_CAMERA("TRY_IN_CAMERA"),
    TRY_IT("TRY_IT"),
    TRY_ON("TRY_ON"),
    UNLIKE_PAGE("UNLIKE_PAGE"),
    UPDATE_APP("UPDATE_APP"),
    USE_APP("USE_APP"),
    USE_MOBILE_APP("USE_MOBILE_APP"),
    VIDEO_ANNOTATION("VIDEO_ANNOTATION"),
    VIDEO_CALL("VIDEO_CALL"),
    VIEW_CHANNEL("VIEW_CHANNEL"),
    VIEW_INSTAGRAM_PROFILE("VIEW_INSTAGRAM_PROFILE"),
    VIEW_PRODUCT("VIEW_PRODUCT"),
    VIEW_RESUME("VIEW_RESUME"),
    VISIT_PAGES_FEED("VISIT_PAGES_FEED"),
    VISIT_PROFILE("VISIT_PROFILE"),
    VISIT_WORLD("VISIT_WORLD"),
    VOTE_NOW("VOTE_NOW"),
    WATCH_APP_UPGRADE("WATCH_APP_UPGRADE"),
    WATCH_MORE("WATCH_MORE"),
    WATCH_MUSIC_VIDEO("WATCH_MUSIC_VIDEO"),
    WATCH_VIDEO("WATCH_VIDEO"),
    WHATSAPP_LINK("WHATSAPP_LINK"),
    WHATSAPP_MESSAGE("WHATSAPP_MESSAGE"),
    WOODHENGE_SUPPORT("WOODHENGE_SUPPORT");
    
    public static final Map A01 = null;
    public static final Parcelable.Creator CREATOR = null;
    public final String A00;

    public final int describeContents() {
        return 0;
    }

    /* access modifiers changed from: public */
    static {
        int i;
        CallToActionType[] callToActionTypeArr;
        A02 = 0oU.A00(callToActionTypeArr);
        LinkedHashMap linkedHashMap = new LinkedHashMap(DbY.A00(r4));
        for (CallToActionType callToActionType : values()) {
            linkedHashMap.put(callToActionType.A00, callToActionType);
        }
        A01 = linkedHashMap;
        CREATOR = new SWT(82);
    }

    public final String toString() {
        return this.A00;
    }

    /* access modifiers changed from: public */
    CallToActionType(String str) {
        this.A00 = str;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        Dbb.A0q(parcel, this);
    }
}
