package com.instagram.model.reels.sponsored;

import X.0oU;
import X.0qQ;
import X.0se;
import X.C376399Hv;
import android.os.Parcel;
import android.os.Parcelable;
import java.util.LinkedHashMap;
import java.util.Map;

public enum AutoGeneratedCardType implements Parcelable {
    UNRECOGNIZED("AutoGeneratedCardType_unspecified"),
    CAPTION("CAPTION"),
    CLICK_TO_MESSAGING_FAQS("CLICK_TO_MESSAGING_FAQS"),
    CLICK_TO_MESSAGING_WHATSAPP("CLICK_TO_MESSAGING_WHATSAPP"),
    COLLECTION("COLLECTION"),
    FIRST_QUESTION_CONTACT_INFO_LEADGEN("FIRST_QUESTION_CONTACT_INFO_LEADGEN"),
    FIRST_QUESTION_LEADGEN("FIRST_QUESTION_LEADGEN"),
    FIRST_QUESTION_SHORT_ANSWER_LEADGEN("FIRST_QUESTION_SHORT_ANSWER_LEADGEN"),
    GENERIC_CARD("GENERIC_CARD"),
    LEADGEN("LEADGEN"),
    MAI("MAI"),
    OFFSITE_LEADGEN_CARD("OFFSITE_LEADGEN_CARD"),
    ORIGINAL("ORIGINAL"),
    PRODUCT_EXTENSION("PRODUCT_EXTENSION"),
    PROFILE("PROFILE"),
    SHOWCASE("SHOWCASE");
    
    public static final Map A01 = null;
    public static final Parcelable.Creator CREATOR = null;
    public final String A00;

    public final int describeContents() {
        return 0;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        0qQ.A0B(parcel, 0);
        parcel.writeInt(ordinal());
    }

    /* access modifiers changed from: public */
    static {
        int i;
        AutoGeneratedCardType[] autoGeneratedCardTypeArr;
        A02 = 0oU.A00(autoGeneratedCardTypeArr);
        int A0L = 0se.A0L(r3);
        if (A0L < 16) {
            A0L = 16;
        }
        LinkedHashMap linkedHashMap = new LinkedHashMap(A0L);
        for (AutoGeneratedCardType autoGeneratedCardType : values()) {
            linkedHashMap.put(autoGeneratedCardType.A00, autoGeneratedCardType);
        }
        A01 = linkedHashMap;
        CREATOR = new C376399Hv(44);
    }

    public final String toString() {
        return this.A00;
    }

    /* access modifiers changed from: public */
    AutoGeneratedCardType(String str) {
        this.A00 = str;
    }
}
