package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import java.util.Locale;

/* renamed from: X.6LE  reason: invalid class name */
public final class AnonymousClass6LE extends 0Yg implements 0sP {
    public static final AnonymousClass6LE A00 = new AnonymousClass6LE();

    public AnonymousClass6LE() {
        super(1);
    }

    public final /* bridge */ /* synthetic */ Object invoke(Object obj) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) obj;
        0qQ.A0B(autoGeneratedCardType, 0);
        String lowerCase = autoGeneratedCardType.A00.toLowerCase(Locale.ROOT);
        0qQ.A07(lowerCase);
        return lowerCase;
    }
}
