package X;

/* renamed from: X.8LN  reason: invalid class name */
public enum AnonymousClass8LN {
    FaceTrackerFaceAlign,
    FaceTrackerFaceDetect,
    FaceTrackerFaceContour,
    FaceTrackerFaceMesh,
    Caffe2InitNet,
    Caffe2PredictNet,
    ExpressionFitting,
    NametagDetectionInit,
    NametagDetectionPred,
    NametagOcrInit,
    NametagOcrPred,
    MSuggestionsCoreP13NFilteringInit,
    MSuggestionsCoreP13NFilteringFeatures,
    MSuggestionsCoreP13NFilteringPredict,
    MSuggestionsCoreSensitivityInit,
    MSuggestionsCoreSensitivityPredict,
    MSuggestionsCoreStickerReceiverIntentInit,
    MSuggestionsCoreStickerReceiverIntentPredict,
    MSuggestionsCoreStickerReceiverTagPredict,
    MSuggestionsCoreStickerReceiverTagInit,
    MSuggestionsCoreStickerSenderIntentInit,
    MSuggestionsCoreStickerSenderIntentPredict,
    MSuggestionsCoreStickerSenderTagInit,
    MSuggestionsCoreStickerSenderTagPredict,
    MulticlassInitNet,
    MulticlassPredictNet,
    PytorchModel,
    Unknown,
    XrayClasses,
    XrayConfiguration,
    XrayInitNet,
    XrayPredictNet,
    Ocr2goDetModel,
    Ocr2goRcgModel,
    Ocr2goConfig,
    RecognitionClassificationInit,
    RecognitionDetectionInit,
    RuntimeRigRetargetingConfig,
    BodyTracking3DDetection,
    BodyTracking3DLandmark
}
