package X;

import android.content.Context;
import com.facebook.proxygen.TraceFieldType;
import com.instagram.api.schemas.IntentAwareAdsInfoIntf;
import com.instagram.common.session.UserSession;
import com.instagram.model.effect.AttributedAREffect;
import com.instagram.model.reels.Reel;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.react.modules.base.IgReactQEModule;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import kotlin.Deprecated;

/* renamed from: X.3PI  reason: invalid class name */
public final class AnonymousClass3PI {
    public static final AnonymousClass3PI A00 = new Object();

    public static final C255773uh A00(UserSession userSession, 1Nv r3) {
        0qQ.A0B(userSession, 1);
        if (r3 instanceof Reel) {
            Reel reel = (Reel) r3;
            List A0O = reel.A0O(userSession);
            0qQ.A07(A0O);
            if (!A0O.isEmpty()) {
                return reel.A0A(userSession, 0);
            }
            return null;
        } else if (r3 instanceof C255773uh) {
            return (C255773uh) r3;
        } else {
            return null;
        }
    }

    public static final LinkedHashMap A02(List list) {
        if (list != null) {
            LinkedHashMap linkedHashMap = new LinkedHashMap();
            Iterator it = list.iterator();
            while (it.hasNext()) {
                C255783ui r3 = (C255783ui) it.next();
                if (r3.A11.ordinal() == 29) {
                    C272024jy A0E = r3.A0E();
                    if (A0E != null) {
                        String A002 = AnonymousClass9OX.A00(A0E);
                        if (!("poll".length() == 0 || A002 == null)) {
                            linkedHashMap.put("poll", A002);
                        }
                    } else {
                        throw new IllegalStateException("Required value was null.");
                    }
                }
            }
            if (!linkedHashMap.isEmpty()) {
                return linkedHashMap;
            }
        }
        return null;
    }

    public static final void A03(Context context, C254533sd r7) {
        0qQ.A0B(context, 1);
        float A01 = 0nA.A01(context, (float) 0nA.A09(context));
        float A012 = 0nA.A01(context, (float) 0nA.A08(context));
        float f = 0nA.A0H(context).density;
        r7.EjI(A01, A012, ((float) 0nA.A06(context)) / f, ((float) 0nA.A05(context)) / f, f);
    }

    public static final void A05(AnonymousClass0iw r1, UserSession userSession, Long l, String str, String str2, String str3, String str4) {
        0qQ.A0B(userSession, 0);
        0qQ.A0B(str, 1);
        VF8.A00(r1, AnonymousClass0kN.A01(r1, userSession), userSession, l, str, str2, str3, str4);
    }

    public static final void A04(IntentAwareAdsInfoIntf intentAwareAdsInfoIntf, C254523sc r3) {
        if (intentAwareAdsInfoIntf != null) {
            r3.A1g = true;
            Integer BUY = intentAwareAdsInfoIntf.BUY();
            if (BUY != null) {
                r3.A3m = Long.valueOf((long) BUY.intValue());
            }
            String Br2 = intentAwareAdsInfoIntf.Br2();
            if (Br2 != null) {
                r3.A5Z = Br2;
            }
            String BUa = intentAwareAdsInfoIntf.BUa();
            if (BUa != null) {
                r3.A62 = BUa;
                r3.A64 = BUa;
                r3.A62 = BUa;
                r3.A64 = BUa;
            }
            String C9y = intentAwareAdsInfoIntf.C9y();
            if (C9y != null) {
                r3.A5j = C9y;
            }
            if (intentAwareAdsInfoIntf.CbN() != null) {
                r3.A1v = intentAwareAdsInfoIntf.CbN();
            }
            if (intentAwareAdsInfoIntf.BHg() != null) {
                r3.A63 = intentAwareAdsInfoIntf.BHg();
            }
        }
    }

    public static final void A06(C254523sc r2, Reel reel) {
        String str;
        Integer num = reel.A0f;
        if (num != null) {
            r2.A68 = C14510TxW.A00(num);
            r2.A66 = reel.A0G();
            switch (num.intValue()) {
                case 0:
                case 3:
                case 4:
                case 9:
                case IgReactQEModule.CONFIG_KEY_OFFSET /*12*/:
                    C270054g7 r0 = reel.A0a;
                    if (r0 != null) {
                        str = r0.C9L();
                        break;
                    } else {
                        throw new IllegalStateException("Reel should have a SimpleAction");
                    }
                case 1:
                    C270064g8 r1 = reel.A0R;
                    if (r1 != null) {
                        1Xj r02 = reel.A0F;
                        if (r02 != null) {
                            r2.A5u = r02.getId();
                        }
                        str = r1.A00.C9L();
                        break;
                    } else {
                        throw new IllegalStateException("Ad4ad netego should have an Ad4ad object");
                    }
                case 2:
                    C270074g9 r03 = reel.A0Q;
                    if (r03 != null) {
                        str = r03.A00.A06;
                        break;
                    } else {
                        throw new IllegalStateException("SU netego should have a SimpleSuggestedUsers object");
                    }
                case 5:
                    throw new IllegalStateException("Suggested clips netego should have a SuggestedClips object");
                case 6:
                case 8:
                    throw new IllegalStateException("Shops For You netego should have a SuggestedShops object");
                case 10:
                    C270094gB r04 = reel.A0S;
                    if (r04 != null) {
                        str = r04.A01.A07;
                        break;
                    } else {
                        throw new IllegalStateException("Bloks netego should have a Bloks object");
                    }
                case 11:
                    C270084gA r05 = reel.A0K;
                    if (r05 != null) {
                        str = r05.A03.A08;
                        break;
                    } else {
                        throw new IllegalStateException("Trending prompts netego should have a PromptsInStory object");
                    }
                case 13:
                    C270104gC r06 = reel.A0T;
                    if (r06 != null) {
                        str = r06.A00.C9L();
                        break;
                    } else {
                        throw new IllegalStateException("Share comments to story netego should have a CommentShareNetego object");
                    }
                case 14:
                    C270124gE r07 = reel.A0U;
                    if (r07 != null) {
                        str = r07.A07;
                        break;
                    } else {
                        throw new IllegalStateException("Meta Gallery stories netego should have a MetaGalleryNetegoInfo object");
                    }
                case 15:
                    C270114gD r08 = reel.A0V;
                    if (r08 != null) {
                        str = r08.A00.C9L();
                        break;
                    } else {
                        throw new IllegalStateException("Threads in stories unit Netego needs to have a ThreadsInStoriesUnitNetego object");
                    }
                default:
                    throw new IllegalArgumentException(C273654mx.A00(526));
            }
            if (str == null) {
                str = "";
            }
            r2.A67 = str;
            return;
        }
        throw new IllegalStateException("Netego item should have a netego type");
    }

    public static final void A07(C254523sc r8, C255773uh r9, C250973mM r10, C310666bQ r11, C309426Yf r12, int i, boolean z) {
        List list;
        String str;
        C2801750l BDc;
        List AZX;
        C2801550j r0;
        A09(r8, new GT8(r11.A01, r10.A0H, r9, r10, r12, i, z));
        r8.A6g = r11.A08;
        r8.A7Q = r11.A06.getSessionId();
        r8.A72 = r11.A07;
        r8.A2q = Integer.valueOf(AnonymousClass0xl.A00(C61170le.A00).A00());
        r8.A2u = Integer.valueOf(AnonymousClass1GD.A03() ? 1 : 0);
        r8.A6u = r11.A00;
        List unmodifiableList = Collections.unmodifiableList(r12.A1D);
        if (unmodifiableList != null) {
            list = 00k.A0a(unmodifiableList);
        } else {
            list = null;
        }
        r8.A7k = list;
        1Xj r02 = r9.A0b;
        if (r02 == null || (BDc = r02.A0C.BDc()) == null || (AZX = BDc.AZX()) == null || (r0 = (C2801550j) 00k.A0O(AZX, 0)) == null) {
            str = null;
        } else {
            str = r0.Bkc();
        }
        r8.A5V = str;
    }

    public static final void A08(C254523sc r7, C255773uh r8, AnonymousClass6YY r9, C310666bQ r10) {
        C254523sc r0 = r7;
        A07(r0, r8, r9.A00, r10, r9.A02, r9.A01.A00(r8), r9.A03);
    }

    public static final void A09(C254523sc r11, GT8 gt8) {
        int i;
        Map map;
        int i2;
        C255783ui r0;
        String str;
        String str2;
        Reel reel = gt8.A02;
        String id = reel.getId();
        0qQ.A07(id);
        r11.A6c = id;
        r11.A4B = Long.valueOf((long) gt8.A00);
        UserSession userSession = gt8.A01;
        r11.A45 = Long.valueOf((long) reel.A0O(userSession).size());
        C250973mM r3 = gt8.A04;
        if (r3.A0L) {
            i = 0;
        } else {
            i = r3.A00;
        }
        r11.A46 = Long.valueOf((long) i);
        r11.A44 = Long.valueOf((long) gt8.A00());
        r11.A6h = reel.A0H(userSession);
        C309426Yf r7 = gt8.A05;
        r11.A48 = Long.valueOf((long) r7.A0I);
        C255773uh r2 = gt8.A03;
        LinkedHashMap A02 = A02(r2.A0b());
        if (A02 != null) {
            map = Collections.unmodifiableMap(A02);
        } else {
            map = null;
        }
        r11.A88 = map;
        if (reel.A17(userSession)) {
            i2 = reel.A00;
        } else {
            i2 = -1;
        }
        r11.A3N = Long.valueOf((long) i2);
        r11.A24 = Boolean.valueOf(gt8.A07);
        r11.A1b = Boolean.valueOf(C297785sK.A0i(r2, r3));
        AnonymousClass3WT r6 = AnonymousClass3WT.RESHARE_VIEW_SHOP_CTA;
        r11.A1A = Boolean.valueOf(r2.A1t(r6));
        Integer num = reel.A0g;
        if (num != null) {
            r11.A3U = Long.valueOf((long) num.intValue());
        }
        AttributedAREffect attributedAREffect = reel.A0G;
        if (!(attributedAREffect == null || (str2 = attributedAREffect.A09) == null)) {
            try {
                r11.A3V = 00y.A0n(10, str2);
            } catch (NumberFormatException unused) {
                0wb.A03("ReelLoggerUtil", "Unable to convert invalid effect id into Long");
            }
        }
        Reel reel2 = r3.A0H;
        List list = reel2.A0w;
        if (list != null) {
            int A002 = gt8.A00();
            if (!list.isEmpty()) {
                r11.A7n = list;
            }
            r11.A45 = Long.valueOf((long) C297785sK.A03(list));
            r11.A44 = Long.valueOf((long) C297785sK.A04(list, A002));
            r11.A4A = Long.valueOf((long) A002);
            if (A002 == 1 && list.get(A002) == AutoGeneratedCardType.GENERIC_CARD) {
                r11.A0j = reel2.A06();
            }
        }
        r11.A2X = Double.valueOf(((double) (r7.A0A * r7.A0B)) / 1000.0d);
        boolean CcK = r2.CcK();
        Long valueOf = Long.valueOf((long) r3.A0E);
        if (CcK) {
            r11.A3H = valueOf;
        } else {
            r11.A4G = valueOf;
        }
        List Bkd = r2.Bkd(r6);
        if (!(Bkd == null || (r0 = (C255783ui) 00k.A0J(Bkd)) == null || (str = r0.A1c) == null)) {
            r11.A6n = str;
        }
        A04(reel.A0B, r11);
        if (C297785sK.A0l(r3)) {
            r11.A3o = Long.valueOf((long) reel.A0O(userSession).size());
            r11.A3x = Long.valueOf((long) gt8.A00());
        }
    }

    public final void A0B(Context context, C254523sc r16, C255773uh r17, AnonymousClass6UP r18, AnonymousClass6YY r19, C310666bQ r20) {
        C310666bQ r1 = r20;
        UserSession userSession = r1.A01;
        AnonymousClass6YY r2 = r19;
        C250973mM r6 = r2.A00;
        C255773uh r5 = r17;
        GT8 gt8 = new GT8(userSession, r6.A0H, r5, r6, r2.A02, r2.A01.A00(r5), r2.A03);
        UserSession userSession2 = userSession;
        A0A(context, userSession2, r16, r5, r1.A03, gt8, r18);
    }

    public final void A0C(AnonymousClass0iw r9, UserSession userSession, AnonymousClass3BN r11, C228102kn r12, Double d, Integer num, Integer num2, String str, String str2, long j, boolean z, boolean z2) {
        long j2;
        String str3;
        int i;
        Long l;
        String str4 = str2;
        0qQ.A0B(userSession, 0);
        0qQ.A0B(r9, 1);
        0wc A01 = AnonymousClass0kN.A01(r9, userSession);
        0Aj A002 = A01.A00(A01.A00, "reel_tray_refresh");
        if (A002.isSampled()) {
            AnonymousClass3BO r7 = r11.A01;
            AnonymousClass3BP r3 = r7.A01;
            if (r3.A02 != 0) {
                j2 = 1;
            } else {
                j2 = 0;
            }
            A002.A9F("has_my_reel", Long.valueOf(j2));
            String str5 = str;
            if (str != null) {
                A002.AAJ("tray_session_id", str5);
                A002.A9F("new_reel_count", Long.valueOf((long) r3.A01));
                A002.A9F("viewed_reel_count", Long.valueOf((long) r3.A03));
                A002.A8D("tray_refresh_time", Double.valueOf(((double) j) / 1000.0d));
                if (z) {
                    str3 = "disk";
                } else {
                    str3 = "network";
                }
                A002.AAJ("tray_refresh_type", str3);
                A002.A7p("was_successful", Boolean.valueOf(z2));
                AnonymousClass3BP r5 = r7.A00;
                A002.A9F("live_reel_count", Long.valueOf((long) r5.A01));
                A002.A9F("muted_reel_count", Long.valueOf((long) r3.A00));
                A002.A9F("muted_live_reel_count", Long.valueOf((long) r5.A00));
                if (r12 != null) {
                    i = r12.A0R.size();
                } else {
                    i = 0;
                }
                A002.A9F("unfetched_reel_count", Long.valueOf((long) i));
                if (str2 == null) {
                    str4 = "";
                }
                A002.AAJ("story_ranking_token", str4);
                A002.AAJ("tray_refresh_reason", 1NZ.A00(num));
                if (num2 != null) {
                    l = Long.valueOf((long) num2.intValue());
                } else {
                    l = null;
                }
                A002.A9F(TraceFieldType.StatusCode, l);
                A002.A8D("num_of_pogs_visible", d);
                A002.Cgf();
                return;
            }
            throw new IllegalStateException("Required value was null.");
        }
    }

    @Deprecated(message = "Viewed Impression logging in ReelViewerLogger is being deprecated. ")
    public final void A0D(C254523sc r9, GT8 gt8) {
        if (gt8 != null) {
            C309426Yf r3 = gt8.A05;
            float f = r3.A0A;
            float f2 = r3.A0B;
            r9.A2R = Double.valueOf(((double) (f * f2)) / 1000.0d);
            float f3 = 1.0f - f2;
            float f4 = 0.0f;
            if (0.0f < f3) {
                f4 = f3;
            }
            r9.A2S = Double.valueOf(((double) (f * f4)) / 1000.0d);
            r9.A2N = Double.valueOf(r3.A00);
            r9.A2P = Double.valueOf(r3.A03);
            r9.A2O = Double.valueOf(r3.A01);
        }
    }

    /* JADX WARNING: type inference failed for: r1v40, types: [com.instagram.api.schemas.MoreInfoStickerCTAType] */
    /* JADX WARNING: Code restructure failed: missing block: B:109:0x027c, code lost:
        if (r7.A0C.C05() == null) goto L_0x027e;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:126:0x02ce, code lost:
        if (r1 == null) goto L_0x02d0;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:158:0x035b, code lost:
        if (r3.A15() != false) goto L_0x035d;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:177:0x03ad, code lost:
        if (X.C297785sK.A0N(r11, r2, r14) != false) goto L_0x03af;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:74:0x01fa, code lost:
        r0 = r0.BF0();
     */
    /* JADX WARNING: Multi-variable type inference failed */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final void A0A(android.content.Context r10, com.instagram.common.session.UserSession r11, X.C254523sc r12, X.1Nv r13, X.AnonymousClass3BQ r14, X.GT8 r15, X.AnonymousClass6UP r16) {
        /*
            r9 = this;
            boolean r0 = r13.CcK()
            if (r0 == 0) goto L_0x04f2
            X.3uh r2 = A00(r11, r13)
            if (r2 == 0) goto L_0x04d8
            java.lang.String r0 = r2.A0Z(r11)
            java.lang.String r0 = X.002.A0B(r0)
            r12.A71 = r0
            java.lang.String r0 = r2.A0Y(r11)
            r12.A4a = r0
            java.lang.String r0 = r2.A0X(r11)
            if (r0 == 0) goto L_0x0046
            java.lang.String r0 = r2.A0X(r11)
            r12.A56 = r0
            X.3mL r3 = r2.A0e
            X.3mL r1 = X.C250963mL.MEDIA
            if (r3 != r1) goto L_0x04c5
            X.1Xj r0 = r2.A0b
            r0.getClass()
            java.lang.String r0 = X.C231122qu.A0A(r11, r0)
        L_0x0037:
            r12.A55 = r0
            if (r3 != r1) goto L_0x04c2
            X.1Xj r0 = r2.A0b
            r0.getClass()
            java.lang.String r0 = X.C231122qu.A0C(r11, r0)
        L_0x0044:
            r12.A57 = r0
        L_0x0046:
            r3 = r16
            if (r16 == 0) goto L_0x0115
            int r0 = r3.A0N
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A3I = r0
            int r0 = r3.A0P
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A47 = r0
            int r0 = r3.A0O
            r12.A07(r0)
            X.6Yf r0 = r15.A05
            int r0 = r0.A0I
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A3G = r0
            boolean r4 = r3.A0L
            int r0 = r3.A04
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            if (r4 == 0) goto L_0x04b5
            r12.A41 = r0
            int r0 = r3.A01
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A3S = r0
        L_0x0082:
            int r0 = r3.A05
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A42 = r0
            int r0 = r3.A00
            r12.A06(r0)
            int r0 = r3.A06
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A43 = r0
            int r0 = r3.A02
            r12.A0A(r0)
            X.2vm r4 = r3.A08
            r12.A0O(r4)
            int r0 = r3.A03
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A3z = r0
            X.3Hd r0 = r3.A07
            if (r0 == 0) goto L_0x00c9
            int r1 = r0.A00
            java.lang.String r0 = r0.A02
            r12.A4P = r0
            long r0 = (long) r1
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A3b = r0
            java.lang.Long r0 = r3.A0H
            r12.A3p = r0
            java.lang.Integer r0 = r3.A0A
            r12.A2l = r0
            java.lang.Integer r0 = r3.A0B
            r12.A2m = r0
        L_0x00c9:
            if (r4 == 0) goto L_0x00d3
            boolean r0 = r4.A01
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1w = r0
        L_0x00d3:
            java.lang.Integer r0 = r3.A0F
            r12.A38 = r0
            java.lang.Integer r0 = r3.A09
            r12.A2x = r0
            java.lang.Long r0 = r3.A0J
            r12.A3r = r0
            boolean r0 = r3.A0M
            if (r0 == 0) goto L_0x00ef
            java.lang.Long r0 = r3.A0I
            r12.A3q = r0
            java.lang.Integer r0 = r3.A0D
            r12.A30 = r0
            java.lang.Integer r0 = r3.A0E
            r12.A31 = r0
        L_0x00ef:
            java.lang.Long r0 = r3.A0K
            r12.A3s = r0
            java.lang.Integer r0 = r3.A0G
            r12.A39 = r0
            java.lang.Integer r0 = r3.A0C
            r12.A2z = r0
            X.0Tu r3 = X.0Tu.A05
            r0 = 36312733012919528(0x81023d000f04e8, double:3.027656804785192E-306)
            boolean r0 = X.182.A06(r3, r11, r0)
            if (r0 == 0) goto L_0x0112
            boolean r0 = X.C316216lI.A0A(r10)
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1Q = r0
        L_0x0112:
            r0 = 1
            r12.A8A = r0
        L_0x0115:
            int r0 = X.0nA.A09(r10)
            float r0 = (float) r0
            float r3 = X.0nA.A01(r10, r0)
            int r0 = X.0nA.A08(r10)
            float r0 = (float) r0
            float r1 = X.0nA.A01(r10, r0)
            android.util.DisplayMetrics r0 = X.0nA.A0H(r10)
            float r0 = r0.density
            r12.A04(r3, r1, r0)
            X.6Yf r4 = r15.A05
            X.6MB r1 = r4.A0S
            if (r1 == 0) goto L_0x014e
            java.util.Map r0 = r1.BLs()
            r12.A0Y(r0)
            java.util.Map r1 = r1.BN6()
            if (r1 == 0) goto L_0x04b2
            java.lang.String r0 = "caption_highlights_showed"
            java.lang.Object r0 = r1.get(r0)
            java.util.List r0 = (java.util.List) r0
        L_0x014b:
            r12.A0W(r0)
        L_0x014e:
            boolean r0 = X.C297785sK.A0d(r2)
            X.0jB r3 = r12.A0m
            if (r3 != 0) goto L_0x015d
            X.0jB r3 = new X.0jB
            r3.<init>()
            r12.A0m = r3
        L_0x015d:
            X.0j9 r1 = X.C271774jZ.A4p
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r3.A04(r1, r0)
            com.instagram.model.reels.Reel r1 = r15.A02
            X.3mM r6 = r15.A04
            com.instagram.common.session.UserSession r5 = r15.A01
            X.3uh r3 = r15.A03
            int r0 = r6.A03(r5, r3)
            boolean r0 = r1.A0v(r0)
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1I = r0
            boolean r0 = X.C309506Yn.A0A(r5, r3, r6)
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1L = r0
            boolean r0 = X.C309506Yn.A0A(r5, r3, r6)
            if (r0 == 0) goto L_0x04af
            X.1Xj r1 = r3.A0b
            if (r1 == 0) goto L_0x04af
            java.lang.String r0 = r1.A2l()
            r7 = 1
            if (r0 == 0) goto L_0x0489
            int r0 = r0.length()
            if (r0 == 0) goto L_0x0489
            X.1Xy r0 = r1.A0C
            X.41Z r0 = r0.BUC()
            if (r0 == 0) goto L_0x0489
            X.4hQ r0 = r0.At8()
            if (r0 == 0) goto L_0x0489
            com.instagram.api.schemas.MoreInfoStickerCTAType r0 = r0.AtM()
            if (r0 == 0) goto L_0x0489
        L_0x01b1:
            r0 = 1
        L_0x01b2:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1K = r0
            boolean r0 = X.C309506Yn.A0A(r5, r3, r6)
            r1 = 0
            if (r0 == 0) goto L_0x01e5
            X.1Xj r8 = r3.A0b
            if (r8 == 0) goto L_0x046a
            java.lang.String r0 = r8.A2l()
            if (r0 == 0) goto L_0x0457
            int r0 = r0.length()
            if (r0 == 0) goto L_0x0457
            X.1Xy r0 = r8.A0C
            X.41Z r0 = r0.BUC()
            if (r0 == 0) goto L_0x01e1
            X.4hQ r0 = r0.At8()
            if (r0 == 0) goto L_0x01e1
            com.instagram.api.schemas.MoreInfoStickerCTAType r1 = r0.AtM()
        L_0x01e1:
            java.lang.String r1 = java.lang.String.valueOf(r1)
        L_0x01e5:
            r12.A4x = r1
            boolean r1 = X.C309506Yn.A0A(r5, r3, r6)
            r0 = 0
            if (r1 == 0) goto L_0x0204
            X.1Xj r1 = r3.A0b
            if (r1 == 0) goto L_0x0204
            X.1Xy r0 = r1.A0C
            X.3lZ r0 = r0.getInjected()
            if (r0 == 0) goto L_0x0454
            com.instagram.api.schemas.IGCTATextVariant r0 = r0.BF0()
            if (r0 == 0) goto L_0x0454
            java.lang.String r0 = r0.AtR()
        L_0x0204:
            r12.A4v = r0
            boolean r1 = X.C309506Yn.A0A(r5, r3, r6)
            r0 = 0
            if (r1 == 0) goto L_0x0223
            X.1Xj r1 = r3.A0b
            if (r1 == 0) goto L_0x0223
            X.1Xy r0 = r1.A0C
            X.3lZ r0 = r0.getInjected()
            if (r0 == 0) goto L_0x0451
            com.instagram.api.schemas.IGCTATextVariant r0 = r0.BF0()
            if (r0 == 0) goto L_0x0451
            java.lang.Boolean r0 = r0.BAz()
        L_0x0223:
            r12.A15 = r0
            boolean r1 = X.C309506Yn.A0A(r5, r3, r6)
            r0 = 0
            if (r1 == 0) goto L_0x0242
            X.1Xj r1 = r3.A0b
            if (r1 == 0) goto L_0x0242
            X.1Xy r0 = r1.A0C
            X.3lZ r0 = r0.getInjected()
            if (r0 == 0) goto L_0x044e
            com.instagram.api.schemas.IGCTATextVariant r0 = r0.BF0()
            if (r0 == 0) goto L_0x044e
            java.lang.String r0 = r0.BKV()
        L_0x0242:
            r12.A4u = r0
            boolean r1 = X.C309506Yn.A0A(r5, r3, r6)
            r0 = 0
            if (r1 == 0) goto L_0x0265
            X.1Xj r1 = r3.A0b
            if (r1 == 0) goto L_0x0265
            X.1Xy r0 = r1.A0C
            X.3lZ r0 = r0.getInjected()
            if (r0 == 0) goto L_0x044b
            com.instagram.api.schemas.IGCTATextVariant r0 = r0.BF0()
            if (r0 == 0) goto L_0x044b
            com.instagram.api.schemas.IGCTATextVariantSource r0 = r0.C5d()
            if (r0 == 0) goto L_0x044b
            java.lang.String r0 = r0.A00
        L_0x0265:
            r12.A4w = r0
            boolean r0 = r3.A1f()
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1x = r0
            X.1Xj r7 = r3.A0b
            if (r7 == 0) goto L_0x027e
            X.1Xy r0 = r7.A0C
            X.3lx r1 = r0.C05()
            r0 = 1
            if (r1 != 0) goto L_0x027f
        L_0x027e:
            r0 = 0
        L_0x027f:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1O = r0
            if (r7 == 0) goto L_0x0448
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x0448
            java.lang.Boolean r1 = r0.BZi()
            r0 = 1
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            boolean r0 = X.0qQ.A0K(r1, r0)
        L_0x029c:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1M = r0
            if (r7 == 0) goto L_0x0445
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x0445
            java.lang.Boolean r1 = r0.BZj()
            r0 = 1
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            boolean r0 = X.0qQ.A0K(r1, r0)
        L_0x02b9:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1N = r0
            if (r7 == 0) goto L_0x02d0
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x02d0
            X.3lv r1 = r0.Auw()
            r0 = 1
            if (r1 != 0) goto L_0x02d1
        L_0x02d0:
            r0 = 0
        L_0x02d1:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A1J = r0
            if (r7 == 0) goto L_0x02ef
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x02ef
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x0442
            X.3lv r0 = r0.Auw()
            if (r0 == 0) goto L_0x0442
        L_0x02ef:
            r0 = 0
        L_0x02f0:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A16 = r0
            if (r7 == 0) goto L_0x043f
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x043f
            X.3lv r0 = r0.Auw()
            if (r0 == 0) goto L_0x043f
            java.lang.Float r0 = r0.CGt()
            if (r0 == 0) goto L_0x043f
            float r0 = r0.floatValue()
            double r0 = (double) r0
            java.lang.Double r0 = java.lang.Double.valueOf(r0)
        L_0x0315:
            r12.A2I = r0
            if (r7 == 0) goto L_0x043c
            X.1Xy r0 = r7.A0C
            X.3lx r0 = r0.C05()
            if (r0 == 0) goto L_0x043c
            X.3lv r0 = r0.Auw()
            if (r0 == 0) goto L_0x043c
            java.lang.Float r0 = r0.CHS()
            if (r0 == 0) goto L_0x043c
            float r0 = r0.floatValue()
            double r0 = (double) r0
            java.lang.Double r0 = java.lang.Double.valueOf(r0)
        L_0x0336:
            r12.A2J = r0
            float r0 = r4.A08
            double r0 = (double) r0
            java.lang.Double r0 = java.lang.Double.valueOf(r0)
            r12.A2K = r0
            float r0 = r4.A09
            double r0 = (double) r0
            java.lang.Double r0 = java.lang.Double.valueOf(r0)
            r12.A2L = r0
            java.util.ArrayList r0 = X.C309506Yn.A04(r5, r3, r6)
            r12.A7o = r0
            boolean r0 = X.C297785sK.A0I(r5, r3, r6)
            if (r0 == 0) goto L_0x035d
            boolean r1 = r3.A15()
            r0 = 1
            if (r1 == 0) goto L_0x035e
        L_0x035d:
            r0 = 0
        L_0x035e:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r12.A28 = r0
            X.1Xj r6 = r2.A0b
            if (r6 == 0) goto L_0x03a2
            X.1Xy r0 = r6.A0C
            java.lang.String r3 = r0.getDominantColor()
            if (r3 == 0) goto L_0x0386
            int r0 = r3.length()
            if (r0 <= 0) goto L_0x0386
            X.0jB r1 = r12.A0m
            if (r1 != 0) goto L_0x0381
            X.0jB r1 = new X.0jB
            r1.<init>()
            r12.A0m = r1
        L_0x0381:
            X.0j9 r0 = X.C271774jZ.A1i
            r1.A04(r0, r3)
        L_0x0386:
            X.0jB r5 = r12.A0m
            if (r5 != 0) goto L_0x0391
            X.0jB r5 = new X.0jB
            r5.<init>()
            r12.A0m = r5
        L_0x0391:
            X.0j9 r3 = X.C271774jZ.A0u
            int r0 = r6.A0n()
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r5.A04(r3, r0)
            r12.A0L(r6)
        L_0x03a2:
            boolean r0 = X.C316216lI.A0B(r10)
            if (r0 == 0) goto L_0x03af
            boolean r1 = X.C297785sK.A0N(r11, r2, r14)
            r0 = 1
            if (r1 == 0) goto L_0x03b0
        L_0x03af:
            r0 = 0
        L_0x03b0:
            X.0jB r2 = r12.A0m
            if (r2 != 0) goto L_0x03bb
            X.0jB r2 = new X.0jB
            r2.<init>()
            r12.A0m = r2
        L_0x03bb:
            X.0j9 r1 = X.C271774jZ.A4u
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r2.A04(r1, r0)
            java.util.Map r0 = r4.A0Z
            if (r0 == 0) goto L_0x04d8
            java.util.Collection r1 = r0.values()
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>(r1)
            java.util.List r1 = java.util.Collections.unmodifiableList(r0)
            if (r1 == 0) goto L_0x04d8
            boolean r0 = r1.isEmpty()
            if (r0 != 0) goto L_0x04d8
            java.util.ArrayList r2 = new java.util.ArrayList
            r2.<init>()
            java.util.Iterator r5 = r1.iterator()
        L_0x03e6:
            boolean r0 = r5.hasNext()
            if (r0 == 0) goto L_0x04c8
            java.lang.Object r4 = r5.next()
            X.Cw6 r4 = (X.C45426Cw6) r4
            r0 = 0
            X.0qQ.A0B(r4, r0)
            X.0jB r3 = new X.0jB
            r3.<init>()
            java.lang.String r1 = r4.A07
            java.lang.String r0 = "id"
            r3.A0A(r0, r1)
            java.lang.String r1 = r4.A08
            java.lang.String r0 = "type"
            r3.A0A(r0, r1)
            float r1 = r4.A06
            java.lang.String r0 = "width"
            r3.A08(r0, r1)
            float r1 = r4.A02
            java.lang.String r0 = "height"
            r3.A08(r0, r1)
            float r1 = r4.A00
            java.lang.String r0 = "center_x"
            r3.A08(r0, r1)
            float r1 = r4.A01
            java.lang.String r0 = "center_y"
            r3.A08(r0, r1)
            float r1 = r4.A03
            java.lang.String r0 = "rotation"
            r3.A08(r0, r1)
            float r0 = r4.A04
            java.lang.String r1 = "scale_x"
            r3.A08(r1, r0)
            float r0 = r4.A05
            r3.A08(r1, r0)
            r2.add(r3)
            goto L_0x03e6
        L_0x043c:
            r0 = 0
            goto L_0x0336
        L_0x043f:
            r0 = 0
            goto L_0x0315
        L_0x0442:
            r0 = 1
            goto L_0x02f0
        L_0x0445:
            r0 = 0
            goto L_0x02b9
        L_0x0448:
            r0 = 0
            goto L_0x029c
        L_0x044b:
            r0 = 0
            goto L_0x0265
        L_0x044e:
            r0 = 0
            goto L_0x0242
        L_0x0451:
            r0 = 0
            goto L_0x0223
        L_0x0454:
            r0 = 0
            goto L_0x0204
        L_0x0457:
            X.1Xy r0 = r8.A0C
            X.41Z r0 = r0.BUC()
            if (r0 == 0) goto L_0x046a
            X.4hQ r0 = r0.B7C()
            if (r0 == 0) goto L_0x046a
            com.instagram.api.schemas.MoreInfoProductTagType r7 = r0.BgU()
            goto L_0x046b
        L_0x046a:
            r7 = r1
        L_0x046b:
            com.instagram.api.schemas.MoreInfoProductTagType r0 = com.instagram.api.schemas.MoreInfoProductTagType.THUMBNAIL
            if (r7 == r0) goto L_0x0485
            if (r8 == 0) goto L_0x01e5
            X.1Xy r0 = r8.A0C
            X.41Z r0 = r0.BUC()
            if (r0 == 0) goto L_0x01e5
            X.4hQ r0 = r0.At8()
            if (r0 == 0) goto L_0x01e5
            com.instagram.api.schemas.MoreInfoProductTagType r0 = r0.BgU()
            if (r0 == 0) goto L_0x01e5
        L_0x0485:
            java.lang.String r1 = r0.A00
            goto L_0x01e5
        L_0x0489:
            java.util.ArrayList r0 = r1.A3K(r7)
            if (r0 == 0) goto L_0x04af
            boolean r0 = r0.isEmpty()
            if (r0 != 0) goto L_0x04af
            boolean r0 = X.C297785sK.A0S(r1)
            if (r0 != 0) goto L_0x01b1
            boolean r0 = X.C297785sK.A0T(r1)
            if (r0 != 0) goto L_0x01b1
            boolean r0 = X.C297785sK.A0P(r1)
            if (r0 != 0) goto L_0x01b1
            boolean r0 = X.C297785sK.A0Q(r1)
            if (r0 == 0) goto L_0x04af
            goto L_0x01b1
        L_0x04af:
            r0 = 0
            goto L_0x01b2
        L_0x04b2:
            r0 = 0
            goto L_0x014b
        L_0x04b5:
            r12.A40 = r0
            int r0 = r3.A01
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r12.A3R = r0
            goto L_0x0082
        L_0x04c2:
            r0 = 0
            goto L_0x0044
        L_0x04c5:
            r0 = 0
            goto L_0x0037
        L_0x04c8:
            X.0jB r1 = r12.A0m
            if (r1 != 0) goto L_0x04d3
            X.0jB r1 = new X.0jB
            r1.<init>()
            r12.A0m = r1
        L_0x04d3:
            java.lang.String r0 = "stickers"
            r1.A0B(r0, r2)
        L_0x04d8:
            X.0wX r0 = X.C61170le.A00
            X.0xm r0 = X.AnonymousClass0xl.A00(r0)
            int r0 = r0.A00()
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)
            r12.A2q = r0
            boolean r0 = X.AnonymousClass1GD.A03()
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)
            r12.A2u = r0
        L_0x04f2:
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: X.AnonymousClass3PI.A0A(android.content.Context, com.instagram.common.session.UserSession, X.3sc, X.1Nv, X.3BQ, X.GT8, X.6UP):void");
    }

    /* JADX WARNING: Code restructure failed: missing block: B:15:0x00d4, code lost:
        if (r1 > 0) goto L_0x00d6;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static final java.lang.String A01(com.instagram.common.session.UserSession r19, X.C233172vA r20, X.AnonymousClass4DU r21, X.C250973mM r22, X.1PW r23, java.lang.Integer r24, java.lang.Integer r25, java.lang.Integer r26, java.lang.String r27, java.lang.String r28, java.lang.String r29, java.util.List r30, int r31, int r32, boolean r33, boolean r34) {
        /*
            java.lang.String r5 = "Error converting event to json"
            r11 = 0
            r18 = 1
            r0 = 2
            r7 = r22
            X.0qQ.A0B(r7, r0)
            r0 = 7
            r2 = r24
            X.0qQ.A0B(r2, r0)
            r8 = r20
            java.lang.Long r17 = r8.A00()
            com.instagram.model.reels.Reel r10 = r7.A0H
            r14 = r21
            r0 = r27
            X.3sc r4 = X.C254513sb.A04(r10, r14, r0)
            r9 = r19
            boolean r0 = r10.A15(r9)
            if (r0 != 0) goto L_0x003c
            X.3uh r0 = r10.A0A(r9, r11)
            boolean r0 = r0.CWu()
            if (r0 == 0) goto L_0x003c
            X.3uh r0 = r10.A0A(r9, r11)
            X.1Xj r0 = r0.A0b
            r4.A0G(r9, r0)
        L_0x003c:
            r6 = r23
            int r0 = r6.A09
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A42 = r0
            int r0 = r6.A01
            r4.A06(r0)
            int r0 = r6.A0A
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A43 = r0
            int r0 = r6.A04
            r4.A0A(r0)
            X.2vm r0 = r10.A0b
            if (r0 == 0) goto L_0x022b
            r4.A0O(r0)
            int r0 = r10.A01
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A3z = r0
            r0 = r31
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A47 = r0
            int r0 = r6.A02
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A48 = r0
            r0 = r32
            r4.A07(r0)
            r4.A2r = r2
            boolean r0 = r6.A0H
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r4.A1p = r0
            X.0wX r0 = X.C61170le.A00
            X.0xm r0 = X.AnonymousClass0xl.A00(r0)
            int r0 = r0.A00()
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)
            r4.A2q = r0
            boolean r0 = X.AnonymousClass1GD.A03()
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)
            r4.A2u = r0
            long r15 = java.lang.System.currentTimeMillis()
            long r2 = r7.A0F
            r12 = 0
            int r0 = (r2 > r12 ? 1 : (r2 == r12 ? 0 : -1))
            if (r0 == 0) goto L_0x021f
            long r15 = r15 - r2
            java.lang.Long r0 = java.lang.Long.valueOf(r15)
            r4.A4E = r0
            if (r17 != 0) goto L_0x01b9
            r0 = 0
        L_0x00bb:
            r4.A2b = r0
            r0 = r28
            r4.A4M = r0
            java.lang.String r0 = r7.A0I
            r4.A6l = r0
            java.lang.String r0 = r7.A0J
            r4.A6m = r0
            java.lang.Long r0 = r8.A0N
            if (r0 == 0) goto L_0x00d6
            long r12 = r0.longValue()
            int r1 = (r12 > r2 ? 1 : (r12 == r2 ? 0 : -1))
            r0 = 1
            if (r1 <= 0) goto L_0x00d7
        L_0x00d6:
            r0 = 0
        L_0x00d7:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            r4.A2G = r0
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r33)
            r4.A1y = r0
            java.lang.String r0 = X.C233832wY.A00(r9)
            r4.A4S = r0
            boolean r0 = X.C228342lQ.A02(r9)
            if (r0 == 0) goto L_0x0107
            X.1Av r0 = X.1Au.A00(r9)
            X.1Az r0 = X.C228342lQ.A01(r0)
            java.lang.String r0 = r0.toString()
            r4.A4X = r0
            X.1Az r0 = X.C228342lQ.A00(r9)
            java.lang.String r0 = r0.toString()
            r4.A4Y = r0
        L_0x0107:
            java.lang.Long r0 = r8.A0N
            if (r0 == 0) goto L_0x011a
            long r2 = r0.longValue()
            long r0 = java.lang.System.currentTimeMillis()
            long r0 = r0 - r2
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A4F = r0
        L_0x011a:
            X.3Hd r0 = r10.A0X
            if (r0 == 0) goto L_0x012b
            java.lang.String r1 = r0.A02
            int r0 = r0.A00
            r4.A4P = r1
            long r0 = (long) r0
            java.lang.Long r0 = java.lang.Long.valueOf(r0)
            r4.A3b = r0
        L_0x012b:
            com.instagram.api.schemas.IntentAwareAdsInfo r0 = r10.A0B
            A04(r0, r4)
            java.lang.Integer r0 = X.AnonymousClass05K.A00
            java.lang.Integer r1 = r6.A0C
            if (r0 != r1) goto L_0x016f
            java.util.List r0 = r6.A00()
            r4.A80 = r0
            int r0 = r6.A03
            r4.A0G = r0
            if (r26 == 0) goto L_0x0148
            int r0 = r26.intValue()
            r4.A0T = r0
        L_0x0148:
            if (r25 == 0) goto L_0x0150
            int r0 = r25.intValue()
            r4.A0R = r0
        L_0x0150:
            r1 = r30
            if (r30 == 0) goto L_0x0161
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>(r1)
            r4.A7e = r0
            int r0 = r1.size()
            r4.A0S = r0
        L_0x0161:
            int r0 = r6.A08
            java.lang.Integer r0 = java.lang.Integer.valueOf(r0)
            r4.A37 = r0
            org.json.JSONObject r2 = new org.json.JSONObject
            r2.<init>()
            goto L_0x01c9
        L_0x016f:
            java.lang.Integer r0 = X.AnonymousClass05K.A01
            if (r0 != r1) goto L_0x0161
            java.util.List r0 = r6.A00()
            boolean r0 = r0.isEmpty()
            r0 = r0 ^ 1
            r3 = 0
            if (r0 == 0) goto L_0x018c
            java.util.List r0 = r6.A00()
            java.lang.Object r0 = r0.get(r11)
            java.lang.String r0 = (java.lang.String) r0
            r4.A7P = r0
        L_0x018c:
            int r0 = r6.A03
            r4.A08 = r0
            double r0 = r6.A00
            r4.A02 = r0
            X.3uh r0 = r7.A08(r9)
            X.1Xj r0 = r0.A0b
            if (r0 == 0) goto L_0x0161
            int r2 = r0.A0m()
            java.lang.String r1 = r0.A2p()
            r0 = -1
            if (r2 == r0) goto L_0x01ad
            java.lang.Integer r0 = java.lang.Integer.valueOf(r2)
            r4.A2k = r0
        L_0x01ad:
            int r0 = r1.length()
            if (r0 <= 0) goto L_0x01b4
            r3 = 1
        L_0x01b4:
            if (r3 == 0) goto L_0x0161
            r4.A6C = r1
            goto L_0x0161
        L_0x01b9:
            long r0 = java.lang.System.currentTimeMillis()
            long r12 = r17.longValue()
            long r0 = r0 - r12
            double r12 = (double) r0
            java.lang.Double r0 = java.lang.Double.valueOf(r12)
            goto L_0x00bb
        L_0x01c9:
            X.0xI r0 = r4.A00()     // Catch:{ JSONException -> 0x01f9 }
            X.0xF r7 = r0.A06     // Catch:{ JSONException -> 0x01f9 }
            r3 = 0
        L_0x01d0:
            X.0j0 r10 = r7.A00     // Catch:{ JSONException -> 0x01f9 }
            int r1 = r10.A00     // Catch:{ JSONException -> 0x01f9 }
            r0 = 0
            if (r3 >= r1) goto L_0x01d8
            r0 = 1
        L_0x01d8:
            if (r0 == 0) goto L_0x01fd
            java.lang.String r6 = r10.A03(r3)     // Catch:{ JSONException -> 0x01f9 }
            r0 = r3
            int r3 = r3 + 1
            java.lang.Object r1 = r10.A01(r0)     // Catch:{ JSONException -> 0x01f9 }
            android.util.Pair r0 = new android.util.Pair     // Catch:{ JSONException -> 0x01f9 }
            r0.<init>(r6, r1)     // Catch:{ JSONException -> 0x01f9 }
            java.lang.Object r1 = r0.first     // Catch:{ JSONException -> 0x01f4 }
            java.lang.String r1 = (java.lang.String) r1     // Catch:{ JSONException -> 0x01f4 }
            java.lang.Object r0 = r0.second     // Catch:{ JSONException -> 0x01f4 }
            r2.put(r1, r0)     // Catch:{ JSONException -> 0x01f4 }
            goto L_0x01d0
        L_0x01f4:
            r0 = move-exception
            X.0wb.A07(r5, r0)     // Catch:{ JSONException -> 0x01f9 }
            goto L_0x01d0
        L_0x01f9:
            r0 = move-exception
            X.0wb.A07(r5, r0)
        L_0x01fd:
            java.lang.Boolean r1 = r8.A03
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r18)
            boolean r0 = X.0qQ.A0K(r1, r0)
            if (r0 == 0) goto L_0x020f
            r0 = r29
            if (r29 == 0) goto L_0x020f
            r4.A5p = r0
        L_0x020f:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r34)
            r4.A1w = r0
            java.lang.Integer r0 = X.AnonymousClass05K.A01
            X.C233822wX.A0I(r9, r4, r14, r0)
            java.lang.String r0 = r2.toString()
            return r0
        L_0x021f:
            r0 = 472(0x1d8, float:6.61E-43)
            java.lang.String r1 = X.C273654mx.A00(r0)
            java.lang.IllegalStateException r0 = new java.lang.IllegalStateException
            r0.<init>(r1)
            throw r0
        L_0x022b:
            java.lang.String r1 = "Required value was null."
            java.lang.IllegalStateException r0 = new java.lang.IllegalStateException
            r0.<init>(r1)
            throw r0
        */
        throw new UnsupportedOperationException("Method not decompiled: X.AnonymousClass3PI.A01(com.instagram.common.session.UserSession, X.2vA, X.4DU, X.3mM, X.1PW, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.util.List, int, int, boolean, boolean):java.lang.String");
    }
}
