package X;

/* renamed from: X.819  reason: invalid class name */
public enum AnonymousClass819 implements AnonymousClass0Ac {
    ACTIONSHEET_SINGLE_SHARE_STORY("actionsheet_single_share_story"),
    BOTTOMSHEET_CCP_REELS("bottomsheet_ccp_reels"),
    BOTTOMSHEET_CCP_REELS_AGGREGATED_FEEDBACK_DISCLOSURE("bottomsheet_ccp_reels_aggregated_feedback_disclosure"),
    BOTTOMSHEET_CCP_SHARE_LATER_REELS("bottomsheet_ccp_share_later_reels"),
    BOTTOMSHEET_CLOSE_FRIENDS_STORY_FEED("bottomsheet_close_friends_story_feed"),
    BOTTOMSHEET_CROSSPOSTING_UPSELL_SNOOZE("bottomsheet_crossposting_upsell_snooze"),
    BOTTOMSHEET_DUAL_DESTPICKER_STORIES("bottomsheet_dual_destpicker_stories"),
    BOTTOMSHEET_FEED("bottomsheet_feed"),
    BOTTOMSHEET_FEED_REEL_CCP_MIGRATION_STORY("bottomsheet_feed_reel_ccp_migration_story"),
    BOTTOMSHEET_FEED_THREADS("BOTTOMSHEET_FEED_THREADS"),
    BOTTOMSHEET_FEED_THREADS_CONFIRMATION("BOTTOMSHEET_FEED_THREADS_CONFIRMATION"),
    BOTTOMSHEET_FEED_THREADS_NEW_USER_ACTIVATION("BOTTOMSHEET_FEED_THREADS_NEW_USER_ACTIVATION "),
    BOTTOMSHEET_META_BUSINESS_SUITE_STORY("bottomsheet_meta_business_suite_story"),
    BOTTOMSHEET_MIGRATION_FEED_WAVE2("bottomsheet_migration_feed_wave2"),
    BOTTOMSHEET_MIGRATION_STORIES_WAVE2("bottomsheet_migration_stories_wave2"),
    BOTTOMSHEET_PANAVISION_DISCLOSURE("bottomsheet_panavision_disclosure"),
    BOTTOMSHEET_REEL_CCP_MIGRATION_FEED("bottomsheet_reel_ccp_migration_feed"),
    BOTTOMSHEET_REEL_CCP_MIGRATION_STORY("bottomsheet_reel_ccp_migration_story"),
    BOTTOMSHEET_SHARE_LATER_FEED("bottomsheet_share_later_feed"),
    BOTTOMSHEET_SHARE_LATER_STORY("bottomsheet_share_later_story"),
    BOTTOMSHEET_STORY("bottomsheet_story"),
    BOTTOMSHEET_STORY_REEL_CCP_MIGRATION_FEED("bottomsheet_story_reel_ccp_migration_feed"),
    BOTTOMSHEET_UNIFIED_STORIES_FEED("bottomsheet_unified_stories_feed"),
    BOTTOMSHEET_UNIFIED_STORIES_FEED_REELS("bottomsheet_unified_stories_feed_reels"),
    BOTTOMSHEET_UNLINKED_USER_EVERGREEN_STORY("BOTTOMSHEET_UNLINKED_USER_EVERGREEN_STORY"),
    BOTTOMSHEET_UNLINKED_USER_FEED("bottomsheet_unlinked_user_feed"),
    BOTTOMSHEET_UNLINKED_USER_STORY("bottomsheet_unlinked_user_story"),
    BOTTOMSHEET_XAR_CCP_MIGRATION_REELS("bottomsheet_xar_ccp_migration_reels"),
    BOTTOMSHEET_XAR_CCP_MIGRATION_REELS_V2("bottomsheet_xar_ccp_migration_reels_v2"),
    BOTTOMSHEET_XAR_CCP_MIGRATION_REELS_V3("bottomsheet_xar_ccp_migration_reels_v3"),
    BOTTOMSHEET_XAR_REELS("bottomsheet_xar_reels"),
    BOTTOMSHEET_XAR_SHARE_LATER_REELS("bottomsheet_xar_share_later_reels"),
    BOTTOMSHEET_XAR_USERS_STORIES_FEED_V1("bottomsheet_xar_users_stories_feed_v1"),
    BOTTOMSHEET_XAR_USERS_STORIES_FEED_V2("bottomsheet_xar_users_stories_feed_v2"),
    BOTTOMSHEET_XAR_USERS_STORIES_FEED_V3("bottomsheet_xar_users_stories_feed_v3"),
    BOTTOMSHEET_XPOSTING_CHANNEL_CONTROLS("bottomsheet_xposting_channels_controls"),
    BOTTOMSHEET_XPOSTING_CHANNELS("bottomsheet_xposting_channels"),
    DIALOG_3_OPTION_STORY("dialog_3_option_story"),
    DIALOG_3_OPTION_TURN_OFF_STORY("dialog_3_option_turn_off_story"),
    DIALOG_AUTO_OFF_ONE_TIME_SHARE_ON_STORY("dialog_auto_off_one_time_share_on_story"),
    DIALOG_AUTO_ON_ONE_TIME_SHARE_OFF_STORY("dialog_auto_on_one_time_share_off_story"),
    DIALOG_FEED("dialog_feed"),
    DIALOG_SHARE_LATER_FEED("DIALOG_SHARE_LATER_FEED"),
    DIALOG_SINGLE_CCP_REEL("dialog_single_ccp_reel"),
    DIALOG_SINGLE_XAR_REEL("dialog_single_xar_reel"),
    DIALOG_STORY("dialog_story"),
    DIALOG_STORY_SHARE_SHEET_ACCOUNT_LINKING("dialog_story_share_sheet_account_linking"),
    FULLSCREEN_INCENTIVES_XAR_REELS("fullscreen_incentives_xar_reels"),
    FULLSCREEN_UNIFIED_STORIES_FEED("fullscreen_unified_stories_feed"),
    MESSAGE_FOOTER_XPOSTING_CHANNELS("message_footer_xposting_channels"),
    ROWSHARE_AUTO_SETTING_FEED("rowshare_auto_setting_feed"),
    ROWSHARE_AUTO_SETTING_STORY("rowshare_auto_setting_story"),
    ROWSHARE_SINGLE_CCP_REEL("rowshare_single_ccp_reel"),
    ROWSHARE_SINGLE_FEED("rowshare_single_feed"),
    ROWSHARE_SINGLE_STORY("rowshare_single_story"),
    ROWSHARE_SINGLE_XAR_REEL("rowshare_single_xar_reel"),
    TOOLTIP_AUTOSHARE_FEED("tooltip_autoshare_feed"),
    TOOLTIP_CURRENTLY_SHARING_FEED("tooltip_currently_sharing_feed"),
    TOOLTIP_NUX_STORIES("tooltip_nux_stories"),
    TOOLTIP_SHARE_LATER_REELS("tooltip_share_later_reels"),
    TOOLTIP_SHARE_SHEET_CCP_REELS("tooltip_share_sheet_ccp_reels"),
    TOOLTIP_SHORTCUT_DESTINATION_PICKER_NOT_SHARING_STORIES("tooltip_shortcut_destination_picker_not_sharing_stories"),
    TOOLTIP_SHORTCUT_DESTINATION_PICKER_STORIES("tooltip_shortcut_destination_picker_stories"),
    TOOLTIP_XPOSTING_CHANNELS("tooltip_xposting_channels");
    
    public final String A00;

    /* access modifiers changed from: public */
    AnonymousClass819(String str) {
        this.A00 = str;
    }
}
