package X;

/* renamed from: X.779  reason: invalid class name */
public enum AnonymousClass779 {
    UNSUPPORTED,
    IG_SINGLE_IMAGE_POST_SHARE,
    IG_MULTIPOST_SHARE,
    IG_STORY_REPLY,
    IG_STORY_PHOTO_SHARE,
    IG_STORY_PHOTO_MENTION,
    IG_CLIPS_SHARE,
    IG_SINGLE_VIDEO_POST_SHARE,
    IG_STORY_VIDEO_SHARE,
    IG_STORY_REACTION,
    IG_IGTV_SHARE,
    IG_SHOP_SHARE,
    IG_PROFILE_SHARE,
    IG_STORY_PHOTO_HIGHLIGHT_SHARE,
    IG_STORY_VIDEO_HIGHLIGHT_SHARE,
    IG_STORY_VIDEO_MENTION,
    IG_STORY_HIGHLIGHT_REPLY,
    IG_STORY_HIGHLIGHT_REACTION,
    IG_EXTERNAL_LINK,
    IG_RECEIVER_FETCH,
    FB_FEED_SHARE,
    FB_STORY_REPLY,
    FB_STORY_SHARE,
    FB_STORY_MENTION,
    FB_FEED_VIDEO_SHARE,
    FB_GAMING_CUSTOM_UPDATE,
    FB_PRODUCER_STORY_REPLY,
    FB_EVENT,
    MSG_EXTERNAL_LINK_SHARE,
    MSG_P2P_PAYMENT,
    MSG_LOCATION_SHARING,
    RTC_AUDIO_CALL,
    RTC_VIDEO_CALL,
    RTC_MISSED_AUDIO_CALL,
    RTC_MISSED_VIDEO_CALL,
    RTC_GROUP_AUDIO_CALL,
    RTC_GROUP_VIDEO_CALL,
    RTC_MISSED_GROUP_AUDIO_CALL,
    RTC_MISSED_GROUP_VIDEO_CALL,
    DATACLASS_SENDER_COPY;

    /* access modifiers changed from: public */
    static {
        AnonymousClass779[] r1;
        A00 = 0oU.A00(r1);
    }
}
