package X;

import com.instagram.api.schemas.MediaGenAIDetectionMethod;
import com.instagram.creation.capture.quickcapture.analytics.common.ShareMediaLoggingInfo;
import com.instagram.model.venue.Venue;
import com.instagram.music.common.model.AudioOverlayTrack;
import com.instagram.user.model.UpcomingEvent;
import java.util.List;

/* renamed from: X.9OY  reason: invalid class name */
public final class AnonymousClass9OY extends AnonymousClass0T0 {
    public final int A00;
    public final long A01;
    public final long A02;
    public final long A03;
    public final long A04;
    public final C381689cA A05;
    public final C61080JwI A06;
    public final C61062Jw0 A07;
    public final C61100JxB A08;
    public final MediaGenAIDetectionMethod A09;
    public final C279584ys A0A;
    public final ShareMediaLoggingInfo A0B;
    public final C370018vh A0C;
    public final C63815L7w A0D;
    public final AnonymousClass9P8 A0E;
    public final C357588Yu A0F;
    public final C2801950r A0G;
    public final C388649oA A0H;
    public final C61000Juw A0I;
    public final C377999Ob A0J;
    public final C381639c5 A0K;
    public final AnonymousClass3QO A0L;
    public final Venue A0M;
    public final AudioOverlayTrack A0N;
    public final C272024jy A0O;
    public final UpcomingEvent A0P;
    public final String A0Q;
    public final String A0R;
    public final String A0S;
    public final String A0T;
    public final String A0U;
    public final String A0V;
    public final String A0W;
    public final String A0X;
    public final String A0Y;
    public final String A0Z;
    public final String A0a;
    public final String A0b;
    public final String A0c;
    public final String A0d;
    public final String A0e;
    public final List A0f;
    public final List A0g;
    public final List A0h;
    public final List A0i;
    public final List A0j;
    public final List A0k;
    public final List A0l;
    public final List A0m;
    public final boolean A0n;
    public final boolean A0o;
    public final boolean A0p;
    public final boolean A0q;
    public final boolean A0r;
    public final boolean A0s;
    public final boolean A0t;
    public final boolean A0u;
    public final boolean A0v;
    public final boolean A0w;
    public final boolean A0x;
    public final boolean A0y;
    public final boolean A0z;
    public final LMS A10;
    public final AudioOverlayTrack A11;
    public final List A12;

    public AnonymousClass9OY(C381689cA r10, C61080JwI jwI, C61062Jw0 jw0, C61100JxB jxB, MediaGenAIDetectionMethod mediaGenAIDetectionMethod, C279584ys r15, ShareMediaLoggingInfo shareMediaLoggingInfo, C370018vh r17, C63815L7w l7w, AnonymousClass9P8 r19, C357588Yu r20, C2801950r r21, C388649oA r22, C61000Juw juw, LMS lms, C377999Ob r25, C381639c5 r26, AnonymousClass3QO r27, Venue venue, AudioOverlayTrack audioOverlayTrack, AudioOverlayTrack audioOverlayTrack2, C272024jy r31, UpcomingEvent upcomingEvent, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, List list, List list2, List list3, List list4, List list5, List list6, List list7, List list8, List list9, int i, long j, long j2, long j3, long j4, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13) {
        List list10 = list;
        String str16 = str;
        AnonymousClass7TF.A1G(str16, 1, list10);
        String str17 = str4;
        0qQ.A0B(str17, 18);
        List list11 = list3;
        0qQ.A0B(list11, 23);
        List list12 = list4;
        0qQ.A0B(list12, 27);
        List list13 = list7;
        0qQ.A0B(list13, 35);
        List list14 = list8;
        0qQ.A0B(list14, 53);
        List list15 = list9;
        0qQ.A0B(list15, 54);
        this.A0W = str16;
        this.A0G = r21;
        this.A04 = j;
        this.A03 = j2;
        this.A01 = j3;
        this.A02 = j4;
        this.A0z = z;
        this.A0b = str2;
        this.A0m = list10;
        this.A12 = list2;
        this.A0N = audioOverlayTrack;
        this.A11 = audioOverlayTrack2;
        this.A0e = str3;
        this.A0C = r17;
        this.A0B = shareMediaLoggingInfo;
        this.A0E = r19;
        this.A0Q = str17;
        this.A0S = str5;
        this.A05 = r10;
        this.A0w = z2;
        this.A0U = str6;
        this.A0k = list11;
        this.A0O = r31;
        this.A0L = r27;
        this.A0R = str7;
        this.A0g = list12;
        this.A0T = str8;
        this.A0M = venue;
        this.A0d = str9;
        this.A0j = list5;
        this.A0f = list6;
        this.A0A = r15;
        this.A0x = z3;
        this.A0i = list13;
        this.A0P = upcomingEvent;
        this.A0X = str10;
        this.A0V = str11;
        this.A0Y = str12;
        this.A0F = r20;
        this.A0H = r22;
        this.A10 = lms;
        this.A0o = z4;
        this.A0D = l7w;
        this.A07 = jw0;
        this.A0K = r26;
        this.A0r = z5;
        this.A0q = z6;
        this.A0t = z7;
        this.A0v = z8;
        this.A0s = z9;
        this.A0h = list14;
        this.A0l = list15;
        this.A0c = str13;
        this.A00 = i;
        this.A0J = r25;
        this.A0p = z10;
        this.A0a = str14;
        this.A0Z = str15;
        this.A0I = juw;
        this.A08 = jxB;
        this.A06 = jwI;
        this.A0n = z11;
        this.A09 = mediaGenAIDetectionMethod;
        this.A0u = z12;
        this.A0y = z13;
    }
}
