package X;

import com.instagram.direct.capabilities.Capabilities;

/* renamed from: X.9HC  reason: invalid class name */
public final class AnonymousClass9HC {
    public static final AnonymousClass9HD A1b = new Object();
    public final int A00;
    public final Capabilities A01;
    public final AnonymousClass0eM A02;
    public final AnonymousClass0eM A03;
    public final AnonymousClass0eM A04;
    public final AnonymousClass0eM A05;
    public final AnonymousClass0eM A06;
    public final AnonymousClass0eM A07;
    public final AnonymousClass0eM A08;
    public final AnonymousClass0eM A09;
    public final AnonymousClass0eM A0A;
    public final AnonymousClass0eM A0B;
    public final AnonymousClass0eM A0C;
    public final AnonymousClass0eM A0D;
    public final AnonymousClass0eM A0E;
    public final AnonymousClass0eM A0F;
    public final AnonymousClass0eM A0G;
    public final AnonymousClass0eM A0H;
    public final AnonymousClass0eM A0I;
    public final AnonymousClass0eM A0J;
    public final AnonymousClass0eM A0K;
    public final AnonymousClass0eM A0L;
    public final AnonymousClass0eM A0M;
    public final AnonymousClass0eM A0N;
    public final AnonymousClass0eM A0O;
    public final AnonymousClass0eM A0P;
    public final AnonymousClass0eM A0Q;
    public final AnonymousClass0eM A0R;
    public final AnonymousClass0eM A0S;
    public final AnonymousClass0eM A0T;
    public final AnonymousClass0eM A0U;
    public final AnonymousClass0eM A0V;
    public final AnonymousClass0eM A0W;
    public final AnonymousClass0eM A0X;
    public final AnonymousClass0eM A0Y;
    public final AnonymousClass0eM A0Z;
    public final AnonymousClass0eM A0a;
    public final AnonymousClass0eM A0b;
    public final AnonymousClass0eM A0c;
    public final AnonymousClass0eM A0d;
    public final AnonymousClass0eM A0e;
    public final AnonymousClass0eM A0f;
    public final AnonymousClass0eM A0g;
    public final AnonymousClass0eM A0h;
    public final AnonymousClass0eM A0i;
    public final AnonymousClass0eM A0j;
    public final AnonymousClass0eM A0k;
    public final AnonymousClass0eM A0l;
    public final AnonymousClass0eM A0m;
    public final AnonymousClass0eM A0n;
    public final AnonymousClass0eM A0o;
    public final AnonymousClass0eM A0p;
    public final AnonymousClass0eM A0q;
    public final AnonymousClass0eM A0r;
    public final AnonymousClass0eM A0s;
    public final AnonymousClass0eM A0t;
    public final AnonymousClass0eM A0u;
    public final AnonymousClass0eM A0v;
    public final AnonymousClass0eM A0w;
    public final AnonymousClass0eM A0x;
    public final AnonymousClass0eM A0y;
    public final AnonymousClass0eM A0z;
    public final AnonymousClass0eM A10;
    public final AnonymousClass0eM A11;
    public final AnonymousClass0eM A12;
    public final AnonymousClass0eM A13;
    public final AnonymousClass0eM A14;
    public final AnonymousClass0eM A15;
    public final AnonymousClass0eM A16;
    public final AnonymousClass0eM A17;
    public final AnonymousClass0eM A18;
    public final AnonymousClass0eM A19;
    public final AnonymousClass0eM A1A;
    public final AnonymousClass0eM A1B;
    public final AnonymousClass0eM A1C;
    public final AnonymousClass0eM A1D;
    public final AnonymousClass0eM A1E;
    public final AnonymousClass0eM A1F;
    public final AnonymousClass0eM A1G;
    public final AnonymousClass0eM A1H;
    public final AnonymousClass0eM A1I;
    public final AnonymousClass0eM A1J;
    public final AnonymousClass0eM A1K;
    public final AnonymousClass0eM A1L;
    public final AnonymousClass0eM A1M;
    public final AnonymousClass0eM A1N;
    public final AnonymousClass0eM A1O;
    public final AnonymousClass0eM A1P;
    public final AnonymousClass0eM A1Q;
    public final AnonymousClass0eM A1R;
    public final AnonymousClass0eM A1S;
    public final boolean A1T;
    public final boolean A1U;
    public final boolean A1V;
    public final boolean A1W;
    public final boolean A1X;
    public final boolean A1Y;
    public final boolean A1Z;
    public final AnonymousClass0eM A1a;

    public AnonymousClass9HC(Capabilities capabilities, AnonymousClass0eM r3, AnonymousClass0eM r4, AnonymousClass0eM r5, AnonymousClass0eM r6, AnonymousClass0eM r7, AnonymousClass0eM r8, AnonymousClass0eM r9, AnonymousClass0eM r10, AnonymousClass0eM r11, AnonymousClass0eM r12, AnonymousClass0eM r13, AnonymousClass0eM r14, AnonymousClass0eM r15, AnonymousClass0eM r16, AnonymousClass0eM r17, AnonymousClass0eM r18, AnonymousClass0eM r19, AnonymousClass0eM r20, AnonymousClass0eM r21, AnonymousClass0eM r22, AnonymousClass0eM r23, AnonymousClass0eM r24, AnonymousClass0eM r25, AnonymousClass0eM r26, AnonymousClass0eM r27, AnonymousClass0eM r28, AnonymousClass0eM r29, AnonymousClass0eM r30, AnonymousClass0eM r31, AnonymousClass0eM r32, AnonymousClass0eM r33, AnonymousClass0eM r34, AnonymousClass0eM r35, AnonymousClass0eM r36, AnonymousClass0eM r37, AnonymousClass0eM r38, AnonymousClass0eM r39, AnonymousClass0eM r40, AnonymousClass0eM r41, AnonymousClass0eM r42, AnonymousClass0eM r43, AnonymousClass0eM r44, AnonymousClass0eM r45, AnonymousClass0eM r46, AnonymousClass0eM r47, AnonymousClass0eM r48, AnonymousClass0eM r49, AnonymousClass0eM r50, AnonymousClass0eM r51, AnonymousClass0eM r52, AnonymousClass0eM r53, AnonymousClass0eM r54, AnonymousClass0eM r55, AnonymousClass0eM r56, AnonymousClass0eM r57, AnonymousClass0eM r58, AnonymousClass0eM r59, AnonymousClass0eM r60, AnonymousClass0eM r61, AnonymousClass0eM r62, AnonymousClass0eM r63, AnonymousClass0eM r64, AnonymousClass0eM r65, AnonymousClass0eM r66, AnonymousClass0eM r67, AnonymousClass0eM r68, AnonymousClass0eM r69, AnonymousClass0eM r70, AnonymousClass0eM r71, AnonymousClass0eM r72, AnonymousClass0eM r73, AnonymousClass0eM r74, AnonymousClass0eM r75, AnonymousClass0eM r76, AnonymousClass0eM r77, AnonymousClass0eM r78, AnonymousClass0eM r79, AnonymousClass0eM r80, AnonymousClass0eM r81, AnonymousClass0eM r82, AnonymousClass0eM r83, AnonymousClass0eM r84, AnonymousClass0eM r85, AnonymousClass0eM r86, AnonymousClass0eM r87, AnonymousClass0eM r88, AnonymousClass0eM r89, AnonymousClass0eM r90, AnonymousClass0eM r91, AnonymousClass0eM r92, int i, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7) {
        this.A01 = capabilities;
        this.A02 = r3;
        this.A1D = r4;
        this.A1E = r5;
        this.A1F = r6;
        this.A03 = r7;
        this.A04 = r8;
        this.A06 = r9;
        this.A1L = r10;
        this.A0y = r11;
        this.A1A = r12;
        this.A12 = r13;
        this.A15 = r14;
        this.A11 = r15;
        this.A0f = r16;
        this.A1X = z;
        this.A1B = r17;
        this.A1Y = z2;
        this.A0O = r18;
        this.A0P = r19;
        this.A0T = r20;
        this.A0n = r21;
        this.A0B = r22;
        this.A13 = r23;
        this.A05 = r24;
        this.A0N = r25;
        this.A0S = r26;
        this.A10 = r27;
        this.A08 = r28;
        this.A0L = r29;
        this.A0R = r30;
        this.A0b = r31;
        this.A09 = r32;
        this.A0Z = r33;
        this.A0Y = r34;
        this.A07 = r35;
        this.A0J = r36;
        this.A0W = r37;
        this.A0X = r38;
        this.A0U = r39;
        this.A0V = r40;
        this.A0p = r41;
        this.A0K = r42;
        this.A19 = r43;
        this.A0o = r44;
        this.A1C = r45;
        this.A0w = r46;
        this.A0t = r47;
        this.A0r = r48;
        this.A0s = r49;
        this.A0Q = r50;
        this.A1V = z3;
        this.A1U = z4;
        this.A1Q = r51;
        this.A0q = r52;
        this.A0e = r53;
        this.A1W = z5;
        this.A1a = r54;
        this.A00 = i;
        this.A0H = r55;
        this.A1Z = z6;
        this.A1J = r56;
        this.A1P = r57;
        this.A0k = r58;
        this.A0i = r59;
        this.A0l = r60;
        this.A0j = r61;
        this.A1R = r62;
        this.A1S = r63;
        this.A0z = r64;
        this.A14 = r65;
        this.A1T = z7;
        this.A1M = r66;
        this.A0E = r67;
        this.A1N = r68;
        this.A1K = r69;
        this.A0I = r70;
        this.A1O = r71;
        this.A0M = r72;
        this.A0a = r73;
        this.A0u = r74;
        this.A0v = r75;
        this.A1G = r76;
        this.A0h = r77;
        this.A18 = r78;
        this.A17 = r79;
        this.A0g = r80;
        this.A0m = r81;
        this.A0x = r82;
        this.A0c = r83;
        this.A1I = r84;
        this.A1H = r85;
        this.A0F = r86;
        this.A0A = r87;
        this.A0G = r88;
        this.A0d = r89;
        this.A16 = r90;
        this.A0C = r91;
        this.A0D = r92;
    }
}
