package X;

/* renamed from: X.7GM  reason: invalid class name */
public enum AnonymousClass7GM {
    PERMISSIONS,
    PERMISSIONS_THREAD,
    DISABLED,
    THREAD,
    BLOCKED,
    FEATURE_LIMITED,
    ENFORCEMENT_NOTICE,
    ARMADILLO_PROFESSIONAL_FEATURE_LIMITED,
    PROFESSIONAL_HMPS_LIMITED,
    BROADCAST_CHAT_LIMITED,
    SOCIAL_CHAT_LIMITED,
    NULL_THREAD_LIMITED,
    DISABLED_OLD_BUILDS,
    XAC_READ_ONLY,
    EPHEMERAL_MODE_DISABLED_COMPOSER,
    DELETE_MESSAGE,
    REACHABILITY_COMPOSER_BLOCK,
    META_AI_NUX_COMPOSER_BLOCK,
    LIGHTWEIGHT_INTERVENTION_AND_APPEAL_COMPOSER_BLOCK,
    REACHABLE_USER_COMPOSER_BLOCK;

    /* access modifiers changed from: public */
    static {
        AnonymousClass7GM[] r0;
        A00 = 0oU.A00(r0);
    }
}
