package X;

/* renamed from: X.337  reason: invalid class name */
public enum AnonymousClass337 {
    FEED_REEL_VIEWER_TALL_VIDEO,
    FEED_REEL_VIEWER_OTHER_RESOLUTION,
    FEED_WATCH_AND_BROWSE,
    CLIPS_FEED_WATCH_AND_BROWSE,
    CLIPS_FEED_WATCH_AND_BROWSE_WITH_CHAINING,
    CLIPS_FEED_TALL_VIDEO_WATCH_AND_BROWSE_WITH_CHAINING,
    CLIPS_FEED_WATCH_AND_BROWSE_LEADGEN,
    EXPLORE_FEED_WATCH_AND_BROWSE,
    EXPLORE_GRID_WATCH_AND_BROWSE,
    EXPLORE_FEED_SEED_AD,
    CLIPS_MULTI_ADS_WATCH_AND_BROWSE,
    CLIPS_OVERLAY_WATCH_MORE_REELS,
    FEED_OF_ADS,
    SEED_AD,
    FEED_PAE_MULTI_ADS_WATCH_AND_BROWSE,
    FEED_SA_MULTI_ADS_WATCH_AND_BROWSE;

    /* access modifiers changed from: public */
    static {
        AnonymousClass337[] r0;
        A00 = 0oU.A00(r0);
    }
}
