package X;

/* renamed from: X.5OZ  reason: invalid class name */
public enum AnonymousClass5OZ {
    UNKNOWN("UNKNOWN"),
    GROOT_INFRA("GROOT_INFRA"),
    PLAYER_ERROR("PLAYER_ERROR"),
    PLAYER_WARNING("PLAYER_WARNING"),
    PLAYBACK_ANOMALY("PLAYBACK_ANOMALY"),
    DECODER("DECODER"),
    NETWORK("NETWORK"),
    NETWORK_SOURCE("NETWORK_SOURCE"),
    EXOPLAYER2_SOURCE("EXOPLAYER2_SOURCE"),
    EXOPLAYER2_UNEXPECTED("EXOPLAYER2_UNEXPECTED"),
    EXOPLAYER2_RENDERER("EXOPLAYER2_RENDERER"),
    EXOPLAYER2_UNEXPECTED_STOP_LOADING("EXOPLAYER2_UNEXPECTED_STOP_LOADING"),
    PREFETCH_MANAGER("PREFETCH_MANAGER"),
    MANIFEST("MANIFEST"),
    RENDERER("RENDERER"),
    CACHE("CACHE"),
    EXOPLAYER2_PREFETCH("EXOPLAYER2_PREFETCH"),
    DRM("DRM"),
    AUDIO("AUDIO"),
    BLACK_SCREEN("BLACK_SCREEN"),
    GROOT_PLUGINS("GROOT_PLUGINS"),
    BLACK_SCREEN_AFTER_PLAY("BLACK_SCREEN_AFTER_PLAY"),
    AV1_INSTANTIATION("AV1_INSTANTIATION"),
    FAILOVER("FAILOVER"),
    ATOM_PARSE("ATOM_PARSE"),
    HERO_SERVICE("HERO_SERVICE"),
    JSON_PARSING("JSON_PARSING"),
    CAPTIONING("CAPTIONING"),
    EMSG("EMSG"),
    MIXED_CODEC_MANIFEST("MIXED_CODEC_MANIFEST"),
    MEDIA_CODEC_RENDERER_UPGRADE("MEDIA_CODEC_RENDERER_UPGRADE"),
    PLAYER_RELEASE_TIMEOUT("PLAYER_RELEASE_TIMEOUT"),
    PLAYER_EXTERNAL_ERROR("PLAYER_EXTERNAL_ERROR");
    
    public final String A00;

    /* access modifiers changed from: public */
    AnonymousClass5OZ(String str) {
        this.A00 = str;
    }

    public static AnonymousClass5OZ A00(String str) {
        try {
            return valueOf(str);
        } catch (IllegalArgumentException | NullPointerException unused) {
            return UNKNOWN;
        }
    }
}
