package X;

import com.google.android.gms.common.Feature;

/* renamed from: X.RnI  reason: case insensitive filesystem */
public abstract class C10141RnI {
    public static final Feature A00;
    public static final Feature A01;
    public static final Feature A02;
    public static final Feature A03;
    public static final Feature A04;
    public static final Feature A05;
    public static final Feature A06;
    public static final Feature A07;
    public static final Feature A08;
    public static final Feature A09;
    public static final Feature A0A;
    public static final Feature A0B;
    public static final Feature A0C;
    public static final Feature A0D;
    public static final Feature A0E;
    public static final Feature A0F;
    public static final Feature A0G;
    public static final Feature A0H;
    public static final Feature A0I;
    public static final Feature A0J;
    public static final Feature A0K;
    public static final Feature A0L;
    public static final Feature A0M;
    public static final Feature A0N;
    public static final Feature A0O;
    public static final Feature A0P;
    public static final Feature A0Q;
    public static final Feature A0R;
    public static final Feature A0S;
    public static final Feature[] A0T;

    static {
        Feature A0X = Pxe.A0X("cancel_target_direct_transfer", 1);
        A03 = A0X;
        Feature A0X2 = Pxe.A0X("delete_credential", 1);
        A04 = A0X2;
        Feature A0X3 = Pxe.A0X("delete_device_public_key", 1);
        A05 = A0X3;
        Feature A0X4 = Pxe.A0X("get_or_generate_device_public_key", 1);
        A06 = A0X4;
        Feature A0X5 = Pxe.A0X("get_passkeys", 1);
        A07 = A0X5;
        Feature A0X6 = Pxe.A0X("update_passkey", 1);
        A08 = A0X6;
        Feature A0X7 = Pxe.A0X("is_user_verifying_platform_authenticator_available_for_credential", 1);
        A09 = A0X7;
        Feature A0X8 = Pxe.A0X("is_user_verifying_platform_authenticator_available", 1);
        A0A = A0X8;
        Feature A0X9 = Pxe.A0X("privileged_api_list_credentials", 2);
        A0B = A0X9;
        Feature A0X10 = Pxe.A0X("start_target_direct_transfer", 1);
        A0C = A0X10;
        Feature A0X11 = Pxe.A0X("first_party_api_get_link_info", 1);
        A0D = A0X11;
        Feature A0X12 = Pxe.A0X("zero_party_api_register", 3);
        A0E = A0X12;
        Feature A0X13 = Pxe.A0X("zero_party_api_sign", 3);
        A0F = A0X13;
        Feature A0X14 = Pxe.A0X("zero_party_api_list_discoverable_credentials", 2);
        A0G = A0X14;
        Feature A0X15 = Pxe.A0X("zero_party_api_authenticate_passkey", 3);
        A0H = A0X15;
        Feature A0X16 = Pxe.A0X("zero_party_api_register_passkey", 1);
        A0I = A0X16;
        Feature A0X17 = Pxe.A0X("zero_party_api_register_passkey_with_sync_account", 1);
        A0J = A0X17;
        Feature A0X18 = Pxe.A0X("zero_party_api_get_hybrid_client_registration_pending_intent", 1);
        A0K = A0X18;
        Feature A0X19 = Pxe.A0X("zero_party_api_get_hybrid_client_sign_pending_intent", 1);
        A0L = A0X19;
        Feature A0X20 = Pxe.A0X("get_browser_hybrid_client_sign_pending_intent", 1);
        A0M = A0X20;
        Feature A0X21 = Pxe.A0X("get_browser_hybrid_client_registration_pending_intent", 1);
        A0N = A0X21;
        Feature A0X22 = Pxe.A0X("privileged_authenticate_passkey", 2);
        A0O = A0X22;
        Feature A0X23 = Pxe.A0X("privileged_register_passkey_with_sync_account", 1);
        A0P = A0X23;
        Feature A0X24 = Pxe.A0X("zero_party_api_get_privileged_hybrid_client_registration_pending_intent", 1);
        A0Q = A0X24;
        Feature A0X25 = Pxe.A0X("zero_party_api_get_privileged_hybrid_client_sign_pending_intent", 1);
        A0R = A0X25;
        Feature A0X26 = Pxe.A0X("zero_party_api_get_fido_security_key_only_sign_pending_intent", 1);
        A0S = A0X26;
        Feature A0X27 = Pxe.A0X("zero_party_api_get_fido_security_key_only_registration_pending_intent", 1);
        A00 = A0X27;
        Feature A0X28 = Pxe.A0X("zero_party_api_get_privileged_fido_security_key_only_sign_pending_intent", 1);
        A01 = A0X28;
        Feature A0X29 = Pxe.A0X("zero_party_api_get_privileged_fido_security_key_only_registration_pending_intent", 1);
        A02 = A0X29;
        Feature[] featureArr = new Feature[29];
        System.arraycopy(new Feature[]{A0X28, A0X29}, AnonymousClass7TF.A1X(new Feature[]{A0X, A0X2, A0X3, A0X4, A0X5, A0X6, A0X7, A0X8, A0X9, A0X10, A0X11, A0X12, A0X13, A0X14, A0X15, A0X16, A0X17, A0X18, A0X19, A0X20, A0X21, A0X22, A0X23, A0X24, A0X25, A0X26, A0X27}, featureArr) ? 1 : 0, featureArr, 27, 2);
        A0T = featureArr;
    }
}
