package X;

/* renamed from: X.Uwa  reason: case insensitive filesystem */
public enum C16530Uwa {
    CLIPS,
    HASH_TAG,
    DISCOVERY_MAP,
    POST,
    PROMOTE_AUDIENCE,
    PHOTOS_RENDER,
    SEARCH_NEARBY,
    NEARBY_PLACES,
    VIDEO_PLAYER_LOGGER,
    FOREGROUND_LOCATION_TRACKER,
    LOCATION_PAGE,
    LOCATION_INFO_BLOCK_BINDER,
    LOCATION_SERVICE_DATA_SOURCE,
    LOCATION_SERVICE_ENABLED_FILTER,
    REELS_LOCATION_SHEET,
    CLIPS_RECIPE_SHEET,
    STORY,
    STORY_ARCHIVE_MAP,
    MEDIA_MAP,
    BUSSINESS_PROMOTE,
    IN_APP_CAPTURE_VIEW,
    QCC_STATE,
    EDIT_POST,
    IG_LOCATION_SOURCE,
    IG_LOCATION_SOURCE_MAPBOX,
    IG_PAPAYA_LOGGER,
    NETWORK_INSIGHTS_LOGGER,
    NETWORK_STATE_LOGGER,
    IG4A_NDX,
    FRIEND_MAP,
    THREADS_COMPOSER,
    UNKNOWN;

    /* access modifiers changed from: public */
    static {
        C16530Uwa[] uwaArr;
        A00 = 0oU.A00(uwaArr);
    }
}
