package X;

import com.facebook.catalyst.modules.cameraroll.CameraRollManager;
import com.instagram.debug.devoptions.direct.burner.BurnerSendSettingsHelper;
import com.instagram.react.modules.base.IgReactQEModule;
import go.Seq;
import org.webrtc.EglBase14Impl;

/* renamed from: X.VFk  reason: case insensitive filesystem */
public abstract class C17036VFk {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 1:
                return "CANVAS_GIF_BACKGROUND";
            case 2:
                return "JOIN_CHAT_STICKER";
            case 3:
                return "SUBSCRIBER_CHAT_STICKER";
            case 4:
                return "CLIPS_RESHARE";
            case 5:
                return "CLIPS_ENDCARD";
            case 6:
                return "CLIPS_ENDCARD_STATIC";
            case 7:
                return "CLIPS_WATERMARK";
            case 8:
                return "COUNTDOWN_STICKER";
            case 9:
                return "DATE_TIME_STICKER";
            case 10:
                return "FUNDRAISER_STICKER";
            case 11:
                return "GALLERY_STICKER";
            case IgReactQEModule.CONFIG_KEY_OFFSET /*12*/:
                return "GROUP_POLL_STICKER";
            case 13:
                return "HASHTAG_STICKER";
            case 14:
                return "IGTV_RESHARE";
            case 15:
                return "INTERNAL_STICKER";
            case 16:
                return "KARAOKE_CAPTION_STICKER";
            case 17:
                return "LOCATION_STICKER";
            case EglBase14Impl.EGLExt_SDK_VERSION /*18*/:
                return "LYRICS_STICKER";
            case 19:
                return "MEDIA_STICKER";
            case 20:
                return "MENTION_STICKER";
            case 21:
                return "MUSIC_OVERLAY_STICKER";
            case 22:
                return "PHOTO_CRED_STICKER";
            case 23:
                return "POLAROID_STICKER";
            case 24:
                return "SWAPPABLE_GALLERY_STICKER";
            case 25:
                return "POLL_STICKER";
            case 26:
                return "POLL_STICKER_V2";
            case 27:
                return "PROFILE_CARD_STICKER";
            case 28:
                return "PROMPT_STICKER";
            case CameraRollManager.IMAGES_MEDIA_LATITUDE_LONGITUDE_DEPRECATED_API_LEVEL:
                return "CLIPS_PROMPT_STICKER";
            case 30:
                return "BEFORE_AND_AFTER_PROMPT_STICKER";
            case 31:
                return "QUESTION_STICKER";
            case 32:
                return "CLIPS_QUESTION_STICKER";
            case 33:
                return "QUIZ_STICKER";
            case 34:
                return "SECRET_STICKER";
            case 35:
                return "SELFIE_STICKER";
            case 36:
                return "SLIDER_STICKER";
            case 37:
                return "STATIC_STICKER";
            case 38:
                return "TEXT_STICKER";
            case 39:
                return "TIMED_STICKER";
            case 40:
                return "UPCOMING_EVENT_STICKER";
            case Seq.NULL_REFNUM /*41*/:
                return "VIDEO_STICKER";
            case Seq.RefTracker.REF_OFFSET /*42*/:
                return "DUAL_PHOTO";
            case 43:
                return "LINK_STICKER";
            case 44:
                return "USER_PAY_BADGES_STICKER";
            case 45:
                return "I_TAKE_CARE_STICKER";
            case 46:
                return "REELS_VISUAL_REPLIES_STICKER";
            case 47:
                return "REACTION_STICKER";
            case 48:
                return "SUBSCRIPTIONS_STICKER";
            case 49:
                return "FB_COMMUNITY_STICKER";
            case BurnerSendSettingsHelper.MESSAGE_SEND_BATCH_SIZE /*50*/:
                return "FB_TAG_STICKER";
            case 51:
                return "AVATAR_STATIC";
            case 52:
                return "SHARE_PLATFORM_STICKER";
            case 53:
                return "FEATURE_LINKING_STICKER";
            case 54:
                return "MESSAGE_SHARE_STICKER";
            case 55:
                return "CHANNEL_CHALLENGE_STICKER";
            case 56:
                return "BEFORE_AND_AFTER_STICKER";
            case 57:
                return "IG_INTERNAL_FEATURE_STICKER";
            case 58:
                return "GROUP_MENTION_STICKER";
            case 59:
                return "EVENT_STICKER";
            case 60:
                return "FOLLOWER_MILESTONE_STICKER";
            case 61:
                return "STORIES_TEMPLATE_TEXT_STICKER";
            case 62:
                return AnonymousClass000.A00(1027);
            case 63:
                return "MAGIC_MOD_STICKER";
            case 64:
                return "BIO_PRODUCT_STICKER";
            case 65:
                return "MUSIC_PICK_STICKER";
            case 66:
                return AnonymousClass000.A00(4301);
            case 67:
                return "NOTIFY_ME_STICKER";
            case 68:
                return "IMAGINE_TEMPLATE_STICKER";
            case 69:
                return "IMAGINE_STICKER";
            case 70:
                return "IMAGINE_ME_STICKER";
            case 71:
                return "TEXT_FILLABLE_STICKER";
            case 72:
                return "GALLERY_FILLABLE_STICKER";
            case 73:
                return "INSTAPAL_STICKER";
            case 74:
                return "PICS_PLEASE_STICKER";
            case 75:
                return "WHATSAPP_STICKER";
            default:
                return "BITMAP_STICKER";
        }
    }
}
