package X;

/* renamed from: X.XQw  reason: case insensitive filesystem */
public enum C21251XQw {
    ACCOUNT_PRIVACY,
    ARCHIVING_AND_DOWNLOADING,
    CONTENT_PREFERENCES,
    DAILY_LIMIT,
    HIDDEN_WORDS,
    MAIN_SETTINGS_SCREEN,
    MENTIONS,
    MESSAGE_CONTROLS,
    MESSAGE_CONTROLS_GROUPS,
    MESSAGE_CONTROLS_IG_VERIFIED,
    MESSAGE_CONTROLS_OTHERS_ON_IG,
    MESSAGE_CONTROLS_YOUR_FOLLOWERS_ON_IG,
    NOTIFICATIONS,
    REMIXES,
    SENSITIVE_CONTENT,
    SENSITIVE_CONTENT_CONTROL,
    SHARING_AND_REMIXES,
    SHARING_AND_REUSE,
    SLEEP_MODE,
    TAGS,
    TAGS_AND_MENTIONS,
    UNWANTED_COMMENTS_AND_MESSAGE_REQUESTS,
    WHAT_YOU_SEE,
    WHO_CAN_INTERACT_WITH_YOU,
    YOUR_ACCOUNT,
    YOUR_ACCOUNT_PRIVACY;

    /* access modifiers changed from: public */
    static {
        C21251XQw[] xQwArr;
        A00 = 0oU.A00(xQwArr);
    }
}
