package X;

/* renamed from: X.XSh  reason: case insensitive filesystem */
public enum C21277XSh implements MXZ {
    ACCOUNT_PRIVACY_SETTING,
    ALLOW_NOTES_ON_POSTS_AND_REELS,
    ALLOW_PEOPLE_TO_DOWNLOAD_YOUR_REELS,
    ALLOW_POSTS_TO_BE_VISIBLE_IN_COLLECTIONS_SHARED_WITH_OTHERS,
    ALLOW_POST_AND_REEL_SHARING_TO_STORIES,
    ALLOW_PROFILE_PICTURE_EXPANSION,
    ALLOW_REQUESTS_TO_FEATURE_YOUR_POSTS_IN_SHOPS,
    ALLOW_REUSE_OF_FEED_VIDEOS,
    ALLOW_REUSE_OF_POSTS,
    ALLOW_REUSE_OF_REELS,
    ALLOW_STORY_SHARING_IN_MESSAGES,
    ARCHIVING_SAVE_LIVE_TO_ARCHIVE,
    ARCHIVING_SAVE_STORY_TO_ARCHIVE,
    ARCHIVING_SAVE_STORY_TO_CAMERA_GALLERY,
    CUSTOM_WORDS_HIDE_COMMENTS,
    CUSTOM_WORDS_HIDE_MESSAGE_REQUESTS,
    FEATURED_CONTENT_REQUESTS_IN_SHOPS,
    HIDDEN_WORDS_ADVANCED_COMMENT_FILTERING,
    HIDDEN_WORDS_HIDE_COMMENTS,
    HIDDEN_WORDS_HIDE_MESSAGE_REQUESTS,
    IS_SLEEP_MODE_ENABLED,
    MESSAGE_REACHABILITY_LINKED_PAGE_DIRECT_MESSAGE,
    POSTS_AND_REELS_TO_STORIES,
    SEO_INDEXING_OPT_OUT,
    STORIES_IN_MESSAGES,
    TAGS_MENTIONS_HOW_YOU_MANAGE_BOOSTS_RESHARE_MEDIA,
    TAGS_MENTIONS_MANUALLY_APPROVE_TAGS,
    TAGS_MENTIONS_WHO_CAN_BOOST,
    TAGS_MENTIONS_WHO_CAN_TAG_ON_OTHER_APPS;

    /* access modifiers changed from: public */
    static {
        C21277XSh[] xShArr;
        A00 = 0oU.A00(xShArr);
    }

    public final String BOI() {
        return C13989Tnp.A0s(this);
    }
}
