package X;

/* renamed from: X.Xza  reason: case insensitive filesystem */
public final class C22325Xza implements C13961TmO {
    public static final C22325Xza A00 = new Object();
    public static final C11357SOt A01;
    public static final C11357SOt A02;
    public static final C11357SOt A03;
    public static final C11357SOt A04;
    public static final C11357SOt A05;
    public static final C11357SOt A06;
    public static final C11357SOt A07;
    public static final C11357SOt A08;
    public static final C11357SOt A09;
    public static final C11357SOt A0A;
    public static final C11357SOt A0B;
    public static final C11357SOt A0C;
    public static final C11357SOt A0D;
    public static final C11357SOt A0E;
    public static final C11357SOt A0F;
    public static final C11357SOt A0G;
    public static final C11357SOt A0H;
    public static final C11357SOt A0I;
    public static final C11357SOt A0J;
    public static final C11357SOt A0K;
    public static final C11357SOt A0L;
    public static final C11357SOt A0M;
    public static final C11357SOt A0N;
    public static final C11357SOt A0O;
    public static final C11357SOt A0P;
    public static final C11357SOt A0Q;
    public static final C11357SOt A0R;
    public static final C11357SOt A0S;
    public static final C11357SOt A0T;
    public static final C11357SOt A0U;
    public static final C11357SOt A0V;
    public static final C11357SOt A0W;
    public static final C11357SOt A0X;
    public static final C11357SOt A0Y;
    public static final C11357SOt A0Z;
    public static final C11357SOt A0a;
    public static final C11357SOt A0b;
    public static final C11357SOt A0c;
    public static final C11357SOt A0d;
    public static final C11357SOt A0e;
    public static final C11357SOt A0f;
    public static final C11357SOt A0g;
    public static final C11357SOt A0h;
    public static final C11357SOt A0i;
    public static final C11357SOt A0j;
    public static final C11357SOt A0k;
    public static final C11357SOt A0l;
    public static final C11357SOt A0m;
    public static final C11357SOt A0n;
    public static final C11357SOt A0o;
    public static final C11357SOt A0p;
    public static final C11357SOt A0q;
    public static final C11357SOt A0r;
    public static final C11357SOt A0s;
    public static final C11357SOt A0t;
    public static final C11357SOt A0u;
    public static final C11357SOt A0v;
    public static final C11357SOt A0w;
    public static final C11357SOt A0x;
    public static final C11357SOt A0y;
    public static final C11357SOt A0z;
    public static final C11357SOt A10;
    public static final C11357SOt A11;
    public static final C11357SOt A12;
    public static final C11357SOt A13;
    public static final C11357SOt A14;

    /* JADX WARNING: type inference failed for: r0v0, types: [X.Xza, java.lang.Object] */
    static {
        SUa A032 = SUa.A03("systemInfo");
        RDO rdo = RDO.DEFAULT;
        A0g = SUa.A0D(rdo, A032, 1);
        A0h = SUa.A0D(rdo, SUa.A03("eventName"), 2);
        A0i = SUa.A0D(rdo, SUa.A03("isThickClient"), 37);
        A0j = SUa.A0D(rdo, SUa.A03("clientType"), 61);
        A0k = SUa.A0D(rdo, SUa.A03("modelDownloadLogEvent"), 3);
        A0l = SUa.A0D(rdo, SUa.A03("customModelLoadLogEvent"), 20);
        A0m = SUa.A0D(rdo, SUa.A03("customModelInferenceLogEvent"), 4);
        A0n = SUa.A0D(rdo, SUa.A03("customModelCreateLogEvent"), 29);
        A0o = SUa.A0D(rdo, SUa.A03("onDeviceFaceDetectionLogEvent"), 5);
        A0p = SUa.A0D(rdo, SUa.A03("onDeviceFaceLoadLogEvent"), 59);
        A0q = SUa.A0D(rdo, SUa.A03("onDeviceTextDetectionLogEvent"), 6);
        A0r = SUa.A0D(rdo, SUa.A03("onDeviceBarcodeDetectionLogEvent"), 7);
        A0s = SUa.A0D(rdo, SUa.A03("onDeviceBarcodeLoadLogEvent"), 58);
        A0t = SUa.A0D(rdo, SUa.A03("onDeviceImageLabelCreateLogEvent"), 48);
        A0u = SUa.A0D(rdo, SUa.A03("onDeviceImageLabelLoadLogEvent"), 49);
        A0v = SUa.A0D(rdo, SUa.A03("onDeviceImageLabelDetectionLogEvent"), 18);
        A0w = SUa.A0D(rdo, SUa.A03("onDeviceObjectCreateLogEvent"), 26);
        A0x = SUa.A0D(rdo, SUa.A03("onDeviceObjectLoadLogEvent"), 27);
        A0y = SUa.A0D(rdo, SUa.A03("onDeviceObjectInferenceLogEvent"), 28);
        A0z = SUa.A0D(rdo, SUa.A03("onDevicePoseDetectionLogEvent"), 44);
        A10 = SUa.A0D(rdo, SUa.A03("onDeviceSegmentationLogEvent"), 45);
        A11 = SUa.A0D(rdo, SUa.A03("onDeviceSmartReplyLogEvent"), 19);
        A12 = SUa.A0D(rdo, SUa.A03("onDeviceLanguageIdentificationLogEvent"), 21);
        A13 = SUa.A0D(rdo, SUa.A03("onDeviceTranslationLogEvent"), 22);
        A14 = SUa.A0D(rdo, SUa.A03("cloudFaceDetectionLogEvent"), 8);
        A01 = SUa.A0D(rdo, SUa.A03("cloudCropHintDetectionLogEvent"), 9);
        A02 = SUa.A0D(rdo, SUa.A03("cloudDocumentTextDetectionLogEvent"), 10);
        A03 = SUa.A0D(rdo, SUa.A03("cloudImagePropertiesDetectionLogEvent"), 11);
        A04 = SUa.A0D(rdo, SUa.A03("cloudImageLabelDetectionLogEvent"), 12);
        A05 = SUa.A0D(rdo, SUa.A03("cloudLandmarkDetectionLogEvent"), 13);
        A06 = SUa.A0D(rdo, SUa.A03("cloudLogoDetectionLogEvent"), 14);
        A07 = SUa.A0D(rdo, SUa.A03("cloudSafeSearchDetectionLogEvent"), 15);
        A08 = SUa.A0D(rdo, SUa.A03("cloudTextDetectionLogEvent"), 16);
        A09 = SUa.A0D(rdo, SUa.A03("cloudWebSearchDetectionLogEvent"), 17);
        A0A = SUa.A0D(rdo, SUa.A03("automlImageLabelingCreateLogEvent"), 23);
        A0B = SUa.A0D(rdo, SUa.A03("automlImageLabelingLoadLogEvent"), 24);
        A0C = SUa.A0D(rdo, SUa.A03("automlImageLabelingInferenceLogEvent"), 25);
        A0D = SUa.A0D(rdo, SUa.A03("isModelDownloadedLogEvent"), 39);
        A0E = SUa.A0D(rdo, SUa.A03("deleteModelLogEvent"), 40);
        A0F = SUa.A0D(rdo, SUa.A03("aggregatedAutomlImageLabelingInferenceLogEvent"), 30);
        A0G = SUa.A0D(rdo, SUa.A03("aggregatedCustomModelInferenceLogEvent"), 31);
        A0H = SUa.A0D(rdo, SUa.A03("aggregatedOnDeviceFaceDetectionLogEvent"), 32);
        A0I = SUa.A0D(rdo, SUa.A03("aggregatedOnDeviceBarcodeDetectionLogEvent"), 33);
        A0J = SUa.A0D(rdo, SUa.A03("aggregatedOnDeviceImageLabelDetectionLogEvent"), 34);
        A0K = SUa.A0D(rdo, SUa.A03("aggregatedOnDeviceObjectInferenceLogEvent"), 35);
        A0L = SUa.A0D(rdo, SUa.A03("aggregatedOnDeviceTextDetectionLogEvent"), 36);
        A0M = SUa.A0D(rdo, SUa.A03("aggregatedOnDevicePoseDetectionLogEvent"), 46);
        A0N = SUa.A0D(rdo, SUa.A03("aggregatedOnDeviceSegmentationLogEvent"), 47);
        A0O = SUa.A0D(rdo, SUa.A03("pipelineAccelerationInferenceEvents"), 69);
        A0P = SUa.A0D(rdo, SUa.A03("remoteConfigLogEvent"), 42);
        A0Q = SUa.A0D(rdo, SUa.A03("inputImageConstructionLogEvent"), 50);
        A0R = SUa.A0D(rdo, SUa.A03("leakedHandleEvent"), 51);
        A0S = SUa.A0D(rdo, SUa.A03("cameraSourceLogEvent"), 52);
        A0T = SUa.A0D(rdo, SUa.A03("imageLabelOptionalModuleLogEvent"), 53);
        A0U = SUa.A0D(rdo, SUa.A03("languageIdentificationOptionalModuleLogEvent"), 54);
        A0V = SUa.A0D(rdo, SUa.A03("faceDetectionOptionalModuleLogEvent"), 60);
        A0W = SUa.A0D(rdo, SUa.A03("nlClassifierOptionalModuleLogEvent"), 55);
        A0X = SUa.A0D(rdo, SUa.A03("nlClassifierClientLibraryLogEvent"), 56);
        A0Y = SUa.A0D(rdo, SUa.A03("accelerationAllowlistLogEvent"), 57);
        A0Z = SUa.A0D(rdo, SUa.A03("toxicityDetectionCreateEvent"), 62);
        A0a = SUa.A0D(rdo, SUa.A03("toxicityDetectionLoadEvent"), 63);
        A0b = SUa.A0D(rdo, SUa.A03("toxicityDetectionInferenceEvent"), 64);
        A0c = SUa.A0D(rdo, SUa.A03("barcodeDetectionOptionalModuleLogEvent"), 65);
        A0d = SUa.A0D(rdo, SUa.A03("customImageLabelOptionalModuleLogEvent"), 66);
        A0e = SUa.A0D(rdo, SUa.A03("codeScannerScanApiEvent"), 67);
        A0f = SUa.A0D(rdo, SUa.A03("codeScannerOptionalModuleEvent"), 68);
    }

    public final /* bridge */ /* synthetic */ void ARq(Object obj, Object obj2) {
        C10758Rxc rxc = (C10758Rxc) obj;
        C13745TgH tgH = (C13745TgH) obj2;
        tgH.A7Q(A0g, rxc.A04);
        tgH.A7Q(A0h, rxc.A02);
        tgH.A7Q(A0i, (Object) null);
        tgH.A7Q(A0j, rxc.A01);
        tgH.A7Q(A0k, (Object) null);
        tgH.A7Q(A0l, (Object) null);
        tgH.A7Q(A0m, (Object) null);
        tgH.A7Q(A0n, (Object) null);
        tgH.A7Q(A0o, (Object) null);
        tgH.A7Q(A0p, (Object) null);
        tgH.A7Q(A0q, rxc.A03);
        tgH.A7Q(A0r, (Object) null);
        tgH.A7Q(A0s, (Object) null);
        tgH.A7Q(A0t, (Object) null);
        tgH.A7Q(A0u, (Object) null);
        tgH.A7Q(A0v, (Object) null);
        tgH.A7Q(A0w, (Object) null);
        tgH.A7Q(A0x, (Object) null);
        tgH.A7Q(A0y, (Object) null);
        tgH.A7Q(A0z, (Object) null);
        tgH.A7Q(A10, (Object) null);
        tgH.A7Q(A11, (Object) null);
        tgH.A7Q(A12, (Object) null);
        tgH.A7Q(A13, (Object) null);
        tgH.A7Q(A14, (Object) null);
        tgH.A7Q(A01, (Object) null);
        tgH.A7Q(A02, (Object) null);
        tgH.A7Q(A03, (Object) null);
        tgH.A7Q(A04, (Object) null);
        tgH.A7Q(A05, (Object) null);
        tgH.A7Q(A06, (Object) null);
        tgH.A7Q(A07, (Object) null);
        tgH.A7Q(A08, (Object) null);
        tgH.A7Q(A09, (Object) null);
        tgH.A7Q(A0A, (Object) null);
        tgH.A7Q(A0B, (Object) null);
        tgH.A7Q(A0C, (Object) null);
        tgH.A7Q(A0D, (Object) null);
        tgH.A7Q(A0E, (Object) null);
        tgH.A7Q(A0F, (Object) null);
        tgH.A7Q(A0G, (Object) null);
        tgH.A7Q(A0H, (Object) null);
        tgH.A7Q(A0I, (Object) null);
        tgH.A7Q(A0J, (Object) null);
        tgH.A7Q(A0K, (Object) null);
        tgH.A7Q(A0L, rxc.A00);
        tgH.A7Q(A0M, (Object) null);
        tgH.A7Q(A0N, (Object) null);
        tgH.A7Q(A0O, (Object) null);
        tgH.A7Q(A0P, (Object) null);
        tgH.A7Q(A0Q, (Object) null);
        tgH.A7Q(A0R, (Object) null);
        tgH.A7Q(A0S, (Object) null);
        tgH.A7Q(A0T, (Object) null);
        tgH.A7Q(A0U, (Object) null);
        tgH.A7Q(A0V, (Object) null);
        tgH.A7Q(A0W, (Object) null);
        tgH.A7Q(A0X, (Object) null);
        tgH.A7Q(A0Y, (Object) null);
        tgH.A7Q(A0Z, (Object) null);
        tgH.A7Q(A0a, (Object) null);
        tgH.A7Q(A0b, (Object) null);
        tgH.A7Q(A0c, (Object) null);
        tgH.A7Q(A0d, (Object) null);
        tgH.A7Q(A0e, (Object) null);
        tgH.A7Q(A0f, (Object) null);
    }
}
