package X;

/* renamed from: X.3Ds  reason: invalid class name and case insensitive filesystem */
public enum C238863Ds implements AnonymousClass0Ac {
    LIKE_LINK(5),
    TITLE(10),
    MEDIA_GENERIC(11),
    PHOTO(12),
    ATTACHMENT(15),
    USER_MESSAGE(18),
    SUBTITLE(19),
    DESCRIPTION(20),
    PAGE_PROFILE_PIC(69),
    GENERIC_CALL_TO_ACTION_BUTTON(86),
    SPONSORED_CONTEXT(97),
    THUMBNAIL_LINK(149),
    SAVE_BUTTON(191),
    STORY_HEADER(230),
    CAROUSEL_CARD_STORY(237),
    STORY(301),
    PROFILE_LINK(312),
    REACTION_BROWSER(316),
    PROFILE_NAV_ITEM(318),
    SNACKS(321),
    PROFILE_TILE(322),
    GENERIC_PROFILE_BROWSER(335),
    AR_ADS_OPEN_CAMERA(393),
    AR_ADS_CTA(423),
    PBIA_PROFILE(424),
    PRODUCT_TAG(425),
    VIEW_PRODUCTS(429),
    INSTAGRAM_EXPLORE(438),
    REMINDER_AD_CTA_BUTTON(439),
    CTA_MARGIN_AREA(442),
    IG_STORY_SHOWCASE_ADS_CLICK(466),
    COLLECTION_PRODUCT_TILE(469),
    EXPLORE_GRID_ADS_CTA_BUTTON(485),
    EXPLORE_GRID_ADS_PROFILE_NAME(486),
    ADS_PRODUCT_PAGE(525),
    SEARCH_GRID_ADS_CTA_BUTTON(531),
    SEARCH_GRID_ADS_PROFILE_NAME(532),
    TOOLTIP_CTA(534),
    BOTTOM_SHEET(543),
    ATTRIBUTION_ROW_PILL(548),
    PROFILE_TAB_PRODUCT_TILE(567),
    SOCIAL_CONTEXT_SHEET(571);
    
    public final long A00;

    /* access modifiers changed from: public */
    C238863Ds(long j) {
        this.A00 = j;
    }
}
