package X;

/* renamed from: X.3aa  reason: invalid class name and case insensitive filesystem */
public enum C244063aa implements AnonymousClass0Ac {
    CAPTION("CAPTION"),
    CARD_OVERLAY_CAPTION("CARD_OVERLAY_CAPTION"),
    CARD_OVERLAY_CTA("CARD_OVERLAY_CTA"),
    CARD_OVERLAY_INFO_LABEL("CARD_OVERLAY_INFO_LABEL"),
    CARD_OVERLAY_SUBTITLE("CARD_OVERLAY_SUBTITLE"),
    CARD_OVERLAY_TITLE("CARD_OVERLAY_TITLE"),
    CAROUSEL_INDEX_INDICATOR("CAROUSEL_INDEX_INDICATOR"),
    CTA("CTA"),
    DISCLAIMER("DISCLAIMER"),
    DPA_HEADLINE("DPA_HEADLINE"),
    END_SCENE_CTA("END_SCENE_CTA"),
    END_SCENE_SUBTITLE("END_SCENE_SUBTITLE"),
    END_SCENE_TITLE("END_SCENE_TITLE"),
    LEADGEN_CARD_ADVERTISER_PROFILE_IMAGE("LEADGEN_CARD_ADVERTISER_PROFILE_IMAGE"),
    LEADGEN_CARD_ADVERTISER_SUBTITLE("LEADGEN_CARD_ADVERTISER_SUBTITLE"),
    LEADGEN_CARD_CONTINUE_BUTTON("LEADGEN_CARD_CONTINUE_BUTTON"),
    LEADGEN_CARD_MULTIPLE_CHOICE_OPTION("LEADGEN_CARD_MULTIPLE_CHOICE_OPTION"),
    LEADGEN_CARD_QUESTION_LABEL("LEADGEN_CARD_QUESTION_LABEL"),
    MEDIA("MEDIA"),
    MEDIA_THUMBNAIL("MEDIA_THUMBNAIL"),
    MID_SCENE_CARD("MID_SCENE_CARD"),
    MID_SCENE_CARD_IMAGE("MID_SCENE_IMAGE"),
    MID_SCENE_CARD_TITLE("MID_SCENE_CARD_TITLE"),
    MULTI_ADS_TITLE("MULTI_ADS_TITLE"),
    PROFILE_IMAGE("PROFILE_IMAGE"),
    SAVE_TO_COLLECTION("SAVE_TO_COLLECTION"),
    SPONSORED_LABEL("SPONSORED_LABEL"),
    TITLE("TITLE"),
    VIDEO_VIEW_COUNT("VIDEO_VIEW_COUNT"),
    VIEW_ALL_COMMENTS("VIEW_ALL_COMMENTS"),
    VIEW_LIKES("VIEW_LIKES");
    
    public final String A00;

    /* access modifiers changed from: public */
    C244063aa(String str) {
        this.A00 = str;
    }
}
