package X;

import android.content.Context;
import android.net.Uri;
import android.text.TextUtils;
import com.instagram.api.schemas.CameraTool;
import com.instagram.api.schemas.FanClubStoriesTeaserType;
import com.instagram.api.schemas.FeedItemType;
import com.instagram.api.schemas.GenAIToolInfoDictIntf;
import com.instagram.api.schemas.IGAdCreativeStory9x16CaptionData;
import com.instagram.api.schemas.IGAdTransparencyDisclaimerPlacement;
import com.instagram.api.schemas.StoryMusicPickTappableDataIntf;
import com.instagram.api.schemas.StoryPromptTappableDataIntf;
import com.instagram.api.schemas.StoryPromptType;
import com.instagram.common.session.UserSession;
import com.instagram.common.typedurl.ImageUrl;
import com.instagram.feed.media.ReelCTAIntf;
import com.instagram.model.effect.AttributedAREffect;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.model.venue.Venue;
import com.instagram.react.modules.base.IgReactQEModule;
import com.instagram.reels.prompt.model.PromptStickerModel;
import com.instagram.user.model.User;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import org.webrtc.EglBase14Impl;

/* renamed from: X.3uh  reason: invalid class name and case insensitive filesystem */
public final class C255773uh implements C249693kD, 1Nv, C242713Vq {
    public int A00;
    public int A01;
    public FanClubStoriesTeaserType A02;
    public AnonymousClass3IL A03;
    public OLT A04;
    public AttributedAREffect A05;
    public C46313DUq A06;
    public C270084gA A07;
    public AnonymousClass3HX A08;
    public C270074g9 A09;
    public C270094gB A0A;
    public C270104gC A0B;
    public C270124gE A0C;
    public C270114gD A0D;
    public C64113LOb A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Long A0H;
    public String A0I;
    public String A0J;
    public List A0K;
    public List A0L;
    public List A0M;
    public boolean A0N;
    public boolean A0O;
    public boolean A0P;
    public boolean A0Q;
    public boolean A0R;
    public boolean A0S;
    public boolean A0T;
    public boolean A0U;
    public boolean A0V;
    public boolean A0W;
    public long A0X;
    public long A0Y;
    public C270174gJ A0Z;
    public String A0a;
    public final 1Xj A0b;
    public final C270194gL A0c;
    public final C270184gK A0d;
    public final C250963mL A0e;
    public final C270064g8 A0f;
    public final AnonymousClass3OA A0g;
    public final C270054g7 A0h;
    public final User A0i;
    public final String A0j;
    public final String A0k;
    public final List A0l;
    public final List A0m;
    public final List A0n;
    public final List A0o;
    public final List A0p;
    public final Set A0q;
    public final Set A0r;
    public AnonymousClass3IB mBrandResearchSurvey;
    public final C270204gM mBrandSurveyImpression;

    public final String A0V(UserSession userSession) {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            C257783xx A022 = C231122qu.A02(userSession, r0);
            if (A022 != null) {
                return C247573gZ.A00(IGAdTransparencyDisclaimerPlacement.BELOW_IMAGE, A022);
            }
        }
        return null;
    }

    public final float A00() {
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A02;
        } else if (ordinal != 1 && ordinal != 9) {
            return 0.0f;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.A0l();
        }
    }

    public final int A01() {
        if (this.A0e.ordinal() != 1) {
            return 0;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A10();
    }

    public final long A02() {
        Long l;
        1Xj r7 = this.A0b;
        if (r7 != null) {
            long A17 = r7.A17();
            if (A17 > 0 && A17 < Long.MAX_VALUE) {
                return r7.A17();
            }
        }
        C270194gL r0 = this.A0c;
        if (r0 == null || (l = r0.A0S) == null) {
            return Long.MAX_VALUE;
        }
        long longValue = l.longValue();
        if (longValue <= 0 || longValue >= Long.MAX_VALUE) {
            return Long.MAX_VALUE;
        }
        return TimeUnit.SECONDS.toMillis(longValue);
    }

    public final long A03() {
        Long l;
        Long l2;
        C250963mL r1 = this.A0e;
        0qQ.A0B(r1, 0);
        if (C250983mN.A00.containsValue(r1)) {
            return this.A0Y;
        }
        int ordinal = r1.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            long j = r0.A00.A0e;
            if (j == 0) {
                return System.currentTimeMillis() / 1000;
            }
            return j;
        } else if (ordinal == 1) {
            1Xj r02 = this.A0b;
            if (r02 != null) {
                return r02.A1A();
            }
            return 0;
        } else if (ordinal == 3 || ordinal == 4) {
            C270194gL r03 = this.A0c;
            if (r03 != null) {
                return r03.A01();
            }
            return 0;
        } else if (ordinal == 31) {
            return this.A0X;
        } else {
            if (ordinal == 33) {
                AnonymousClass3IL r04 = this.A03;
                if (r04 == null || (l = r04.A04) == null) {
                    return 0;
                }
                return l.longValue();
            } else if (ordinal != 23 || (l2 = this.A0H) == null) {
                return 0;
            } else {
                return l2.longValue();
            }
        }
    }

    public final C2808454k A04() {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A0C.BME();
    }

    public final DUA A05() {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A0C.BoV();
    }

    public final ImageUrl A06() {
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            String str = r0.A00.A33;
            str.getClass();
            return C253833rU.A01(new File(str));
        } else if (ordinal != 1 && ordinal != 9 && ordinal != 6 && ordinal != 5 && ordinal != 10) {
            return null;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.A1Q();
        }
    }

    public final ImageUrl A07(int i) {
        C270194gL r1;
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r12 = this.A0d;
            r12.getClass();
            AnonymousClass3Q2 r2 = r12.A00;
            if (r2.A0q()) {
                String str = r2.A33;
                str.getClass();
                Uri fromFile = Uri.fromFile(new File(str));
                0qQ.A07(fromFile);
                return C253833rU.A00(fromFile, -1, -1);
            }
        } else if (ordinal == 1 || ordinal == 9) {
            1Xj r13 = this.A0b;
            r13.getClass();
            if (!r13.A4o()) {
                return r13.A1m(i);
            }
            Uri uri = r13.A05;
            uri.getClass();
            return C253833rU.A00(uri, -1, -1);
        } else if ((ordinal == 3 || ordinal == 4) && (r1 = this.A0c) != null) {
            return r1.A02();
        }
        return null;
    }

    public final ImageUrl A08(Context context) {
        User user;
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (!(ordinal == 1 || ordinal == 9)) {
                if (ordinal == 3 || ordinal == 4) {
                    C270194gL r0 = this.A0c;
                    if (r0 != null) {
                        return r0.A02();
                    }
                    return null;
                } else if (ordinal != 6) {
                    if (ordinal != 31 || (user = this.A0i) == null) {
                        return null;
                    }
                    return user.Bh3();
                }
            }
            1Xj r1 = this.A0b;
            r1.getClass();
            if (!r1.A4o()) {
                return r1.A1n(context);
            }
            Uri uri = r1.A05;
            uri.getClass();
            return C253833rU.A00(uri, -1, -1);
        }
        C270184gK r02 = this.A0d;
        r02.getClass();
        AnonymousClass3Q2 r12 = r02.A00;
        if (!r12.A0q()) {
            return null;
        }
        String str = r12.A33;
        str.getClass();
        Uri fromFile = Uri.fromFile(new File(str));
        0qQ.A07(fromFile);
        return C253833rU.A00(fromFile, -1, -1);
    }

    /* JADX WARNING: type inference failed for: r0v7, types: [java.lang.Object, X.1Nv] */
    public final 1Nv A09() {
        String str;
        C250963mL r2 = this.A0e;
        0qQ.A0B(r2, 0);
        if (C250983mN.A00.containsValue(r2)) {
            return new ITA(this);
        }
        switch (r2.ordinal()) {
            case 0:
                C270184gK r0 = this.A0d;
                r0.getClass();
                return r0;
            case 1:
                C270064g8 r02 = this.A0f;
                if (r02 == null) {
                    return this.A0b;
                }
                return r02;
            case 3:
            case 4:
                C270194gL r22 = this.A0c;
                if (r22 == null) {
                    return null;
                }
                C278124wJ r1 = r22.A0o;
                if (r1.A00 == null && (str = r22.A0e) != null) {
                    r1.A00 = str;
                }
                return r1;
            case 5:
            case 6:
            case 10:
            case 14:
            case 15:
                return this.A0h;
            case 7:
                return this.A09;
            case 8:
            case 11:
            case IgReactQEModule.CONFIG_KEY_OFFSET /*12*/:
            case 13:
                return null;
            case 9:
                return this.A0b;
            case 16:
                return this.A0A;
            case 17:
                return this.A07;
            case EglBase14Impl.EGLExt_SDK_VERSION:
                return this.A0B;
            case 19:
                return this.A0D;
            case 20:
                return this.A0C;
            case 22:
            case 34:
            case 35:
                return new Object();
            case 31:
                return this.A0Z;
            case 32:
                return this.mBrandSurveyImpression;
            case 33:
                return new ITB(this);
            default:
                throw new UnsupportedOperationException(002.A0R("This item does not represent an ImpressionItem. Item type: ", r2.toString()));
        }
    }

    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v0, resolved type: com.instagram.feed.media.ReelCTAIntf} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v1, resolved type: com.instagram.feed.media.ReelCTAIntf} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r1v1, resolved type: java.lang.Object} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v6, resolved type: com.instagram.feed.media.ReelCTAIntf} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r3v3, resolved type: com.instagram.feed.media.ReelCTAIntf} */
    /* JADX WARNING: Multi-variable type inference failed */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final com.instagram.feed.media.ReelCTAIntf A0A() {
        /*
            r4 = this;
            X.3mL r0 = r4.A0e
            int r1 = r0.ordinal()
            r0 = 0
            if (r1 == r0) goto L_0x0012
            r0 = 1
            if (r1 == r0) goto L_0x0039
            r0 = 9
            if (r1 == r0) goto L_0x0039
            r3 = 0
        L_0x0011:
            return r3
        L_0x0012:
            X.4gK r0 = r4.A0d
            r0.getClass()
            X.3Q2 r0 = r0.A00
            java.util.List r0 = r0.A4Z
            r3 = 0
            if (r0 == 0) goto L_0x0011
            java.util.Iterator r2 = r0.iterator()
        L_0x0022:
            boolean r0 = r2.hasNext()
            if (r0 == 0) goto L_0x0036
            java.lang.Object r1 = r2.next()
            r0 = r1
            com.instagram.feed.media.ReelCTAIntf r0 = (com.instagram.feed.media.ReelCTAIntf) r0
            java.lang.String r0 = X.AnonymousClass6MS.A00(r0)
            if (r0 == 0) goto L_0x0022
            r3 = r1
        L_0x0036:
            com.instagram.feed.media.ReelCTAIntf r3 = (com.instagram.feed.media.ReelCTAIntf) r3
            return r3
        L_0x0039:
            X.1Xj r0 = r4.A0b
            r0.getClass()
            com.instagram.feed.media.ReelCTAIntf r3 = r0.A1h()
            return r3
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.A0A():com.instagram.feed.media.ReelCTAIntf");
    }

    public final AnonymousClass3QO A0B() {
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A1F;
        } else if (ordinal != 1) {
            return AnonymousClass3QO.DEFAULT;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.A1t();
        }
    }

    public final 1iA A0C() {
        C250963mL r1 = this.A0e;
        0qQ.A0B(r1, 0);
        if (C250983mN.A00.containsValue(r1)) {
            return 1iA.A0a;
        }
        int ordinal = r1.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A1G;
        } else if (ordinal == 1 || ordinal == 9) {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.BR7();
        } else if (ordinal == 3 || ordinal == 4) {
            return 1iA.A0L;
        } else {
            return null;
        }
    }

    public final C270164gI A0D() {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A0C.B95();
    }

    public final JSN A0E() {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A0C.BM7();
    }

    public final C258033yM A0F() {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A0C.C0R();
    }

    /* JADX WARNING: type inference failed for: r1v3, types: [java.lang.Object, X.6LR] */
    public final AnonymousClass6LR A0G() {
        if (this.A0e.ordinal() != 1) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        C247733gp A1T = r0.A1T();
        if (A1T == null) {
            return null;
        }
        ? obj = new Object();
        obj.A06 = A1T.A0d;
        obj.A03 = A1T.A0a;
        obj.A04 = A1T.A0b;
        obj.A08 = A1T.A0g;
        obj.A07 = A1T.A0e;
        obj.A02 = Integer.valueOf(A1T.A0S);
        obj.A00 = A1T.A0X;
        obj.A01 = A1T.A0Y;
        return obj;
    }

    public final AnonymousClass6LR A0H() {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A1x();
    }

    /* JADX WARNING: type inference failed for: r1v4, types: [X.A88, java.lang.Object] */
    public final A88 A0I() {
        IGAdCreativeStory9x16CaptionData iGAdCreativeStory9x16CaptionData;
        float f;
        if (this.A0e.ordinal() != 1) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        C247733gp A1T = r0.A1T();
        C250513lZ injected = r0.A0C.getInjected();
        if (injected != null) {
            iGAdCreativeStory9x16CaptionData = injected.C3f();
        } else {
            iGAdCreativeStory9x16CaptionData = null;
        }
        if (A1T == null || iGAdCreativeStory9x16CaptionData == null) {
            return null;
        }
        ? obj = new Object();
        obj.A0B = A1T.A0d;
        obj.A0A = iGAdCreativeStory9x16CaptionData.AlT();
        obj.A08 = iGAdCreativeStory9x16CaptionData.AlO();
        obj.A09 = iGAdCreativeStory9x16CaptionData.AlP();
        obj.A04 = iGAdCreativeStory9x16CaptionData.AlR();
        obj.A05 = iGAdCreativeStory9x16CaptionData.AlS();
        obj.A00 = iGAdCreativeStory9x16CaptionData.AlV();
        obj.A07 = iGAdCreativeStory9x16CaptionData.AlY();
        Integer AlU = iGAdCreativeStory9x16CaptionData.AlU();
        if (AlU != null) {
            f = (float) AlU.intValue();
        } else {
            f = 16.0f;
        }
        obj.A03 = Float.valueOf(f);
        obj.A01 = iGAdCreativeStory9x16CaptionData.AlZ();
        obj.A02 = iGAdCreativeStory9x16CaptionData.Ala();
        obj.A06 = iGAdCreativeStory9x16CaptionData.AlQ();
        return obj;
    }

    public final User A0L() {
        1Xj r3 = this.A0b;
        if (r3 == null || this.A0e != C250963mL.MEDIA) {
            return null;
        }
        return r3.A29();
    }

    /* JADX WARNING: Code restructure failed: missing block: B:9:0x0015, code lost:
        if (r2 != 6) goto L_0x0017;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final X.AnonymousClass3WR A0M(com.instagram.common.session.UserSession r4) {
        /*
            r3 = this;
            X.3mL r0 = r3.A0e
            int r2 = r0.ordinal()
            r0 = 1
            if (r2 == r0) goto L_0x0021
            r0 = 9
            if (r2 == r0) goto L_0x0021
            r0 = 3
            r1 = 0
            if (r2 == r0) goto L_0x0018
            r0 = 4
            if (r2 == r0) goto L_0x0018
            r0 = 6
            if (r2 == r0) goto L_0x0021
        L_0x0017:
            return r1
        L_0x0018:
            X.4gL r0 = r3.A0c
            if (r0 == 0) goto L_0x0017
            X.3WR r1 = r0.A04(r4)
            return r1
        L_0x0021:
            X.1Xj r0 = r3.A0b
            r0.getClass()
            X.3WR r1 = r0.A2D()
            return r1
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.A0M(com.instagram.common.session.UserSession):X.3WR");
    }

    /* JADX WARNING: Code restructure failed: missing block: B:3:0x000d, code lost:
        if (r1 != false) goto L_0x000f;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final java.lang.Boolean A0N() {
        /*
            r2 = this;
            X.3WT r0 = X.AnonymousClass3WT.MULTI_PRODUCT
            java.util.List r0 = r2.Bkd(r0)
            if (r0 == 0) goto L_0x000f
            boolean r1 = r0.isEmpty()
            r0 = 1
            if (r1 == 0) goto L_0x0010
        L_0x000f:
            r0 = 0
        L_0x0010:
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)
            return r0
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.A0N():java.lang.Boolean");
    }

    public final Long A0O(UserSession userSession) {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 0) {
            if (ordinal != 1) {
                return null;
            }
            1Xj r0 = this.A0b;
            r0.getClass();
            return r0.A0C.AcN();
        } else if (!A1d()) {
            return null;
        } else {
            1E8 A002 = 1E7.A00(userSession);
            C270184gK r02 = this.A0d;
            r02.getClass();
            1Xj A022 = A002.A02(r02.A00.A2K);
            if (A022 != null) {
                return Long.valueOf(A022.A1A());
            }
            return null;
        }
    }

    public final String A0P() {
        List A0j2;
        C255783ui r0;
        C19469WaH A0A2;
        1Xj r02 = this.A0b;
        if (r02 == null || (A0j2 = 1Xj.A0j(r02)) == null || (r0 = (C255783ui) 00k.A0J(A0j2)) == null || (A0A2 = r0.A0A()) == null) {
            return null;
        }
        return A0A2.A02();
    }

    public final String A0Q() {
        DSJ BGV;
        DSM Bc0;
        1Xj r0 = this.A0b;
        if (r0 == null || (BGV = r0.A0C.BGV()) == null || (Bc0 = BGV.Bc0()) == null) {
            return null;
        }
        return Bc0.getUrl();
    }

    public final String A0R() {
        C250963mL r1 = this.A0e;
        0qQ.A0B(r1, 0);
        if (C250983mN.A00.containsValue(r1)) {
            C64113LOb lOb = this.A0E;
            lOb.getClass();
            return (String) C18409VrB.A01.get(lOb.A04);
        }
        int ordinal = r1.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A3V;
        } else if (ordinal != 1 && ordinal != 9) {
            return null;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.A0M;
        }
    }

    public final String A0S() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 1 && ordinal != 9) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.BTL();
    }

    /* JADX WARNING: Code restructure failed: missing block: B:20:0x0051, code lost:
        X.17k.A07(r1, r0);
     */
    /* JADX WARNING: Code restructure failed: missing block: B:21:0x0058, code lost:
        throw X.AnonymousClass00P.createAndThrow();
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final java.lang.String A0T() {
        /*
            r2 = this;
            X.3mL r0 = r2.A0e
            int r1 = r0.ordinal()
            r0 = 1
            if (r1 == r0) goto L_0x0083
            r0 = 20
            if (r1 == r0) goto L_0x006c
            r0 = 6
            if (r1 == r0) goto L_0x0059
            r0 = 5
            if (r1 == r0) goto L_0x0059
            r0 = 10
            if (r1 == r0) goto L_0x0059
            switch(r1) {
                case 7: goto L_0x00a3;
                case 8: goto L_0x003c;
                case 9: goto L_0x001a;
                case 10: goto L_0x001a;
                case 11: goto L_0x004a;
                case 12: goto L_0x004a;
                case 13: goto L_0x004e;
                case 14: goto L_0x0059;
                case 15: goto L_0x0059;
                case 16: goto L_0x0022;
                case 17: goto L_0x0040;
                case 18: goto L_0x002e;
                case 19: goto L_0x0091;
                default: goto L_0x001a;
            }
        L_0x001a:
            java.lang.String r1 = "Reel item isn't a netego unit with an action"
            java.lang.UnsupportedOperationException r0 = new java.lang.UnsupportedOperationException
            r0.<init>(r1)
            throw r0
        L_0x0022:
            X.4gB r1 = r2.A0A
            java.lang.String r0 = "Bloks Netego unit needs to have a bloks netego object."
            X.17k.A07(r1, r0)
            X.3Hj r0 = r1.A01
            java.lang.String r1 = r0.A04
            goto L_0x009e
        L_0x002e:
            X.4gC r1 = r2.A0B
            java.lang.String r0 = "Share Comment to Story Netego needs to have a CommentShareNetego"
            X.17k.A07(r1, r0)
            X.3II r0 = r1.A00
            java.lang.String r1 = r0.getCtaText()
            goto L_0x009e
        L_0x003c:
            r1 = 0
            java.lang.String r0 = "Netego suggested clips unit needs to have an suggested clips object"
            goto L_0x0051
        L_0x0040:
            X.4gA r1 = r2.A07
            java.lang.String r0 = "Netego trending prompt unit needs to have an prompts in story object"
            X.17k.A07(r1, r0)
            java.lang.String r1 = r1.A04
            return r1
        L_0x004a:
            r1 = 0
            java.lang.String r0 = "Netego products for you unit needs to have an suggested products object"
            goto L_0x0051
        L_0x004e:
            r1 = 0
            java.lang.String r0 = "Netego shops for you unit needs to have an suggested shops object"
        L_0x0051:
            X.17k.A07(r1, r0)
            X.00P r0 = X.AnonymousClass00P.createAndThrow()
            throw r0
        L_0x0059:
            X.4g7 r1 = r2.A0h
            java.lang.String r0 = "Netego bakeoff units, quality surveys, story creation upsells and ads consent growth need to have a SimpleAction"
            X.17k.A07(r1, r0)
            X.3IK r0 = r1.A00
            java.lang.String r1 = r0.Air()
            java.lang.String r0 = "Netego's SimpleAction will always have button text"
            X.17k.A07(r1, r0)
            return r1
        L_0x006c:
            X.4gE r1 = r2.A0C
            java.lang.String r0 = "Meta Gallery Stories Netego needs to have a MetaGalleryNetegoInfo"
            X.17k.A07(r1, r0)
            X.3I6 r0 = r1.A01
            java.lang.String r1 = r0.getCtaText()
            if (r1 != 0) goto L_0x00ae
            java.lang.String r1 = "Required value was null."
            java.lang.IllegalStateException r0 = new java.lang.IllegalStateException
            r0.<init>(r1)
            throw r0
        L_0x0083:
            X.4g8 r1 = r2.A0f
            java.lang.String r0 = "Netego ad4ad unit needs to have an Ad4ad object"
            X.17k.A07(r1, r0)
            X.3Hc r0 = r1.A00
            java.lang.String r1 = r0.AYU()
            goto L_0x009e
        L_0x0091:
            X.4gD r1 = r2.A0D
            java.lang.String r0 = "Threads in stories unit Netego needs to have a ThreadsInStoriesUnitNetego"
            X.17k.A07(r1, r0)
            X.3IS r0 = r1.A00
            java.lang.String r1 = r0.getCtaText()
        L_0x009e:
            if (r1 != 0) goto L_0x00ae
            java.lang.String r1 = ""
            return r1
        L_0x00a3:
            X.4g9 r1 = r2.A09
            java.lang.String r0 = "Netego SU unit needs to have an SU object"
            X.17k.A07(r1, r0)
            X.3IN r0 = r1.A00
            java.lang.String r1 = r0.A03
        L_0x00ae:
            return r1
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.A0T():java.lang.String");
    }

    public final String A0U(UserSession userSession) {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return C231122qu.A07(userSession, r0);
    }

    public final String A0W(UserSession userSession) {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r1 = this.A0b;
        r1.getClass();
        AnonymousClass3OA A002 = 1wN.A00(userSession).A00(r1);
        if (A002 != null) {
            return A002.A0X;
        }
        return r1.A0C.Axm();
    }

    public final String A0X(UserSession userSession) {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return C231122qu.A0B(userSession, r0);
    }

    public final String A0Y(UserSession userSession) {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return C231122qu.A0D(userSession, r0);
    }

    public final String A0Z(UserSession userSession) {
        if (this.A0e != C250963mL.MEDIA) {
            return null;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return C231122qu.A0E(userSession, r0);
    }

    public final List A0a() {
        if (this.A0e != C250963mL.MEDIA) {
            return new ArrayList();
        }
        1Xj r2 = this.A0b;
        r2.getClass();
        List BUb = r2.A0C.BUb();
        if (BUb != null) {
            return BUb;
        }
        ArrayList arrayList = new ArrayList();
        r2.A0C.Edg(arrayList);
        return arrayList;
    }

    public final List A0b() {
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A4b;
        } else if (ordinal != 1 && ordinal != 6) {
            return null;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.A3F();
        }
    }

    public final List A0c() {
        List CFJ;
        if (this.A0e.ordinal() != 1) {
            return new ArrayList();
        }
        1Xj r2 = this.A0b;
        r2.getClass();
        synchronized (r2) {
            CFJ = r2.A0C.CFJ();
            if (CFJ == null) {
                CFJ = new ArrayList();
                r2.A0C.Eqg(CFJ);
            }
        }
        return CFJ;
    }

    public final void A0d() {
        this.A0p.clear();
        this.A0r.clear();
        this.A0n.clear();
        this.A0q.clear();
        this.A0o.clear();
        this.A0N = false;
    }

    /* JADX WARNING: Can't fix incorrect switch cases order */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final void A0e(java.lang.String r4) {
        /*
            r3 = this;
            if (r4 == 0) goto L_0x000e
            int r0 = r4.hashCode()
            r2 = 1
            r1 = 0
            switch(r0) {
                case -1077756671: goto L_0x001f;
                case 3083677: goto L_0x001c;
                case 1843485230: goto L_0x000f;
                default: goto L_0x000b;
            }
        L_0x000b:
            r0 = 0
        L_0x000c:
            r3.A0G = r0
        L_0x000e:
            return
        L_0x000f:
            java.lang.String r0 = "network"
            boolean r0 = r4.equals(r0)
            if (r0 == 0) goto L_0x000b
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r1)
            goto L_0x000c
        L_0x001c:
            java.lang.String r0 = "disk"
            goto L_0x0021
        L_0x001f:
            java.lang.String r0 = "memory"
        L_0x0021:
            boolean r0 = r4.equals(r0)
            if (r0 == 0) goto L_0x000b
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r2)
            goto L_0x000c
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.A0e(java.lang.String):void");
    }

    public final boolean A0f() {
        Boolean AkT;
        1Xj r0 = this.A0b;
        if (r0 == null || (AkT = r0.A0C.AkT()) == null || !AkT.booleanValue()) {
            return false;
        }
        return true;
    }

    public final boolean A0h() {
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A4z;
        } else if (ordinal != 1) {
            return false;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            Boolean CZo = r02.A0C.CZo();
            if (CZo != null) {
                return CZo.booleanValue();
            }
            return false;
        }
    }

    public final boolean A0i() {
        1Xj r0 = this.A0b;
        if (r0 == null || r0.A0C.ApS() == null) {
            return false;
        }
        return true;
    }

    public final boolean A0j() {
        1Xj r0 = this.A0b;
        if (r0 == null || !r0.A4c()) {
            return false;
        }
        return true;
    }

    public final boolean A0k() {
        1Xj r0 = this.A0b;
        if (r0 == null || !0qQ.A0K(r0.A0C.AkE(), true)) {
            return false;
        }
        return true;
    }

    public final boolean A0m() {
        1Xj r0 = this.A0b;
        if (r0 != null) {
            return r0.A4Y();
        }
        C270194gL r02 = this.A0c;
        if (r02 == null) {
            return false;
        }
        Boolean bool = r02.A0L;
        if (bool == null || !bool.booleanValue()) {
            return true;
        }
        return false;
    }

    public final boolean A0n() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A4Z()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0o() {
        String str;
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            List list = r0.A00.A4Z;
            if (list != null) {
                str = AnonymousClass6MS.A01((ReelCTAIntf) list.get(0));
            } else {
                str = null;
            }
        } else if (ordinal != 1) {
            return false;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            str = r02.A2j();
        }
        return !TextUtils.isEmpty(str);
    }

    public final boolean A0p() {
        ReelCTAIntf reelCTAIntf;
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            List C0M = r0.A0C.C0M();
            if (C0M == null || (reelCTAIntf = (ReelCTAIntf) 00k.A0J(C0M)) == null || !0qQ.A0K(reelCTAIntf.BBN(), true)) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0q() {
        if (A1t(AnonymousClass3WT.POLLING) || A1t(AnonymousClass3WT.QUESTION) || A1t(AnonymousClass3WT.QUIZ) || A1t(AnonymousClass3WT.SLIDER)) {
            return true;
        }
        return false;
    }

    public final boolean A0r() {
        List list;
        ReelCTAIntf reelCTAIntf;
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            List list2 = r0.A00.A4Z;
            if (list2 == null || (reelCTAIntf = (ReelCTAIntf) 00k.A0O(list2, 0)) == null) {
                list = null;
            } else {
                list = reelCTAIntf.BN4();
            }
            return !AnonymousClass4KJ.A00(list);
        } else if (ordinal != 1) {
            return false;
        } else {
            1Xj r1 = this.A0b;
            r1.getClass();
            if (!AnonymousClass4KJ.A00(r1.A3h()) || (!r1.A3P().isEmpty())) {
                return true;
            }
            return false;
        }
    }

    public final boolean A0s() {
        int ordinal;
        C250963mL r3 = this.A0e;
        0qQ.A0B(r3, 0);
        if (C250983mN.A00.containsValue(r3) || (ordinal = r3.ordinal()) == 0) {
            return true;
        }
        if (ordinal != 1 && ordinal != 9) {
            return false;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        return r0.A4p();
    }

    public final boolean A0t() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (r0.A20() == null) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0w() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (r0.A1y() == null) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0x() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (r0.A21() == null) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0y() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (r0.A1z() == null) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0z() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A4z()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A10() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            Boolean BCJ = r0.A0C.BCJ();
            if (BCJ == null || !BCJ.booleanValue()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A11() {
        Venue A24;
        1Xj r0 = this.A0b;
        if (r0 == null || (A24 = r0.A24()) == null || A24.A00() == null || A24.A01() == null) {
            return false;
        }
        return true;
    }

    public final boolean A12() {
        if (this.A0e != C250963mL.AR_EFFECT_PREVIEW || this.A05 == null) {
            return false;
        }
        return true;
    }

    public final boolean A13() {
        StoryPromptType storyPromptType;
        StoryPromptTappableDataIntf Bhq;
        if (this.A0e != C250963mL.MEDIA) {
            return false;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        List<AnonymousClass5B2> C0x = r0.A0C.C0x();
        if (C0x == null) {
            return false;
        }
        if ((C0x instanceof Collection) && C0x.isEmpty()) {
            return false;
        }
        for (AnonymousClass5B2 r2 : C0x) {
            StoryPromptTappableDataIntf Bhq2 = r2.Bhq();
            if (Bhq2 != null) {
                storyPromptType = Bhq2.Bhw();
            } else {
                storyPromptType = null;
            }
            if (storyPromptType == StoryPromptType.STORY_TEMPLATE && (Bhq = r2.Bhq()) != null && 0qQ.A0K(Bhq.Cej(), true)) {
                return true;
            }
        }
        return false;
    }

    public final boolean A14() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.CAPTION != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A15() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r1 = this.A0b;
            r1.getClass();
            if (r1.A0C.Ae3() == null || r1.A0C.Ae3() == AutoGeneratedCardType.UNRECOGNIZED) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A17() {
        if (this.A0e == C250963mL.BROADCAST) {
            return true;
        }
        return false;
    }

    public final boolean A18() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.CLICK_TO_MESSAGING_FAQS != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A19() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.CLICK_TO_MESSAGING_WHATSAPP != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1A() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A5H()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1B() {
        C250963mL r2 = this.A0e;
        if (r2 == C250963mL.EMPTY_STORIES_STATE_CONTACT_IMPORT || r2 == C250963mL.EMPTY_STORIES_STATE_SUGGESTED_USERS) {
            return true;
        }
        return false;
    }

    public final boolean A1C() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A5N()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1D() {
        1Xj r0 = this.A0b;
        if (r0 == null || !r0.A5P()) {
            return false;
        }
        return true;
    }

    public final boolean A1E() {
        if (this.A0e == C250963mL.STORIES_TEASER) {
            return true;
        }
        return false;
    }

    public final boolean A1F() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.FIRST_QUESTION_LEADGEN != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1G() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.FIRST_QUESTION_SHORT_ANSWER_LEADGEN != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1I() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.GENERIC_CARD != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1J() {
        if (this.A0Q) {
            return true;
        }
        1Xj r0 = this.A0b;
        if (r0 == null || r0.A0C.B2n() != null) {
            return false;
        }
        return true;
    }

    public final boolean A1K() {
        StoryPromptType storyPromptType;
        GenAIToolInfoDictIntf B91;
        if (this.A0e != C250963mL.MEDIA) {
            return false;
        }
        1Xj r0 = this.A0b;
        r0.getClass();
        List<AnonymousClass5B2> C0x = r0.A0C.C0x();
        if (C0x == null) {
            return false;
        }
        if ((C0x instanceof Collection) && C0x.isEmpty()) {
            return false;
        }
        for (AnonymousClass5B2 r3 : C0x) {
            StoryPromptTappableDataIntf Bhq = r3.Bhq();
            CameraTool cameraTool = null;
            if (Bhq != null) {
                storyPromptType = Bhq.Bhw();
            } else {
                storyPromptType = null;
            }
            if (storyPromptType == StoryPromptType.STORY_TEMPLATE) {
                StoryPromptTappableDataIntf Bhq2 = r3.Bhq();
                if (!(Bhq2 == null || (B91 = Bhq2.B91()) == null)) {
                    cameraTool = B91.C8A();
                }
                if (cameraTool == CameraTool.IMAGINE) {
                    return true;
                }
            }
        }
        return false;
    }

    public final boolean A1L() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A5b()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1M() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.LEADGEN != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1N() {
        if (this.A0e == C250963mL.LOADING_PLACEHOLDER) {
            return true;
        }
        return false;
    }

    public final boolean A1O() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A5e()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1P() {
        C250963mL r2 = this.A0e;
        if (r2 == C250963mL.NETEGO_BAKEOFF || this.A0f != null || A1U() || A1S() || A1T() || r2 == C250963mL.NETEGO_VISIT_THESE_SHOPS_AGAIN || r2 == C250963mL.NETEGO_BLOKS || A1Q() || A1R() || A1V() || r2 == C250963mL.NETEGO_META_GALLERY_STORIES) {
            return true;
        }
        return false;
    }

    public final boolean A1Q() {
        if (this.A0e == C250963mL.NETEGO_TRENDING_PROMPTS_IN_STORY) {
            return true;
        }
        return false;
    }

    public final boolean A1R() {
        if (this.A0e == C250963mL.NETEGO_SHARE_COMMENT_TO_STORY) {
            return true;
        }
        return false;
    }

    public final boolean A1S() {
        if (this.A0e == C250963mL.NETEGO_SUGGESTED_CLIPS) {
            return true;
        }
        return false;
    }

    public final boolean A1T() {
        C250963mL r2 = this.A0e;
        if (r2 == C250963mL.NETEGO_RECON_CONTINUE_SHOPPING || r2 == C250963mL.NETEGO_RECON_PRODUCTS_FOR_YOU) {
            return true;
        }
        return false;
    }

    public final boolean A1U() {
        if (this.A0e == C250963mL.NETEGO_SUGGESTED_USERS) {
            return true;
        }
        return false;
    }

    public final boolean A1V() {
        if (this.A0e == C250963mL.NETEGO_THREADS_IN_STORIES_UNIT_ACQUISITION) {
            return true;
        }
        return false;
    }

    /* JADX WARNING: Code restructure failed: missing block: B:25:0x0043, code lost:
        if (r0.A01.A09 == false) goto L_0x0045;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final boolean A1W() {
        /*
            r3 = this;
            X.3mL r1 = r3.A0e
            X.3mL r0 = X.C250963mL.NETEGO_BAKEOFF
            if (r1 == r0) goto L_0x0056
            X.4g8 r0 = r3.A0f
            if (r0 != 0) goto L_0x0056
            boolean r0 = r3.A1U()
            if (r0 != 0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_QUALITY_SURVEY
            if (r1 == r0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_INSIGHTS_GROWTH
            if (r1 == r0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_STORY_CREATION_UPSELL
            if (r1 == r0) goto L_0x0056
            boolean r0 = r3.A1S()
            if (r0 != 0) goto L_0x0056
            boolean r0 = r3.A1T()
            if (r0 != 0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_VISIT_THESE_SHOPS_AGAIN
            if (r1 == r0) goto L_0x0056
            boolean r0 = r3.A1Q()
            if (r0 != 0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_IG_ADS_CONSENT_GROWTH
            if (r1 == r0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_BLOKS
            if (r1 != r0) goto L_0x0045
            X.4gB r0 = r3.A0A
            r0.getClass()
            X.3Hj r0 = r0.A01
            boolean r0 = r0.A09
            if (r0 != 0) goto L_0x0056
        L_0x0045:
            boolean r0 = r3.A1R()
            if (r0 != 0) goto L_0x0056
            boolean r0 = r3.A1V()
            if (r0 != 0) goto L_0x0056
            X.3mL r0 = X.C250963mL.NETEGO_META_GALLERY_STORIES
            r2 = 0
            if (r1 != r0) goto L_0x0057
        L_0x0056:
            r2 = 1
        L_0x0057:
            return r2
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.A1W():boolean");
    }

    public final boolean A1X() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (AutoGeneratedCardType.OFFSITE_LEADGEN_CARD != r0.A0C.Ae3()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1Y() {
        if (this.A0e != C250963mL.OPTIMISTIC_MEDIA || this.A0d == null) {
            return false;
        }
        return true;
    }

    public final boolean A1Z() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A5o()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1a() {
        int ordinal = this.A0e.ordinal();
        if (ordinal != 3 && ordinal != 4) {
            return A1m();
        }
        if (!A1m() || this.A0c == null) {
            return false;
        }
        return true;
    }

    public final boolean A1c() {
        1Xj r0 = this.A0b;
        if (r0 == null || !0qQ.A0K(r0.A0C.Ccm(), true)) {
            return false;
        }
        return true;
    }

    public final boolean A1d() {
        Object obj;
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            obj = r0.A00.A2K;
        } else if (ordinal != 1) {
            return false;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            obj = r02.A0C.AcN();
        }
        if (obj != null) {
            return true;
        }
        return false;
    }

    public final boolean A1e() {
        1Xj r0 = this.A0b;
        if (r0 == null || !0qQ.A0K(r0.A0C.Cb0(), true)) {
            return false;
        }
        return true;
    }

    public final boolean A1f() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A60()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1h() {
        1Xj r1 = this.A0b;
        if (r1 == null || r1.CcK() || ((!r1.A4u() && r1.A3o(AnonymousClass3WT.MULTI_PRODUCT) == null && r1.A26() == null) || r1.A3F().isEmpty())) {
            return false;
        }
        return true;
    }

    public final boolean A1i() {
        if (this.A0e == C250963mL.STORY_SNAPSHOT) {
            return true;
        }
        return false;
    }

    public final boolean A1j() {
        if (this.A0e == C250963mL.MEDIA) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A68()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1k() {
        C250963mL r1 = this.A0e;
        0qQ.A0B(r1, 0);
        return C250983mN.A00.containsValue(r1);
    }

    public final boolean A1l() {
        C250963mL r1 = this.A0e;
        0qQ.A0B(r1, 0);
        if (C250983mN.A00.containsValue(r1)) {
            C64113LOb lOb = this.A0E;
            lOb.getClass();
            if (C18409VrB.A01.get(lOb.A04) != null) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A1m() {
        C250963mL r2 = this.A0e;
        0qQ.A0B(r2, 0);
        if (C250983mN.A00.containsValue(r2)) {
            return true;
        }
        int ordinal = r2.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return r0.A00.A12();
        } else if (ordinal == 1 || ordinal == 9) {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.CeS();
        } else if (ordinal == 3 || ordinal == 4) {
            return true;
        } else {
            return false;
        }
    }

    public final boolean A1n(UserSession userSession) {
        String str;
        if (this.A0e != C250963mL.MEDIA) {
            return false;
        }
        1Xj r1 = this.A0b;
        r1.getClass();
        0qQ.A0B(userSession, 0);
        List<XB2> C0m = r1.A0C.C0m();
        if (C0m == null) {
            return false;
        }
        if ((C0m instanceof Collection) && C0m.isEmpty()) {
            return false;
        }
        for (XB2 BUv : C0m) {
            StoryMusicPickTappableDataIntf BUv2 = BUv.BUv();
            if (BUv2 != null) {
                str = BUv2.Ae0();
            } else {
                str = null;
            }
            if (0qQ.A0K(str, 0eE.A00(userSession).A00().getId())) {
                return true;
            }
        }
        return false;
    }

    public final boolean A1o(UserSession userSession) {
        if (this.A0e != C250963mL.BRAND_SURVEY || !182.A06(0Tu.A05, userSession, 36318106016225149L)) {
            return false;
        }
        return true;
    }

    public final boolean A1p(UserSession userSession) {
        if (this.A0e != C250963mL.BRAND_SURVEY || !182.A06(0Tu.A05, userSession, 36318106016225149L)) {
            return false;
        }
        return true;
    }

    public final boolean A1q(UserSession userSession) {
        C250963mL r3 = this.A0e;
        if (r3 == C250963mL.NETEGO_BAKEOFF || r3 == C250963mL.NETEGO_SUGGESTED_USERS || r3 == C250963mL.NETEGO_QUALITY_SURVEY || r3 == C250963mL.NETEGO_INSIGHTS_GROWTH || r3 == C250963mL.NETEGO_STORY_CREATION_UPSELL || r3 == C250963mL.NETEGO_IG_ADS_CONSENT_GROWTH || r3 == C250963mL.NETEGO_RECON_PRODUCTS_FOR_YOU || r3 == C250963mL.NETEGO_RECON_CONTINUE_SHOPPING || r3 == C250963mL.NETEGO_SUGGESTED_CLIPS || r3 == C250963mL.NETEGO_TRENDING_PROMPTS_IN_STORY || r3 == C250963mL.NETEGO_VISIT_THESE_SHOPS_AGAIN || r3 == C250963mL.NETEGO_BLOKS || r3 == C250963mL.STORY_INTERSTITIAL_CHAINING || ((r3 == C250963mL.STORY_INTERSTITIAL_POG_GARDEN_CHAINING && 182.A06(0Tu.A06, userSession, 36328027390884730L)) || r3 == C250963mL.STORIES_TEASER || r3 == C250963mL.NETEGO_SHARE_COMMENT_TO_STORY || r3 == C250963mL.NETEGO_THREADS_IN_STORIES_UNIT_ACQUISITION || r3 == C250963mL.NETEGO_META_GALLERY_STORIES || r3 == C250963mL.STORY_SNAPSHOT || r3 == C250963mL.EMPTY_STORIES_STATE_CONTACT_IMPORT || r3 == C250963mL.EMPTY_STORIES_STATE_SUGGESTED_USERS)) {
            return true;
        }
        return false;
    }

    public final boolean A1r(UserSession userSession) {
        if (this.A0e != C250963mL.MEDIA) {
            return false;
        }
        1Xj r1 = this.A0b;
        r1.getClass();
        AnonymousClass3OA A002 = 1wN.A00(userSession).A00(r1);
        if (A002 != null) {
            return A002.A0n;
        }
        return r1.A6K();
    }

    public final boolean A1s(UserSession userSession) {
        1Xj r1 = this.A0b;
        if (r1 == null || !2R8.A02(userSession, r1) || !r1.A6b(userSession) || !182.A06(0Tu.A05, userSession, 36327237116573937L)) {
            return false;
        }
        return true;
    }

    public final 1Xj BPf() {
        return this.A0b;
    }

    public final List Bkd(AnonymousClass3WT r3) {
        int ordinal = this.A0e.ordinal();
        if (ordinal == 0) {
            C270184gK r0 = this.A0d;
            r0.getClass();
            return AnonymousClass497.A01(r3, r0.A00.A4b);
        } else if (ordinal != 1) {
            return null;
        } else {
            1Xj r02 = this.A0b;
            r02.getClass();
            return r02.A3o(r3);
        }
    }

    public final /* bridge */ /* synthetic */ User CCd() {
        return this.A0i;
    }

    public final String CFY() {
        String str = this.A0a;
        if (str != null) {
            return str;
        }
        String A062 = 0mp.A06("%s_%s", new Object[]{this.A0j, this.A0k});
        this.A0a = A062;
        return A062;
    }

    public final boolean CWu() {
        if (this.A0e != C250963mL.MEDIA || this.A0b == null) {
            return false;
        }
        return true;
    }

    public final boolean CYg() {
        if (this.A0e == C250963mL.ROLL_CALL_EMPTY_STATE || A09() == null || !A09().CYg()) {
            return false;
        }
        return true;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof C255773uh) || !2PP.A00(((C255773uh) obj).A0j, this.A0j)) {
            return false;
        }
        return true;
    }

    public final String getId() {
        return this.A0j;
    }

    public final int hashCode() {
        return Arrays.hashCode(new Object[]{this.A0j});
    }

    public final PromptStickerModel A0J() {
        List<C255783ui> A0b2 = A0b();
        if (A0b2 != null) {
            for (C255783ui A0F2 : A0b2) {
                PromptStickerModel A0F3 = A0F2.A0F();
                if (A0F3 != null) {
                    return A0F3;
                }
            }
        }
        return null;
    }

    public final PromptStickerModel A0K() {
        List<C255783ui> A0b2 = A0b();
        if (A0b2 != null) {
            for (C255783ui A0F2 : A0b2) {
                PromptStickerModel A0F3 = A0F2.A0F();
                if (A0F3 != null && A0F3.A0M()) {
                    return A0F3;
                }
            }
        }
        return null;
    }

    public final boolean A0g() {
        if (CWu()) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.A4N()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A0l() {
        String str;
        ReelCTAIntf A0A2 = A0A();
        if (A0A2 != null) {
            str = AnonymousClass6MS.A00(A0A2);
        } else {
            str = null;
        }
        if (TextUtils.isEmpty(str) || A12()) {
            return false;
        }
        return true;
    }

    public final boolean A0u() {
        C255783ui A002 = AnonymousClass497.A00(AnonymousClass3WT.MUSIC_OVERLAY, A0b());
        if (AnonymousClass497.A00(AnonymousClass3WT.MUSIC_LYRICS, A0b()) != null || A002 == null || !0mp.A0B(A002.A1g)) {
            return false;
        }
        return true;
    }

    public final boolean A0v() {
        if (A0t()) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (r0.CcK()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final boolean A16() {
        if (!A1Y()) {
            return false;
        }
        C270184gK r0 = this.A0d;
        r0.getClass();
        AnonymousClass3Q2 r1 = r0.A00;
        if (r1.A10() || C59911Jba.A02(r1)) {
            return true;
        }
        if ((!r1.A12() || r1.A3V != null) && r1.A33 != null) {
            return false;
        }
        return true;
    }

    public final boolean A1H() {
        if (A05() != null) {
            return true;
        }
        return false;
    }

    public final boolean A1b() {
        if (A1m() || this.A0e != C250963mL.MEDIA) {
            return false;
        }
        return true;
    }

    public final boolean A1g() {
        if (A05() == null) {
            return true;
        }
        if (A05().Bu2() == null || A05().Bu2().booleanValue()) {
            return false;
        }
        return true;
    }

    public final boolean A1t(AnonymousClass3WT r3) {
        List Bkd = Bkd(r3);
        if (Bkd == null || Bkd.isEmpty()) {
            return false;
        }
        return true;
    }

    public final float AcY(UserSession userSession) {
        return A00();
    }

    public final String ByO(UserSession userSession) {
        return C231122qu.A06(userSession, A09());
    }

    public final boolean CUz() {
        if (A09() == null || !A09().CUz()) {
            return false;
        }
        return true;
    }

    public final boolean CcK() {
        if (CWu()) {
            1Xj r0 = this.A0b;
            r0.getClass();
            if (!r0.CcK()) {
                return false;
            }
            return true;
        }
        return false;
    }

    public C255773uh(1Xj r5, AnonymousClass3OA r6, User user, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = r5;
        this.A0g = r6;
        this.A0d = null;
        this.A0e = C250963mL.MEDIA;
        this.A0j = r5.getId();
        this.A0i = user;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A0F = null;
        this.A07 = null;
        this.A00 = 0;
        this.mBrandSurveyImpression = null;
        if (!r5.A3F().isEmpty()) {
            Iterator it = r5.A3F().iterator();
            while (it.hasNext()) {
                ((C255783ui) it.next()).A1d = str;
            }
        }
    }

    public C255773uh(1Xj r5, C250963mL r6, User user, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = r5;
        this.A0g = null;
        this.A0d = null;
        this.A0e = r6;
        this.A0j = r5.getId();
        this.A0i = user;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A0F = null;
        this.A00 = 0;
        if (!r5.A3F().isEmpty()) {
            Iterator it = r5.A3F().iterator();
            while (it.hasNext()) {
                ((C255783ui) it.next()).A1d = str;
            }
        }
        this.mBrandSurveyImpression = null;
    }

    public C255773uh(1Xj r5, C270084gA r6, C270074g9 r7, C270064g8 r8, C270094gB r9, C270104gC r10, C270124gE r11, C270114gD r12, C270054g7 r13, User user, Integer num, String str) {
        C250963mL r0;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0d = null;
        this.A0c = null;
        this.mBrandSurveyImpression = null;
        switch (num.intValue()) {
            case 0:
                17k.A07(r13, "Netego bakeoff units needs to have a SimpleAction");
                this.A0j = r13.getId();
                this.A0e = C250963mL.NETEGO_BAKEOFF;
                this.A0h = r13;
                this.A0f = null;
                this.A09 = null;
                this.A07 = null;
                this.A0b = r5;
                this.A0g = null;
                this.A0i = null;
                this.A0A = null;
                this.A0D = null;
                return;
            case 1:
                17k.A07(r8, "Netego ad4ad unit needs to have an Ad4ad object");
                this.A0j = r8.getId();
                this.A0e = C250963mL.MEDIA;
                this.A0f = r8;
                this.A09 = null;
                this.A0h = null;
                this.A07 = null;
                this.A0b = r5;
                this.A0g = null;
                this.A0i = user;
                this.A0A = null;
                this.A0D = null;
                return;
            case 2:
                17k.A07(r7, "Netego SU unit needs to have an SU object");
                this.A0j = r7.getId();
                this.A0e = C250963mL.NETEGO_SUGGESTED_USERS;
                this.A0f = null;
                this.A09 = r7;
                this.A0h = null;
                this.A07 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A0A = null;
                this.A0D = null;
                return;
            case 3:
                17k.A07(r13, "Netego quality survey needs to have a SimpleAction");
                this.A0j = r13.getId();
                r0 = C250963mL.NETEGO_QUALITY_SURVEY;
                break;
            case 4:
                17k.A07(r13, "Story creation upsell needs to have a SimpleAction");
                this.A0j = r13.getId();
                r0 = C250963mL.NETEGO_STORY_CREATION_UPSELL;
                break;
            case 5:
                17k.A07((Object) null, "Netego suggested clips unit needs to have an suggested clips object");
                throw AnonymousClass00P.createAndThrow();
            case 6:
            case 7:
                17k.A07((Object) null, "Netego PFY unit needs to have an suggested products object");
                throw AnonymousClass00P.createAndThrow();
            case 8:
                17k.A07((Object) null, "Netego shops for you unit needs to have an suggested shops object");
                throw AnonymousClass00P.createAndThrow();
            case 9:
                17k.A07(r13, "Ads consent growth story needs to have a SimpleAction");
                this.A0j = r13.getId();
                this.A0e = C250963mL.NETEGO_IG_ADS_CONSENT_GROWTH;
                this.A0h = r13;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0D = null;
                return;
            case 10:
                17k.A07(r9, "Bloks netego needs to have a BloksStoryNetego.");
                this.A0j = r9.A01.A05;
                this.A0e = C250963mL.NETEGO_BLOKS;
                this.A0f = null;
                this.A09 = null;
                this.A0h = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0A = r9;
                this.A0D = null;
                return;
            case 11:
                17k.A07(r6, "Netego trending prompts unit needs to have a prompts in story object");
                this.A0j = r6.getId();
                this.A0e = C250963mL.NETEGO_TRENDING_PROMPTS_IN_STORY;
                this.A0f = null;
                this.A09 = null;
                this.A0h = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = r6;
                this.A0A = null;
                this.A0D = null;
                return;
            case IgReactQEModule.CONFIG_KEY_OFFSET /*12*/:
                17k.A07(r13, "Insights netego needs to have a SimpleAction");
                this.A0j = r13.getId();
                r0 = C250963mL.NETEGO_INSIGHTS_GROWTH;
                break;
            case 13:
                17k.A07(r10, "Share Comment to Story Netego needs to have a CommentShareNetego");
                this.A0j = r10.getId();
                this.A0e = C250963mL.NETEGO_SHARE_COMMENT_TO_STORY;
                this.A0h = null;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0B = r10;
                this.A0D = null;
                return;
            case 14:
                17k.A07(r11, "Meta Gallery Stories Netegos need to have a MetaGalleryNetegoInfo");
                this.A0j = r11.getId();
                this.A0e = C250963mL.NETEGO_META_GALLERY_STORIES;
                this.A0f = null;
                this.A09 = null;
                this.A0h = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0A = null;
                this.A0C = r11;
                this.A0D = null;
                return;
            case 15:
                17k.A07(r12, "Threads in stories unit Netego needs to have a ThreadsInStoriesUnitNetego");
                this.A0j = r12.getId();
                this.A0e = C250963mL.NETEGO_THREADS_IN_STORIES_UNIT_ACQUISITION;
                this.A0h = null;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A07 = null;
                this.A0B = null;
                this.A0D = r12;
                return;
            default:
                this.A0h = null;
                this.A0f = null;
                this.A09 = null;
                this.A0b = null;
                this.A0g = null;
                this.A0i = null;
                this.A0A = null;
                this.A07 = null;
                this.A0D = null;
                throw new IllegalArgumentException(C273654mx.A00(526));
        }
        this.A0e = r0;
        this.A0h = r13;
        this.A0f = null;
        this.A09 = null;
        this.A0b = null;
        this.A0g = null;
        this.A0i = null;
        this.A07 = null;
        this.A0A = null;
        this.A0D = null;
    }

    public C255773uh(1Xj r2, User user, String str) {
        this(r2, C250963mL.MEDIA, user, str);
    }

    /* JADX WARNING: type inference failed for: r2v1, types: [X.1Xy, java.lang.Object] */
    public C255773uh(AnonymousClass3IB r7, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0e = C250963mL.BRAND_SURVEY;
        this.mBrandResearchSurvey = r7;
        String str2 = r7.A04;
        str2.getClass();
        String str3 = r7.A08;
        this.mBrandSurveyImpression = new C270204gM(str2, str3);
        this.A0g = null;
        1Xv r0 = 1Xj.A0h;
        1Xj r02 = new 1Xj(new 1hu((UserSession) null), new Object());
        this.A0b = r02;
        r02.A4G(str);
        r02.A0C.Eeu(str3);
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A0d = null;
        this.A09 = null;
        this.A07 = null;
        this.A0j = str2;
        this.A0i = null;
    }

    public C255773uh(AnonymousClass3IL r5, User user, String str, String str2) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0j = str2;
        this.A0e = C250963mL.STORY_SNAPSHOT;
        this.A0i = user;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
        this.A03 = r5;
    }

    public C255773uh(C250963mL r5, User user, String str, String str2) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0e = r5;
        this.A0j = str2;
        this.A0i = user;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
    }

    public C255773uh(C270184gK r6, User user, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0d = r6;
        this.A0b = null;
        this.A0g = null;
        this.A0e = C250963mL.OPTIMISTIC_MEDIA;
        this.A0j = r6.A00.A3t;
        this.A0i = user;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
    }

    public C255773uh(C270194gL r5, C250963mL r6, String str) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0c = r5;
        String str2 = r5.A0e;
        str2.getClass();
        this.A0j = str2;
        User user = r5.A09;
        user.getClass();
        this.A0i = user;
        this.A0e = r6;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        this.mBrandSurveyImpression = null;
    }

    /* JADX WARNING: type inference failed for: r1v2, types: [java.lang.Object, X.4g9] */
    public C255773uh(C46313DUq dUq, String str, String str2) {
        C250963mL r5;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0j = str2;
        C46313DUq dUq2 = dUq;
        if (dUq2.C4Z().equals("suggested_users_contact_import")) {
            r5 = C250963mL.EMPTY_STORIES_STATE_CONTACT_IMPORT;
            this.A0e = r5;
        } else if (dUq2.C4Z().equals("suggested_users_ayml_card")) {
            r5 = C250963mL.EMPTY_STORIES_STATE_SUGGESTED_USERS;
            this.A0e = r5;
        } else {
            r5 = C250963mL.EMPTY_STORIES_STATE_UNKNOWN;
            this.A0e = r5;
        }
        this.A0i = null;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        if (r5 != C250963mL.EMPTY_STORIES_STATE_SUGGESTED_USERS || dUq2.BH8() == null) {
            this.A09 = null;
        } else {
            ArrayList arrayList = new ArrayList();
            for (AnonymousClass3UK r4 : dUq2.BH8()) {
                0qQ.A0B(r4, 0);
                String algorithm = r4.getAlgorithm();
                algorithm = algorithm == null ? "unknown" : algorithm;
                String BxN = r4.BxN();
                BxN = BxN == null ? "" : BxN;
                User CCd = r4.CCd();
                if (CCd != null) {
                    new 1E9(new 1hu((UserSession) null), 6, false);
                    Boolean B6t = r4.B6t();
                    Integer BPt = r4.BPt();
                    List BxQ = r4.BxQ();
                    String CDC = r4.CDC();
                    new 1E9(new 1hu((UserSession) null), 6, false);
                    arrayList.add(new C241283Op((C270814hL) null, (C241273Oo) null, CCd, B6t, (Boolean) null, false, (Float) null, (Float) null, BPt, algorithm, (String) null, (String) null, (String) null, BxN, CDC, (List) null, (List) null, (List) null, BxQ, (List) null));
                } else {
                    throw new IllegalStateException("Required value was null.");
                }
            }
            AnonymousClass3IN r13 = new AnonymousClass3IN(FeedItemType.A2I, "", "", "Suggested for you", "", arrayList, 15, 0, false, true, true, true, true, false, true, true, true);
            ? obj = new Object();
            obj.A00 = r13;
            this.A09 = obj;
        }
        this.A07 = null;
        this.mBrandSurveyImpression = null;
        this.A06 = dUq2;
    }

    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v14, resolved type: X.4gJ} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v15, resolved type: X.4gJ} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v16, resolved type: java.lang.Object} */
    /* JADX DEBUG: Multi-variable search result rejected for TypeSearchVarInfo{r0v17, resolved type: X.4gJ} */
    /* JADX WARNING: Multi-variable type inference failed */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public C255773uh(com.instagram.api.schemas.FanClubStoriesTeaserType r6, com.instagram.common.session.UserSession r7, com.instagram.user.model.User r8, java.lang.String r9, long r10) {
        /*
            r5 = this;
            java.lang.String r3 = "fan_club_stories_teaser"
            r5.<init>()
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>()
            r5.A0l = r0
            r2 = 0
            r5.A0B = r2
            r5.A0Z = r2
            r5.A0D = r2
            r5.A0C = r2
            r4 = 0
            r5.A0W = r4
            r0 = 0
            r5.A0Y = r0
            r5.A0X = r0
            r5.A0N = r4
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>()
            r5.A0p = r0
            java.util.HashSet r0 = new java.util.HashSet
            r0.<init>()
            r5.A0r = r0
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>()
            r5.A0n = r0
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>()
            r5.A0o = r0
            java.util.HashSet r0 = new java.util.HashSet
            r0.<init>()
            r5.A0q = r0
            java.util.ArrayList r0 = new java.util.ArrayList
            r0.<init>()
            r5.A0m = r0
            r5.A0S = r4
            com.instagram.api.schemas.FanClubStoriesTeaserType r0 = com.instagram.api.schemas.FanClubStoriesTeaserType.A05
            r5.A02 = r0
            r5.A01 = r4
            r5.A0k = r9
            r5.A0b = r2
            r5.A0g = r2
            r5.A0d = r2
            r5.A0c = r2
            X.3mL r0 = X.C250963mL.STORIES_TEASER
            r5.A0e = r0
            X.0Tu r4 = X.0Tu.A06
            r0 = 36327073907751059(0x810f4800003893, double:3.036726044422801E-306)
            boolean r0 = X.182.A06(r4, r7, r0)
            r5.A0S = r0
            r0 = 36321610709476957(0x810a500002265d, double:3.033271095835725E-306)
            boolean r0 = X.182.A06(r4, r7, r0)
            if (r0 == 0) goto L_0x0092
            X.4gJ r0 = new X.4gJ
            r0.<init>()
        L_0x007d:
            r5.A0Z = r0
            r5.A0j = r3
            r5.A0i = r8
            r5.A0h = r2
            r5.A0f = r2
            r5.A09 = r2
            r5.A07 = r2
            r5.mBrandSurveyImpression = r2
            r5.A0X = r10
            r5.A02 = r6
            return
        L_0x0092:
            r0 = r2
            goto L_0x007d
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C255773uh.<init>(com.instagram.api.schemas.FanClubStoriesTeaserType, com.instagram.common.session.UserSession, com.instagram.user.model.User, java.lang.String, long):void");
    }

    public C255773uh(UserSession userSession, C250963mL r6, C63731L4p l4p, User user, String str, String str2) {
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        this.A0k = str;
        this.A0j = str2;
        this.A0e = r6;
        this.A0i = user;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0h = null;
        this.A0f = null;
        this.A09 = null;
        this.A07 = null;
        if (C18409VrB.A02.compareAndSet(false, true)) {
            0nY.A00().ATE(new KIS());
        }
        this.A0E = new C64113LOb(userSession, l4p);
        this.mBrandSurveyImpression = null;
        Integer num = l4p.A00.A01;
        if (num != null) {
            this.A0Y = num.longValue();
        }
    }

    public C255773uh(Integer num, List list, List list2) {
        String str;
        C250963mL r0;
        this.A0l = new ArrayList();
        this.A0B = null;
        this.A0Z = null;
        this.A0D = null;
        this.A0C = null;
        this.A0W = false;
        this.A0Y = 0;
        this.A0X = 0;
        this.A0N = false;
        this.A0p = new ArrayList();
        this.A0r = new HashSet();
        this.A0n = new ArrayList();
        this.A0o = new ArrayList();
        this.A0q = new HashSet();
        this.A0m = new ArrayList();
        this.A0S = false;
        this.A02 = FanClubStoriesTeaserType.A05;
        this.A01 = 0;
        int intValue = num.intValue();
        switch (intValue) {
            case 1:
                str = "story_interstitial_roll_call";
                break;
            case 2:
                str = "story_interstitial_fan_club_teaser";
                break;
            case 3:
                str = "story_interstitial_pog_garden_chaining";
                break;
            default:
                str = "story_interstitial_chaining";
                break;
        }
        this.A0k = str;
        this.A0b = null;
        this.A0g = null;
        this.A0d = null;
        this.A0c = null;
        this.A0i = null;
        this.A0j = str;
        this.A0h = null;
        this.A0f = null;
        this.mBrandSurveyImpression = null;
        if (intValue == 0) {
            this.A0K = list;
            this.A0L = list2;
            r0 = C250963mL.STORY_INTERSTITIAL_CHAINING;
        } else if (intValue == 3) {
            this.A0K = list;
            this.A0L = list2;
            r0 = C250963mL.STORY_INTERSTITIAL_POG_GARDEN_CHAINING;
        } else if (intValue == 1) {
            r0 = C250963mL.ROLL_CALL_EMPTY_STATE;
        } else if (intValue == 2) {
            r0 = C250963mL.STORIES_TEASER;
        } else {
            this.A0K = null;
            this.A0L = null;
            throw new IllegalArgumentException("unsupported story interstitial type");
        }
        this.A0e = r0;
    }
}
