package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;

/* renamed from: X.4ho  reason: invalid class name and case insensitive filesystem */
public abstract class C271044ho {
    public static final AutoGeneratedCardType A00(String str) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) AutoGeneratedCardType.A01.get(str);
        if (autoGeneratedCardType == null) {
            return AutoGeneratedCardType.UNRECOGNIZED;
        }
        return autoGeneratedCardType;
    }
}
