package X;

import android.graphics.Color;
import android.graphics.RectF;
import android.graphics.drawable.GradientDrawable;
import android.text.Layout;
import android.view.View;
import com.instagram.api.schemas.CarouselRenderingType;
import com.instagram.api.schemas.IGStoryTextAlignmentTypeEnum;
import com.instagram.api.schemas.IntentAwareAdsFormatType;
import com.instagram.api.schemas.IntentAwareAdsInfo;
import com.instagram.api.schemas.MoreInfoProductTagType;
import com.instagram.api.schemas.MoreInfoType;
import com.instagram.common.session.UserSession;
import com.instagram.model.reels.Reel;
import com.instagram.model.reels.sponsored.AutoGeneratedCardType;
import com.instagram.model.showreel.IgShowreelComposition;
import com.instagram.user.model.User;
import java.util.ArrayList;
import java.util.List;

/* renamed from: X.5sK  reason: invalid class name and case insensitive filesystem */
public abstract class C297785sK {
    public static final List A00 = 0sr.A1P(new IntentAwareAdsFormatType[]{IntentAwareAdsFormatType.MAC_SUBTLE_V1, IntentAwareAdsFormatType.MAC_SUBTLE_V2});

    /* JADX WARNING: Code restructure failed: missing block: B:31:0x005d, code lost:
        if (r3 > 1) goto L_0x005f;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:37:0x006d, code lost:
        if (r1.A65() == true) goto L_0x005a;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static final int A02(com.instagram.common.session.UserSession r5, X.C255773uh r6, X.C250973mM r7, X.C255783ui r8) {
        /*
            r0 = 3
            X.0qQ.A0B(r5, r0)
            if (r8 == 0) goto L_0x0034
            int r4 = r8.A06
        L_0x0008:
            if (r4 < 0) goto L_0x0072
            X.1Xj r3 = r6.A0b
            if (r3 == 0) goto L_0x0072
            boolean r1 = r3.A65()
            boolean r0 = A0l(r7)
            r2 = 0
            if (r0 == 0) goto L_0x0031
            r0 = 0
        L_0x001a:
            if (r1 == 0) goto L_0x0037
            X.1Xy r1 = r3.A0C
            com.instagram.model.showreel.IgShowreelComposition r1 = r1.BwC()
            if (r1 == 0) goto L_0x002e
            java.util.List r1 = r1.Acn()
            if (r1 == 0) goto L_0x002e
            int r2 = r1.size()
        L_0x002e:
            int r2 = r2 * r0
            int r2 = r2 + r4
            return r2
        L_0x0031:
            int r0 = r7.A01
            goto L_0x001a
        L_0x0034:
            int r4 = r7.A01
            goto L_0x0008
        L_0x0037:
            r4 = 1
            java.util.List r1 = X.C250973mM.A00(r5, r7)
            int r3 = r1.size()
            boolean r1 = A0l(r7)
            r2 = 2
            if (r1 != 0) goto L_0x0070
            if (r3 <= r2) goto L_0x005d
            X.3uh r1 = r7.A0A(r5, r2)
            if (r1 == 0) goto L_0x005f
            X.1Xj r1 = r1.A0b
            if (r1 == 0) goto L_0x005f
            boolean r1 = r1.A65()
            if (r1 != r4) goto L_0x005f
            r2 = 3
        L_0x005a:
            int r2 = r0 - r2
            return r2
        L_0x005d:
            if (r3 <= r4) goto L_0x0070
        L_0x005f:
            X.3uh r1 = r7.A0A(r5, r4)
            if (r1 == 0) goto L_0x0070
            X.1Xj r1 = r1.A0b
            if (r1 == 0) goto L_0x0070
            boolean r1 = r1.A65()
            if (r1 != r4) goto L_0x0070
            goto L_0x005a
        L_0x0070:
            r2 = 1
            goto L_0x005a
        L_0x0072:
            return r4
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C297785sK.A02(com.instagram.common.session.UserSession, X.3uh, X.3mM, X.3ui):int");
    }

    public static final int A04(List list, int i) {
        int i2 = 0;
        int i3 = 0;
        while (i2 < list.size() && i2 <= i) {
            if (list.get(i2) == AutoGeneratedCardType.ORIGINAL) {
                i3++;
            }
            i2++;
        }
        return Math.max(0, i3 - 1);
    }

    public static final String A06(UserSession userSession, C255773uh r4, 1Ns r5) {
        0qQ.A0B(userSession, 0);
        0qQ.A0B(r5, 1);
        if (r5.CAm() == AnonymousClass05K.A01) {
            User user = r4.A0i;
            if (user == null) {
                throw new IllegalStateException("Required value was null.");
            } else if (user.equals(r5.CCd()) && r4.CWu()) {
                1Xj r1 = r4.A0b;
                r1.getClass();
                User A2A = r1.A2A(userSession);
                if (A2A == null) {
                    throw new IllegalStateException("Required value was null.");
                } else if (A2A.A2Q()) {
                    return C231122qu.A0G(userSession, r1);
                }
            }
        }
        if (r4.A0e == C250963mL.MEDIA) {
            1Xj r12 = r4.A0b;
            r12.getClass();
            if (C231122qu.A0V(userSession, r12)) {
                return C231122qu.A08(userSession, r12);
            }
        }
        return r5.getName();
    }

    public static final void A07(View view, UserSession userSession, C255773uh r5, C250973mM r6, C255783ui r7) {
        int A02;
        C238883Du r0;
        C238873Dt r02;
        0qQ.A0B(r5, 3);
        0qQ.A0B(userSession, 4);
        if (view != null) {
            1Xj r1 = r5.A0b;
            if ((r1 == null || r1.A5J() || !r1.A65() || 182.A06(0Tu.A06, userSession, 2342171182633073715L)) && (A02 = A02(userSession, r5, r6, r7)) >= 0 && C238833Dp.A00(userSession).A07.A02.get(view) != null && (r0 = (C238883Du) C238833Dp.A00(userSession).A07.A02.get(view)) != null && (r02 = r0.A04) != null) {
                Object obj = r02.A01;
                C238863Ds r12 = C238863Ds.ATTACHMENT;
                if (2PP.A00(obj, r12)) {
                    C238833Dp.A00(userSession).A06(view, r12, A02);
                }
            }
        }
    }

    public static final boolean A09(MoreInfoType moreInfoType) {
        return moreInfoType != null && 0sc.A07(new MoreInfoType[]{MoreInfoType.ADS_VIEW, MoreInfoType.ADS_VISIT, MoreInfoType.LIKED_BY, MoreInfoType.PROFILE_PAGE_VISIT_COUNT}).contains(moreInfoType);
    }

    /* JADX WARNING: Code restructure failed: missing block: B:11:0x002d, code lost:
        if (r0.length() == 0) goto L_0x002f;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:16:0x003b, code lost:
        if (r1 == 0) goto L_0x003d;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:23:0x0051, code lost:
        if (r1 == 0) goto L_0x0053;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:5:0x001d, code lost:
        if (r0.length() == 0) goto L_0x001f;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static final boolean A0B(com.instagram.common.session.UserSession r6, X.C255773uh r7) {
        /*
            r0 = 1
            X.0qQ.A0B(r6, r0)
            X.0Tu r2 = X.0Tu.A05
            r0 = 36324037365935820(0x810c8500012ecc, double:3.034805723151671E-306)
            boolean r1 = X.182.A06(r2, r6, r0)
            r5 = 0
            if (r1 == 0) goto L_0x001f
            java.lang.String r0 = r7.A0V(r6)
            if (r0 == 0) goto L_0x001f
            int r0 = r0.length()
            r4 = 1
            if (r0 != 0) goto L_0x002f
        L_0x001f:
            r4 = 0
            if (r1 != 0) goto L_0x002f
            java.lang.String r0 = r7.A0Y(r6)
            if (r0 == 0) goto L_0x002f
            int r0 = r0.length()
            r3 = 1
            if (r0 != 0) goto L_0x0030
        L_0x002f:
            r3 = 0
        L_0x0030:
            java.lang.String r0 = r7.A0X(r6)
            if (r0 == 0) goto L_0x003d
            int r1 = r0.length()
            r0 = 0
            if (r1 != 0) goto L_0x003e
        L_0x003d:
            r0 = 1
        L_0x003e:
            r2 = r0 ^ 1
            boolean r0 = r7.A1r(r6)
            if (r0 == 0) goto L_0x0053
            java.lang.String r0 = r7.A0W(r6)
            if (r0 == 0) goto L_0x0053
            int r1 = r0.length()
            r0 = 1
            if (r1 != 0) goto L_0x0054
        L_0x0053:
            r0 = 0
        L_0x0054:
            if (r4 != 0) goto L_0x005c
            if (r3 != 0) goto L_0x005c
            if (r2 != 0) goto L_0x005c
            if (r0 == 0) goto L_0x005d
        L_0x005c:
            r5 = 1
        L_0x005d:
            return r5
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C297785sK.A0B(com.instagram.common.session.UserSession, X.3uh):boolean");
    }

    public static final boolean A0F(UserSession userSession, C255773uh r3) {
        0qQ.A0B(userSession, 1);
        1Xj r0 = r3.A0b;
        if (r0 == null || !C243213Xw.A04(userSession, r0) || C309506Yn.A07(userSession, r3)) {
            return false;
        }
        return true;
    }

    public static final boolean A0I(UserSession userSession, C255773uh r5, C250973mM r6) {
        C239733Hx r1;
        if (!r5.CcK() || r5.A1f() || A0B(userSession, r5) || r5.A15() || !AnonymousClass4EQ.A0G(r5) || (r1 = r6.A0H.A0A) == null || !0qQ.A0K(r1.A01, true) || r5.A1A() || A0d(r5) || A0c(r5)) {
            return false;
        }
        return 182.A06(0Tu.A06, userSession, 36319059498769290L);
    }

    public static final boolean A0J(UserSession userSession, C255773uh r4, C250973mM r5) {
        0qQ.A0B(userSession, 0);
        if (A0K(userSession, r4, r5) && A0C(userSession, r4)) {
            Object obj = C69333NjY.A01.get(182.A04(0Tu.A05, userSession, 36880763911864678L));
            if (obj == null) {
                obj = C69333NjY.A04;
            }
            if (obj == C69333NjY.A04) {
                return false;
            }
            return true;
        }
        return false;
    }

    public static final boolean A0L(UserSession userSession, C255773uh r4, C250973mM r5) {
        0qQ.A0B(r4, 1);
        0qQ.A0B(userSession, 2);
        1Xj r2 = r4.A0b;
        if (r2 == null || !r5.A0H.A0w(r5.A03(userSession, r4))) {
            return false;
        }
        r2.getClass();
        if (r2.A5J()) {
            return false;
        }
        float A002 = r4.A00();
        if (0.5525f > A002 || A002 > 0.5725f || !r2.A5p()) {
            return true;
        }
        return false;
    }

    /* JADX WARNING: Code restructure failed: missing block: B:26:0x0063, code lost:
        if (X.C309456Yi.A03(r11) == false) goto L_0x0065;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:42:0x00a0, code lost:
        if (r7 != false) goto L_0x00a2;
     */
    /* JADX WARNING: Removed duplicated region for block: B:41:0x009f  */
    /* JADX WARNING: Removed duplicated region for block: B:46:0x00a9  */
    /* JADX WARNING: Removed duplicated region for block: B:52:? A[RETURN, SYNTHETIC] */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static final boolean A0M(com.instagram.common.session.UserSession r9, X.C255773uh r10, X.C250973mM r11, X.AnonymousClass3BQ r12, X.C309426Yf r13) {
        /*
            r3 = 1
            boolean r0 = r10.A1O()
            r8 = 0
            if (r0 != 0) goto L_0x0057
            boolean r0 = r10.A1f()
            if (r0 != 0) goto L_0x0057
            boolean r0 = A0B(r9, r10)
            if (r0 != 0) goto L_0x0057
            boolean r0 = A0l(r11)
            if (r0 != 0) goto L_0x0057
            X.3BQ r0 = X.AnonymousClass3BQ.MULTI_ADVERTISER_CAROUSEL_POP_UP
            if (r12 == r0) goto L_0x0057
            java.util.List r0 = X.C250973mM.A00(r9, r11)
            int r1 = r0.size()
            if (r1 == r3) goto L_0x0057
            com.instagram.model.reels.Reel r2 = r11.A0H
            boolean r0 = r2.A17(r9)
            if (r0 != 0) goto L_0x0035
            int r0 = r11.A01
            int r1 = r1 - r3
            if (r0 == r1) goto L_0x0049
        L_0x0035:
            boolean r0 = A0K(r9, r10, r11)
            if (r0 != 0) goto L_0x0049
            java.util.List r0 = X.C250973mM.A00(r9, r11)
            int r1 = r0.size()
            int r0 = r2.A00
            int r0 = r0 + 1
            if (r1 != r0) goto L_0x0057
        L_0x0049:
            X.0Tu r2 = X.0Tu.A05
            r0 = 36320829025297287(0x81099a00002387, double:3.032776755612912E-306)
            boolean r0 = X.182.A06(r2, r9, r0)
            if (r0 == 0) goto L_0x0057
            r8 = 1
        L_0x0057:
            boolean r7 = X.C309456Yi.A02(r11)
            r6 = 0
            if (r7 == 0) goto L_0x0065
            boolean r0 = X.C309456Yi.A03(r11)
            r5 = 1
            if (r0 != 0) goto L_0x0066
        L_0x0065:
            r5 = 0
        L_0x0066:
            boolean r0 = A0l(r11)
            if (r0 == 0) goto L_0x00b3
            com.instagram.model.reels.Reel r4 = r11.A0H
            boolean r0 = A0V(r4)
            if (r0 == 0) goto L_0x0081
            X.0Tu r2 = X.0Tu.A06
            r0 = 36317818255578709(0x8106dd00241655, double:3.030872732719487E-306)
            boolean r0 = X.182.A06(r2, r9, r0)
            if (r0 != 0) goto L_0x0094
        L_0x0081:
            boolean r0 = A0W(r4)
            if (r0 == 0) goto L_0x00b3
            X.0Tu r2 = X.0Tu.A06
            r0 = 36317818255644246(0x8106dd00251656, double:3.030872732760933E-306)
            boolean r0 = X.182.A06(r2, r9, r0)
            if (r0 == 0) goto L_0x00b3
        L_0x0094:
            r2 = 1
        L_0x0095:
            java.util.List r0 = X.C250973mM.A00(r9, r11)
            int r0 = r0.size()
            if (r0 != r3) goto L_0x00a2
            r1 = 1
            if (r7 == 0) goto L_0x00a3
        L_0x00a2:
            r1 = 0
        L_0x00a3:
            boolean r0 = A0k(r10, r11, r12, r13)
            if (r0 == 0) goto L_0x00b2
            if (r8 != 0) goto L_0x00b1
            if (r5 != 0) goto L_0x00b1
            if (r1 != 0) goto L_0x00b1
            if (r2 == 0) goto L_0x00b2
        L_0x00b1:
            r6 = 1
        L_0x00b2:
            return r6
        L_0x00b3:
            r2 = 0
            goto L_0x0095
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C297785sK.A0M(com.instagram.common.session.UserSession, X.3uh, X.3mM, X.3BQ, X.6Yf):boolean");
    }

    public static final boolean A0U(Reel reel) {
        Integer CAm;
        0qQ.A0B(reel, 0);
        1Ns r0 = reel.A0W;
        if (r0 == null) {
            CAm = null;
        } else {
            CAm = r0.CAm();
        }
        if (CAm == AnonymousClass05K.A04) {
            return true;
        }
        return false;
    }

    public static final boolean A0c(C255773uh r2) {
        0qQ.A0B(r2, 0);
        1Xj r22 = r2.A0b;
        if (r22 == null || !r22.A65() || r22.A5H()) {
            return false;
        }
        return true;
    }

    public static final boolean A0d(C255773uh r2) {
        0qQ.A0B(r2, 0);
        1Xj r22 = r2.A0b;
        if (r22 == null || !r22.A66() || r22.A5H()) {
            return false;
        }
        return true;
    }

    /* JADX WARNING: Removed duplicated region for block: B:13:0x0028  */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static final boolean A0e(X.C255773uh r6) {
        /*
            r0 = 0
            if (r6 == 0) goto L_0x003d
            java.util.List r2 = r6.A0b()
        L_0x0007:
            X.3WT r1 = X.AnonymousClass3WT.MULTI_PRODUCT
            X.3ui r5 = X.C289745e8.A00(r1, r2)
            r4 = 0
            if (r6 == 0) goto L_0x0038
            X.1Xj r2 = r6.A0b
            if (r2 == 0) goto L_0x0038
            r1 = 1
            java.util.ArrayList r1 = r2.A3K(r1)
            if (r1 == 0) goto L_0x0038
            int r3 = r1.size()
        L_0x001f:
            X.1Xj r1 = r6.A0b
        L_0x0021:
            boolean r2 = A0Q(r1)
            r1 = 1
            if (r2 != 0) goto L_0x0032
            if (r6 == 0) goto L_0x002c
            X.1Xj r0 = r6.A0b
        L_0x002c:
            boolean r0 = A0S(r0)
            if (r0 == 0) goto L_0x0037
        L_0x0032:
            if (r5 == 0) goto L_0x0037
            if (r3 != r1) goto L_0x0037
            r4 = 1
        L_0x0037:
            return r4
        L_0x0038:
            r3 = 0
            if (r6 != 0) goto L_0x001f
            r1 = r0
            goto L_0x0021
        L_0x003d:
            r2 = r0
            goto L_0x0007
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C297785sK.A0e(X.3uh):boolean");
    }

    public static final boolean A0i(C255773uh r7, C250973mM r8) {
        0qQ.A0B(r7, 0);
        0qQ.A0B(r8, 1);
        1Xj r2 = r7.A0b;
        if (r2 != null && r7.A1m()) {
            double A0k = r2.A0k();
            if (C309456Yi.A02(r8)) {
                if (C309456Yi.A03(r8)) {
                    List list = r8.A0H.A17;
                    if (list != null) {
                        Number number = (Number) list.get(list.size() - 1);
                        0qQ.A0A(number);
                        A0k -= number.doubleValue();
                    } else {
                        throw new IllegalStateException("Required value was null.");
                    }
                }
            }
            if (A0k >= A00(r2)) {
                return true;
            }
            return false;
        }
        return false;
    }

    public static final boolean A0l(C250973mM r2) {
        Integer num;
        0qQ.A0B(r2, 0);
        1Ns r0 = r2.A0H.A0W;
        if (r0 != null) {
            num = r0.CAm();
        } else {
            num = null;
        }
        if (num == AnonymousClass05K.A04) {
            return true;
        }
        return false;
    }

    public static final double A00(1Xj r3) {
        Integer Aze = r3.A0C.Aze();
        if (Aze != null) {
            return 16.0d + ((double) Aze.intValue());
        }
        return 16.0d;
    }

    public static final Layout.Alignment A05(C255773uh r1) {
        AnonymousClass560 C5H;
        IGStoryTextAlignmentTypeEnum C4r;
        1Xj r0 = r1.A0b;
        if (!(r0 == null || (C5H = r0.A0C.C5H()) == null || (C4r = C5H.C4r()) == null)) {
            int ordinal = C4r.ordinal();
            if (ordinal == 3) {
                return Layout.Alignment.ALIGN_OPPOSITE;
            }
            if (ordinal == 2) {
                return Layout.Alignment.ALIGN_CENTER;
            }
        }
        return Layout.Alignment.ALIGN_NORMAL;
    }

    public static final void A08(View view, C255773uh r4) {
        1Xj r0 = r4.A0b;
        r0.getClass();
        String A2u = r0.A2u();
        String A2t = r0.A2t();
        if (A2u != null && A2u.length() != 0 && A2t != null && A2t.length() != 0) {
            RectF rectF = 0nA.A01;
            view.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM, new int[]{Color.parseColor(A2u), Color.parseColor(A2t)}));
        }
    }

    public static final boolean A0E(UserSession userSession, C255773uh r4) {
        MoreInfoType moreInfoType;
        AnonymousClass41Z BUC;
        C270854hQ B1Z;
        1Xj r0 = r4.A0b;
        if (r0 == null || (BUC = r0.A0C.BUC()) == null || (B1Z = BUC.B1Z()) == null) {
            moreInfoType = null;
        } else {
            moreInfoType = B1Z.BUD();
        }
        if (!A09(moreInfoType) || !182.A06(0Tu.A05, userSession, 36321683723789965L)) {
            return false;
        }
        return true;
    }

    public static final boolean A0G(UserSession userSession, C255773uh r4) {
        AnonymousClass41Z BUC;
        1Xj r0 = r4.A0b;
        if (r0 == null || (BUC = r0.A0C.BUC()) == null || BUC.B7C() == null || !182.A06(0Tu.A05, userSession, 2342163894073828269L)) {
            return false;
        }
        return true;
    }

    public static final boolean A0K(UserSession userSession, C255773uh r6, C250973mM r7) {
        CarouselRenderingType carouselRenderingType;
        List list;
        Reel reel = r7.A0H;
        if (!reel.A17(userSession) || r7.A07 || r7.A01 != reel.A00 || C250973mM.A00(userSession, r7).size() <= reel.A00 + 1) {
            AnonymousClass3HX r3 = r6.A08;
            CarouselRenderingType carouselRenderingType2 = null;
            if (r3 != null) {
                carouselRenderingType = r3.A01;
            } else {
                carouselRenderingType = null;
            }
            if (carouselRenderingType != CarouselRenderingType.OPT_IN) {
                if (r3 != null) {
                    carouselRenderingType2 = r3.A01;
                }
                if (carouselRenderingType2 != CarouselRenderingType.DPA) {
                    return false;
                }
            }
            if (r3 == null || (list = r3.A1j) == null || list.size() <= 1) {
                return false;
            }
        }
        return true;
    }

    public static final boolean A0P(1Xj r2) {
        MoreInfoProductTagType moreInfoProductTagType;
        AnonymousClass41Z BUC;
        C270854hQ At8;
        if (r2 == null || (BUC = r2.A0C.BUC()) == null || (At8 = BUC.At8()) == null) {
            moreInfoProductTagType = null;
        } else {
            moreInfoProductTagType = At8.BgU();
        }
        if (moreInfoProductTagType == MoreInfoProductTagType.PRODUCT_NAME_CTA) {
            return true;
        }
        return false;
    }

    public static final boolean A0Q(1Xj r2) {
        MoreInfoProductTagType moreInfoProductTagType;
        AnonymousClass41Z BUC;
        C270854hQ At8;
        if (r2 == null || (BUC = r2.A0C.BUC()) == null || (At8 = BUC.At8()) == null) {
            moreInfoProductTagType = null;
        } else {
            moreInfoProductTagType = At8.BgU();
        }
        if (moreInfoProductTagType == MoreInfoProductTagType.PRODUCT_NAME_WITH_POST_TAP_CTA) {
            return true;
        }
        return false;
    }

    public static final boolean A0R(1Xj r2) {
        MoreInfoProductTagType moreInfoProductTagType;
        AnonymousClass41Z BUC;
        C270854hQ B7C;
        if (r2 == null || (BUC = r2.A0C.BUC()) == null || (B7C = BUC.B7C()) == null) {
            moreInfoProductTagType = null;
        } else {
            moreInfoProductTagType = B7C.BgU();
        }
        if (moreInfoProductTagType == MoreInfoProductTagType.PILL) {
            return true;
        }
        return false;
    }

    public static final boolean A0S(1Xj r2) {
        MoreInfoProductTagType moreInfoProductTagType;
        AnonymousClass41Z BUC;
        C270854hQ B7C;
        if (r2 == null || (BUC = r2.A0C.BUC()) == null || (B7C = BUC.B7C()) == null) {
            moreInfoProductTagType = null;
        } else {
            moreInfoProductTagType = B7C.BgU();
        }
        if (moreInfoProductTagType == MoreInfoProductTagType.THUMBNAIL) {
            return true;
        }
        return false;
    }

    public static final boolean A0T(1Xj r2) {
        MoreInfoProductTagType moreInfoProductTagType;
        AnonymousClass41Z BUC;
        C270854hQ At8;
        if (r2 == null || (BUC = r2.A0C.BUC()) == null || (At8 = BUC.At8()) == null) {
            moreInfoProductTagType = null;
        } else {
            moreInfoProductTagType = At8.BgU();
        }
        if (moreInfoProductTagType == MoreInfoProductTagType.WIDE_CTA) {
            return true;
        }
        return false;
    }

    public static final boolean A0V(Reel reel) {
        Integer num;
        IntentAwareAdsInfo intentAwareAdsInfo = reel.A0B;
        if (intentAwareAdsInfo == null || (num = intentAwareAdsInfo.A02) == null || num.intValue() != 13) {
            return false;
        }
        return true;
    }

    public static final boolean A0W(Reel reel) {
        Integer num;
        IntentAwareAdsInfo intentAwareAdsInfo = reel.A0B;
        if (intentAwareAdsInfo == null || (num = intentAwareAdsInfo.A02) == null || num.intValue() != 12) {
            return false;
        }
        return true;
    }

    public static final boolean A0X(C255773uh r1) {
        String str;
        C250513lZ injected;
        C257973yG C0P;
        1Xj r0 = r1.A0b;
        if (r0 == null || (injected = r0.A0C.getInjected()) == null || (C0P = injected.C0P()) == null) {
            str = null;
        } else {
            str = C0P.AcZ();
        }
        if (0qQ.A0K(str, "RATIO_2X3") || 0qQ.A0K(str, "RATIO_3X4") || 0qQ.A0K(str, "RATIO_4X5")) {
            return true;
        }
        return false;
    }

    public static final boolean A0a(C255773uh r1) {
        C250513lZ injected;
        C257973yG C0P;
        1Xj r0 = r1.A0b;
        if (r0 == null || (injected = r0.A0C.getInjected()) == null || (C0P = injected.C0P()) == null) {
            return false;
        }
        return 0qQ.A0K(C0P.AcF(), true);
    }

    public static final boolean A0o(C250973mM r1, C309426Yf r2) {
        if (r2.A1A || r1.A07) {
            return true;
        }
        return false;
    }

    public static final float A01(C255773uh r1, C250973mM r2, C309426Yf r3) {
        if (!A0i(r1, r2) || A0o(r2, r3)) {
            return r3.A0A;
        }
        1Xj r0 = r1.A0b;
        r0.getClass();
        return ((float) A00(r0)) * 1000.0f;
    }

    public static final int A03(List list) {
        int i = 0;
        for (Object obj : list) {
            if (obj == AutoGeneratedCardType.ORIGINAL) {
                i++;
            }
        }
        return i;
    }

    public static final boolean A0A(UserSession userSession, Reel reel) {
        if (A0V(reel) && 182.A06(0Tu.A06, userSession, 36317818254857802L)) {
            return true;
        }
        if (A0W(reel) && 182.A06(0Tu.A06, userSession, 36317818255382098L)) {
            return true;
        }
        if (!A0V(reel) || !182.A06(0Tu.A06, userSession, 36317818255906394L)) {
            return false;
        }
        return true;
    }

    public static final boolean A0C(UserSession userSession, C255773uh r5) {
        if (!r5.CcK() || r5.A1O() || r5.A1f()) {
            return false;
        }
        String A0Y = r5.A0Y(userSession);
        if ((A0Y == null || A0Y.length() == 0) && 182.A06(0Tu.A05, userSession, 36317813958252086L)) {
            return true;
        }
        return false;
    }

    public static final boolean A0D(UserSession userSession, C255773uh r2) {
        if (r2.A1f() || r2.A1Z() || r2.A1O() || A0B(userSession, r2)) {
            return true;
        }
        return false;
    }

    public static final boolean A0H(UserSession userSession, C255773uh r3, C250973mM r4) {
        String str;
        IgShowreelComposition BwC;
        if (!A0l(r4)) {
            r3 = (C255773uh) C250973mM.A00(userSession, r4).get(0);
        }
        1Xj r0 = r3.A0b;
        if (r0 == null || (BwC = r0.A0C.BwC()) == null) {
            str = null;
        } else {
            str = BwC.C4b();
        }
        return 0qQ.A0K(str, "bloks_dpa_showcase_six_tiles");
    }

    public static final boolean A0N(UserSession userSession, C255773uh r2, AnonymousClass3BQ r3) {
        if (!r2.CWu() || !r2.CcK() || !r3.A01() || !A0B(userSession, r2)) {
            return false;
        }
        return true;
    }

    public static final boolean A0O(1Xj r2) {
        MoreInfoProductTagType moreInfoProductTagType;
        AnonymousClass41Z BUC;
        C270854hQ B7C;
        if (!A0R(r2) && !A0S(r2)) {
            if (r2 == null || (BUC = r2.A0C.BUC()) == null || (B7C = BUC.B7C()) == null) {
                moreInfoProductTagType = null;
            } else {
                moreInfoProductTagType = B7C.BgU();
            }
            if (moreInfoProductTagType == MoreInfoProductTagType.LINK_STICKER_ONLY || A0T(r2) || A0P(r2) || A0Q(r2)) {
                return true;
            }
            return false;
        }
        return true;
    }

    public static final boolean A0Y(C255773uh r3) {
        1Xj r0;
        DUI BKT;
        if (!A0Z(r3) || (r0 = r3.A0b) == null || (BKT = r0.A0C.BKT()) == null || BKT.CGY() == null || BKT.BCu() == null || BKT.Byw() == null || BKT.Byy() == null) {
            return false;
        }
        return true;
    }

    public static final boolean A0Z(C255773uh r2) {
        if ((!r2.CcK() || r2.A1A() || r2.A00() < 0.79f || r2.A00() > 1.93f) && !A0X(r2)) {
            return false;
        }
        return true;
    }

    public static final boolean A0b(C255773uh r6) {
        int i;
        ArrayList A3K;
        C255783ui A002 = C289745e8.A00(AnonymousClass3WT.MULTI_PRODUCT, r6.A0b());
        1Xj r3 = r6.A0b;
        if (r3 == null || (A3K = r3.A3K(true)) == null) {
            i = 0;
        } else {
            i = A3K.size();
        }
        if ((A0Q(r3) || A0S(r3)) && A002 != null && i > 1) {
            return true;
        }
        return false;
    }

    public static final boolean A0f(C255773uh r2) {
        String str;
        C269824fk r1;
        AnonymousClass6LR A0G = r2.A0G();
        if (A0G == null || (str = A0G.A06) == null || str.length() == 0 || (r1 = A0G.A00) == null || r1.CGb() == null || r1.BCy() == null || r1.Byx() == null || r1.Byz() == null) {
            return false;
        }
        return true;
    }

    public static final boolean A0g(C255773uh r3) {
        JSN A0E;
        C270164gI A0D = r3.A0D();
        if ((A0D == null || !0qQ.A0K(A0D.Bui(), true)) && ((A0E = r3.A0E()) == null || !0qQ.A0K(A0E.Bui(), true))) {
            return false;
        }
        return true;
    }

    public static final boolean A0h(C255773uh r2) {
        String str;
        A88 A0I = r2.A0I();
        if (A0I == null || (str = A0I.A0B) == null || str.length() == 0 || A0I.A04 == null || A0I.A05 == null || A0I.A0A == null || A0I.A08 == null || A0I.A09 == null) {
            return false;
        }
        return true;
    }

    public static final boolean A0j(C255773uh r3, C250973mM r4) {
        String str;
        List list;
        AnonymousClass6LR A0G = r3.A0G();
        if (A0G != null) {
            str = A0G.A06;
        } else {
            str = null;
        }
        if (str == null || str.length() == 0 || (((list = r4.A0H.A0w) != null && list.contains(AutoGeneratedCardType.CAPTION)) || A0X(r3))) {
            return false;
        }
        return true;
    }

    public static final boolean A0k(C255773uh r1, C250973mM r2, AnonymousClass3BQ r3, C309426Yf r4) {
        if (r1.A0F() == null || !r2.A0N || ((A0i(r1, r2) && A0o(r2, r4)) || !r3.A01())) {
            return false;
        }
        return true;
    }

    public static final boolean A0m(C250973mM r2) {
        if (!A0l(r2) || 00k.A0u(A00, r2.A05())) {
            return false;
        }
        return true;
    }

    public static final boolean A0n(C250973mM r2) {
        if (!A0l(r2) || !00k.A0u(A00, r2.A05())) {
            return false;
        }
        return true;
    }
}
