package X;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/* renamed from: X.6aL  reason: invalid class name and case insensitive filesystem */
public final class C310046aL {
    public final Map A00 = new HashMap();
    public final Set A01 = new HashSet();
    public final Set A02 = new HashSet();
    public final Set A03 = new HashSet();
    public final Set A04 = new HashSet();
    public final Set A05 = new HashSet();
    public final Set A06 = new HashSet();
    public final Set A07 = new HashSet();
    public final Set A08 = new HashSet();
    public final Set A09 = new HashSet();

    public final boolean A01(C255773uh r7, C309426Yf r8) {
        C41886B5e b5e = (C41886B5e) this.A00.get(r7.A0k);
        if (b5e == null) {
            return false;
        }
        double d = ((double) (r8.A0A * r8.A0B)) / 1000.0d;
        if (r7.CcK()) {
            b5e.A01 += d;
            b5e.A00 += r8.A03;
        } else {
            b5e.A03 += d;
            b5e.A02 += r8.A03;
        }
        b5e.A05 = r8.A0v;
        b5e.A06 = r8.A19;
        Integer num = r8.A0W;
        0qQ.A07(num);
        b5e.A04 = num;
        return true;
    }

    /* JADX WARNING: Code restructure failed: missing block: B:10:0x003b, code lost:
        if (com.instagram.model.reels.sponsored.AutoGeneratedCardType.ORIGINAL == r0.A0C.Ae3()) goto L_0x003d;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final boolean A00(X.C255773uh r5, X.C250973mM r6) {
        /*
            r4 = this;
            com.instagram.model.reels.Reel r0 = r6.A0H
            java.lang.String r1 = r0.getId()
            X.0qQ.A07(r1)
            java.util.Map r0 = r4.A00
            java.lang.Object r2 = r0.get(r1)
            X.B5e r2 = (X.C41886B5e) r2
            if (r2 != 0) goto L_0x0072
            X.B5e r2 = new X.B5e
            r2.<init>()
            r0.put(r1, r2)
            r3 = 1
        L_0x001c:
            boolean r0 = r5.A1Y()
            if (r0 != 0) goto L_0x004d
            boolean r0 = r5.CcK()
            if (r0 == 0) goto L_0x0057
            X.3mL r1 = r5.A0e
            X.3mL r0 = X.C250963mL.MEDIA
            if (r1 != r0) goto L_0x003d
            X.1Xj r0 = r5.A0b
            r0.getClass()
            com.instagram.model.reels.sponsored.AutoGeneratedCardType r1 = com.instagram.model.reels.sponsored.AutoGeneratedCardType.ORIGINAL
            X.1Xy r0 = r0.A0C
            com.instagram.model.reels.sponsored.AutoGeneratedCardType r0 = r0.Ae3()
            if (r1 != r0) goto L_0x004d
        L_0x003d:
            boolean r0 = r5.A1m()
            if (r0 == 0) goto L_0x004e
            java.util.Set r1 = r2.A08
        L_0x0045:
            java.lang.String r0 = r5.A0j
            X.0qQ.A07(r0)
            r1.add(r0)
        L_0x004d:
            return r3
        L_0x004e:
            boolean r0 = r5.A1b()
            if (r0 == 0) goto L_0x004d
            java.util.Set r1 = r2.A07
            goto L_0x0045
        L_0x0057:
            boolean r0 = r5.A17()
            if (r0 == 0) goto L_0x0060
            java.util.Set r1 = r2.A0C
            goto L_0x0045
        L_0x0060:
            boolean r0 = r5.A1m()
            if (r0 == 0) goto L_0x0069
            java.util.Set r1 = r2.A0B
            goto L_0x0045
        L_0x0069:
            boolean r0 = r5.A1b()
            if (r0 == 0) goto L_0x004d
            java.util.Set r1 = r2.A0A
            goto L_0x0045
        L_0x0072:
            r3 = 0
            goto L_0x001c
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C310046aL.A00(X.3uh, X.3mM):boolean");
    }
}
