package X;

import com.instagram.common.session.UserSession;

/* renamed from: X.6c2  reason: invalid class name and case insensitive filesystem */
public final class C311046c2 implements C310726bW {
    public final UserSession A00;
    public final C310666bQ A01;
    public final C311056c3 A02;
    public final C311086c7 A03;

    public final void ABc(C2354830a r1, C2354830a r2, C255773uh r3, C250973mM r4) {
    }

    public final void ABe(C2354830a r1, C2354830a r2, C255773uh r3, C250973mM r4) {
    }

    /* JADX WARNING: Code restructure failed: missing block: B:9:0x003e, code lost:
        if (r9.mBrandResearchSurvey == null) goto L_0x0045;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final void ABh(android.view.View r6, X.C2354830a r7, X.C2354830a r8, X.C255773uh r9, X.C250973mM r10) {
        /*
            r5 = this;
            r0 = 0
            X.0qQ.A0B(r6, r0)
            r0 = 1
            X.0qQ.A0B(r9, r0)
            r0 = 3
            X.0qQ.A0B(r7, r0)
            X.6bQ r0 = r5.A01
            X.4DU r0 = r0.A02
            boolean r0 = X.AnonymousClass3WX.A02(r9, r0)
            if (r0 == 0) goto L_0x005d
            com.instagram.common.session.UserSession r3 = r5.A00
            X.0Tu r2 = X.0Tu.A05
            r0 = 36310813161554229(0x81007e00000135, double:3.026442683051156E-306)
            boolean r0 = X.182.A06(r2, r3, r0)
            if (r0 == 0) goto L_0x0048
            X.6c3 r4 = r5.A02
            X.3mL r1 = r9.A0e
            X.3mL r0 = X.C250963mL.MEDIA
            if (r1 != r0) goto L_0x0040
            X.1Xj r0 = r9.A0b
            r0.getClass()
            com.instagram.model.reels.sponsored.AutoGeneratedCardType r1 = com.instagram.model.reels.sponsored.AutoGeneratedCardType.ORIGINAL
            X.1Xy r0 = r0.A0C
            com.instagram.model.reels.sponsored.AutoGeneratedCardType r0 = r0.Ae3()
            if (r1 == r0) goto L_0x0040
            X.3IB r0 = r9.mBrandResearchSurvey
            if (r0 == 0) goto L_0x0045
        L_0x0040:
            java.util.Map r0 = r4.A04
            r0.put(r9, r6)
        L_0x0045:
            r7.A00(r4)
        L_0x0048:
            r0 = 36315155373624354(0x81047100020c22, double:3.029188715448988E-306)
            boolean r0 = X.182.A06(r2, r3, r0)
            if (r0 == 0) goto L_0x005d
            X.6c7 r1 = r5.A03
            java.util.Map r0 = r1.A00
            r0.put(r9, r6)
            r7.A00(r1)
        L_0x005d:
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C311046c2.ABh(android.view.View, X.30a, X.30a, X.3uh, X.3mM):void");
    }

    public C311046c2(C310666bQ r4) {
        this.A01 = r4;
        UserSession userSession = r4.A01;
        this.A00 = userSession;
        AnonymousClass4DU r1 = r4.A02;
        this.A02 = new C311056c3(userSession, r1);
        this.A03 = new C311086c7(userSession, r1);
    }
}
