package X;

/* renamed from: X.6jD  reason: invalid class name and case insensitive filesystem */
public enum C315016jD {
    ADD_MENTIONS,
    PRODUCT_STICKER,
    CLOSE_FRIENDS_BADGE,
    EXCLUSIVE_STORY_BADGE,
    COUNTDOWN,
    POLL,
    SLIDER,
    SLIDER_VOTERS_RESULTS,
    QUESTION_VIEWER,
    QUESTION_VOTERS_RESULTS,
    QUIZ_VIEWER,
    QUIZ_ANSWERS_RESULTS,
    STORY_TO_REEL,
    CREATE_FROM_STORY,
    HIGHLIGHTS,
    ONE_TAP_FB_SHARE,
    PROMOTE,
    PROMOTE_STORY_WITH_ELIGIBLE_STICKER,
    MULTI_AUTHOR_STORY_VIEW_COUNT,
    SAVED_EFFECTS_NUX,
    BLOKS_TAPPABLE,
    SHARE_PROFESSIONAL_PROFILE,
    STORY_LIKES_FACEPILE_NUX,
    AVATAR_STICKER,
    AD_EXPAND_STORY_BUTTON,
    TAPPABLE_REACTION_STICKER,
    REACTION_STICKER_FACEPILE_NUX,
    SHARE_BUTTON_LOCATION_NUX,
    STORIES_TEMPLATES,
    BOOSTED_STORY_MENTIONS_SETTINGS,
    STORY_COMMENTS,
    BOOSTED_RESHARED_MEDIA_SETTINGS,
    ACHIEVEMENT_STICKER_NUX;

    /* access modifiers changed from: public */
    static {
        C315016jD[] r1;
        A00 = 0oU.A00(r1);
    }
}
