package X;

import android.view.View;
import android.view.ViewStub;
import android.widget.TextView;
import com.instagram.android.R;
import com.instagram.reels.viewer.attribution.CyclingFrameLayout;

/* renamed from: X.6lO  reason: invalid class name and case insensitive filesystem */
public final class C316276lO {
    public TextView A00;
    public TextView A01;
    public TextView A02;
    public TextView A03;
    public TextView A04;
    public TextView A05;
    public final View A06;
    public final C2806852z A07;
    public final C316296lQ A08;
    public final C316446lf A09;
    public final C316666m1 A0A;
    public final C316306lR A0B;
    public final C316676m2 A0C;
    public final C316686m3 A0D;
    public final C316346lV A0E;
    public final C316556lq A0F;
    public final C316646lz A0G;
    public final CyclingFrameLayout A0H;
    public final C316516lm A0I;
    public final C316576ls A0J;
    public final C316656m0 A0K;
    public final C316406lb A0L;
    public final C316456lg A0M;
    public final C316466lh A0N;
    public final C316416lc A0O;
    public final C316426ld A0P;
    public final C316436le A0Q;
    public final C316606lv A0R;
    public final C316366lX A0S;
    public final C316596lu A0T;
    public final C316506ll A0U;
    public final C316536lo A0V;
    public final C316546lp A0W;
    public final C316616lw A0X;
    public final C316286lP A0Y;
    public final C316496lk A0Z;
    public final C316696m4 A0a;
    public final C316526ln A0b;
    public final C316486lj A0c;
    public final C316476li A0d;
    public final C316626lx A0e;
    public final C316586lt A0f;
    public final C316386lZ A0g;
    public final C316636ly A0h;
    public final C316566lr A0i;
    public final C316376lY A0j;
    public final C316356lW A0k;
    public final C316336lU A0l;
    public final C316396la A0m;
    public final C316326lT A0n;
    public final C316316lS A0o;
    public final C316316lS A0p;

    public C316276lO(View view) {
        2eS.A04(view, AnonymousClass05K.A01);
        this.A06 = view.findViewById(R.id.reel_viewer_header);
        this.A0H = (CyclingFrameLayout) view.findViewById(R.id.reel_viewer_attribution_frame_layout);
        View requireViewById = view.requireViewById(R.id.multiple_lists_attribution_stub);
        0qQ.A07(requireViewById);
        this.A0Y = new C316286lP((ViewStub) requireViewById);
        View requireViewById2 = view.requireViewById(R.id.reel_app_attribution_subtitle_stub);
        0qQ.A07(requireViewById2);
        this.A08 = new C316296lQ((ViewStub) requireViewById2);
        View requireViewById3 = view.requireViewById(R.id.reel_bloks_attribution_subtitle_stub);
        0qQ.A07(requireViewById3);
        this.A0B = new C316306lR((ViewStub) requireViewById3);
        View requireViewById4 = view.requireViewById(R.id.reel_effect_attribution_subtitle_stub);
        0qQ.A07(requireViewById4);
        this.A0o = new C316316lS((ViewStub) requireViewById4);
        View requireViewById5 = view.requireViewById(R.id.reel_format_attribution_subtitle_stub);
        0qQ.A07(requireViewById5);
        this.A0p = new C316316lS((ViewStub) requireViewById5);
        View requireViewById6 = view.requireViewById(R.id.reel_camera_tool_attribution_subtitle_stub);
        0qQ.A07(requireViewById6);
        this.A0n = new C316326lT((ViewStub) requireViewById6);
        View requireViewById7 = view.requireViewById(R.id.reel_music_attribution_subtitle_stub);
        0qQ.A07(requireViewById7);
        this.A07 = new C2806852z((ViewStub) requireViewById7);
        View requireViewById8 = view.requireViewById(R.id.reel_video_call_attribution_subtitle_stub);
        0qQ.A07(requireViewById8);
        this.A0l = new C316336lU((ViewStub) requireViewById8);
        View requireViewById9 = view.requireViewById(R.id.reel_canvas_attribution_subtitle_stub);
        0qQ.A07(requireViewById9);
        this.A0E = new C316346lV((ViewStub) requireViewById9);
        View requireViewById10 = view.requireViewById(R.id.reel_unlockable_sticker_attribution_subtitle_stub);
        0qQ.A07(requireViewById10);
        this.A0k = new C316356lW((ViewStub) requireViewById10);
        View requireViewById11 = view.requireViewById(R.id.reel_internal_attribution_subtitle_stub);
        0qQ.A07(requireViewById11);
        this.A0S = new C316366lX((ViewStub) requireViewById11);
        View requireViewById12 = view.requireViewById(R.id.reel_translation_attribution_subtitle_stub);
        0qQ.A07(requireViewById12);
        this.A0j = new C316376lY((ViewStub) requireViewById12);
        View requireViewById13 = view.requireViewById(R.id.story_template_attribution_stub);
        0qQ.A07(requireViewById13);
        this.A0g = new C316386lZ((ViewStub) requireViewById13);
        this.A0m = new C316396la((ViewStub) view.requireViewById(R.id.reel_wearable_attribution_subtitle_stub));
        View requireViewById14 = view.requireViewById(R.id.reel_gallery_grid_format_attribution_subtitle_stub);
        0qQ.A07(requireViewById14);
        this.A0L = new C316406lb((ViewStub) requireViewById14);
        View requireViewById15 = view.requireViewById(R.id.reel_group_profile_attribution_subtitle_stub);
        0qQ.A07(requireViewById15);
        this.A0O = new C316416lc((ViewStub) requireViewById15);
        View requireViewById16 = view.requireViewById(R.id.reel_highlights_attribution_subtitle_stub);
        0qQ.A07(requireViewById16);
        this.A0P = new C316426ld((ViewStub) requireViewById16);
        View requireViewById17 = view.requireViewById(R.id.reel_highlights_rewind_attribution_subtitle_stub);
        0qQ.A07(requireViewById17);
        this.A0Q = new C316436le((ViewStub) requireViewById17);
        View requireViewById18 = view.requireViewById(R.id.reel_avatar_sticker_attribution_subtitle_stub);
        0qQ.A07(requireViewById18);
        this.A09 = new C316446lf((ViewStub) requireViewById18);
        View requireViewById19 = view.requireViewById(R.id.reel_gen_ai_detection_attribution_subtitle_stub);
        0qQ.A07(requireViewById19);
        this.A0M = new C316456lg((ViewStub) requireViewById19);
        View requireViewById20 = view.requireViewById(R.id.reel_gen_ai_sticker_attribution_subtitle_stub);
        0qQ.A07(requireViewById20);
        this.A0N = new C316466lh((ViewStub) requireViewById20);
        View requireViewById21 = view.requireViewById(R.id.reel_share_to_friends_story_attribution_subtitle_stub);
        0qQ.A07(requireViewById21);
        this.A0d = new C316476li((ViewStub) requireViewById21);
        View requireViewById22 = view.requireViewById(R.id.reel_secret_sticker_attribution_subtitle_stub);
        0qQ.A07(requireViewById22);
        this.A0c = new C316486lj((ViewStub) requireViewById22);
        View requireViewById23 = view.requireViewById(R.id.reel_polaroid_sticker_attribution_subtitle_stub);
        0qQ.A07(requireViewById23);
        this.A0Z = new C316496lk((ViewStub) requireViewById23);
        this.A0U = new C316506ll(new C71662eb((ViewStub) view.requireViewById(R.id.reel_memories_attribution_subtitle_stub)));
        this.A0I = new C316516lm(new C71662eb((ViewStub) view.requireViewById(R.id.reel_first_take_attribution_subtitle_stub)));
        this.A0b = new C316526ln(new C71662eb((ViewStub) view.requireViewById(R.id.reel_roll_call_timebox_attribution_subtitle_stub)));
        View requireViewById24 = view.requireViewById(R.id.reel_mention_reshare_attribution_stub);
        0qQ.A07(requireViewById24);
        this.A0V = new C316536lo((ViewStub) requireViewById24);
        View requireViewById25 = view.requireViewById(R.id.reel_message_share_attribution_stub);
        0qQ.A07(requireViewById25);
        this.A0W = new C316546lp((ViewStub) requireViewById25);
        View requireViewById26 = view.requireViewById(R.id.reel_channel_challenge_attribution_stub);
        0qQ.A07(requireViewById26);
        this.A0F = new C316556lq((ViewStub) requireViewById26);
        View requireViewById27 = view.requireViewById(R.id.superlative_attribution_subtitle_stub);
        0qQ.A07(requireViewById27);
        this.A0i = new C316566lr((ViewStub) requireViewById27);
        View requireViewById28 = view.requireViewById(R.id.from_superlative_view_yours_attribution_subtitle_stub);
        0qQ.A07(requireViewById28);
        this.A0J = new C316576ls((ViewStub) requireViewById28);
        View requireViewById29 = view.requireViewById(R.id.story_snapshot_attribution_subtitle_stub);
        0qQ.A07(requireViewById29);
        this.A0f = new C316586lt((ViewStub) requireViewById29);
        View requireViewById30 = view.requireViewById(R.id.magic_mod_attribution_stub);
        0qQ.A07(requireViewById30);
        this.A0T = new C316596lu((ViewStub) requireViewById30);
        View requireViewById31 = view.requireViewById(R.id.imagine_templates_attribution_stub);
        0qQ.A07(requireViewById31);
        this.A0R = new C316606lv((ViewStub) requireViewById31);
        View requireViewById32 = view.requireViewById(R.id.meta_ai_attribution_stub);
        0qQ.A07(requireViewById32);
        this.A0X = new C316616lw((ViewStub) requireViewById32);
        View requireViewById33 = view.requireViewById(R.id.stories_teaser_attribution_stub);
        0qQ.A07(requireViewById33);
        this.A0e = new C316626lx((ViewStub) requireViewById33);
        View requireViewById34 = view.requireViewById(R.id.suggested_reel_attribution_stub);
        0qQ.A07(requireViewById34);
        this.A0h = new C316636ly((ViewStub) requireViewById34);
        View requireViewById35 = view.requireViewById(R.id.stories_cutout_anything_attribution_stub);
        0qQ.A07(requireViewById35);
        this.A0G = new C316646lz((ViewStub) requireViewById35);
        View requireViewById36 = view.requireViewById(R.id.full_screen_reel_reshare_attribution_stub);
        0qQ.A07(requireViewById36);
        this.A0K = new C316656m0((ViewStub) requireViewById36);
        View requireViewById37 = view.requireViewById(R.id.barcelona_attribution_stub);
        0qQ.A07(requireViewById37);
        this.A0A = new C316666m1((ViewStub) requireViewById37);
        View requireViewById38 = view.requireViewById(R.id.campfire_attribution_stub);
        0qQ.A07(requireViewById38);
        this.A0C = new C316676m2((ViewStub) requireViewById38);
        View requireViewById39 = view.requireViewById(R.id.campfire_self_view_attribution_stub);
        0qQ.A07(requireViewById39);
        this.A0D = new C316686m3((ViewStub) requireViewById39);
        View requireViewById40 = view.requireViewById(R.id.quick_snap_recap_attribution_stub);
        0qQ.A07(requireViewById40);
        this.A0a = new C316696m4((ViewStub) requireViewById40);
    }
}
