package X;

/* renamed from: X.6oG  reason: invalid class name and case insensitive filesystem */
public enum C318046oG {
    ACHIEVEMENTS("achievements_sticker"),
    AI_STICKER("ai_sticker"),
    AI_STICKER_SEARCH("ai_sticker_search"),
    ANONYMOUS_QUESTION("anonymous_question_sticker"),
    ANTI_BULLY_ENG_ONLY("anti_bully_sticker"),
    ANTI_BULLY_GLOBAL("anti_bully_global_sticker"),
    AVATAR("avatar"),
    AVATAR_ANIMATED("avatar_animated"),
    AVATAR_SEARCH("avatar_search"),
    AVATAR_STATIC("avatar_static"),
    BEFORE_AND_AFTER_STICKER("before_and_after_sticker"),
    BIO_PRODUCT("igbio_product"),
    BLOKS("bloks_sticker"),
    BLOKS_ANIMATED("bloks_sticker"),
    CHANNEL_CHALLENGE("channel_challenge"),
    CLIPS_PROMPT("clips_prompt_sticker"),
    CLIPS_QUESTION("clips_question_sticker"),
    COUNTDOWN("countdown_sticker"),
    CUTOUT_PHOTO("cutout_photo"),
    CUTOUT_VIDEO("cutout_video"),
    CUT_OUT_STICKER("cut_out_sticker"),
    ELECTION_ADD_YOURS("election_add_yours"),
    ELECTION_STICKER("election_sticker"),
    EVENT_STICKER("event_sticker"),
    EXPLORE_SHAREABLE_GRID("explore_shareable_grid"),
    FB_COMMUNITY("fb_community"),
    FB_TAG("fb_tag"),
    FILLABLE_GALLERY_STICKER("fillable_gallery_sticker"),
    FILLABLE_MUSIC_STICKER("fillable_music_sticker"),
    FILLABLE_TEXT_STICKER("fillable_text_sticker"),
    FITNESS_STICKER("fitness_sticker"),
    FITNESS_STICKER_CREATION("fitness_sticker_creation"),
    FOLLOWER_MILESTONE_STICKER("follower_milestone_sticker"),
    FUNDRAISER("fundraiser_sticker"),
    FUNDRAISER_THANKS("fundraiser_sticker_thanks"),
    GALLERY("gallery"),
    GALLERY_BROWSE("gallery_browse"),
    GEO_STICKER("geo_sticker"),
    GIF("gif"),
    GIF_SEARCH("gif_search"),
    GROUP_MENTION_STICKER("group_mention_sticker"),
    GROUP_POLL_STICKER("group_poll_sticker"),
    GUIDE("guide"),
    HASHTAG_STICKER("hashtag_sticker"),
    IG_FEATURE_LINKING_STICKER("ig_feature_linking_sticker"),
    IMAGINE_ME("imagine_me"),
    IMAGINE_TEMPLATE("imagine_template"),
    INSTAPAL_STICKER("instapal_sticker"),
    INTERNAL("internal_sticker"),
    I_TAKE_CARE_STICKER("i_take_care_sticker"),
    JOIN_CHAT("join_chat_sticker"),
    KARAOKE_CAPTION("karaoke_caption_sticker"),
    KEYBOARD_CONTENT_STICKER("keyboard_content_sticker"),
    LINK_STICKER("link_sticker"),
    MAGIC_MOD_ADD_YOURS_BACKDROP("magic_mod_add_yours_backdrop"),
    MAGIC_MOD_BACKDROP("magic_mod_backdrop"),
    MAGIC_MOD_RESTYLE("magic_mod_restyle"),
    MEDIA("media"),
    MEMORIES("memories"),
    MEMORIES_STICKER("memories_sticker"),
    MENTION("mention"),
    MESSAGE_SHARE("message_share"),
    MUSIC_OVERLAY("music_overlay_sticker"),
    MUSIC_PICK_STICKER("music_pick_sticker"),
    MUSIC_TRACK_PREVIEW("music_track_preview_sticker"),
    NORMAL("normal"),
    NOTIFY_ME("notify_me"),
    PHOTO_CRED("photo_cred"),
    PICS_PLEASE_STICKER("pics_please_sticker"),
    PLACEHOLDER_STICKER("placeholder_sticker"),
    POLAROID_STICKER("polaroid_sticker"),
    POLLING("polling_sticker"),
    POLL_STICKER_V2("poll_sticker_v2"),
    PRODUCT("product_item_sticker"),
    PRODUCT_SHARE("product_share_sticker"),
    PROFILE_STICKER("profile_sticker"),
    PROMPT("prompt_sticker"),
    PUBLIC_COLLECTIONS("public_collection_stricker"),
    QUESTION("question_sticker"),
    QUESTION_RESPONSE_RESHARE("question_response_reshare"),
    QUICKSNAP_RECAP_STICKER("quicksnap_recap_sticker"),
    QUIZ("quiz_sticker"),
    REACTION_STICKER("reaction_sticker"),
    REELS_VISUAL_REPLIES("reels_visual_replies_sticker"),
    RESHARE_STICKER("reshare_sticker"),
    SECRET_STICKER("secret_sticker"),
    SHARE_PLATFORM("share_platorm"),
    SHOPPING("shopping_sticker"),
    SHOPPING_COLLECTION_SHARE("shopping_collection_share_sticker"),
    SHOP_SHARE("shop_share_sticker"),
    SLIDER("slider_sticker"),
    SMB_DELIVERY_STICKER("smb_delivery_sticker"),
    SMB_GET_QUOTE_STICKER("smb_get_quote_sticker"),
    SMB_GIFT_CARD_STICKER("smb_support_sticker"),
    STORIES_TEMPLATE("stories_template"),
    STORIES_TEMPLATE_GALLERY_OVERLAY("stories_template_gallery_overlay"),
    SUBSCRIBER_CHAT("subscriber_chat_sticker"),
    SUBSCRIPTIONS_STICKER("subscriptions_sticker"),
    SUPERLATIVE_STORY("superlative_story"),
    SUPPORT_DIVERSITY_BUSINESS_PROFILE_STICKER("amplify_diversity_business_profile_sticker"),
    SUPPORT_PERSONALIZED_ADS_STICKER("support_personalized_ads_sticker"),
    SUPPORT_SMB_BUSINESS_PROFILE_STICKER("share_professional_profile_sticker"),
    SWAPPABLE_GALLERY_STICKER("swappable_gallery_sticker"),
    TEXT("text"),
    TIME("time"),
    UNIVERSAL_LOCATION("universal_location"),
    UPCOMING_EVENT("upcoming_event_sticker"),
    USER_PAY_BADGES_THANKS_STICKER("user_pay_badges_thanks_sticker"),
    VOTER_REGISTRATION("voter_registration_sticker"),
    VOTING_INFO_CENTER("voting_info_center"),
    WHATSAPP_STICKER("whatsapp_sticker");
    
    public final String A00;

    /* access modifiers changed from: public */
    static {
        C318046oG[] r2;
        A01 = 0oU.A00(r2);
    }

    public final String toString() {
        return this.A00;
    }

    /* access modifiers changed from: public */
    C318046oG(String str) {
        this.A00 = str;
    }
}
