package X;

/* renamed from: X.7Bo  reason: invalid class name and case insensitive filesystem */
public enum C327627Bo {
    NUX_TYPE_NONE,
    NUX_TYPE_DOUBLE_TAP_TO_LIKE,
    NUX_TYPE_DOUBLE_TAP_TO_REACT_WITH_AVATAR,
    NUX_TYPE_LONG_PRESS_TO_REACT,
    NUX_TYPE_TAP_TO_FORWARD,
    NUX_TYPE_REPLY,
    NUX_TYPE_GIFT_MESSAGE,
    NUX_TYPE_CREATE_HEADMOJI_STICKER,
    NUX_TYPE_SAVED_REPLY,
    NUX_TYPE_AVATAR_QR,
    NUX_TYPE_AVATAR_STICKER,
    NUX_TYPE_COLLAB_COLLECTION,
    NUX_TYPE_SELFIE_REACTION,
    NUX_TYPE_SHARE_MESSAGE,
    NUX_TYPE_CHANNEL_MEMBER_REPLY,
    NUX_TYPE_CHANNEL_TRANSLATION,
    NUX_TYPE_TAG_CHANNEL_ON_POST,
    NUX_TYPE_GET_BARCELONA,
    NUX_TYPE_GET_AI_AGENT,
    NUX_TYPE_BRANDED_CONTENT_UPSELL,
    NUX_TYPE_TRY_AI_ASSISTANT,
    NUX_TYPE_TRY_META_AI_TEXT,
    NUX_TYPE_TRY_IMAGINE,
    NUX_TYPE_IMAGINE_ANIMATE,
    NUX_TYPE_CHANNEL_XPOSTING_UPSELL,
    NUX_TYPE_CHANNEL_MESSAGE_XPOSTED_HINT,
    NUX_TYPE_CUSTOMER_DETAILS,
    NUX_TYPE_AVATAR_UPDATE,
    NUX_TYPE_ADD_REACTIONS,
    NUX_TYPE_META_AI_INTENT_DETECTION,
    NUX_TYPE_AI_AGENT_REGENERATE,
    NUX_TYPE_TRY_IT_IMAGINE_ME,
    NUX_TYPE_MEMU_IN_FEED_IMAGINE_YOURSELF,
    NUX_TYPE_GEN_AI_IMAGINE_CREATE,
    NUX_TYPE_EDIT_WITH_AI,
    NUX_TYPE_CHANNEL_XPOSTING_CREATION_UPSELL,
    NUX_TYPE_RETAKE_PHOTO_FOR_IMAGINE_ME,
    NUX_TYPE_LONG_PRESS_REPLY_TO_AI,
    NUX_TYPE_ONE_CLICK_UPSELL_ICEBREAKER;

    /* access modifiers changed from: public */
    static {
        C327627Bo[] r1;
        A00 = 0oU.A00(r1);
    }
}
