package X;

/* renamed from: X.7dR  reason: invalid class name and case insensitive filesystem */
public enum C335727dR {
    EMPATHY,
    DEFAULT,
    RESPECTFUL_STORY_CREATION_BOTTOM_SHEET,
    RESPECTFUL_MEDIA_CREATION_BOTTOM_SHEET,
    RESPECTFUL_STORY_REPLY_BOTTOM_SHEET,
    RESPECTFUL_STORY_REPLY_LIGHTWEIGHT,
    PENDING_REVIEW_STORY_REPLY_BOTTOM_SHEET,
    WELCOME_LIGHTWEIGHT,
    WARNING_LIGHTWEIGHT,
    PERSISTENT_WELCOME_LIGHTWEIGHT,
    PERSISTENT_WARNING_LIGHTWEIGHT,
    SET_TONE_LIGHTWEIGHT,
    PERSISTENT_SET_TONE_LIGHTWEIGHT,
    DIRECT_CHANNEL_REPLY_NUDGE,
    TEXT_POST_APP_SET_TONE,
    NONE;

    /* access modifiers changed from: public */
    static {
        C335727dR[] r0;
        A00 = 0oU.A00(r0);
    }
}
