package X;

/* renamed from: X.8sJ  reason: invalid class name and case insensitive filesystem */
public enum C368248sJ implements AnonymousClass0Ac {
    ACL_CHECK_FAILURE(1),
    FETCH_FAILURE(2),
    FETCH_START(3),
    FETCH_SUCCESS(4),
    REMOVE_FAILURE(5),
    REMOVE_START(6),
    REMOVE_SUCCESS(7),
    REPLICATED_STORAGE_TARGET_APP_FETCH_FAILURE(19),
    REPLICATED_STORAGE_TARGET_APP_FETCH_START(20),
    REPLICATED_STORAGE_TARGET_APP_FETCH_SUCCESS(21),
    REPLICATED_STORAGE_TARGET_APP_REMOVE_FAILURE(22),
    REPLICATED_STORAGE_TARGET_APP_REMOVE_RECEIVED(23),
    REPLICATED_STORAGE_TARGET_APP_REMOVE_SUCCESS(24),
    REPLICATED_STORAGE_TARGET_APP_SAVE_FAILURE(25),
    REPLICATED_STORAGE_TARGET_APP_SAVE_RECEIVED(26),
    REPLICATED_STORAGE_TARGET_APP_SAVE_SUCCESS(27),
    TARGET_APP_FETCH_FAILURE(28),
    TARGET_APP_FETCH_SUCCESS(30),
    WRITE_FAILURE(8),
    WRITE_START(9),
    WRITE_SUCCESS(10);
    
    public final long A00;

    /* access modifiers changed from: public */
    C368248sJ(long j) {
        this.A00 = j;
    }
}
