package X;

/* renamed from: X.9Gx  reason: invalid class name and case insensitive filesystem */
public enum C376179Gx {
    RAVEN_VISUAL_MESSAGING(1),
    SECRET_CHATS(2),
    THREAD_DETAILS(3),
    RTC_VIDEO_CALL(4),
    RTC_VOICE_CALL(5),
    SHH_MODE(6),
    STICKER(7),
    GIF(8),
    THREAD_DETAILS_SHOW_THEME_SETTINGS(9),
    THREAD_DETAILS_SHOW_CUSTOM_SOUNDS_SETTINGS(10),
    THREAD_DETAILS_SHOW_RESTRICT_SETTINGS(11),
    THREAD_DETAILS_ADD_MEMBER_TO_GROUP_CHAT(12),
    THREAD_DETAILS_OPEN_USER_PROFILE(14),
    COMPOSER_APPOINTMENT_BOOKING(15),
    REACTIONS(16),
    MESSAGE_REPLY(17),
    MESSAGE_FORWARDING(18),
    MESSAGE_UNSEND(19),
    MESSAGE_REPORTING(20),
    POLL_MESSAGE_CREATION(21),
    ENABLE_VISUAL_MESSAGE_REPLY(22),
    VOICE(23),
    MESSAGE_SAVE_MEDIA(24),
    BLOCK(25),
    REPORT_USER(26),
    MUTE_MESSAGES(27),
    SORT_BY_DRAFT_TIMESTAMP(28),
    SEEN_INDICATOR(29),
    STAR_THREAD(30),
    MARK_THREAD_AS_UNREAD(31),
    MOVE_FOLDER(32),
    CUSTOMIZE_THEME_FROM_THREAD(33),
    THREAD_DETAILS_SHOW_MUTE_CALL_NOTIFICATIONS(34),
    CUSTOMIZE_THREAD_NAME(35),
    MUTE_MENTIONS(36),
    HEADMOJI_STICKERS(37),
    HOT_LIKE(38),
    BIZ_PERSISTENT_MENU(39),
    RTC_GROUP_VIDEO_CALL(40),
    RTC_GROUP_VOICE_CALL(41),
    P2M_PAYMENT_REQUEST(42),
    MESSAGE_REQUEST_GROUP_INVITE(43),
    MUTE_REACTIONS(44),
    MESSAGE_REQUEST_COMPOSER_BANNER(45),
    READ_RECEIPTS_TOGGLE(46),
    BROADCAST_CHANNEL_RESTRICTION_BYPASS(47),
    SEND_GALLERY_MEDIA(48),
    NAVIGATE_TO_USER_PROFILE(49),
    REMINDER(50),
    PSEUDO_THREAD_CONTEXT_MODEL_CREATION_ON_THREAD_UPDATED(-1),
    PSEUDO_PRODUCT_PICKER(-2),
    PSEUDO_RESET_UNSEEN_MESSAGE_TIMESTAMP_ON_THREAD_UPDATED(-3),
    PSEUDO_UPDATE_ACTION_BAR_SUBTITLE_ON_PRESENCE_CHANGE(-7),
    PSEUDO_LOG_TAP_ON_REVEAL_MESSAGE(-8),
    PSEUDO_CHANGE_IMAGE_REVEAL_STATUS(-10),
    PSEUDO_LOG_NAVIGATION_TO_PRODUCT_VIEWER(-11),
    PSEUDO_NAVIGATE_TO_XMA_DETAILS(-12),
    PSEUDO_PRESENCE_HEADS(-13),
    PSEUDO_TRANSLATE_THREAD_MESSAGES(-14),
    PSEUDO_MARK_THREAD_AS_UNREAD(-15),
    PSEUDO_WARN_ABOUT_REPORTED_USER(-16),
    PSEUDO_REPORT_MESSAGE(-17),
    PSEUDO_SHOW_THREAD_INFO_WITH_DIRECT_THREAD_OBJECT(-18),
    PSEUDO_STAR_THREAD(-19),
    PSEUDO_SHOW_THREAD_VIEW_NUXES(-20),
    PSEUDO_GET_DIRECT_MESSAGE_OBJECT_FROM_DATASOURCE(-22),
    PSEUDO_GET_DIRECT_MESSAGE_ROW_DATA_FROM_DATASOURCE(-23),
    PSEUDO_GET_EXTENDED_DIRECT_THREAD_FROM_DATASOURCE(-24),
    PSEUDO_COLLAPSE_ADMIN_MESSAGES(-25),
    PSEUDO_INSTANT_REPLIES_IN_COMPOSER(-26),
    PSEUDO_USE_DIRECT_MESSAGE_WHEN_SENDING_INLINE_LIKE(-27),
    PSEUDO_GET_MENTIONED_USER_IDS(-28),
    PSEUDO_CO_PRESENCE_ENABLED(-29),
    PSEUDO_UPDATE_QP_TRIGGER_CONTEXT(-31),
    PSEUDO_MESSAGE_DELIVERY_TRIGGER(-32),
    DEBUG_SELECTABLE_AS_LINKED_CUTOVER_THREAD(-33);
    
    public final int A00;

    /* access modifiers changed from: public */
    static {
        C376179Gx[] r0;
        A01 = 0oU.A00(r0);
    }

    /* access modifiers changed from: public */
    C376179Gx(int i) {
        this.A00 = i;
    }
}
