package X;

/* renamed from: X.9tP  reason: invalid class name and case insensitive filesystem */
public enum C391639tP implements C66374MPg {
    A02,
    PHONE_SCREEN_OFF,
    STREAM_STARTING,
    STREAM_STARTED,
    STREAM_PAUSE,
    STREAM_RESUME,
    STREAM_ENDS,
    STREAM_ERROR,
    TOGGLE_TO_PHONE,
    TOGGLE_TO_SG,
    PHONE_SCREEN_ON,
    PROMPT_DOUBLE_CAPTURE_PRESS,
    STREAM_ENDING,
    TOGGLE_TO_SG_PRE_LIVE,
    TOGGLE_TO_SG_WHILE_LIVE,
    STREAM_BROADCASTING,
    PHONE_VIDEO_OFF,
    PHONE_SCREEN_OFF_PRE_LIVE,
    PROMPT_PHONE_VIDEO_OFF_ERROR,
    PROMPT_GENERIC_ERROR,
    PROMPT_VIDEO_CAPTURE_USER_ED,
    PROMPT_PHOTO_CAPTURE_USER_ED,
    PHOTO_CAPTURED,
    PROMPT_PREVIEWING_FROM_GLASSES,
    PROMPT_SWITCH_TO_GLASSES_CAPTURE_USER_ED,
    PROMPT_ENABLE_PERMISSIONS_ERROR,
    PROMPT_DOUBLE_CAPTURE_PRESS_VARIATION,
    STREAM_STARTING_CANCEL;

    /* access modifiers changed from: public */
    static {
        C391639tP[] r3;
        A00 = 0oU.A00(r3);
    }
}
