package X;

/* renamed from: X.EZx  reason: case insensitive filesystem */
public enum C48155EZx implements G54 {
    ADD_PHONE,
    FB_CONNECT,
    CONTACT_INVITE,
    CONTACT_INVITE_NO_SKIP_BUTTON,
    CONTACT_INVITE_UPDATED_TEXT_NO_ILLUSTRATION,
    CONTACT_INVITE_REDESIGN_B,
    CONTACT_INVITE_REDESIGN_C,
    PARTIAL_CONTACT_IMPORT,
    ACCOUNT_PRIVACY,
    TAKE_PROFILE_PHOTO,
    TURN_ON_ONETAP,
    CHECK_FOR_PHONE,
    DISCOVER_PEOPLE,
    DISCOVER_PEOPLE_AFTER_PARTIAL_CI,
    DP_NUX_QUICK_FRIENDING,
    DP_NUX_QUICK_FRIENDING_AFTER_PARTIAL_CI,
    REELS_TUNING,
    DISCOVER_ACCOUNTS,
    FOLLOW_FROM_LOGGED_IN_ACCOUNTS,
    A0D,
    IDENTITY_SYNCING,
    IDENTITY_SYNCING_AFTER_NUX_LINKING,
    LIGHTWEIGHT_CONNECTIONS,
    AUTO_CROSSPOSTING,
    PUSH_OPT_IN,
    UXR_SURVEY,
    CP_ACQUISITION_EMAIL,
    CP_ACQUISITION_PHONE,
    UNKNOWN;

    /* access modifiers changed from: public */
    static {
        C48155EZx[] eZxArr;
        A00 = 0oU.A00(eZxArr);
    }
}
