package X;

/* renamed from: X.EZl  reason: case insensitive filesystem */
public enum C48143EZl implements AnonymousClass0Ac {
    ACR_BROWSER_ENTRY_POINT_GALLERY("ACR_BROWSER_ENTRY_POINT_GALLERY"),
    ACR_BROWSER_ENTRY_POINT_DESTINATION_PICKER("ACR_BROWSER_ENTRY_POINT_DESTINATION_PICKER"),
    ACR_BROWSER_ENTRY_POINT_MIDCARD("ACR_BROWSER_ENTRY_POINT_MIDCARD"),
    ACR_BROWSER_ENTRY_POINT_NOTIFICATION("ACR_BROWSER_ENTRY_POINT_NOTIFICATION"),
    ACR_BROWSER_ENTRY_POINT_REELS_VIEWER("ACR_BROWSER_ENTRY_POINT_REELS_VIEWER"),
    ACR_BROWSER_ENTRY_POINT_PROFILE_CREATION_MENU("ACR_BROWSER_ENTRY_POINT_PROFILE_CREATION_MENU"),
    ACR_BROWSER_ENTRY_POINT_AUDIO_PAGE("ACR_BROWSER_ENTRY_POINT_AUDIO_PAGE"),
    ACR_BROWSER_ENTRY_POINT_CAMERA_ROLL_MIDCARD("ACR_BROWSER_ENTRY_POINT_CAMERA_ROLL_MIDCARD"),
    ACR_BROWSER_ENTRY_UNTRACKED("ACR_BROWSER_ENTRY_UNTRACKED");
    
    public final String A00;

    /* access modifiers changed from: public */
    C48143EZl(String str) {
        this.A00 = str;
    }
}
