package X;

/* renamed from: X.HOu  reason: case insensitive filesystem */
public enum C54689HOu implements AnonymousClass0Ac {
    GALLERY_DESTINATION_BAR("GALLERY_DESTINATION_BAR"),
    OPEN_CAROUSEL_ADD_TO_POST("OPEN_CAROUSEL_ADD_TO_POST"),
    OPEN_CAROUSEL_ADD_TO_POST_DISABLED("OPEN_CAROUSEL_ADD_TO_POST_DISABLED"),
    OPEN_CAROUSEL_SUBMIT_PREVIEW("OPEN_CAROUSEL_SUBMIT_PREVIEW"),
    OPEN_CAROUSEL_SUBMIT_CROP("OPEN_CAROUSEL_SUBMIT_CROP"),
    OPEN_CAROUSEL_REVIEW_PAGE("OPEN_CAROUSEL_REVIEW_PAGE"),
    OPEN_CAROUSEL_REVIEW_PAGE_FILTERS("OPEN_CAROUSEL_REVIEW_PAGE_FILTERS"),
    OPEN_CAROUSEL_REVIEW_BANNER("OPEN_CAROUSEL_REVIEW_BANNER"),
    OPEN_CAROUSEL_DECLINE("OPEN_CAROUSEL_DECLINE"),
    OPEN_CAROUSEL_APPROVE("OPEN_CAROUSEL_APPROVE"),
    OPEN_CAROUSEL_TURN_ON_FROM_BANNER("OPEN_CAROUSEL_TURN_ON_FROM_BANNER"),
    OPEN_CAROUSEL_TURN_ON_FROM_MORE_MENU("OPEN_CAROUSEL_TURN_ON_FROM_MORE_MENU"),
    OPEN_CAROUSEL_TURN_OFF("OPEN_CAROUSEL_TURN_OFF"),
    OPEN_CAROUSEL_DELETE_SELF_MEDIA("OPEN_CAROUSEL_DELETE_SELF_MEDIA"),
    OPEN_CAROUSEL_GRID_VIEW_PREVIEW("OPEN_CAROUSEL_GRID_VIEW_PREVIEW"),
    OPEN_CAROUSEL_GRID_VIEW_PREVIEW_SELECT("OPEN_CAROUSEL_GRID_VIEW_PREVIEW_SELECT"),
    OPEN_CAROUSEL_GRID_VIEW_SELECT("OPEN_CAROUSEL_GRID_VIEW_SELECT"),
    FOLLOW_BUTTON("FOLLOW_BUTTON"),
    OPEN_CAROUSEL_ADD_TO_POST_CTA_IN_HEADER("OPEN_CAROUSEL_ADD_TO_POST_CTA_IN_HEADER");
    
    public final String A00;

    public static C54689HOu A00(String str, String str2, int i) {
        return new C54689HOu(str, i, str2);
    }

    /* access modifiers changed from: public */
    C54689HOu(String str) {
        this.A00 = str;
    }
}
