package X;

import android.app.Application;
import com.facebook.common.callercontext.CallerContext;
import com.instagram.common.session.UserSession;
import com.instagram.creation.capture.quickcapture.sundial.viewmodel.drafts.ClipsSharingDraftViewModel;
import com.instagram.creation.sharesheet.update.trial.TrialUseCase;
import com.instagram.pendingmedia.model.recipients.PendingRecipient;

/* renamed from: X.KEi  reason: case insensitive filesystem */
public final class C61607KEi extends C228042kh {
    public final Application A00;
    public final AnonymousClass07Z A01;
    public final CallerContext A02;
    public final C60132JgD A03;
    public final C60112Jft A04;
    public final C60119Jg0 A05;
    public final AnonymousClass0iw A06;
    public final UserSession A07;
    public final ClipsSharingDraftViewModel A08;
    public final C60259JiG A09;
    public final LO3 A0A;
    public final LFG A0B;
    public final C60264JiL A0C;
    public final C65173Loc A0D;
    public final C60288Jik A0E;
    public final C60164Jgj A0F;
    public final C60187Jh6 A0G;
    public final AnonymousClass89T A0H;
    public final PendingRecipient A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final boolean A0M;
    public final boolean A0N;
    public final boolean A0O;
    public final boolean A0P;
    public final boolean A0Q;
    public final boolean A0R;
    public final boolean A0S;
    public final boolean A0T;

    public final /* bridge */ /* synthetic */ 2YL create() {
        UserSession userSession = this.A07;
        ClipsSharingDraftViewModel clipsSharingDraftViewModel = this.A08;
        AnonymousClass07Z r4 = this.A01;
        KO2 ko2 = new KO2(r4, userSession, clipsSharingDraftViewModel);
        String str = this.A0K;
        boolean z = this.A0O;
        boolean z2 = this.A0P;
        boolean z3 = this.A0R;
        C61824KNn kNn = new C61824KNn(userSession, str, z, z2, z3, this.A0M);
        KOD kod = new KOD(userSession, ko2);
        C61849KOo kOo = new C61849KOo(userSession, this.A0A, this.A0B, ko2);
        C61836KOa kOa = new C61836KOa(ko2);
        KOA koa = new KOA(ko2);
        KOS kos = new KOS(userSession, ko2, this.A0N, this.A0S, this.A0T);
        C65173Loc loc = this.A0D;
        Application application = this.A00;
        UserSession userSession2 = userSession;
        C61850KOp kOp = new C61850KOp(DbT.A05(application), userSession2, loc, ko2, (0sP) null, false);
        C61839KOd kOd = new C61839KOd(userSession, ko2);
        boolean z4 = this.A0Q;
        AnonymousClass0iw r6 = this.A06;
        C61846KOl kOl = new C61846KOl(r6, userSession, ko2, z4);
        KOT kot = new KOT(r6, userSession2, ko2, z, z2, z4);
        String str2 = this.A0L;
        String str3 = str2;
        C61844KOi kOi = new C61844KOi(r6, userSession, ko2, str2);
        KOU kou = new KOU(ko2);
        KOZ koz = new KOZ(ko2);
        KOK kok = new KOK(userSession, ko2);
        KOY koy = new KOY(userSession, ko2, z3);
        C61848KOn kOn = new C61848KOn(this.A02, userSession, ko2, this.A0E, this.A0F, this.A0H, r6.getModuleName(), z, z2, z3);
        KOW kow = new KOW(userSession, ko2, this.A0G);
        KOJ koj = new KOJ(userSession, ko2);
        KO9 ko9 = new KO9(ko2);
        KOQ koq = new KOQ(ko2);
        KOB kob = new KOB(ko2);
        KOV kov = new KOV(ko2);
        C61842KOg kOg = new C61842KOg(r4, userSession, ko2);
        C61847KOm kOm = new C61847KOm(DbT.A05(application), loc.A00, r6, userSession, ko2);
        KOI koi = new KOI(userSession, C62462KgC.CLIPS, ko2, z3);
        KOG kog = new KOG(userSession, ko2);
        C61838KOc kOc = new C61838KOc(userSession, ko2);
        TrialUseCase trialUseCase = new TrialUseCase(r6, userSession, ko2, z2, z3);
        C61843KOh kOh = new C61843KOh(DbT.A05(application), userSession, ko2);
        PendingRecipient pendingRecipient = this.A0I;
        KOR kor = new KOR(r6, userSession, ko2, pendingRecipient);
        KOM kom = new KOM(userSession, ko2, r6.getModuleName());
        KOE koe = new KOE(userSession, ko2, str, this.A0J);
        KOL kol = new KOL(userSession, ko2, z3);
        KOH koh = new KOH(userSession, ko2);
        C60112Jft jft = this.A04;
        C60259JiG jiG = this.A09;
        C60264JiL jiL = this.A0C;
        C60119Jg0 jg0 = this.A05;
        return new C61829KNs(application, r4, this.A03, jft, jg0, userSession, kod, jiG, jiL, kNn, ko9, koq, kOl, kog, kOc, kou, kOa, koa, koh, kOo, koi, ko2, koz, koj, kom, koe, kOp, kOg, kos, kOi, kor, kok, kOm, kol, koy, kOh, kot, kob, kov, trialUseCase, kOd, kow, kOn, pendingRecipient, str3, z3);
    }

    public C61607KEi(Application application, AnonymousClass07Z r19, CallerContext callerContext, C60132JgD jgD, C60112Jft jft, C60119Jg0 jg0, AnonymousClass0iw r24, UserSession userSession, ClipsSharingDraftViewModel clipsSharingDraftViewModel, C60259JiG jiG, LO3 lo3, LFG lfg, C60264JiL jiL, C65173Loc loc, C60288Jik jik, C60164Jgj jgj, C60187Jh6 jh6, AnonymousClass89T r35, PendingRecipient pendingRecipient, String str, String str2, String str3, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8) {
        C60187Jh6 jh62 = jh6;
        C60164Jgj jgj2 = jgj;
        C60288Jik jik2 = jik;
        ClipsSharingDraftViewModel clipsSharingDraftViewModel2 = clipsSharingDraftViewModel;
        CallerContext callerContext2 = callerContext;
        C51974G9v.A1S(callerContext2, clipsSharingDraftViewModel2, jh62, jik2, jgj2);
        C60264JiL jiL2 = jiL;
        C60259JiG jiG2 = jiG;
        C60112Jft jft2 = jft;
        C60119Jg0 jg02 = jg0;
        C51974G9v.A1Q(jft2, jiG2, jiL2, jg02);
        UserSession userSession2 = userSession;
        C60132JgD jgD2 = jgD;
        C51969G9p.A1P(jgD2, 11, userSession2);
        LO3 lo32 = lo3;
        C65173Loc loc2 = loc;
        C51969G9p.A1S(lo32, 15, loc2);
        AnonymousClass0iw r11 = r24;
        0qQ.A0B(r11, 18);
        String str4 = str3;
        0qQ.A0B(str4, 21);
        this.A00 = application;
        this.A02 = callerContext2;
        this.A08 = clipsSharingDraftViewModel2;
        this.A0G = jh62;
        this.A0E = jik2;
        this.A0F = jgj2;
        this.A04 = jft2;
        this.A09 = jiG2;
        this.A0C = jiL2;
        this.A05 = jg02;
        this.A03 = jgD2;
        this.A0H = r35;
        this.A01 = r19;
        this.A07 = userSession2;
        this.A0A = lo32;
        this.A0B = lfg;
        this.A0D = loc2;
        this.A06 = r11;
        this.A0K = str;
        this.A0J = str2;
        this.A0L = str4;
        this.A0R = z;
        this.A0O = z2;
        this.A0P = z3;
        this.A0Q = z4;
        this.A0N = z5;
        this.A0S = z6;
        this.A0T = z7;
        this.A0I = pendingRecipient;
        this.A0M = z8;
    }
}
