package X;

/* renamed from: X.KkY  reason: case insensitive filesystem */
public enum C62672KkY implements AnonymousClass0Ac {
    ARCHIVE_FEED_STICKER("ARCHIVE_FEED_STICKER"),
    BRANDED_CONTENT("BRANDED_CONTENT"),
    COMMENT_SHARE_STICKER("COMMENT_SHARE_STICKER"),
    IGTV_STICKER("IGTV_STICKER"),
    IMMERSIVE_MENTION_RESHARE("IMMERSIVE_MENTION_RESHARE"),
    MAGIC_MOD("MAGIC_MOD"),
    MENTION_RESHARE("MENTION_RESHARE"),
    PRODUCT_SHARE("PRODUCT_SHARE"),
    REELS_RESHARE("REELS_RESHARE"),
    STORY_TEMPLATE("STORY_TEMPLATE"),
    STORY_TEMPLATE_RESHARE_XPOSTING_INELIGIBLE_PINNED_ITEMS("STORY_TEMPLATE_RESHARE_XPOSTING_INELIGIBLE_PINNED_ITEMS");
    
    public final String A00;

    /* access modifiers changed from: public */
    C62672KkY(String str) {
        this.A00 = str;
    }
}
