package X;

import com.instagram.api.schemas.MediaCroppingCoordinates;
import com.instagram.clips.model.metadata.ClipsFanClubMetadata;
import com.instagram.music.common.model.MusicOverlayStickerModel;
import com.instagram.pendingmedia.model.ClipInfo;
import com.instagram.share.facebook.model.FBReelsAudienceType;
import java.util.List;
import java.util.Set;

/* renamed from: X.LQn  reason: case insensitive filesystem */
public final class C64150LQn {
    public float A00;
    public int A01;
    public C61080JwI A02;
    public C61062Jw0 A03;
    public C61100JxB A04;
    public MediaCroppingCoordinates A05;
    public ClipsFanClubMetadata A06;
    public AnonymousClass8J0 A07;
    public AnonymousClass3QO A08;
    public MusicOverlayStickerModel A09;
    public ClipInfo A0A;
    public AnonymousClass3QS A0B;
    public FBReelsAudienceType A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Integer A0H;
    public Integer A0I;
    public Integer A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public List A0Z;
    public List A0a;
    public List A0b;
    public List A0c;
    public List A0d;
    public List A0e;
    public List A0f;
    public List A0g;
    public List A0h;
    public List A0i;
    public List A0j;
    public List A0k;
    public List A0l;
    public List A0m;
    public List A0n;
    public Set A0o;
    public boolean A0p;
    public boolean A0q;
    public boolean A0r;
    public boolean A0s;
    public boolean A0t;
    public boolean A0u;
    public boolean A0v = true;
    public boolean A0w;
    public boolean A0x;
    public boolean A0y;
    public boolean A0z;
    public boolean A10;
    public boolean A11;
    public boolean A12;
    public boolean A13;

    public static void A00(C64150LQn lQn, List list) {
        lQn.A0a = list;
        lQn.A0Z = list;
        lQn.A0o = 0sl.A00;
        lQn.A0b = list;
        lQn.A0l = list;
        lQn.A0m = list;
        lQn.A0c = list;
        lQn.A0f = list;
        lQn.A0i = list;
        lQn.A0k = list;
        lQn.A0G = false;
        lQn.A0D = false;
        lQn.A0E = false;
        lQn.A0F = false;
        lQn.A0J = 0;
    }

    public C64150LQn(C61080JwI jwI, C61062Jw0 jw0, C61100JxB jxB, MediaCroppingCoordinates mediaCroppingCoordinates, ClipsFanClubMetadata clipsFanClubMetadata, AnonymousClass8J0 r14, AnonymousClass3QO r15, MusicOverlayStickerModel musicOverlayStickerModel, ClipInfo clipInfo, AnonymousClass3QS r18, FBReelsAudienceType fBReelsAudienceType, Integer num, Integer num2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, List list, List list2, List list3, List list4, List list5, List list6, List list7, List list8, List list9, List list10, List list11, List list12, List list13, List list14, List list15, Set set, float f, int i, int i2, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19) {
        List list16 = list12;
        0qQ.A0B(r15, 1);
        List list17 = list2;
        0qQ.A0B(list17, 19);
        List list18 = list7;
        0qQ.A0B(list18, 25);
        List list19 = list8;
        0qQ.A0B(list19, 26);
        List list20 = list10;
        0qQ.A0B(list20, 39);
        List list21 = list11;
        0qQ.A0B(list21, 42);
        List list22 = 0sn.A00;
        A00(this, list22);
        this.A08 = r15;
        this.A0L = str;
        this.A0M = str2;
        this.A0K = str3;
        this.A10 = z;
        this.A05 = mediaCroppingCoordinates;
        this.A11 = z2;
        this.A12 = z3;
        this.A0z = z4;
        this.A0T = str4;
        this.A0U = str5;
        this.A0I = num;
        this.A0e = list;
        this.A0C = fBReelsAudienceType;
        this.A0P = str6;
        this.A0A = clipInfo;
        this.A0o = set;
        this.A0l = list17;
        this.A0m = list3;
        this.A0c = list4;
        this.A09 = musicOverlayStickerModel;
        this.A0h = list5;
        this.A0b = list6;
        this.A0a = list18;
        this.A0Z = list19;
        this.A0n = list9;
        this.A03 = jw0;
        this.A06 = clipsFanClubMetadata;
        this.A0B = r18;
        this.A07 = r14;
        this.A0u = z5;
        this.A0q = z6;
        this.A0R = str9;
        this.A0t = z7;
        this.A0H = num2;
        this.A0V = str7;
        this.A0r = z8;
        this.A0Y = str8;
        this.A0f = list20;
        this.A0N = str10;
        this.A0i = list21;
        this.A0k = list12 == null ? list22 : list16;
        this.A0g = list13;
        this.A0s = z9;
        this.A0p = z10;
        this.A0X = str11;
        this.A0S = str12;
        this.A0O = str13;
        this.A0W = str14;
        this.A0w = z11;
        this.A0y = z12;
        this.A0v = z13;
        this.A0x = z14;
        this.A04 = jxB;
        this.A0Q = str15;
        this.A0E = Boolean.valueOf(z15);
        this.A0J = Integer.valueOf(i);
        this.A0G = Boolean.valueOf(z16);
        this.A00 = f;
        this.A0j = list14;
        this.A0D = Boolean.valueOf(z17);
        this.A0F = Boolean.valueOf(z18);
        this.A0d = list15;
        this.A13 = z19;
        this.A02 = jwI;
        this.A01 = i2;
    }

    public C64150LQn() {
        A00(this, 0sn.A00);
    }
}
