package X;

import com.facebook.cameracore.instagram.ardelivery.networkconsentmanager.IgNetworkConsentStorage;
import com.facebook.catalyst.modules.cameraroll.CameraRollManager;
import com.facebook.proxygen.TraceFieldType;
import com.facebookpay.offsite.models.message.PayButtonCTAType$Companion;
import com.instagram.debug.devoptions.direct.burner.BurnerSendSettingsHelper;
import com.instagram.debug.devoptions.sandboxselector.DevServerEntity;
import com.instagram.react.modules.base.IgReactQEModule;
import com.instagram.realtimeclient.RealtimeConstants;
import go.Seq;
import org.webrtc.CameraCapturer;
import org.webrtc.EglBase14Impl;
import org.webrtc.ScreenCapturerAndroid;

/* renamed from: X.MXk  reason: case insensitive filesystem */
public abstract class C66579MXk {
    public static String A00(int i) {
        switch (i) {
            case 0:
                return "null cannot be cast to non-null type com.instagram.common.bloks.BloksContext";
            case 1:
                return "null cannot be cast to non-null type android.content.Context";
            case 2:
                return "null cannot be cast to non-null type com.instagram.feed.sponsored.common.InsightsHost";
            case 3:
                return "com.instagram.url.extra.SHOULD_RETURN_TO_SENDING_ACTIVITY";
            case 4:
                return "bottom_sheet_content_fragment";
            case 5:
                return "null cannot be cast to non-null type kotlin.collections.List<kotlin.String>";
            case 6:
                return "null cannot be cast to non-null type com.instagram.common.ui.base.IgLinearLayout";
            case 7:
                return "null cannot be cast to non-null type com.instagram.base.activity.BaseFragmentActivity";
            case 8:
                return "Should only be called between onCreateView and onDestroyView";
            case 9:
                return "User session must not be null to access local device cache";
            case 10:
                return "android.intent.action.DIAL";
            case 11:
                return "bottom_sheet_session_id";
            case IgReactQEModule.CONFIG_KEY_OFFSET /*12*/:
                return "device_position";
            case 13:
                return "error_identifier";
            case 14:
                return "finish_host_activity_on_dismissed";
            case 15:
                return "https://www.facebook.com/policies/other-policies/ais-terms";
            case 16:
                return "null cannot be cast to non-null type com.instagram.base.activity.tabactivity.TabWidgetVisibilityDelegate";
            case 17:
                return "null cannot be cast to non-null type com.instagram.search.common.model.SearchItemState";
            case EglBase14Impl.EGLExt_SDK_VERSION:
                return "null cannot be cast to non-null type com.instagram.user.model.User";
            case 19:
                return "DirectShareSheetConstants.shopping_product";
            case 20:
                return "creator_ai_fragment_dismiss_strategy";
            case 21:
                return "null cannot be cast to non-null type androidx.recyclerview.widget.GridLayoutManager";
            case 22:
                return "null cannot be cast to non-null type com.instagram.common.api.base.ApiError.Exception";
            case 23:
                return "null cannot be cast to non-null type com.instagram.common.recyclerview.IgRecyclerViewAdapter";
            case 24:
                return "null cannot be cast to non-null type com.instagram.ui.emptystaterow.EmptyStateView";
            case 25:
                return "reactive_audio_download_url";
            case 26:
                return "session_instance_id";
            case 27:
                return ", isLoading=";
            case 28:
                return "DirectPrivateStoryRecipientFragment.IS_DISPLAYED_IN_BOTTOM_SHEET";
            case CameraRollManager.IMAGES_MEDIA_LATITUDE_LONGITUDE_DEPRECATED_API_LEVEL:
                return "ExplorePeopleFragment.ARGUMENT_FORCED_USER_IDS";
            case 30:
                return "HashtagFeedFragment.ARGUMENT_HASHTAG";
            case 31:
                return "dictionary_manager_entrypoint";
            case 32:
                return "direct_inbox_outcome_upsell";
            case 33:
                return "event_source";
            case 34:
                return "extra_notification_id";
            case 35:
                return "https://help.instagram.com/581066165581870";
            case 36:
                return "message_merchant";
            case 37:
                return "null cannot be cast to non-null type java.util.HashMap<kotlin.String, kotlin.String>";
            case 38:
                return "original_author_id";
            case 39:
                return "participant_ids";
            case 40:
                return "primary_button_text";
            case Seq.NULL_REFNUM:
                return "search_surface";
            case Seq.RefTracker.REF_OFFSET:
                return "suggested_prompts";
            case 43:
                return "upsell_snackbar";
            case 44:
                return "%02d:%02d:%02d";
            case 45:
                return ", contentDescription=";
            case 46:
                return ", imageUrl=";
            case 47:
                return ", isSelected=";
            case 48:
                return ", mediaType=";
            case 49:
                return ", threadId=";
            case BurnerSendSettingsHelper.MESSAGE_SEND_BATCH_SIZE /*50*/:
                return "867051314767696";
            case 51:
                return "DirectInboxSearchFragment.DIRECT_CONTAINER_MARGIN_BOTTOM_PX";
            case 52:
                return "DirectShareSheetConstants.scale_factor";
            case 53:
                return "Failed to convert collection to json";
            case 54:
                return "ReportingConstants.ARG_IS_PRIVATE_IMPERSONATION";
            case 55:
                return "camera_entry_bounds";
            case 56:
                return "channel_daily_prompt_xma";
            case 57:
                return "com.bloks.www.bio.product.details.variants.page.controller";
            case 58:
                return "com.bloks.www.bloks.imagine_create.bottomsheet";
            case 59:
                return "cutout_sticker_id";
            case 60:
                return "effect_action_sheet";
            case 61:
                return "group_thread_subtype";
            case 62:
                return "https://www.instagram.com/avatar/edit/update";
            case 63:
                return "inbox_channel_invitation";
            case 64:
                return "instagram://bloks/";
            case 65:
                return "notes_creation";
            case 66:
                return "null cannot be cast to non-null type android.text.Spannable";
            case 67:
                return "null cannot be cast to non-null type com.instagram.common.ui.widget.imageview.CircularImageView";
            case 68:
                return "prompt_source";
            case 69:
                return "remove_button";
            case 70:
                return "request_error";
            case 71:
                return TraceFieldType.RetryCount;
            case 72:
                return "share_button";
            case 73:
                return "share_to_system_sheet";
            case 74:
                return "something_went_wrong";
            case 75:
                return "story_template_discovery_surface";
            case 76:
                return "thread_details_people";
            case 77:
                return ", aspectRatio=";
            case 78:
                return ", color=";
            case 79:
                return ", cornerRadius=";
            case 80:
                return ", itemType=";
            case 81:
                return ", profilePicUrl=";
            case 82:
                return ", second=";
            case 83:
                return ", uri=";
            case 84:
                return "ARG_CONTAINER_MODULE";
            case 85:
                return "ARG_DISPLAY_FORMAT";
            case 86:
                return "ARG_VIEW_STATE_ITEM_TYPE";
            case 87:
                return "ClipsConstants.ARGS_ALL_CLIPS_MEDIA_RECEIVERS_FROM_CHAT";
            case 88:
                return "ClipsConstants.ARGS_REMOVED_CLIPS_COLLABORATORS_FROM_CHAT";
            case 89:
                return "ClipsConstants.ARGS_SOURCE_CHAT_THREAD_NAME";
            case 90:
                return "Could not access CREATOR field in class ";
            case 91:
                return "DirectReplyModalFragment.allow_swipe_down_to_dismiss";
            case 92:
                return "DirectReplyModalFragment.response_string";
            case 93:
                return "DirectShareSheetConstants.shops_collection_info";
            case 94:
                return "DirectThreadMemberPickFragment.THREAD_MEMBER";
            case 95:
                return "EditMediaFragment.ARGUMENT_MEDIA_CAROUSEL_INDEX";
            case 96:
                return "EditMediaFragment.ARGUMENT_MEDIA_ID";
            case 97:
                return "ExplorePeopleFragment.ARGUMENT_PUSH_ID";
            case 98:
                return "Failed to convert a collection to json";
            case 99:
                return "NOT_ENABLED";
            case 100:
                return "RTC_CALL_CONDITION";
            case 101:
                return "Story ring should not be accessible here.";
            case 102:
                return "Success(data=";
            case 103:
                return NJY.__redex_internal_original_name;
            case 104:
                return "ai_bot_search_plugin";
            case 105:
                return "ai_voice_selection";
            case 106:
                return "allow_reshare";
            case 107:
                return "arg_target_username";
            case 108:
                return "barcelona_is_golden_ticket_reminder_enabled";
            case 109:
                return "business_id";
            case 110:
                return "caller_id";
            case 111:
                return "client_context_id";
            case 112:
                return "client_timestamp_ms";
            case 113:
                return "component_id";
            case 114:
                return "condensed_megaphone";
            case 115:
                return "creator_ai_add_fact_message_igid_extra";
            case 116:
                return "creator_ai_add_fact_question_extra";
            case 117:
                return "creator_invite_link_details";
            case 118:
                return "cursor_thread_id";
            case 119:
                return "cursor_timestamp_milliseconds";
            case 120:
                return "direct_card_gallery";
            case 121:
                return "direct_edit_quick_reply";
            case 122:
                return "direct_nux_impression";
            case 123:
                return "direct_poll_message_details";
            case 124:
                return "direct_reply_to_story_commenter";
            case 125:
                return "disappearing_mode_upgrade_from_vanish_mode_swipe_up";
            case 126:
                return "display_variant";
            case 127:
                return "emoji_pong_high_score";
            case 128:
                return "fan_invite_link_details";
            case 129:
                return "feed_ufi";
            case 130:
                return "feedback_type";
            case 131:
                return "https://help.instagram.com/192435014247952?ref=igapp";
            case 132:
                return "ig_followers";
            case 133:
                return "ig_professional_identity_cache_id";
            case 134:
                return "ig_username";
            case 135:
                return "igd_channels_client_actions";
            case 136:
                return "igd_universal_search:ai_nullstate_donut";
            case 137:
                return "include_consumer_status";
            case 138:
                return "is_confirmed";
            case 139:
                return "is_follower";
            case 140:
                return "is_group_thread";
            case 141:
                return "is_vm_active";
            case 142:
                return "mentioned_user";
            case 143:
                return "message_sent";
            case 144:
                return "not_activity_or_fragment";
            case 145:
                return "null cannot be cast to non-null type android.graphics.drawable.BitmapDrawable";
            case 146:
                return "null cannot be cast to non-null type androidx.lifecycle.LifecycleOwner";
            case 147:
                return "null cannot be cast to non-null type com.instagram.igds.components.button.IgdsButton";
            case 148:
                return "null cannot be cast to non-null type com.instagram.ui.widget.emojigrid.EmojiGridRowItemViewBinder.Holder";
            case 149:
                return "onGifItemSelected(Lcom/instagram/api/schemas/CommentGiphyMediaInfo;)V";
            case 150:
                return "opt_in_status";
            case 151:
                return "partial";
            case 152:
                return "people_you_follow";
            case 153:
                return "previously_joined";
            case 154:
                return "profile_picture";
            case 155:
                return "reminder_toast";
            case 156:
                return "reply_modal";
            case 157:
                return "reshare";
            case 158:
                return "result_count";
            case 159:
                return "result_type";
            case 160:
                return "runtime_params";
            case 161:
                return "secondary_text_color";
            case 162:
                return "section_type";
            case 163:
                return "selected_shipping_option";
            case 164:
                return "selected_user_id";
            case 165:
                return "server_results";
            case 166:
                return "setApi must be called";
            case 167:
                return "shared_secret";
            case 168:
                return "stories_sticker_tray";
            case 169:
                return "student_email";
            case C11152SCh.MAX_FACTORIAL:
                return DevServerEntity.COLUMN_SUPPORTS_VPNLESS;
            case 171:
                return "suppress_reason";
            case 172:
                return "surface_type";
            case 173:
                return "text_language";
            case 174:
                return "universal_link";
            case 175:
                return "unknown error";
            case 176:
                return "unregistered";
            case 177:
                return "unsend_warning_banner_enabled_for_thread_v2/";
            case 178:
                return "users_count";
            case 179:
                return "variant_value";
            case 180:
                return "video/x-matroska";
            case 181:
                return "whatsapp";
            case 182:
                return "xdt_api__v1__devservers__list";
            case 183:
                return "zero_rating_live_nux_count";
            case 184:
                return "\n            ";
            case 185:
                return ", audience=";
            case 186:
                return ", code=";
            case 187:
                return ", content=";
            case 188:
                return ", error: ";
            case 189:
                return ", gridLayoutStrategy=";
            case 190:
                return ", igThreadId=";
            case 191:
                return ", startTime=";
            case 192:
                return ", title=";
            case 193:
                return ", width=";
            case 194:
                return ",acceptRemoteVideoEnabled=";
            case 195:
                return ",content=";
            case 196:
                return ",initialDataMessages=";
            case 197:
                return "APPIRATER_DECLINED_TO_RATE";
            case 198:
                return "APPIRATER_RATED_CURRENT_VERSION";
            case 199:
                return "ARGUEMENT_THEME";
            case 200:
                return "ARGUMENT_PREVIEW_TYPE";
            case 201:
                return "ARGUMENT_UPLOAD_ID";
            case 202:
                return "AdsEventSharingSettingsQuery";
            case 203:
                return "Algorithm kdf does not exist for value";
            case 204:
                return "AudioFocusManager";
            case 205:
                return "BUNDLE_SCREEN";
            case 206:
                return "BugReporterActivity.INTENT_EXTRA_VIEWMODEL";
            case 207:
                return "CLOSE_CLIPS_RIGHT_PANEL_FRAGMENT";
            case 208:
                return PayButtonCTAType$Companion.CONTINUE;
            case 209:
                return "CRITICAL";
            case 210:
                return "CURRENT_LOCATION_UPDATED";
            case 211:
                return "ChannelDiscoverySuggestionsFragment.ARG_SHOW_INVITES_SECTION";
            case 212:
                return "ClickToMessagingOnFeedBottomSheetFragment.ad_id";
            case 213:
                return "ClipsConstants.ARG_SHOULD_CLOSE_CAMERA_ON_EXIT_SOUNDSYNC";
            case 214:
                return NJ3.__redex_internal_original_name;
            case 215:
                return "DETAILS";
            case 216:
                return "DIRECT_THREAD_ANALYTICS_PARAMS_KEY";
            case 217:
                return NJZ.__redex_internal_original_name;
            case 218:
                return "DirectFragment.DIRECT_FRAGMENT_ARGUMENT_ON_DIRECT_SEND_SUCCESS_EXIT_BOUNDS";
            case 219:
                return "DirectMultipleReactionMessagePillsViewHolder";
            case 220:
                return "DirectReplyModalFragment.comment_id";
            case 221:
                return "DirectReplyModalFragment.custom_module_name";
            case 222:
                return "DirectReplyModalFragment.entry_point";
            case 223:
                return "DirectReplyModalFragment.pending_layered_xma";
            case 224:
                return "DirectReplyModalFragment.user_id_to_send_message_to";
            case 225:
                return "DirectShareSheetConstants.reels_audio_asset_id";
            case 226:
                return "DirectShareSheetConstants.reels_audio_asset_subtitle";
            case 227:
                return "DirectShareSheetConstants.reels_audio_asset_title";
            case 228:
                return "DirectShareSheetConstants.shops_share_info";
            case 229:
                return "DirectThreadFragment.ARGUMENT_PRIVATE_REPLY_SENT";
            case 230:
                return "DirectThreadFragment.DIRECT_NOTIFICATION_IMPROVED_EXPERIENCE_ENABLED";
            case 231:
                return "DirectVisualReplyFragment.ARG_REPLY_REEL_CURRENT_ITEM_INDEX";
            case 232:
                return "DirectVisualReplyFragment.ARG_REPLY_REEL_ID";
            case 233:
                return "EditMediaFragment.ARGUMENT_MEDIA_IS_CAROUSEL_BUMPED_POST";
            case 234:
                return "EditMediaFragment.ARGUMENT_MEDIA_POSITION_IN_FEED";
            case 235:
                return "EditMediaFragment.ARGUMENT_MEDIA_TYPE";
            case 236:
                return "Error saving sticker";
            case 237:
                return "GENAI_REMINDER";
            case 238:
                return "GENAI_SUBSCRIPTION";
            case 239:
                return "IS_ELIGIBLE_FOR_LOGGING_KEY";
            case 240:
                return "IgBloksCustomNavigationExtensions";
            case 241:
                return "InstagramContactHelper";
            case 242:
                return "Invalid mode: ";
            case 243:
                return "JsonException";
            case 244:
                return "Key retrieved from keystore is not an ECPrivateKey";
            case 245:
                return "Key retrieved from keystore is not an ECPublicKey";
            case 246:
                return "MAGIC_MEDIA_REMIX_TEMPLATE";
            case 247:
                return "MailboxInstagramReverb";
            case 248:
                return "MsysMultiInstancesBackgroundUserSessionOperationPayload";
            case 249:
                return "ODNC_ENTRY_POINT_KEY";
            case C355538Qj.DEFAULT_SWIPE_ANIMATION_DURATION:
                return "RECENTS";
            case 251:
                return "SHARE_TO_STORY_LONG_PRESS_ACTION";
            case 252:
                return "SecurityAlertLocalDataSource";
            case 253:
                return "The view is not a child of CoordinatorLayout";
            case 254:
                return "Unable to decode image";
            case 255:
                return "XFBVestaInitIqResponseV2";
            case 256:
                return "_display_name";
            case 257:
                return "accepted";
            case 258:
                return "action_menu";
            case 259:
                return "add_collaborators_sheet_rendered";
            case 260:
                return "add_group_member";
            case 261:
                return "ai_agent_direct_share_sheet";
            case 262:
                return "autocomplete_account_type";
            case 263:
                return "back_stack";
            case 264:
                return "bottom_sheet_impression";
            case 265:
                return "call_to_action";
            case 266:
                return "callerId";
            case 267:
                return "card_type";
            case 268:
                return "change_password_entrypoint";
            case 269:
                return "channel_challenge_share_xma";
            case 270:
                return "channel_creation_entry_from_chooser";
            case 271:
                return "channel_link_sticker";
            case 272:
                return "channel_name";
            case 273:
                return "client_timestamp";
            case 274:
                return "clips_cta";
            case 275:
                return "com.bloks.www.instagram.partnership_messages.settings";
            case 276:
                return "com.bloks.www.services.ig.appointment.customer";
            case 277:
                return "com.facebook.mqtt.service.ipc.IMqttPublishListener";
            case 278:
                return "com.google.android.gms.auth.blockstore.DEFAULT_BYTES_DATA_KEY";
            case 279:
                return "combined_config_hash";
            case 280:
                return "comments_sheet_rendered";
            case 281:
                return "create_button";
            case 282:
                return "creator_ai_add_fact_answer_extra";
            case 283:
                return "creator_ai_add_fact_message_otid_extra";
            case 284:
                return "creator_ai_add_fact_thread_igid_extra";
            case 285:
                return "creator_ai_embodiment_captions_enabled";
            case 286:
                return "cta_url";
            case 287:
                return "current_face_effect_id";
            case 288:
                return "current_watching_module";
            case 289:
                return "daily_prompt_responses_sheet";
            case 290:
                return "delete_button";
            case 291:
                return "direct_daily_prompts_add_response";
            case 292:
                return "direct_effect_preview_video";
            case 293:
                return "direct_expiring_media_create_group_failed";
            case 294:
                return "direct_inbox_channel_discovery_suggestions";
            case 295:
                return "direct_inbox_setting_entrypoint";
            case 296:
                return "direct_message_options";
            case 297:
                return "direct_message_professional_notification_status";
            case 298:
                return "direct_message_search_message_list_fragment";
            case 299:
                return "direct_privacy_text";
            case 300:
                return "direct_reply_to_author";
            case 301:
                return "direct_share_photo_failure";
            case 302:
                return "direct_thread_action";
            case 303:
                return "direct_thread_link_impression";
            case 304:
                return "direct_v2_reel_mention";
            case 305:
                return "disappearing_mode_expiry_duration_change_action_log";
            case 306:
                return "disappearing_mode_on_client_admin_message";
            case 307:
                return "disappearing_mode_rollback_action_log";
            case 308:
                return "disappearing_mode_toggle_off_action_log";
            case 309:
                return RealtimeConstants.MQTT_DISCONNECTED;
            case 310:
                return "display_body";
            case 311:
                return "eligible_pending_opt_in";
            case 312:
                return "encrypted_backups_screen";
            case 313:
                return "ephemeral_view_duration_sec";
            case 314:
                return "event_step";
            case 315:
                return "external_link_thread_session_entry_point";
            case 316:
                return "failed_to_load_photo_toast";
            case 317:
                return "favorite";
            case 318:
                return "fb_auth_token";
            case 319:
                return "fetch_type";
            case 320:
                return "followers";
            case 321:
                return "friend_map_last_seen_timestamp";
            case 322:
                return "gif_media_id";
            case 323:
                return "has_seen_multi_modal_ai_nux";
            case 324:
                return "https://help.instagram.com/1992818607740142";
            case 325:
                return "https://help.instagram.com/219914557612468";
            case 326:
                return "https://www.facebook.com/help/instagram/475931443650619";
            case 327:
                return "https://www.instagram.com/";
            case 328:
                return "https://www.instagram.com/ar/";
            case 329:
                return "ig_branded_threads_session_user_info";
            case 330:
                return "ig_generated_content";
            case 331:
                return "ig_its_inappropriate_v1";
            case 332:
                return "ig_post_id";
            case 333:
                return "ig_select_video_nux";
            case 334:
                return "igd_universal_search:ai_typeahead";
            case 335:
                return "ignore_business_opt_in_status";
            case 336:
                return "image_type";
            case 337:
                return "inbox_new_broadcast_chat";
            case 338:
                return "include_e2ee_mentioned_user_list";
            case 339:
                return "inform_module_resource";
            case 340:
                return "instagram://details/toggle_disappearing_messages?active=true";
            case 341:
                return "interaction_type";
            case 342:
                return DevServerEntity.TABLE_NAME;
            case 343:
                return "is_admin";
            case 344:
                return "is_contact_security_alert_enabled";
            case 345:
                return "is_current";
            case 346:
                return "last_session_survey_notification_seen_timestamp_ms";
            case 347:
                return "learn_more";
            case 348:
                return "link_preview";
            case 349:
                return "logging_step";
            case 350:
                return "login_success";
            case 351:
                return "map_query";
            case 352:
                return "maps_perf_logger_on_pause";
            case 353:
                return "media_gallery_logging_step_with_no_flow_id";
            case 354:
                return "member_participation_hub_cta_button";
            case 355:
                return "mentioned_user_id";
            case 356:
                return "menu_ui";
            case 357:
                return "message_client_context_id";
            case 358:
                return "message_reactions";
            case 359:
                return "message_thread";
            case 360:
                return "mounted_ro";
            case 361:
                return "music_overlay_sticker_artist";
            case 362:
                return "mutation";
            case 363:
                return "need_update";
            case 364:
                return "network_request_start";
            case 365:
                return "nonmentionable";
            case 366:
                return "not_supported";
            case 367:
                return "notes_song_title";
            case 368:
                return "notice_type";
            case 369:
                return "null cannot be cast to non-null type android.graphics.drawable.AnimationDrawable";
            case 370:
                return "null cannot be cast to non-null type com.instagram.common.ui.widget.touchinterceptorlayout.TouchInterceptorFrameLayout";
            case 371:
                return "null cannot be cast to non-null type com.instagram.migration.scrollingviewproxy.RefreshableScrollingViewProxy<@[FlexibleNullability] @[RawType] com.instagram.migration.scrollingviewproxy.ScrollingViewAdapterProxy<@[FlexibleNullability] kotlin.Any?>?>";
            case 372:
                return "null cannot be cast to non-null type com.instagram.model.direct.DirectShareTarget";
            case 373:
                return "null cannot be cast to non-null type com.instagram.model.direct.DirectThreadId";
            case 374:
                return "null cannot be cast to non-null type com.instagram.model.direct.threadkey.impl.MsysThreadTarget";
            case 375:
                return "null cannot be cast to non-null type com.instagram.model.hashtag.Hashtag";
            case 376:
                return "null cannot be cast to non-null type java.util.HashMap<*, *>";
            case 377:
                return "others_on_ig";
            case 378:
                return "page_token";
            case 379:
                return "playlist_id";
            case 380:
                return "private_reply_message";
            case 381:
                return "publish_story_with_message";
            case 382:
                return "reachability_settings_upsell";
            case 383:
                return "recs_from_friends_receiver";
            case 384:
                return "recs_from_friends_sender";
            case 385:
                return "reel_index";
            case 386:
                return "reels_max_id";
            case 387:
                return "replyActionSource";
            case 388:
                return "secondary_button";
            case 389:
                return "selected_audio_track";
            case 390:
                return "should_badge_channel";
            case 391:
                return "should_present_peer_device_change_security_alert";
            case 392:
                return "should_present_security_alert";
            case 393:
                return "should_skip_extra_data";
            case 394:
                return "show_direct_admin_remove_message_warning_dialog";
            case 395:
                return "sticker_tray";
            case 396:
                return "stories_viewers";
            case 397:
                return "story_id";
            case 398:
                return "story_quiz_answer_list";
            case 399:
                return "story_slider_answer_list";
            case ScreenCapturerAndroid.VIRTUAL_DISPLAY_DPI:
                return "story_user_tag_page";
            case 401:
                return "target_thread_id";
            case 402:
                return "test_object_id";
            case 403:
                return "thread_details_link";
            case 404:
                return "thread_open";
            case 405:
                return "tracking_type";
            case 406:
                return "trending_tab_category";
            case 407:
                return "unhide_comment_click";
            case 408:
                return "vanish_mode_upgrade_to_disappearing_mode_action_log";
            case 409:
                return "violation_type";
            case 410:
                return "website_cta";
            case 411:
                return "xdt_api__v1__devservers__list_categorized";
            case 412:
                return "xdt_theme_preview(theme_id:$theme_id)";
            case 413:
                return "xdt_unshare_all_highlights_from_main_grid";
            case 414:
                return "xfb_biig_ads_event_sharing_settings";
            case 415:
                return "xfb_delete_thread_subscriptions(data:{\"client_mutation_id\":$client_mutation_id,\"subscription_ids\":$subscription_ids})";
            case 416:
                return "xig_meta_ai_voice_ig_user_setting_fetch";
            case 417:
                return "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001ဈ\u0000\u0002ဈ\u0001";
            case 418:
                return " errorMessage=";
            case 419:
                return " notification";
            case 420:
                return " with source ";
            case 421:
                return ", attributes=";
            case 422:
                return ", avatarUrl=";
            case 423:
                return ", callTarget=";
            case 424:
                return ", coWatchArguments=";
            case 425:
                return ", contentId=";
            case 426:
                return ", createdAt=";
            case 427:
                return ", creatorUsername=";
            case 428:
                return ", e2eeCallType=";
            case 429:
                return ", e2eeInfraOnlyExpGroup=";
            case 430:
                return ", error message: ";
            case 431:
                return ", expirationTime=";
            case 432:
                return ", gestureDetectionModel=";
            case 433:
                return ", isAudioCall=";
            case 434:
                return ", isGroupCall=";
            case 435:
                return ", isPending=";
            case 436:
                return ", mCoordinate=";
            case 437:
                return ", mLayoutFromEnd=";
            case 438:
                return ", mediaCount=";
            case 439:
                return ", merchantUsername=";
            case 440:
                return ", periodValue=";
            case 441:
                return ", productName=";
            case 442:
                return ", recipientUserId=";
            case 443:
                return ", showVerifiedBadge=";
            case 444:
                return ", systemBottomInset=";
            case 445:
                return ", threadSubtype=";
            case 446:
                return ", timestamp=";
            case 447:
                return ", waterfallId: ";
            case 448:
                return ",actionType=";
            case 449:
                return ",adminMessage=";
            case 450:
                return ",contentType=";
            case 451:
                return ",drawable (no bitmap info):";
            case 452:
                return ",inviteRequestedVideo=";
            case 453:
                return ",mediaPositionMs=";
            case 454:
                return ",remoteEnded=";
            case 455:
                return ",sharedCallId=";
            case 456:
                return ",streamState=";
            case 457:
                return ",streamType=";
            case 458:
                return ",thumbnailUrl=";
            case 459:
                return "/fbns_msg_hp";
            case 460:
                return "/fbns_reg_req";
            case 461:
                return "/push_notification";
            case 462:
                return "/send_message_response";
            case 463:
                return RealtimeConstants.MQTT_TOPIC_RTC_MULTI;
            case 464:
                return "2220597908338813";
            case 465:
                return ":discountsPromoLabel";
            case 466:
                return "ADULT_MINOR_GROUP_RESTRICTION";
            case 467:
                return "AFFILIATE_LINKS";
            case 468:
                return "ARG_LIST_CARD_USERS";
            case 469:
                return "ARG_START_POSITION";
            case 470:
                return "AUDIO_CLUSTER_ID";
            case 471:
                return "AUTHOR_PROFILE_PIC";
            case 472:
                return "AUTHOR_USERNAME";
            case 473:
                return "AiAgentSearchSourcesFragment.arg_agent_id";
            case 474:
                return "AiAgentSearchSourcesFragment.arg_bot_response_id";
            case 475:
                return "AiAgentSearchSourcesFragment.arg_sources_url";
            case 476:
                return "AiAgentSearchSourcesFragment.is_v2_design";
            case 477:
                return "AiAgentUpsellInterstitialFragment";
            case 478:
                return "Algorithm aead does not exist for value";
            case 479:
                return "Algorithm mode does not exist for value";
            case 480:
                return "AnchorInfo{mPosition=";
            case 481:
                return "ArmadilloExpressMessageFetcherV2";
            case 482:
                return "ArmadilloExpressSnapshotInterceptManager";
            case 483:
                return "BUNDLE_WAS_TABLE_DROPPED";
            case 484:
                return "BroadcastChannelActivityFeedV2Fragment.ARGUMENT_FETCH_MODE";
            case 485:
                return "BrowserLiteIntent.EXTRA_AUTOFILL_REQUEST_AUTOFILL_JS_BRIDGE_CALL";
            case 486:
                return "BugReporterActivity.INTENT_EXTRA_BUGREPORT";
            case 487:
                return "BugReporterActivity.INTENT_UPLOAD_FAILED";
            case 488:
                return "BugReporterUploader";
            case 489:
                return "CHECKING_HEALTH";
            case 490:
                return "COLLABORATOR";
            case 491:
                return "COLLECTION_ITEM";
            case 492:
                return "Cannot execute task: the task has already been executed (a task can be executed only once)";
            case 493:
                return "Cannot execute task: the task is already running.";
            case 494:
                return "Cannot get random in empty range: ";
            case 495:
                return "CdlLiveEditingPlayer";
            case 496:
                return NVN.__redex_internal_original_name;
            case 497:
                return "ClipsConstants.ARG_CLIPS_COLLABORATORS";
            case 498:
                return "Connectivity probe succeeded: %d.";
            case 499:
                return "DESTROY_ALE_HOLDER";
            case CameraCapturer.OPEN_CAMERA_DELAY_MS:
                return "DESTROY_CDL_HOLDER";
            case 501:
                return "DIRECT_SEARCH_INBOX_FRAGMENT";
            case 502:
                return "DataSource is already opened";
            case 503:
                return "DataSource is not opened";
            case 504:
                return "DirectConversationStarterCameraFragment.ARG_INBOX_ENTRY_POINT";
            case 505:
                return "DirectFragment.DIRECT_FRAGMENT_ARGUMENT_CAMPAIGN_MESSAGE_KEY";
            case 506:
                return "DirectFragment.DIRECT_FRAGMENT_ARGUMENT_IS_MSYS_ENABLED";
            case 507:
                return "DirectInboxFragment.DIRECT_MESSAGE_REQUEST_INBOX_INITIAL_LOAD_COMPLETE_KEY";
            case 508:
                return "DirectInboxFragment.DIRECT_MESSAGE_REQUEST_INBOX_LAUNCH_HIDDEN_FOLDER_KEY";
            case 509:
                return "DirectInboxFragment.DIRECT_MESSAGE_REQUEST_RESULT_REFRESH_INBOX";
            case 510:
                return "DirectPaidPartnershipSettingsFragment.ARGUMENT_CLIENT_CONTEXT";
            case 511:
                return "DirectPaidPartnershipSettingsFragment.ARGUMENT_MESSAGE_ID";
            case 512:
                return "DirectPaidPartnershipSettingsFragment.ARGUMENT_THREAD_ID";
            case 513:
                return "DirectPollMessageDetailsFragment_is_msys";
            case 514:
                return "DirectPollMessageDetailsFragment_poll_id";
            case 515:
                return "DirectPollMessageDetailsFragment_thread_key";
            case 516:
                return "DirectQuickReplyCameraFragment.REPLY_CAM_ARG_CAMERA_AR_EFFECT_ID";
            case 517:
                return "DirectQuickReplyCameraFragment.REPLY_CAM_ARG_CAMERA_INITIAL_CANVAS_ELEMENT";
            case 518:
                return "DirectQuickReplyCameraFragment.REPLY_CAM_ARG_CAMERA_INIT_CONFIG";
            case 519:
                return "DirectReplyCameraFragments.ARG_REPLY_SEND_ATTRIBUTION";
            case 520:
                return "DirectReplyCameraFragments.ARG_REPLY_THUMBNAIL_ENABLED";
            case 521:
                return "DirectReplyCameraFragments.REPLY_CAM_ARG_INSERT_RAVEN_MEDIA_IN_COMPOSER";
            case 522:
                return "DirectReplyModalFragment.avatar_reaction_url";
            case 523:
                return "DirectReplyModalFragment.emoji_reaction_unicode";
            case 524:
                return "DirectReplyModalFragment.has_story_like";
            case 525:
                return "DirectReplyModalFragment.message_recipient_user_id";
            case 526:
                return "DirectReplyModalFragment.poll_vote";
            case 527:
                return "DirectReplyModalFragment.private_reply_info";
            case 528:
                return "DirectReplyModalFragment.question_response_type";
            case 529:
                return "DirectReplyModalFragment.quiz_vote";
            case 530:
                return "DirectReplyModalFragment.send_attribution_postfix";
            case 531:
                return "DirectReplyModalFragment.slider_vote";
            case 532:
                return "DirectReplyModalFragment.story_reply_text";
            case 533:
                return "DirectShareSheetConstants.channel_challenge";
            case 534:
                return "DirectShareSheetConstants.daily_prompt";
            case 535:
                return "DirectShareSheetConstants.message_share_sticker_data";
            case 536:
                return "DirectShareSheetConstants.rooms_xma";
            case 537:
                return "DirectShareSheetConstants.shared_animated_media";
            case 538:
                return "DirectThreadFragment.DIRECT_THREAD_FRAGMENT_ARGUMENT_IS_FROM_DIRECT_PUSH";
            case 539:
                return "DirectThreadFragment.DIRECT_THREAD_FRAGMENT_RESULT_JOINED_OR_DECLINED_CHANNEL_THREAD_ID";
            case 540:
                return "DirectThreadFragment.DIRECT_THREAD_FRAGMENT_RESULT_READ_CHANNEL_THREAD_ID";
            case 541:
                return C71872OsF.__redex_internal_original_name;
            case 542:
                return "DirectThreadSharedMediaFragment.DIRECT_MEDIA_REPLY_ELIGIBILITY_CHECKER";
            case 543:
                return "DirectThreadStore";
            case 544:
                return "DirectThreadToggleController";
            case 545:
                return "DirectVisualReplyFragment.REPLY_CAM_ARG_SKIP_ENTRY_ANIMATION";
            case 546:
                return "DirectVisualTimelineEnabled.REPLY_CAM_ARG_IS_VISUAL_TIMELINE_ENABLED";
            case 547:
                return "EB_DEVICE_ONBOARDED";
            case 548:
                return "EB_FIRST_RESTORE_ATTEMPT_TIMESTAMP_MS";
            case 549:
                return "EMPTY_DEVICE_ID";
            case 550:
                return "ERROR_IN_FETCH";
            case 551:
                return "EXTRA_AUTH_REQUEST";
            case 552:
                return "EXTRA_AUTH_RESPONSE";
            case 553:
                return "EditMediaFragment.ARGUMENT_CHANNEL_TO_TAG_INFO";
            case 554:
                return "EditMediaFragment.ARGUMENT_IS_FROM_BOOST_EDITABLE_CAPTION";
            case 555:
                return "EditMediaFragment.ARGUMENT_IS_MESSAGING_ADS_SELECTED";
            case 556:
                return "Entry should exist before function call.";
            case 557:
                return "Error parsing ciphersuite string: ";
            case 558:
                return "Exception: %s";
            case 559:
                return "Expected DirectThreadKey or MsysThreadId: ";
            case 560:
                return "FACEBOOK_WATCH";
            case 561:
                return "FETCH_BACKUP_STATUS_ERROR";
            case 562:
                return "FETCH_BACKUP_STATUS_GRAPHQL_REQUEST_FAIL";
            case 563:
                return "Failed to fetch messages from EB";
            case 564:
                return "Failed to get contacts from server";
            case 565:
                return "Failed to register callback";
            case 566:
                return "Failed to rename ";
            case 567:
                return "Failure in view hierarchy dump: ";
            case 568:
                return "Fragment Context is null!";
            case 569:
                return "GroupPreviewFragment.INVITE_LINK_SOURCE_KEY";
            case 570:
                return "GroupPreviewFragment.SC_INVITE_ID";
            case 571:
                return "Header icons size was larger than expected";
            case 572:
                return "Http Request Failed";
            case 573:
                return "IG_CREATOR_AGENT_GENERATIVE_AI_BOT";
            case 574:
                return "IG_TAS_SCREEN_IN_THREAD_LIST";
            case 575:
                return "INBOX_NOTES_TRAY";
            case 576:
                return "IgMailbox.get";
            case 577:
                return "Inconsistency detected. Invalid item position ";
            case 578:
                return "Interrupted while tearing down background account instance on account switch";
            case 579:
                return "Interrupted while waiting for media file download";
            case 580:
                return "Invalid icon";
            case 581:
                return "Invalid transition from ";
            case 582:
                return "MAIN_FEED_ACTION_BAR";
            case 583:
                return "MCAMailboxAdvancedCryptoTransport";
            case 584:
                return "MEBHandleProtobufBackupWriteResultNotification";
            case 585:
                return "Manufacturer";
            case 586:
                return "Missing required params";
            case 587:
                return "NOTES_CREATION_NUX_SHOWN";
            case 588:
                return "No external inserts";
            case 589:
                return "No external updates";
            case 590:
                return "NotesRepository";
            case 591:
                return "OPTIMISTIC_PRESENCE_ID";
            case 592:
                return "Operation failed";
            case 593:
                return "PURCHASE_FAILURE";
            case 594:
                return "Point provided does not conform to P256 coordinate size";
            case 595:
                return "Prediction failed with exception: ";
            case 596:
                return E5O.__redex_internal_original_name;
            case 597:
                return C48014ERb.__redex_internal_original_name;
            case 598:
                return "RealtimePresenceDataProvider";
            case 599:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_ENTRY_POINT";
            case 600:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_MEDIA_FILE_PATH";
            case 601:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_MEDIA_FILE_TYPE";
            case 602:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_MESSAGE_ID";
            case 603:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_PRESET_MEDIUM_FILE_PATH";
            case 604:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_PRESET_MEDIUM_IS_VIDEO";
            case 605:
                return "ReelDirectVisualMessageShareCameraFragment.ARGUMENTS_KEY_SENDER_ID";
            case 606:
                return "ReportingConstants.ARG_IS_CONSOLIDATED_IMPERSONATION_REPORTING";
            case 607:
                return "Resource ID #0x";
            case 608:
                return "RpStore.subscribe";
            case 609:
                return "RtcCallAnalyticsManager";
            case 610:
                return "SAVED_COLLECTIONS";
            case 611:
                return "Saved Tab Providers should have position within";
            case 612:
                return "ScreenTimeInit";
            case 613:
                return "Seen duplicate model key for class ";
            case 614:
                return "SerpChildViewModel";
            case 615:
                return "Skip one contact serialization due to error";
            case 616:
                return "StoryTemplateDiscoverySurfaceVideoPlayer";
            case 617:
                return "SubscriptionManager.registerClassLevelSubscription";
            case 618:
                return "SwitchAccount";
            case 619:
                return "SyncCompletion";
            case 620:
                return "SyncTriggerFrom";
            case 621:
                return "TextureViewRenderer";
            case 622:
                return "The dialog option index ";
            case 623:
                return "ThreadKey is null";
            case 624:
                return "Trying to update when capture is not initialized, this could happen if you try to update before a capture";
            case 625:
                return "Unable to log because delegate was null";
            case 626:
                return "Unable to parse photo uri.";
            case 627:
                return "Unexpected parcel contents";
            case 628:
                return "Unknown entry point type ";
            case 629:
                return "Unknown media type";
            case 630:
                return "Unsupported key length: ";
            case 631:
                return "Unsupported media type";
            case 632:
                return "Unsupported relative time period";
            case 633:
                return "VIEW_INSIGHTS";
            case 634:
                return "XFBGenAISearchViewModel";
            case 635:
                return "XFBVestaBeginLoginResponseV2";
            case 636:
                return "XFBVestaBeginRegisterResponseV2";
            case 637:
                return "XFBVestaFinishLoginResponseV2";
            case 638:
                return "XFBVestaFinishRegisterResponseV2";
            case 639:
                return "active_notif_count";
            case 640:
                return "add_incentive";
            case 641:
                return "add_moderator_button";
            case 642:
                return "add_moderators_sheet_rendered";
            case 643:
                return "add_shipping_info";
            case 644:
                return "add_yours_templates_discovery_surface_find_it_first";
            case 645:
                return "add_yours_templates_discovery_surface_hot_right_now";
            case 646:
                return "add_yours_templates_discovery_surface_international_hits";
            case 647:
                return "additional_params";
            case 648:
                return "admin_message";
            case 649:
                return "after_view_lifetime_ms";
            case 650:
                return "agent_response";
            case 651:
                return "agent_search";
            case 652:
                return "ai_bot_quick_reply_payload";
            case 653:
                return "ai_subscription_all";
            case 654:
                return "ai_subscription_item";
            case 655:
                return "ai_subscription_product_type";
            case 656:
                return "ai_subscription_subscription_id";
            case 657:
                return "ai_subscription_title";
            case 658:
                return "already bound";
            case 659:
                return "android.bigText";
            case 660:
                return "android.permission.BLUETOOTH_CONNECT";
            case 661:
                return "android.picture";
            case 662:
                return "android.pictureIcon";
            case 663:
                return "android.title";
            case 664:
                return "app_foregrounded";
            case 665:
                return "application/gzip";
            case 666:
                return "applied_incentives";
            case 667:
                return "arg_is_launched_from_bottomsheet";
            case 668:
                return "arg_meta_ai_share_target";
            case 669:
                return "arg_music_to_display";
            case 670:
                return "attachment_type";
            case 671:
                return "attempted_toggle_value";
            case 672:
                return "attribute_section";
            case 673:
                return "attribution_sdk:GraphQLAttributionEventComplianceActionProvider";
            case 674:
                return "attribution_user_name";
            case 675:
                return "auto_reply_selected_users";
            case 676:
                return "available_space";
            case 677:
                return "avatar_stickers_measurement_typeahead_click";
            case 678:
                return "back_press_key";
            case 679:
                return "backup_state";
            case 680:
                return "base64url_encoded_login_payload";
            case 681:
                return "base64url_encoded_opaque_challenge";
            case 682:
                return "base64url_encoded_opaque_l2";
            case 683:
                return "base64url_encoded_opaque_l2_sig";
            case 684:
                return "base64url_encoded_opaque_r2";
            case 685:
                return "base64url_encoded_opaque_r2_sig";
            case 686:
                return "blackhole_url_deltas";
            case 687:
                return "blend_direct_inbox_nux_seen_count";
            case 688:
                return "broadcast_channel_challenges_nux";
            case 689:
                return "broadcast_chat_add_collaborator_nux/";
            case 690:
                return "bulk_replace_messages";
            case 691:
                return "bundle_thread_id";
            case 692:
                return "bussiness_sayt_list";
            case 693:
                return "bypass_cache";
            case 694:
                return DevServerEntity.COLUMN_CACHE_TIMESTAMP;
            case 695:
                return "camera_product_item_with_ar";
            case 696:
                return "category cannot contain delimiter";
            case 697:
                return "challenge_button";
            case 698:
                return "challenge_pill";
            case 699:
                return "challenge_share_sheet_rendered";
            case 700:
                return "challenge_status";
            case 701:
                return "challenge_submission";
            case 702:
                return "change_password_login_id";
            case 703:
                return "channel_daily_prompt_responses";
            case 704:
                return "channel_inbox_directory_nux_seen_count";
            case 705:
                return "channel_invite_item";
            case 706:
                return "channel_invites_shown_success";
            case 707:
                return "channel_suggestion_item";
            case 708:
                return "channel_thread_key";
            case 709:
                return "channels_directory_info";
            case 710:
                return "channels_suggested_success";
            case 711:
                return "client_generated_id";
            case 712:
                return "client_sample_rate";
            case 713:
                return "client_submit_ecppaymentcontainer_fail";
            case 714:
                return "clips_blend_reply_direct";
            case 715:
                return "cloud_service_account";
            case 716:
                return "collapsed_sr";
            case 717:
                return "collections/list/";
            case 718:
                return "com.bloks.www.biig.tas.label.selection";
            case 719:
                return "com.bloks.www.ig.bonus.bonus-progress-tracking";
            case 720:
                return "com.bloks.www.igca.partnership.inapp.optin.flow";
            case 721:
                return "com.bloks.www.messenger.aibot.feedback_controller";
            case 722:
                return "com.bloks.www.messenger.aibot.good_feedback_submit_controller";
            case 723:
                return "com.facebook.fbwebrtc.multiway.HangupRequest";
            case 724:
                return "com.facebook.rti.fbns.intent.RECEIVE";
            case 725:
                return "com.instagram.android.igns.logging.push_category";
            case 726:
                return "com.instagram.android.igns.logging.push_id";
            case 727:
                return "com.meta.ai.notify.ACTION_DOWNLOAD_COMPLETE";
            case 728:
                return "com\\.instagram\\.android\\.";
            case 729:
                return "comment_create";
            case 730:
                return "comment_custom_filter";
            case 731:
                return "comment_reporting_self_remediation_bottom_sheet";
            case 732:
                return "component_position";
            case 733:
                return "component_subtype";
            case 734:
                return "container_effect_config_id";
            case 735:
                return "context_menu";
            case 736:
                return "contextual_upsell_tap";
            case 737:
                return "cover_artwork_uri";
            case 738:
                return "cpu_kernel_time";
            case 739:
                return "cpu_user_time";
            case 740:
                return "creation_enabled";
            case 741:
                return "creator_ai_audience_control_id";
            case 742:
                return "creator_ai_creator_fbid";
            case 743:
                return "creator_subscriber_chat";
            case 744:
                return "creators_genai_audience";
            case 745:
                return "current_step";
            case 746:
                return "deeplink_reel_id";
            case 747:
                return "deeplink_reel_position";
            case 748:
                return "deleteSeenShhMessages";
            case 749:
                return "deleted_messages";
            case 750:
                return "deviceChangeType";
            case 751:
                return "deviceVolume";
            case 752:
                return "device_change_timestamp_ms";
            case 753:
                return "device_change_type";
            case 754:
                return "device_created_on";
            case 755:
                return "dialog_shown";
            case 756:
                return "directThreadThemes";
            case 757:
                return "direct_broadcast_channel_conversation_starters";
            case 758:
                return "direct_channel_audience_type";
            case 759:
                return "direct_channel_preset_type";
            case 760:
                return "direct_channels_gated_content_upsell";
            case 761:
                return "direct_clips_preview_audio_cluster_id";
            case 762:
                return "direct_clips_preview_author_id";
            case 763:
                return "direct_clips_preview_cdn_url";
            case 764:
                return "direct_clips_preview_draft_id";
            case 765:
                return "direct_clips_preview_should_mute";
            case 766:
                return "direct_compose_select_recipient";
            case 767:
                return "direct_ctd_campaign_messages";
            case 768:
                return "direct_dimiss_nudge_count";
            case 769:
                return "direct_emoji_collection_item_id";
            case 770:
                return "direct_emoji_collection_type";
            case 771:
                return "direct_emoji_message_id";
            case 772:
                return "direct_emoji_pong_fragment_argument_emoji";
            case 773:
                return "direct_emoji_pong_fragment_argument_recipient_ids";
            case 774:
                return "direct_emoji_pong_fragment_argument_thread_id";
            case 775:
                return "direct_emoji_thread_id";
            case 776:
                return "direct_enter_thread";
            case 777:
                return "direct_expiring_media_create_group_chat_failed";
            case 778:
                return "direct_inbox_general_folder_banner";
            case 779:
                return "direct_invite";
            case 780:
                return "direct_invite_main";
            case 781:
                return "direct_is_creating_secret_conversation";
            case 782:
                return "direct_manage_folders_edit";
            case 783:
                return "direct_media_collection";
            case 784:
                return "direct_raven_replayed";
            case 785:
                return "direct_raven_screenshot";
            case 786:
                return "direct_request_allow_folder_dialog_cancel";
            case 787:
                return "direct_request_allow_folder_dialog_impression";
            case 788:
                return "direct_request_block_click";
            case 789:
                return "direct_secure_thread";
            case 790:
                return "direct_share_targets";
            case 791:
                return "direct_sharesheet";
            case 792:
                return "direct_suggested_recipient_impression";
            case 793:
                return "direct_theme_preview";
            case 794:
                return "direct_thread_change_theme";
            case 795:
                return "direct_thread_content_note";
            case 796:
                return "direct_thread_notification_settings";
            case 797:
                return "direct_thread_video_call_xma_start_call_confirmation_count";
            case 798:
                return "direct_thread_view_infra_type";
            case 799:
                return "direct_unknown_error";
            case 800:
                return "direct_v2/get_note_join_chat_thread_preview_info/";
            case 801:
                return "direct_v2_generic";
            case 802:
                return "direct_v2_generic_new_message";
            case 803:
                return "direct_v2_highlights_share";
            case 804:
                return "direct_v2_media";
            case 805:
                return "direct_v2_media_share";
            case 806:
                return "direct_v2_raven";
            case 807:
                return "direct_v2_reel_reaction";
            case 808:
                return "direct_welcome_message_events";
            case 809:
                return "direct_widget";
            case 810:
                return "disappearing_mode_upgrade_from_vanish_mode_update_app";
            case 811:
                return "display_location";
            case 812:
                return "download_success";
            case 813:
                return "eb_third_party_ids(platforms:[\"ANDROID\",\"GOOGLE_DRIVE\",\"GOOGLE_ONE_AUTO_BACKUP\"])";
            case 814:
                return "eligibility_hash";
            case 815:
                return "enable_infinite_pagination";
            case 816:
                return "enabled_status";
            case 817:
                return "encrypted_payload";
            case 818:
                return "encryption_management_delegator_id";
            case 819:
                return "entry_surface";
            case 820:
                return "ephemeral_expiration";
            case 821:
                return "ephemeral_image";
            case 822:
                return "ephemeral_type";
            case 823:
                return "event_subtype";
            case 824:
                return "exception_cause";
            case 825:
                return "experience_id";
            case 826:
                return "expireMessages";
            case 827:
                return "explore_grid_cta";
            case 828:
                return "external_link_thread_viewer_session_id";
            case 829:
                return "external_share_send_attribution_image";
            case 830:
                return "external_sheet_send_attribution_text";
            case 831:
                return "extra_date_range_end";
            case 832:
                return "extra_date_range_start";
            case 833:
                return "extra_hint_text";
            case 834:
                return "extra_listen_for_past_dates";
            case 835:
                return "extra_minute_interval_length";
            case 836:
                return "extra_selected_date";
            case 837:
                return "extra_show_all_day_toggle";
            case 838:
                return "extra_show_done_button";
            case 839:
                return "failed to serialize";
            case 840:
                return "failed_to_load_video_toast";
            case 841:
                return "fb_friends_of_friends";
            case 842:
                return "fbid_based_auth_layer_vesta_begin_login_v2(begin_login_request:$input)";
            case 843:
                return "fbid_based_auth_layer_vesta_begin_register_v2(begin_register_request:$input)";
            case 844:
                return "fbid_based_auth_layer_vesta_finish_login_v2(finish_login_request:$input)";
            case 845:
                return "fbid_based_auth_layer_vesta_finish_register_v2(finish_register_request:$input)";
            case 846:
                return "fbid_based_auth_layer_vesta_login_init_v2(vesta_init_request:$request)";
            case 847:
                return "fbid_based_auth_layer_vesta_register_init_v2(vesta_init_request:$request)";
            case 848:
                return "fetch__XDTUserDict(id:$user_id)";
            case 849:
                return "fetch_data_error";
            case 850:
                return "fetch_params";
            case 851:
                return "filters_button";
            case 852:
                return "friend_map_reply";
            case 853:
                return "gen_ai_accounts";
            case 854:
                return "gen_ai_response_feedback";
            case 855:
                return "generate_message_list_view_models";
            case 856:
                return "getOnClickListener";
            case 857:
                return "get_msys_thread_key_from_direct_threadId";
            case 858:
                return "get_should_use_secure_thread";
            case 859:
                return "go_live_tooltip";
            case 860:
                return "graduation_month";
            case 861:
                return "group_details";
            case 862:
                return "group_message_setting";
            case 863:
                return "has_otc_eligible_devices(family_device_id:$family_device_id)";
            case 864:
                return "has_seen_prompt_note_flywheel_animation";
            case 865:
                return "has_seen_spotify_note_creation_nux";
            case 866:
                return "hidden_locations";
            case 867:
                return "hidden_word_upsell_toast_shown_count";
            case 868:
                return "hidden_words_control_custom_list_enabled";
            case 869:
                return "hidden_words_control_custom_list_strings";
            case 870:
                return "hidden_words_control_predefined_enabled";
            case 871:
                return "hsm_pin_normalization_status";
            case 872:
                return "https://about.fb.com/news/2023/09/building-generative-ai-features-responsibly/";
            case 873:
                return "https://help.instagram.com/331274061770840";
            case 874:
                return "https://help.instagram.com/477434105621119/?helpref=hc_fnav";
            case 875:
                return "https://help.instagram.com/491565145294150";
            case 876:
                return "https://help.instagram.com/585369912141614";
            case 877:
                return "https://help.instagram.com/654906392080948";
            case 878:
                return "https://help.instagram.com/700284123459336";
            case 879:
                return "https://m.facebook.com/policies/other-policies/ais-terms";
            case 880:
                return "https://www.facebook.com/help/instagram/791161338412168?ref=igapp";
            case 881:
                return "https://www.facebook.com/legal/terms/ad_creative_generative_ai_terms";
            case 882:
                return "https://www.instagram.com/linking/fundraiser?fundraiser_id=";
            case 883:
                return "https://www.instagram.com/reels/audio/";
            case 884:
                return "https://www.instagram.com/stories/";
            case 885:
                return "ig_avatar_sticker";
            case 886:
                return "ig_comments_media_id";
            case 887:
                return "ig_detected_outcome_lead";
            case 888:
                return "ig_detected_outcome_order";
            case 889:
                return "ig_direct_emoji_pong_easter_egg";
            case 890:
                return "ig_direct_get_thread_items_v2(ig_item_ids:$ig_item_ids,ig_thread_id:$ig_thread_id,otids:$otids)";
            case 891:
                return "ig_media_igid";
            case 892:
                return "ig_media_publish_success";
            case 893:
                return "ig_message_settings";
            case 894:
                return "ig_object_value";
            case 895:
                return "ig_shopping_pdp_share_sheet_confirmation_toast";
            case 896:
                return "ig_video_nux";
            case 897:
                return "ig_world_pages";
            case 898:
                return "igd_creator_subscriber_chats_action";
            case 899:
                return "igd_thread_id";
            case 900:
                return "igd_universal_search:ai_nullstate_airplane_send";
            case 901:
                return "igd_universal_search:ai_prompt";
            case 902:
                return "igd_universal_search:ai_typeahead_airplane_send";
            case 903:
                return "igd_universal_search:ai_typeahead_donut";
            case 904:
                return "igd_universal_search:ai_typeahead_keyboard_send";
            case 905:
                return "inbox_ads_event_sharing_notice_banner";
            case 906:
                return "inbox_folders_manage_screen_impression";
            case 907:
                return "inbox_notes_tray";
            case 908:
                return "inbox_tray_item";
            case 909:
                return "incentives_to_apply";
            case 910:
                return "inform_module";
            case 911:
                return "inform_treatment";
            case 912:
                return "instagram://avatar_sticker_upsell_bloks_action";
            case 913:
                return "instagram://details/disappearing_message_change_duration";
            case 914:
                return "instagram://details/toggle_disappearing_messages?active=false";
            case 915:
                return "instagram://gen_ai_accounts";
            case 916:
                return "instagram://suggested_reply";
            case 917:
                return "instagram://thread/";
            case 918:
                return "instagram_vc";
            case 919:
                return "instagram_waverly_ig_event";
            case 920:
                return "instagram_wellbeing_warning_system_impression";
            case 921:
                return "invite_state";
            case 922:
                return "invite_status";
            case 923:
                return "is_android_auto_restore_opted_out";
            case 924:
                return "is_avatar_sticker";
            case 925:
                return "is_dm_e2ee_attribution_enabled";
            case 926:
                return "is_dm_thread_eligible";
            case 927:
                return "is_eligible_for_encrypted_backups";
            case 928:
                return "is_final_text_chunk";
            case 929:
                return "is_interop_participant";
            case 930:
                return "is_interop_thread";
            case 931:
                return "is_offensive";
            case 932:
                return "is_suspicious_login";
            case 933:
                return "is_user_opted_out";
            case 934:
                return "last_active_location_audience";
            case 935:
                return "last_user_restriction_sentry_block_event";
            case 936:
                return "leave_group_option";
            case 937:
                return "limited_categories";
            case 938:
                return "limited_features";
            case 939:
                return "live_with_join_flow";
            case 940:
                return "loading_spinner";
            case 941:
                return "local_data_id";
            case 942:
                return "logStartCallQplStep threadId: ";
            case 943:
                return "logger_session_id";
            case 944:
                return "logging_extra";
            case 945:
                return "mThread is null";
            case 946:
                return "magic_media_remix_template_bitmap_paths";
            case 947:
                return "magic_media_remix_template_component_count";
            case 948:
                return "magic_media_remix_template_direct_thread_key";
            case 949:
                return "magic_media_remix_template_layout_name";
            case 950:
                return "magic_media_remix_template_position";
            case 951:
                return "magic_media_remix_template_rule_id";
            case 952:
                return "mailbox_insert_rtc_e2ee_admin_messages";
            case 953:
                return "mailbox_insert_rtc_e2ee_call_xma_messages";
            case 954:
                return "max_attempts_count";
            case 955:
                return "media_note_author_stack";
            case 956:
                return "media_note_id";
            case 957:
                return "mem_offline_sync";
            case 958:
                return "merchant_username";
            case 959:
                return "message_controls_settings_version";
            case 960:
                return "message_menu";
            case 961:
                return "message_options";
            case 962:
                return "message_otid";
            case 963:
                return "message_sender_fbtype";
            case 964:
                return "message_sync_service";
            case 965:
                return "message_text";
            case 966:
                return "messaging_blackhole_urls(client_version_id:$client_version_id)";
            case 967:
                return "messaging_controls";
            case 968:
                return "messaging_meta_ai_intent_detection_event";
            case 969:
                return "meta_ai_intent_detection_nux_clicked";
            case 970:
                return "metadata_type";
            case 971:
                return "mobile_ig_zero_dogfooding_account";
            case 972:
                return "msys://ae-media";
            case 973:
                return "multiple_profile_navigation";
            case 974:
                return "mutation_type";
            case 975:
                return "mutuals_checkup_info";
            case 976:
                return "mwb_cm_inform_treatment_event";
            case 977:
                return "nativeUIControlSlider";
            case 978:
                return "network_request_failed";
            case 979:
                return "network_state";
            case 980:
                return "new_followers";
            case 981:
                return "new_theme_id";
            case 982:
                return "next_client_version_id";
            case 983:
                return "next_page_cursor";
            case 984:
                return "nickname_setting";
            case 985:
                return "notes_creation_sheet";
            case 986:
                return "notice_content_text";
            case 987:
                return "notice_ui_type";
            case 988:
                return "notification_clicked";
            case 989:
                return "notification_tap";
            case 990:
                return "null cannot be cast to non-null type android.app.DownloadManager";
            case 991:
                return "null cannot be cast to non-null type android.text.SpannableStringBuilder";
            case 992:
                return "null cannot be cast to non-null type androidx.recyclerview.widget.StaggeredGridLayoutManager.LayoutParams";
            case 993:
                return "null cannot be cast to non-null type com.facebook.messagingclient.multiinstance.provider.BackgroundAccountSyncProviderV2";
            case 994:
                return "null cannot be cast to non-null type com.google.android.material.appbar.AppBarLayout.LayoutParams";
            case 995:
                return "null cannot be cast to non-null type com.instagram.common.api.base.ApiError.Response<com.instagram.api.response.IgResponse>";
            case 996:
                return "null cannot be cast to non-null type com.instagram.common.lispy.lang.Expression";
            case 997:
                return "null cannot be cast to non-null type com.instagram.common.ui.base.IgEditText";
            case 998:
                return "null cannot be cast to non-null type com.instagram.direct.channels.education.util.ChannelEducationType";
            case 999:
                return "null cannot be cast to non-null type com.instagram.direct.fragment.thread.chatsettings.customthemepreview.CustomThemePreviewFragment";
            case IgNetworkConsentStorage.MAX_ENTRIES /*1000*/:
                return "null cannot be cast to non-null type com.instagram.direct.fragment.thread.infra.open.DirectThreadViewDataLoader";
            case 1001:
                return "null cannot be cast to non-null type com.instagram.direct.model.DirectVisualMessageViewerItem";
            case 1002:
                return "null cannot be cast to non-null type com.instagram.model.direct.gifs.DirectAnimatedMedia";
            case 1003:
                return "null cannot be cast to non-null type com.instagram.model.direct.threadkey.impl.MsysThreadId";
            case 1004:
                return "null cannot be cast to non-null type com.instagram.ui.emptystaterow.EmptyStateBinder.Holder";
            case 1005:
                return "null cannot be cast to non-null type com.instagram.ui.menu.ArrowItem";
            case 1006:
                return "null cannot be cast to non-null type com.instagram.ui.menu.ButtonItem";
            case 1007:
                return "null cannot be cast to non-null type com.instagram.ui.menu.IgdsListCellItem";
            case 1008:
                return "null cannot be cast to non-null type com.instagram.ui.menu.MenuItem";
            case 1009:
                return "null cannot be cast to non-null type com.instagram.ui.menu.SwitchItem";
            case 1010:
                return "null cannot be cast to non-null type java.util.HashMap<kotlin.String, kotlin.Any>";
            case 1011:
                return "null cannot be cast to non-null type kotlin.collections.List<T of com.instagram.direct.search.provider.RTRSearchDelegateImpl>";
            case 1012:
                return "null cannot be cast to non-null type kotlin.collections.MutableMap.MutableEntry<K of kotlin.collections.GroupingKt__GroupingJVMKt.mapValuesInPlace$lambda$4, R of kotlin.collections.GroupingKt__GroupingJVMKt.mapValuesInPlace$lambda$4>";
            case 1013:
                return "num_media_loaded";
            case 1014:
                return "nux_landing_surface";
            case 1015:
                return "old_theme_id";
            case 1016:
                return "onAiStickerSearchSuccess";
            case 1017:
                return "onCancelClicked";
            case 1018:
                return "on_device_nudity_banner_state/recipient/";
            case 1019:
                return "on_device_nudity_banner_state/sender/";
            case 1020:
                return "on_device_nudity_control_image_scan_enabled";
            case 1021:
                return "on_prompt_created";
            case 1022:
                return "onboarding_decision";
            case 1023:
                return "one_click_upsell";
            case 1024:
                return "original_folder_name";
            case 1025:
                return "other is null";
            case 1026:
                return "other_folder_names";
            case 1027:
                return "other_mutuals_count";
            case 1028:
                return "others_on_fb";
            case 1029:
                return "pager_bottom_sheet_launch_config";
            case 1030:
                return "paging_token";
            case 1031:
                return "participantUserId";
            case 1032:
                return "pending_inbox";
            case 1033:
                return "pending_requests_total";
            case 1034:
                return "people_who_follow_you";
            case 1035:
                return "people_with_your_phone_number";
            case 1036:
                return "permanent_image";
            case 1037:
                return "pinned_address";
            case 1038:
                return "pinned_get_directions";
            case 1039:
                return "pinned_ssc_on_profile";
            case 1040:
                return "plugin_response";
            case 1041:
                return "poll_question_text";
            case 1042:
                return "preference_last_local_call_id";
            case 1043:
                return "preference_last_shared_call_id";
            case 1044:
                return "preview_data";
            case 1045:
                return "preview_fetch_start";
            case 1046:
                return "primary_action";
            case 1047:
                return "primary_family_device_id";
            case 1048:
                return "primary_folder_name_for_deletion";
            case 1049:
                return "promote_ads_manager_toast_update_error_rebranding";
            case 1050:
                return "promote_automatic_creative_optimization_bottom_sheet";
            case 1051:
                return "prompt_index";
            case 1052:
                return "prompt_note_bottom_sheet_note_unavailable";
            case 1053:
                return "prompt_responses";
            case 1054:
                return "prompt_sticker_id";
            case 1055:
                return "prompts_entry_point";
            case 1056:
                return "proxy_refusal";
            case 1057:
                return "push_identifier";
            case 1058:
                return "push_notification_action";
            case 1059:
                return "query_length";
            case 1060:
                return "question_response_text";
            case 1061:
                return "quiet_mode_next_end_timestamp";
            case 1062:
                return "reaction_pill_tag";
            case 1063:
                return "recent_mutual_users";
            case 1064:
                return "reel_dashboard_reactor";
            case 1065:
                return "reel_dashboard_viewer";
            case 1066:
                return "reel_owner_id";
            case 1067:
                return "reel_profile_cta";
            case 1068:
                return "registration_success";
            case 1069:
                return "render_video_success";
            case 1070:
                return "replacement_text";
            case 1071:
                return "reply_bubble_tag";
            case 1072:
                return "report_button";
            case 1073:
                return "requester_user_id";
            case 1074:
                return "resign_collaborator_dialog";
            case 1075:
                return "resign_moderator_dialog";
            case 1076:
                return "resolver_type";
            case 1077:
                return "restrict_option";
            case 1078:
                return "result_index";
            case 1079:
                return "rtc_avatar_effect_compatibility_version";
            case 1080:
                return "rtc_device_shutdown_local_call_id";
            case 1081:
                return "rtc_device_shutdown_time";
            case 1082:
                return "runInstagramXmaClipsShareClientSend";
            case 1083:
                return "runInstagramXmaIgtvShareClientSend";
            case 1084:
                return "runInstagramXmaPostShareClientSend";
            case 1085:
                return "runInstagramXmaProfileShareClientSend";
            case 1086:
                return "runInstagramXmaReplyWithStickerClientSend";
            case 1087:
                return "runInstagramXmaSendStandaloneV2";
            case 1088:
                return "runInstagramXmaStoryMentionClientSend";
            case 1089:
                return "runInstagramXmaStoryReplyClientSend";
            case 1090:
                return "runInstagramXmaStoryShareClientSend";
            case 1091:
                return "rxmailbox_send_secure_image_message";
            case 1092:
                return "safebrowsing_instagram_standalone";
            case 1093:
                return "sample_audio_url";
            case 1094:
                return "scaling_factor";
            case 1095:
                return "scheduled_messages";
            case 1096:
                return "screen_capture_error_message";
            case 1097:
                return "screen_capture_is_discarded";
            case 1098:
                return "screen_capture_is_photobooth";
            case 1099:
                return "screen_capture_is_success";
            case 1100:
                return "screen_capture_share_arguments_camera_view_model";
            case 1101:
                return "screen_capture_share_arguments_key_entry_point";
            case 1102:
                return "screen_capture_share_arguments_key_file_path";
            case 1103:
                return "screen_capture_share_types";
            case 1104:
                return "search_grid_cta";
            case 1105:
                return "search_plugin_response";
            case 1106:
                return "search_string";
            case 1107:
                return "secondary_snapshot";
            case 1108:
                return "section_order";
            case 1109:
                return "security_exception";
            case 1110:
                return "security_question_type";
            case 1111:
                return "see_all_button";
            case 1112:
                return "see_channel_tooltip";
            case 1113:
                return "seed_message_id";
            case 1114:
                return "seen_direct_admin_remove_message_warning_dialog";
            case 1115:
                return "selected_emoji_item";
            case 1116:
                return "selected_fulfillment_option";
            case 1117:
                return "selected_shipping_address";
            case 1118:
                return "self_setting";
            case 1119:
                return "selfie_thumbnail_xma";
            case 1120:
                return "send_attribution_overflow_composer_imagine";
            case 1121:
                return "send_frequency_with_timezone_offset(gmt_offset_seconds:$gmt_offset_seconds)";
            case 1122:
                return "send_group_size";
            case 1123:
                return "send_message";
            case 1124:
                return "send_quick_message";
            case 1125:
                return "send_service";
            case 1126:
                return "send_time_with_timezone_offset(gmt_offset_seconds:$gmt_offset_seconds)";
            case 1127:
                return "sender_not_verified";
            case 1128:
                return "server_bug_id";
            case 1129:
                return "session_level_survey";
            case 1130:
                return "session_level_survey_notification";
            case 1131:
                return "setting_page";
            case 1132:
                return "share_reason";
            case 1133:
                return "share_to_story_message_button";
            case 1134:
                return "should_be_featured";
            case 1135:
                return "should_display_device_change_admin_message";
            case 1136:
                return "show_add_chats";
            case 1137:
                return "show_delete_button";
            case 1138:
                return "show_optimistic_message";
            case 1139:
                return "single_media_cta";
            case 1140:
                return "smart_suggestion_accept";
            case 1141:
                return "smart_suggestion_dismiss";
            case 1142:
                return "smart_suggestion_impression";
            case 1143:
                return "social_channel_invite_id";
            case 1144:
                return "status_update_timestamp";
            case 1145:
                return "stella_share_sheet";
            case 1146:
                return "sticker_count";
            case 1147:
                return "sticker_position_index";
            case 1148:
                return "stories/prompt_stickers/top_participants_pagination/";
            case 1149:
                return "story_poll_vote_list";
            case 1150:
                return "story_question_response_list";
            case 1151:
                return "story_viewer_rendered";
            case 1152:
                return "subscribe called on finalized RpStore. No updates will be provided.";
            case 1153:
                return "subscribe_to_join_chat_sheet";
            case 1154:
                return "subscription_ids";
            case 1155:
                return "suggested_replies_toggle";
            case 1156:
                return "suggestions_home_last_checked_prefs_key";
            case 1157:
                return "support_ticket";
            case 1158:
                return "tap_component";
            case 1159:
                return "text_request_id";
            case 1160:
                return "text_response_id";
            case 1161:
                return "third_party_id";
            case 1162:
                return "third_party_link";
            case 1163:
                return "thread_background_color";
            case 1164:
                return "thread_channel_controls";
            case 1165:
                return "thread_ctd_upsell_launch_boost_flow";
            case 1166:
                return "thread_detail_bundle";
            case 1167:
                return "thread_is_open";
            case 1168:
                return "thread_is_open_or_dm_is_active";
            case 1169:
                return "thread_jid : ";
            case 1170:
                return "thread_limit";
            case 1171:
                return "thread_translation_tooltip_impression";
            case 1172:
                return "thread_with_muted_outgoing_chat_notification";
            case 1173:
                return "top_participants_media_count";
            case 1174:
                return "toplevel_payload";
            case 1175:
                return "total_selected_items";
            case 1176:
                return "unread_pending_requests";
            case 1177:
                return "unrestrict_option";
            case 1178:
                return "unsupported bindergroup added";
            case 1179:
                return "upcoming_event_reminder_notification_tap";
            case 1180:
                return "update_scf_bool_settings(new_value:$new_value,setting_key:$setting_key)";
            case 1181:
                return "update_scf_string_settings(new_value:$new_value,setting_key:$setting_key)";
            case 1182:
                return "url_chunk_hash";
            case 1183:
                return "url_chunk_id";
            case 1184:
                return "userCapabilities";
            case 1185:
                return "user_dot_menu";
            case 1186:
                return "user_paused_video";
            case 1187:
                return "user_pay_fanclub_fetch_failure";
            case 1188:
                return "users/set_limited_interactions_settings/";
            case 1189:
                return "usertags/review_preference/";
            case 1190:
                return "versionName=";
            case 1191:
                return "video_format";
            case 1192:
                return "viewer_is_sender";
            case 1193:
                return "viewer_pause";
            case 1194:
                return "virtual_devices";
            case 1195:
                return "warning_message";
            case 1196:
                return "warning_title";
            case 1197:
                return "xdt__generate_share_url_wrapper(request:$input)";
            case 1198:
                return "xdt_fbsearch__meta_ai_hcm_stream(request_data:{\"entrypoint\":$entrypoint,\"query\":$query,\"search_session_id\":$search_session_id})";
            case 1199:
                return "xdt_get_listening_now_info";
            case 1200:
                return "xdt_music_api_save_song_to_spotify(audio_cluster_id:0,audio_cluster_id_str:$audio_cluster_id,note_id:$note_id)";
            case 1201:
                return "xdt_zero_easy_dogfooding_stop";
            case 1202:
                return "xfb_biig_ads_event_sharing_notice(business_ig_id:$business_ig_id,consumer_ig_id:$consumer_ig_id,event_type:$event_type)";
            case 1203:
                return "xfb_genai_thread_subscriptions_query(product_type:$product_type)";
            case 1204:
                return "xfb_ig_p2m_get_orders(buyer_id:$buyerID,merchant_id:$merchantID)";
            case 1205:
                return "xfb_igd_channel_directory(data:$data)";
            case 1206:
                return "xfb_igd_pending_request_count(pending_thread_filters:$pending_thread_filters)";
            case 1207:
                return "xfb_messaging_search_genai_snippet(entry_point:$entry_point,user_prompt:$user_prompt)";
            case 1208:
                return "xfb_should_show_biig_ads_event_sharing_consent_at_thread_entry(business_ig_id:$business_ig_id,consumer_ig_id:$consumer_ig_id)";
            case 1209:
                return "xig_upsert_ig_easy_zero_dogfooding_account_mobile_ig_zero_dogfooding_account(data:$data)";
            case 1210:
                return "xposting_nux";
            case 1211:
                return "zero_rating_direct_video_nux_count";
            case 1212:
                return "zero_rating_explore_video_nux_count";
            case 1213:
                return "zero_rating_video_autoplay_disabled";
            default:
                return "zero_token(basic_token_hash:$basic_token_hash,fetch_reason:$fetch_reason,fetch_type:$fetch_type,normal_token_hash:$normal_token_hash)";
        }
    }
}
