package X;

/* renamed from: X.NjK  reason: case insensitive filesystem */
public enum C69319NjK {
    DIRECT_COMPOSER_STICKER_BUTTON,
    DIRECT_COMPOSER_STICKER_SHORTCUT,
    DIRECT_CREATOR_SEARCH,
    DIRECT_SAVED_STICKER,
    NOTES_QUICK_REPLY_STICKER_BUTTON,
    NOTES_CREATION_GIF_BUTTON,
    STORY_VIEWER_GIF_BUTTON,
    STORY_VIEWER_STICKER_BUTTON,
    CANVAS_GIF_TOOL,
    COMMENT_COMPOSER,
    COMMENT_CREATOR_SEARCH,
    UPSELL_TRAY,
    AVATAR_STICKER_TAP,
    REELS_GREEN_SCREEN,
    REELS_STACKED_TIMELINE,
    STICKER_SUGGESTIONS,
    WALL_COMPOSER,
    REOPEN_AI_STICKER_TRAY,
    AI_STICKER_NUX,
    MESSAGE_LONG_PRESS_ADD_STICKER,
    MESSAGE_LONG_PRESS_VIEW_STICKER_PACK,
    UNKNOWN;

    /* access modifiers changed from: public */
    static {
        C69319NjK[] njKArr;
        A00 = 0oU.A00(njKArr);
    }
}
