package X;

/* renamed from: X.REu  reason: case insensitive filesystem */
public enum C8902REu {
    CLIENT_LOAD_OFFSITEAVAILABILITY_INIT,
    CLIENT_LOAD_OFFSITEAVAILABILITY_SUCCESS,
    CLIENT_LOAD_OFFSITEAVAILABILITY_FAIL,
    CLIENT_LOAD_OFFSITELOGINWITHAPP_INIT,
    CLIENT_LOAD_OFFSITELOGINWITHAPP_SUCCESS,
    CLIENT_LOAD_OFFSITELOGINWITHAPP_FAIL,
    CLIENT_LOAD_OFFSITEPAYMENTREQUEST_INIT,
    CLIENT_LOAD_OFFSITEPAYMENTREQUEST_SUCCESS,
    CLIENT_LOAD_OFFSITEPAYMENTREQUEST_FAIL,
    CLIENT_LOAD_OFFSITEPAYMENTHANDLED_INIT,
    CLIENT_LOAD_OFFSITEPAYMENTHANDLED_SUCCESS,
    CLIENT_LOAD_OFFSITEPAYMENTHANDLED_FAIL,
    CLIENT_LOAD_OFFSITEPAYMENTDETAILSCHANGED_INIT,
    CLIENT_LOAD_OFFSITEPAYMENTDETAILSCHANGED_SUCCESS,
    CLIENT_LOAD_OFFSITEPAYMENTDETAILSCHANGED_FAIL,
    CLIENT_RENDER_OFFSITEFOOTER_DISPLAY,
    USER_CLICK_OFFSITEDISCLAIMER_ATOMIC,
    CLIENT_FETCH_OFFSITEMERCHANTJAVASCRIPT_INIT,
    CLIENT_FETCH_OFFSITEMERCHANTJAVASCRIPT_SUCCESS,
    CLIENT_FETCH_OFFSITEMERCHANTJAVASCRIPT_FAIL,
    CLIENT_EXECUTE_OFFSITEMERCHANTJAVASCRIPT_INIT,
    CLIENT_EXECUTE_OFFSITEMERCHANTJAVASCRIPT_SUCCESS,
    CLIENT_EXECUTE_OFFSITEMERCHANTJAVASCRIPT_FAIL;

    /* access modifiers changed from: public */
    static {
        C8902REu[] rEuArr;
        A00 = 0oU.A00(rEuArr);
    }
}
