package X;

/* renamed from: X.RIr  reason: case insensitive filesystem */
public enum C8952RIr implements AnonymousClass0Ac {
    IAB_AUTOFILL_ADS_PERSONALIZATION("IAB_AUTOFILL_ADS_PERSONALIZATION"),
    IAB_META_CHECKOUT_FIRMLY("IAB_META_CHECKOUT_FIRMLY"),
    IAB_META_CHECKOUT_METAPAYMENTS_SDK("IAB_META_CHECKOUT_METAPAYMENTS_SDK"),
    IAB_META_CHECKOUT_SHOPIFY_SCA("IAB_META_CHECKOUT_SHOPIFY_SCA"),
    IAB_META_CHECKOUT_SHOPIFY_SDK("IAB_META_CHECKOUT_SHOPIFY_SDK"),
    IAB_NO_ADS_CONTEXT("IAB_NO_ADS_CONTEXT"),
    IAB_PAYPAL_CHECKOUT("IAB_PAYPAL_CHECKOUT"),
    IAB_STICKY_UTM_PARAMS("IAB_STICKY_UTM_PARAMS"),
    IAB_WATCH_AND_BROWSE_WEB_TO_WA("IAB_WATCH_AND_BROWSE_WEB_TO_WA");
    
    public final String A00;

    /* access modifiers changed from: public */
    C8952RIr(String str) {
        this.A00 = str;
    }
}
