package X;

/* renamed from: X.RIq  reason: case insensitive filesystem */
public enum C8951RIq implements AnonymousClass0Ac {
    ERROR_BINDING_DIED("ERROR_BINDING_DIED"),
    ERROR_FAILED_DOWNLOAD_CALLBACK_REGISTER("ERROR_FAILED_DOWNLOAD_CALLBACK_REGISTER"),
    ERROR_NULL_BINDING("ERROR_NULL_BINDING"),
    ERROR_SERVICE_UNAVAILABLE("ERROR_SERVICE_UNAVAILABLE"),
    ERROR_UNEXEPECTED_SERVICE_DISCONNECTION("ERROR_UNEXEPECTED_SERVICE_DISCONNECTION"),
    OEM_FALLBACK_INVALID_CONTEXT("OEM_FALLBACK_INVALID_CONTEXT"),
    OEM_FALLBACK_OEM_STORE_NOT_FOUND("OEM_FALLBACK_OEM_STORE_NOT_FOUND"),
    OEM_FALLBACK_UNSUPPORTED_OEM_STORE_VERSION("OEM_FALLBACK_UNSUPPORTED_OEM_STORE_VERSION");
    
    public final String A00;

    /* access modifiers changed from: public */
    C8951RIq(String str) {
        this.A00 = str;
    }
}
