package X;

/* renamed from: X.RWd  reason: case insensitive filesystem */
public abstract class C9278RWd {
    public static String A00(int i) {
        return i != 4102 ? i != 4503 ? i != 8565 ? i != 9522 ? i != 10344 ? i != 11676 ? i != 13498 ? i != 14327 ? "UNDEFINED_QPL_EVENT" : "AVATAR_CONTENT_DELIVERY_ASSET_GLTF_PROCESS" : "AVATAR_CONTENT_DELIVERY_ASSET_SAVE" : "AVATAR_CONTENT_DELIVERY_AVATAR_COMBINE" : "AVATAR_CONTENT_DELIVERY_RT_RIG_RETARGETING_GRAPHQL" : "AVATAR_CONTENT_DELIVERY_CDL_GENERATE_RAMP" : "AVATAR_CONTENT_DELIVERY_CDL_GENERATE_AVATAR" : "AVATAR_CONTENT_DELIVERY_CDL_UPDATE_BODY_PARAMETRICS" : "AVATAR_CONTENT_DELIVERY_PREFETCH_ASSETS";
    }
}
