package X;

/* renamed from: X.RWr  reason: case insensitive filesystem */
public abstract class C9292RWr {
    public static String A00(int i) {
        return i != 1 ? i != 1614 ? i != 2913 ? i != 3830 ? i != 4585 ? i != 5829 ? i != 11753 ? i != 12221 ? i != 13374 ? "UNDEFINED_QPL_EVENT" : "BLOKS_SHOPS_SHOPS_ADS_OPEN_VARIANT_SELECTOR" : "BLOKS_SHOPS_PAGE_DATA_LOAD_START" : "BLOKS_SHOPS_PAGE_DATA_LOAD_END" : "BLOKS_SHOPS_ASYNC_ACTION" : "BLOKS_SHOPS_SHOPS_PAGINATION_FLOW" : "BLOKS_SHOPS_SHOPS_ADS_OPEN_MINI_CART" : "BLOKS_SHOPS_PAGE_RENDERING_STARTS" : "BLOKS_SHOPS_BUY_NOW_NAVIGATES_TO_CHECKOUT" : "BLOKS_SHOPS_SCREEN_TTRC";
    }
}
