package X;

/* renamed from: X.RXu  reason: case insensitive filesystem */
public abstract class C9321RXu {
    public static String A00(int i) {
        return i != 1240 ? i != 3008 ? i != 3777 ? i != 4895 ? i != 5051 ? i != 7754 ? i != 8099 ? i != 9258 ? i != 14020 ? "UNDEFINED_QPL_EVENT" : "FX_LEGACY_DND_DND_INACTIVATION_REASONS_SCREEN_LOAD" : "FX_LEGACY_DND_DND_REAUTH_SCREEN_LOAD" : "FX_LEGACY_DND_DND_DELETION_OR_DEACTIVATION_SCREEN_LOAD" : "FX_LEGACY_DND_DND_SUBMIT" : "FX_LEGACY_DND_DND_DELETION_LEARN_MORE_SCREEN_LOAD" : "FX_LEGACY_DND_DND_ORPHAN_PROFILES_SCREEN_LOAD" : "FX_LEGACY_DND_DND_INACTIVATION_CONFIRMATION_SCREEN_LOAD" : "FX_LEGACY_DND_DND_INACTIVATION_HELP_SCREEN_LOAD" : "FX_LEGACY_DND_DND_IDENTITY_SELECTION_SCREEN_LOAD";
    }
}
