package X;

/* renamed from: X.RZo  reason: case insensitive filesystem */
public abstract class C9367RZo {
    public static String A00(int i) {
        return i != 3236 ? i != 3246 ? i != 3437 ? i != 4652 ? i != 10084 ? i != 10299 ? i != 10679 ? "UNDEFINED_QPL_EVENT" : "MSGR_PRIVACY_EXPERIENCES_IP_ADDRESS_PROTECTION_TOGGLE" : "MSGR_PRIVACY_EXPERIENCES_INTEROP_THREAD_CREATION" : "MSGR_PRIVACY_EXPERIENCES_TYPING_INDICATOR_SETTING_TOGGLE" : "MSGR_PRIVACY_EXPERIENCES_RAVEN_SCREENSHOT_BLOCKING" : "MSGR_PRIVACY_EXPERIENCES_BULK_THREAD_DELETION_TOAST" : "MSGR_PRIVACY_EXPERIENCES_BULK_THREAD_DELETION" : "MSGR_PRIVACY_EXPERIENCES_BULK_THREAD_DELETION_NUX";
    }
}
