package X;

/* renamed from: X.RZl  reason: case insensitive filesystem */
public abstract class C9364RZl {
    public static String A00(int i) {
        return i != 1602 ? i != 2913 ? i != 7245 ? i != 13052 ? i != 15176 ? i != 15647 ? "UNDEFINED_QPL_EVENT" : "MSG_DOGFOODING_NUDGE_SNOOZED" : "MSG_DOGFOODING_NUDGE_DOWNLOAD_PAGE_PRESENTED" : "MSG_DOGFOODING_NUDGE_PRE_PROD_VERSION_PRESENTED" : "MSG_DOGFOODING_NUDGE_DOWNLOAD_PAGE_CLICKED" : "MSG_DOGFOODING_NUDGE_PRE_PROD_VERSION_CLICK_SUCCEEDED" : "MSG_DOGFOODING_NUDGE_DISMISSED";
    }
}
