package X;

/* renamed from: X.RaO  reason: case insensitive filesystem */
public abstract class C9403RaO {
    public static String A00(int i) {
        return i != 1708 ? i != 3590 ? i != 5956 ? i != 9131 ? i != 10261 ? i != 10445 ? i != 10995 ? i != 13456 ? "UNDEFINED_QPL_EVENT" : "PR_CAMERA_VIDEO_PERF_SMART_TRIM" : "PR_CAMERA_VIDEO_PERF_RESIZE_GALLERY_VIDEOS" : "PR_CAMERA_VIDEO_PERF_SMART_CROP" : "PR_CAMERA_VIDEO_PERF_MEDIA_COMPOSITION_THUMBNAIL" : "PR_CAMERA_VIDEO_PERF_REVERSE_VIDEO_PLAY_TTRC" : "PR_CAMERA_VIDEO_PERF_RMS_PHOTO_BAR_REQUEST_SMOOTH_SCROLL_EXCEPTION" : "PR_CAMERA_VIDEO_PERF_FETCH_MUSIC_LIST_FOR_SOUND_SYNC_TTRC" : "PR_CAMERA_VIDEO_PERF_FETCH_BEATS_AND_PERFORM_SOUND_SYNC_TTRC";
    }
}
