package X;

/* renamed from: X.Ran  reason: case insensitive filesystem */
public abstract class C9428Ran {
    public static String A00(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 8 ? i != 4310 ? i != 7158 ? i != 7321 ? i != 9694 ? "UNDEFINED_QPL_EVENT" : "SHARESHEET_PF_SHARESHEET_SHORTCUT_ITEMS_LOAD_TIME" : "SHARESHEET_PF_SHARESHEET_V_SCROLL_LOAD_TIME" : "SHARESHEET_REAL_TIME_RANKING" : "SHARESHEET_REPOST_COMPONENT_LOAD_TIME" : "SHARESHEET_SHARESHEET_LOAD_TTRC" : "SHARESHEET_SHARESHEET_STORY_POST_TIME" : "SHARESHEET_SHARESHEET_DIRECT_SEND_TIME" : "SHARESHEET_SHARESHEET_NEWFEED_POST_TIME" : "SHARESHEET_SHARESHEET_LOAD_TTI";
    }
}
