package X;

/* renamed from: X.RbH  reason: case insensitive filesystem */
public abstract class C9457RbH {
    public static String A00(int i) {
        return i != 2 ? i != 3 ? i != 4 ? i != 5898 ? i != 6805 ? i != 9555 ? i != 12824 ? i != 13405 ? i != 14049 ? i != 14445 ? i != 15399 ? i != 16154 ? "UNDEFINED_QPL_EVENT" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_REELS_WATCH_AND_OVERLAY_IAB_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_REELS_IOS_WATCH_AND_OVERLAY_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_WATCH_AND_OVERLAY_NAVIGATION_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_WATCH_AND_BROWSE_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_WATCH_AND_OVERLAY_INSTALL_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_WATCH_AND_OVERLAY_IAB_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_WATCH_AND_LEADGEN_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_WATCH_AND_INSTALL_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_ANDROID_SHOWREEL_WATCH_AND_BROWSE_FUNNEL" : "VIDEO_ADS_WATCH_AND_BROWSE_WATCH_AND_BROWSE_LANDING_PAGE_TTI" : "VIDEO_ADS_WATCH_AND_BROWSE_WATCH_AND_BROWSE_RVP_TRANSITION" : "VIDEO_ADS_WATCH_AND_BROWSE_WATCH_AND_BROWSE_TRANSITION";
    }
}
