package X;

/* renamed from: X.RbM  reason: case insensitive filesystem */
public abstract class C9462RbM {
    public static String A00(int i) {
        return i != 2959 ? i != 7576 ? i != 10548 ? i != 10639 ? i != 13797 ? i != 14884 ? "UNDEFINED_QPL_EVENT" : "WA_ML_DOWNLOADER_ML_DOWNLOADER_STALE_MODEL_DELETION" : "WA_ML_DOWNLOADER_ML_DOWNLOADER_MODEL_DOWNLOADING" : "WA_ML_DOWNLOADER_ML_DOWNLOADER_CRON_JOB" : "WA_ML_DOWNLOADER_ML_DOWNLOADER_ENQUEUE_REQUEST" : "WA_ML_DOWNLOADER_ML_DOWNLOADER_CANCELED" : "WA_ML_DOWNLOADER_ML_DOWNLOADER_CLEAN_UP";
    }
}
