package X;

import com.instagram.model.reels.sponsored.AutoGeneratedCardType;

public final class DO5 extends 0Yg implements 0sP {
    public static final DO5 A00 = new DO5();

    public DO5() {
        super(1);
    }

    public final /* bridge */ /* synthetic */ Object invoke(Object obj) {
        AutoGeneratedCardType autoGeneratedCardType = (AutoGeneratedCardType) obj;
        0qQ.A0B(autoGeneratedCardType, 0);
        return autoGeneratedCardType.A00;
    }
}
