package X;

public enum HMF {
    COMMENT_DELETE_UPSELL_TYPE_NONE,
    COMMENT_DELETE_UPSELL_TYPE_HMC,
    COMMENT_DELETE_UPSELL_TYPE_BLOCK,
    COMMENT_DELETE_UPSELL_TYPE_HIDDEN_WORDS,
    COMMENT_DELETE_UPSELL_TYPE_HIDDEN_WORDS_V2,
    COMMENT_DELETE_UPSELL_TYPE_BLOCK_COMMENTS_FROM,
    COMMENT_DELETE_UPSELL_TYPE_HRT_BLOCK_COMMENTS_FROM;

    /* access modifiers changed from: public */
    static {
        HMF[] hmfArr;
        A00 = 0oU.A00(hmfArr);
    }
}
