package X;

import com.instagram.api.schemas.BrandedContentGatingInfo;
import com.instagram.api.schemas.BrandedContentProjectMetadata;
import com.instagram.api.schemas.MediaGenAIDetectionMethod;
import com.instagram.common.gallery.metadata.ImmersiveMediaFields;
import com.instagram.common.gallery.metadata.MediaUploadMetadata;
import com.instagram.music.common.model.InstagramAudioApplySource;
import com.instagram.music.common.model.MusicOverlayStickerModel;
import com.instagram.pendingmedia.model.BrandedContentTag;
import com.instagram.pendingmedia.model.ClipInfo;
import java.util.HashMap;
import java.util.List;

public final class LBT {
    public double A00;
    public int A01;
    public int A02;
    public int A03;
    public C279294yP A04 = C279294yP.NONE;
    public AnonymousClass9J6 A05;
    public BrandedContentGatingInfo A06;
    public BrandedContentProjectMetadata A07;
    public C272044k0 A08;
    public MediaGenAIDetectionMethod A09;
    public MediaUploadMetadata A0A = new MediaUploadMetadata((ImmersiveMediaFields) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, (String) null, false);
    public AnonymousClass3QO A0B;
    public InstagramAudioApplySource A0C;
    public MusicOverlayStickerModel A0D;
    public BrandedContentTag A0E;
    public ClipInfo A0F;
    public C273884nL A0G;
    public C63739L4x A0H;
    public AnonymousClass3QG A0I = new AnonymousClass3QG();
    public Boolean A0J;
    public Boolean A0K;
    public Boolean A0L;
    public Boolean A0M = false;
    public Integer A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public HashMap A0X;
    public HashMap A0Y;
    public List A0Z;
    public List A0a;
    public List A0b;
    public List A0c;
    public List A0d;
    public boolean A0e;
    public boolean A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
}
