package X;

public enum RDC {
    ACCEPT_SINGLE_VALUE_AS_ARRAY,
    ACCEPT_CASE_INSENSITIVE_PROPERTIES,
    WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED,
    WRITE_SORTED_MAP_ENTRIES;

    /* access modifiers changed from: public */
    static {
        ACCEPT_SINGLE_VALUE_AS_ARRAY = new RDC("ACCEPT_SINGLE_VALUE_AS_ARRAY", 0);
        ACCEPT_CASE_INSENSITIVE_PROPERTIES = new RDC("ACCEPT_CASE_INSENSITIVE_PROPERTIES", 1);
        WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED = new RDC("WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED", 5);
        WRITE_SORTED_MAP_ENTRIES = new RDC("WRITE_SORTED_MAP_ENTRIES", 6);
    }
}
