package X;

public abstract class RWL {
    public static String A00(int i) {
        return i != 1173 ? i != 6216 ? i != 6847 ? i != 9063 ? i != 11865 ? i != 14249 ? i != 14263 ? i != 15908 ? "UNDEFINED_QPL_EVENT" : "AIPLATFORM_SEGMENT_ANYTHING_ON_DEVICE" : "AIPLATFORM_VIDEO_STICKER_CREATION" : "AIPLATFORM_SALIENCY_SEGMENT_ANYTHING_ON_DEVICE" : "AIPLATFORM_MODEL_PREFETCH" : "AIPLATFORM_SCENE_UNDERSTANDING" : "AIPLATFORM_MODEL_INFERENCE" : "AIPLATFORM_SALIENCY" : "AIPLATFORM_SEGMENT_ANYTHING_POST_PROCESSING";
    }
}
