package X;

public abstract class RWP {
    public static String A00(int i) {
        return i != 3869 ? i != 6881 ? i != 8081 ? i != 10849 ? i != 12994 ? i != 13925 ? i != 14985 ? "UNDEFINED_QPL_EVENT" : "ANDROID_STORIES_DELIVERY_SUBSCRIPTION_PENDING" : "ANDROID_STORIES_DELIVERY_PREFETCH" : "ANDROID_STORIES_DELIVERY_ASD" : "ANDROID_STORIES_DELIVERY_SUBSCRIPTION" : "ANDROID_STORIES_DELIVERY_DELTA_EVENT" : "ANDROID_STORIES_DELIVERY_INFO" : "ANDROID_STORIES_DELIVERY_STORIES_CSR";
    }
}
