package X;

public abstract class RX8 {
    public static String A00(int i) {
        return i != 1493 ? i != 1728 ? i != 8518 ? i != 10152 ? i != 10377 ? i != 13013 ? "UNDEFINED_QPL_EVENT" : "COUNTDOWN_TIMER_COUNTDOWN_TIMER_PAUSE" : "COUNTDOWN_TIMER_COUNTDOWN_TIMER_RESUME" : "COUNTDOWN_TIMER_COUNTDOWN_TIMER_START" : "COUNTDOWN_TIMER_COUNTDOWN_TIMER_SYNC_CLOCK" : "COUNTDOWN_TIMER_COUNTDOWN_TIMER_E2E_CONSUMPTION" : "COUNTDOWN_TIMER_COUNTDOWN_TIMER_STOP";
    }
}
