package X;

public abstract class RY8 {
    public static String A00(int i) {
        return i != 3389 ? i != 3688 ? i != 6487 ? i != 10480 ? i != 13660 ? i != 14410 ? i != 15969 ? "UNDEFINED_QPL_EVENT" : "HORIZON_CORE_LOOP_QUEST_PUI_PANEL_RIGHT_PANE" : "HORIZON_CORE_LOOP_QUESTS_IN_WORLD_DETAILS" : "HORIZON_CORE_LOOP_QUEST_GIZMO_NEXT_PAGE_LOAD" : "HORIZON_CORE_LOOP_QUEST_PUI_PANEL_LEFT_PANE_CACHING" : "HORIZON_CORE_LOOP_QUEST_PUI_PANEL_LEFT_PANE" : "HORIZON_CORE_LOOP_QUEST_GIZMO_CONTENT" : "HORIZON_CORE_LOOP_REMOTE_EMOTE_DOWNLOAD";
    }
}
