package X;

public abstract class RYJ {
    public static String A00(int i) {
        return i != 1590 ? i != 2162 ? i != 3218 ? i != 8606 ? i != 10474 ? i != 10569 ? i != 12130 ? "UNDEFINED_QPL_EVENT" : "IG_ANDROID_PROFILE_FOLLOWERS_FOLLOWING_TAIL_LOAD" : "IG_ANDROID_PROFILE_NAVIGATION_FOLLOW_LIST" : "IG_ANDROID_PROFILE_GRID_RELOAD" : "IG_ANDROID_PROFILE_GRID_HEAD_LOAD" : "IG_ANDROID_PROFILE_FOLLOWERS_FOLLOWING_PAGE" : "IG_ANDROID_PROFILE_GRID_TAIL_LOAD" : "IG_ANDROID_PROFILE_CLIPS_GRID";
    }
}
