package X;

public abstract class RYP {
    public static String A00(int i) {
        return i != 9 ? i != 11 ? i != 20 ? i != 2617 ? i != 5184 ? i != 6550 ? i != 13854 ? "UNDEFINED_QPL_EVENT" : "IG_CLIENT_PERF_IG_BACKGROUND_TASKS" : "IG_CLIENT_PERF_APP_START_V2" : "IG_CLIENT_PERF_IG_HANDLER_TASKS" : "IG_CLIENT_PERF_REDUNDANT_FIELDS_LOGGING" : "IG_CLIENT_PERF_LOAD_MODULE" : "IG_CLIENT_PERF_APP_START" : "IG_CLIENT_PERF_IMAGE_DOWNLOAD";
    }
}
