package X;

public abstract class RZ1 {
    public static String A00(int i) {
        return i != 2593 ? i != 4289 ? i != 5656 ? i != 6275 ? i != 12824 ? i != 13610 ? i != 13959 ? "UNDEFINED_QPL_EVENT" : "LAX_PLATFORM_ADS_LWI_ADS_CREATE" : "LAX_PLATFORM_ADS_LWI_ADS_UPDATE" : "LAX_PLATFORM_ADS_LWI_DEFAULT_DATA_GEN" : "LAX_PLATFORM_ADS_LWI_DEFAULT_OPTIONS_GEN" : "LAX_PLATFORM_ADS_LWI_ADS_READ" : "LAX_PLATFORM_ADS_LWI_ELIGIBILITY" : "LAX_PLATFORM_ADS_LWI_ADS_SPEC_VALIDATION";
    }
}
