package X;

public abstract class RZH {
    public static String A00(int i) {
        return i != 2764 ? i != 2958 ? i != 4192 ? i != 10721 ? i != 14143 ? i != 14800 ? i != 15524 ? "UNDEFINED_QPL_EVENT" : "MCP_MEDIA_E2EE_MEDIA_RELIABILITY" : "MCP_MEDIA_OPEN_MEDIA_RELIABILITY" : "MCP_MEDIA_OPTIMISTIC_TRANSCODE_UPLOAD" : "MCP_MEDIA_E2EE_MEDIA_S2S" : "MCP_MEDIA_STICKER_MIGRATION" : "MCP_MEDIA_E2EE_MEDIA_DOWNLOAD" : "MCP_MEDIA_OPEN_MEDIA_S2S";
    }
}
