package X;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public final class SE1 {
    public static final SE1 A01 = new SE1();
    public static final Set A02;
    public Set A00 = A02;

    static {
        HashSet A1F = AnonymousClass7TE.A1F();
        A1F.add("org.apache.commons.collections.functors.InvokerTransformer");
        A1F.add("org.apache.commons.collections.functors.InstantiateTransformer");
        A1F.add("org.apache.commons.collections4.functors.InvokerTransformer");
        A1F.add("org.apache.commons.collections4.functors.InstantiateTransformer");
        A1F.add("org.codehaus.groovy.runtime.ConvertedClosure");
        A1F.add("org.codehaus.groovy.runtime.MethodClosure");
        A1F.add("org.springframework.beans.factory.ObjectFactory");
        A1F.add("com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl");
        A1F.add("org.apache.xalan.xsltc.trax.TemplatesImpl");
        A1F.add("com.sun.rowset.JdbcRowSetImpl");
        A1F.add("java.util.logging.FileHandler");
        A1F.add("java.rmi.server.UnicastRemoteObject");
        A1F.add("org.springframework.beans.factory.config.PropertyPathFactoryBean");
        A1F.add("org.springframework.aop.config.MethodLocatingFactoryBean");
        A1F.add("org.springframework.beans.factory.config.BeanReferenceFactoryBean");
        A1F.add("org.apache.tomcat.dbcp.dbcp2.BasicDataSource");
        A1F.add("com.sun.org.apache.bcel.internal.util.ClassLoader");
        A1F.add("org.hibernate.jmx.StatisticsService");
        A1F.add("org.apache.ibatis.datasource.jndi.JndiDataSourceFactory");
        A1F.add("org.apache.ibatis.parsing.XPathParser");
        A1F.add("jodd.db.connection.DataSourceConnectionProvider");
        A1F.add("oracle.jdbc.connector.OracleManagedConnectionFactory");
        A1F.add("oracle.jdbc.rowset.OracleJDBCRowSet");
        A1F.add("org.slf4j.ext.EventData");
        A1F.add("flex.messaging.util.concurrent.AsynchBeansWorkManagerExecutor");
        A1F.add("com.sun.deploy.security.ruleset.DRSHelper");
        A1F.add("org.apache.axis2.jaxws.spi.handler.HandlerResolverImpl");
        A1F.add("org.jboss.util.propertyeditor.DocumentEditor");
        A1F.add("org.apache.openjpa.ee.RegistryManagedRuntime");
        A1F.add("org.apache.openjpa.ee.JNDIManagedRuntime");
        A1F.add("org.apache.openjpa.ee.WASRegistryManagedRuntime");
        A1F.add("org.apache.axis2.transport.jms.JMSOutTransportInfo");
        A1F.add("com.mysql.cj.jdbc.admin.MiniAdmin");
        A1F.add("ch.qos.logback.core.db.DriverManagerConnectionSource");
        A1F.add("org.jdom.transform.XSLTransformer");
        A1F.add("org.jdom2.transform.XSLTransformer");
        A1F.add("net.sf.ehcache.transaction.manager.DefaultTransactionManagerLookup");
        A1F.add("net.sf.ehcache.hibernate.EhcacheJtaTransactionManagerLookup");
        A1F.add("ch.qos.logback.core.db.JNDIConnectionSource");
        A1F.add("com.zaxxer.hikari.HikariConfig");
        A1F.add("com.zaxxer.hikari.HikariDataSource");
        A1F.add("org.apache.cxf.jaxrs.provider.XSLTJaxbProvider");
        A1F.add("org.apache.commons.configuration.JNDIConfiguration");
        A1F.add("org.apache.commons.configuration2.JNDIConfiguration");
        A1F.add("org.apache.xalan.lib.sql.JNDIConnectionPool");
        A1F.add("com.sun.org.apache.xalan.internal.lib.sql.JNDIConnectionPool");
        A1F.add("org.apache.commons.dbcp.cpdsadapter.DriverAdapterCPDS");
        A1F.add("org.apache.commons.dbcp.datasources.PerUserPoolDataSource");
        A1F.add("org.apache.commons.dbcp.datasources.SharedPoolDataSource");
        A1F.add("com.p6spy.engine.spy.P6DataSource");
        A1F.add("org.apache.log4j.receivers.db.DriverManagerConnectionSource");
        A1F.add("org.apache.log4j.receivers.db.JNDIConnectionSource");
        A1F.add("net.sf.ehcache.transaction.manager.selector.GenericJndiSelector");
        A1F.add("net.sf.ehcache.transaction.manager.selector.GlassfishSelector");
        A1F.add("org.apache.xbean.propertyeditor.JndiConverter");
        A1F.add("org.apache.hadoop.shaded.com.zaxxer.hikari.HikariConfig");
        A1F.add("com.ibatis.sqlmap.engine.transaction.jta.JtaTransactionConfig");
        A1F.add("br.com.anteros.dbcp.AnterosDBCPConfig");
        A1F.add("br.com.anteros.dbcp.AnterosDBCPDataSource");
        A1F.add("javax.swing.JEditorPane");
        A1F.add("javax.swing.JTextPane");
        A1F.add("org.apache.shiro.realm.jndi.JndiRealmFactory");
        A1F.add("org.apache.shiro.jndi.JndiObjectFactory");
        A1F.add("org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup");
        A1F.add("org.apache.ignite.cache.jta.jndi.CacheJndiTmFactory");
        A1F.add("org.quartz.utils.JNDIConnectionProvider");
        A1F.add("org.apache.aries.transaction.jms.internal.XaPooledConnectionFactory");
        A1F.add("org.apache.aries.transaction.jms.RecoverablePooledConnectionFactory");
        A1F.add("com.caucho.config.types.ResourceRef");
        A1F.add("org.aoju.bus.proxy.provider.RmiProvider");
        A1F.add("org.aoju.bus.proxy.provider.remoting.RmiProvider");
        A1F.add("org.apache.activemq.ActiveMQConnectionFactory");
        A1F.add("org.apache.activemq.ActiveMQXAConnectionFactory");
        A1F.add("org.apache.activemq.spring.ActiveMQConnectionFactory");
        A1F.add("org.apache.activemq.spring.ActiveMQXAConnectionFactory");
        A1F.add("org.apache.activemq.pool.JcaPooledConnectionFactory");
        A1F.add("org.apache.activemq.pool.PooledConnectionFactory");
        A1F.add("org.apache.activemq.pool.XaPooledConnectionFactory");
        A1F.add("org.apache.activemq.jms.pool.XaPooledConnectionFactory");
        A1F.add("org.apache.activemq.jms.pool.JcaPooledConnectionFactory");
        A1F.add("org.apache.commons.proxy.provider.remoting.RmiProvider");
        A1F.add("org.apache.commons.jelly.impl.Embedded");
        A1F.add("oadd.org.apache.xalan.lib.sql.JNDIConnectionPool");
        A1F.add("oadd.org.apache.commons.dbcp.cpdsadapter.DriverAdapterCPDS");
        A1F.add("oadd.org.apache.commons.dbcp.datasources.PerUserPoolDataSource");
        A1F.add("oadd.org.apache.commons.dbcp.datasources.SharedPoolDataSource");
        A1F.add("oracle.jms.AQjmsQueueConnectionFactory");
        A1F.add("oracle.jms.AQjmsXATopicConnectionFactory");
        A1F.add("oracle.jms.AQjmsTopicConnectionFactory");
        A1F.add("oracle.jms.AQjmsXAQueueConnectionFactory");
        A1F.add("oracle.jms.AQjmsXAConnectionFactory");
        A1F.add("org.jsecurity.realm.jndi.JndiRealmFactory");
        A1F.add("com.pastdev.httpcomponents.configuration.JndiConfiguration");
        A1F.add("com.nqadmin.rowset.JdbcRowSetImpl");
        A1F.add("org.arrah.framework.rdbms.UpdatableJdbcRowsetImpl");
        A1F.add("org.apache.commons.dbcp2.datasources.PerUserPoolDataSource");
        A1F.add("org.apache.commons.dbcp2.datasources.SharedPoolDataSource");
        A1F.add("org.apache.commons.dbcp2.cpdsadapter.DriverAdapterCPDS");
        A1F.add("com.newrelic.agent.deps.ch.qos.logback.core.db.JNDIConnectionSource");
        A1F.add("com.newrelic.agent.deps.ch.qos.logback.core.db.DriverManagerConnectionSource");
        A1F.add("org.apache.tomcat.dbcp.dbcp.cpdsadapter.DriverAdapterCPDS");
        A1F.add("org.apache.tomcat.dbcp.dbcp.datasources.PerUserPoolDataSource");
        A1F.add("org.apache.tomcat.dbcp.dbcp.datasources.SharedPoolDataSource");
        A1F.add("org.apache.tomcat.dbcp.dbcp2.cpdsadapter.DriverAdapterCPDS");
        A1F.add("org.apache.tomcat.dbcp.dbcp2.datasources.PerUserPoolDataSource");
        A1F.add("org.apache.tomcat.dbcp.dbcp2.datasources.SharedPoolDataSource");
        A1F.add("com.oracle.wls.shaded.org.apache.xalan.lib.sql.JNDIConnectionPool");
        A1F.add("org.docx4j.org.apache.xalan.lib.sql.JNDIConnectionPool");
        A02 = Collections.unmodifiableSet(A1F);
    }
}
