package com.facebookpay.form.cell.address;

import X.0qQ;
import X.AnonymousClass7TE;
import X.C10782Ry3;
import X.C41847B3o;
import X.C8027QfH;
import X.Pxe;
import X.Pxg;
import X.SWV;
import android.os.Parcel;
import android.os.Parcelable;
import com.facebook.common.locale.Country;
import com.facebookpay.common.recyclerview.adapteritems.SelectionShippingAddressItem;
import com.facebookpay.form.cell.CellParams;
import com.facebookpay.form.model.AddressFormFieldsConfig;
import com.facebookpay.logging.LoggingContext;
import com.google.common.collect.ImmutableList;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public final class AddressCellParams extends CellParams {
    public static final Parcelable.Creator CREATOR = SWV.A00(58);
    public boolean A00;
    public boolean A01 = true;
    public final int A02;
    public final int A03;
    public final int A04;
    public final int A05;
    public final int A06;
    public final int A07;
    public final int A08;
    public final int A09;
    public final int A0A;
    public final int A0B;
    public final int A0C;
    public final Country A0D;
    public final AddressFormFieldsConfig A0E;
    public final LoggingContext A0F;
    public final ImmutableList A0G;
    public final ImmutableList A0H;
    public final String A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final String A0M;
    public final String A0N;
    public final String A0O;
    public final String A0P;
    public final String A0Q;
    public final List A0R;
    public final Map A0S;
    public final boolean A0T;
    public final boolean A0U;
    public final boolean A0V;
    public final boolean A0W;
    public final boolean A0X;
    public final boolean A0Y;
    public final boolean A0Z;
    public final boolean A0a;
    public final String A0b;

    public final int describeContents() {
        return 0;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        0qQ.A0B(parcel, 0);
        super.writeToParcel(parcel, i);
        parcel.writeString(this.A0I);
        parcel.writeString(this.A0K);
        parcel.writeString(this.A0M);
        parcel.writeString(this.A0Q);
        parcel.writeString(this.A0L);
        parcel.writeParcelable(this.A0D, i);
        parcel.writeString(this.A0N);
        parcel.writeString(this.A0O);
        parcel.writeString(this.A0P);
        parcel.writeParcelable(this.A0E, i);
        parcel.writeInt(this.A0Y ? 1 : 0);
        parcel.writeInt(this.A05);
        parcel.writeInt(this.A06);
        parcel.writeInt(this.A09);
        parcel.writeInt(this.A0A);
        parcel.writeInt(this.A07);
        parcel.writeInt(this.A0B);
        parcel.writeInt(this.A03);
        parcel.writeInt(this.A08);
        parcel.writeInt(this.A0C);
        parcel.writeInt(this.A04);
        parcel.writeInt(this.A0a ? 1 : 0);
        parcel.writeInt(this.A0W ? 1 : 0);
        parcel.writeInt(this.A0X ? 1 : 0);
        parcel.writeInt(this.A0V ? 1 : 0);
        parcel.writeString(this.A0J);
        parcel.writeList(this.A0H);
        parcel.writeString(this.A0b);
        parcel.writeMap(this.A0S);
        parcel.writeInt(this.A0Z ? 1 : 0);
        parcel.writeParcelable(this.A0F, i);
        parcel.writeInt(this.A01 ? 1 : 0);
        parcel.writeList(this.A0R);
        parcel.writeInt(this.A00 ? 1 : 0);
        parcel.writeInt(this.A02);
        parcel.writeInt(this.A0T ? 1 : 0);
        parcel.writeList(this.A0G);
        parcel.writeInt(this.A0U ? 1 : 0);
    }

    public AddressCellParams(Parcel parcel) {
        super(parcel);
        this.A0I = parcel.readString();
        this.A0K = parcel.readString();
        this.A0M = parcel.readString();
        this.A0Q = parcel.readString();
        this.A0L = parcel.readString();
        this.A0D = (Country) C41847B3o.A03(parcel, Country.class);
        this.A0N = parcel.readString();
        this.A0O = parcel.readString();
        this.A0P = parcel.readString();
        AddressFormFieldsConfig addressFormFieldsConfig = (AddressFormFieldsConfig) C41847B3o.A03(parcel, AddressFormFieldsConfig.class);
        if (addressFormFieldsConfig != null) {
            this.A0E = addressFormFieldsConfig;
            this.A0Y = Pxg.A1U(parcel);
            this.A05 = parcel.readInt();
            this.A06 = parcel.readInt();
            this.A09 = parcel.readInt();
            this.A0A = parcel.readInt();
            this.A07 = parcel.readInt();
            this.A0B = parcel.readInt();
            this.A03 = parcel.readInt();
            this.A08 = parcel.readInt();
            this.A0C = parcel.readInt();
            this.A04 = parcel.readInt();
            this.A0a = Pxg.A1U(parcel);
            this.A0W = Pxg.A1U(parcel);
            this.A0X = Pxg.A1U(parcel);
            this.A0V = Pxg.A1U(parcel);
            this.A0J = parcel.readString();
            ArrayList A1C = AnonymousClass7TE.A1C();
            Pxe.A1O(parcel, Integer.TYPE, A1C);
            this.A0H = ImmutableList.copyOf((Collection) A1C);
            this.A0b = parcel.readString();
            HashMap readHashMap = parcel.readHashMap(HashMap.class.getClassLoader());
            this.A0S = !(readHashMap instanceof Map) ? null : readHashMap;
            this.A0Z = Pxg.A1U(parcel);
            this.A0F = (LoggingContext) C41847B3o.A03(parcel, LoggingContext.class);
            this.A01 = Pxg.A1U(parcel);
            ArrayList A1C2 = AnonymousClass7TE.A1C();
            this.A0R = A1C2;
            Pxe.A1O(parcel, SelectionShippingAddressItem.class, A1C2);
            this.A00 = Pxg.A1U(parcel);
            this.A02 = parcel.readInt();
            this.A0T = Pxg.A1U(parcel);
            ArrayList A1C3 = AnonymousClass7TE.A1C();
            Pxe.A1O(parcel, Integer.TYPE, A1C3);
            this.A0G = ImmutableList.copyOf((Collection) A1C3);
            this.A0U = Pxg.A1U(parcel);
            return;
        }
        throw AnonymousClass7TE.A0y();
    }

    public AddressCellParams(C8027QfH qfH) {
        super((C10782Ry3) qfH);
        this.A0I = qfH.A0G;
        this.A0K = qfH.A0I;
        this.A0M = qfH.A0K;
        this.A0Q = null;
        this.A0L = qfH.A0J;
        this.A0D = qfH.A0B;
        this.A0N = qfH.A0L;
        this.A0O = qfH.A0M;
        this.A0P = qfH.A0N;
        this.A0E = qfH.A0C;
        this.A0Y = qfH.A0X;
        this.A05 = qfH.A03;
        this.A06 = qfH.A04;
        this.A09 = qfH.A07;
        this.A0A = qfH.A08;
        this.A07 = qfH.A05;
        this.A0B = qfH.A09;
        this.A03 = qfH.A01;
        this.A08 = qfH.A06;
        this.A0C = qfH.A0A;
        this.A04 = qfH.A02;
        this.A0a = qfH.A0a;
        this.A0W = qfH.A0V;
        this.A0X = qfH.A0W;
        this.A0V = qfH.A0U;
        this.A0J = qfH.A0H;
        this.A0H = qfH.A0F;
        this.A0b = qfH.A0O;
        Map map = qfH.A0Q;
        this.A0S = map == null ? null : map;
        this.A0Z = qfH.A0Y;
        this.A0F = qfH.A0D;
        this.A01 = qfH.A0Z;
        this.A0R = qfH.A0P;
        this.A00 = qfH.A0S;
        this.A02 = qfH.A00;
        this.A0T = qfH.A0R;
        this.A0G = qfH.A0E;
        this.A0U = qfH.A0T;
    }
}
