package com.facebook.graphql.enums;

import X.0sc;
import java.util.HashSet;
import java.util.Set;

public final class GraphQLUserVerificationScreenSet {
    public static final HashSet A00 = 0sc.A05(new String[]{"ADS_SUCCESS", "FAILURE", "INTRODUCTION", "PENDING", "PENDING_MANUAL_REVIEW", "REQUEST_ADDRESS", "REQUEST_CC_CVV", "REQUEST_CC_FIRST_SIX", "REQUEST_DATE_OF_BIRTH", "REQUEST_DATE_OF_BIRTH_AND_ADDRESS", "REQUEST_FULL_SSN", "REQUEST_ID_UPLOAD", "REQUEST_LEGAL_NAME", "REQUEST_NAME_AND_DATE_OF_BIRTH", "REQUEST_NAME_AND_DATE_OF_BIRTH_AND_ADDRESS", "REQUEST_NAME_AND_DATE_OF_BIRTH_AND_SSN_LAST_FOUR_AND_ADDRESS", "REQUEST_NATIONAL_ID", "REQUEST_SSN_LAST_FOUR", "REQUEST_VERIFICATION_DOCUMENT", "SUCCESS"});

    public static final Set getSet() {
        return A00;
    }
}
