package com.facebook.graphql.enums;

import X.0sc;
import X.AnonymousClass7TF;
import java.util.HashSet;
import java.util.Set;

public final class GraphQLStructuredSurveyCustomQuestionTypeSet {
    public static final HashSet A00;

    static {
        String[] strArr = new String[48];
        System.arraycopy(new String[]{"ISP_DETECTION", "LANGUAGE_DYNAMIC_CANDIDATES", "LANGUAGE_DYNAMIC_CANDIDATES_CAPS_RM_LAUNCH", "LANGUAGE_DYNAMIC_CANDIDATES_TOP_N_BLP", "LANGUAGE_DYNAMIC_CANDIDATES_TOP_N_PER_COUNTRY", "LANGUAGE_DYNAMIC_CANDIDATES_TOP_N_PER_REGION", "LOP_NOTIFICATION", "MARKETPLACE_NOTIFICATION", "MESSENGER_CONTACT_TYPEAHEAD_RANDOM", "NOTIFICATION", "PHONE_AND_EMAIL", "PROFILE_PIC", "PUBLIC_ENTITY_TYPEAHEAD_RANDOM", "SMILEY_RATING", "SOLUTION_ENG_FOCUS_ACCOUNT_SELECTOR", "TAB_BAR_BASE", "TAB_BAR_INTRO", "TASK_TITLE", "UNIVERSAL_FEEDBACK", "UNIVERSAL_FEEDBACK_TEXT", "WORKFORCE_PRODUCTION_FEEDBACK_CONTROLLER"}, AnonymousClass7TF.A1X(new String[]{"AYMF_RECOMMENDATION_QUALITY", "BUFF_RECOMMENDATION_QUALITY", "BUSINESS_MANAGER_SELECTOR", "CARRIER_DETECTION", "CARRIER_DETECTION2", "CITY_WITH_FIVE_CANDIDATES_PIPED_MULTIPLE_CHOICE", "DATA_FETCHER", "DATE", "DATE_OF_BIRTH", "EMAIL_ADDRESS", "EVENTS_PAGE_SELECTOR", "FB_REACTION", "FRIEND_DISTANCE_MAX_DIFF", "FRIEND_GRAPH_MANAGEMENT", "FRIEND_GRAPH_MANAGEMENT_END_PAGE", "FRIEND_TYPEAHEAD_RANDOM", "GROUP_SELECTOR", "HOME_CITY_PIPED", "HOME_CITY_WITH_FIVE_CANDIDATES_PIPED", "HOME_COUNTRY_PIPED", "HOME_ZIPCODE", "INSTANT_ARTICLE_CREATOR_STUDIO_IN_PRODUCT_DISATISFIED_ADS_FUNCTIONALITIES", "INSTANT_ARTICLE_CREATOR_STUDIO_IN_PRODUCT_DISATISFIED_ORGANIC_FUNCTIONALITIES", "INSTANT_ARTICLE_CREATOR_STUDIO_IN_PRODUCT_OTHER_THOUGHTS", "INSTANT_ARTICLE_CREATOR_STUDIO_IN_PRODUCT_SATISFACTION", "INSTANT_ARTICLE_CREATOR_STUDIO_IN_PRODUCT_USEFUL_FUNCTIONALITIES", "INSTANT_ARTICLE_ORGANIC_CREATOR_STUDIO_IN_PRODUCT_SATISFACTION"}, strArr) ? 1 : 0, strArr, 27, 21);
        A00 = 0sc.A05(strArr);
    }

    public static final Set getSet() {
        return A00;
    }
}
