package com.instagram.model.reels;

import X.0oU;
import X.0qQ;
import X.C376399Hv;
import android.os.Parcel;
import android.os.Parcelable;

public enum ReelHeaderAttributionType implements Parcelable {
    APP_ATTRIBUTION,
    AREFFECT_PREVIEW_ATTRIBUTION,
    AVATAR_STICKER_ATTRIBUTION,
    AUDIENCE_LISTS_ATTRIBUTION,
    BLOKS_ATTRIBUTION,
    CAMERA_FORMAT_ATTRIBUTION,
    CAMPFIRE_ATTRIBUTION,
    CAMPFIRE_SELF_VIEW_ATTRIBUTION,
    CANVAS_ATTRIBUTION,
    CLIPS_ATTRIBUTION,
    CLIPS_FULL_SCREEN_RESHARE_ATTRIBUTION,
    CLIPS_RESHARE_ATTRIBUTION,
    CLOSE_FRIENDS_ATTRIBUTION,
    CHANNEL_CHALLENGE_ATTRIBUTION,
    CUTOUT_ANYTHING_ATTRIBUTION,
    EFFECT_ATTRIBUTION,
    GALLERY_GRID_FORMAT_ATTRIBUTION,
    GEN_AI_DETECTION_ATTRIBUTION,
    GEN_AI_STICKER_ATTRIBUTION,
    GROUP_PROFILE_ATTRIBUTION,
    GROUP_REEL_ATTRIBUTION,
    HIGHLIGHTS_ATTRIBUTION,
    INTERNAL_ATTRIBUTION,
    SHARE_TO_FRIENDS_STORY_ATTRIBUTION,
    MAGIC_MOD_ATTRIBUTION,
    MEMORIES_ATTRIBUTION,
    MESSAGE_SHARE_ATTRIBUTION,
    META_AI_ATTRIBUTION,
    MULTIPLE_LISTS_ATTRIBUTION,
    MUSIC_ATTRIBUTION,
    PERSISTED_REEL_ATTRIBUTION,
    POLAROID_STICKER_ATTRIBUTION,
    SECRET_STICKER_ATTRIBUTION,
    RESHARED_REEL_ATTRIBUTION,
    RESHARE_ATTRIBUTION,
    ROLL_CALL_FIRST_TAKE,
    ROLL_CALL_TIMEBOX,
    SPONSORED_TAG_ATTRIBUTION,
    STATE_SPONSORED_MEDIA_LABEL_ATTRIBUTION,
    STORY_TEMPLATE_ATTRIBUTION,
    IMAGINE_TEMPLATE_ATTRIBUTION,
    SUGGESTED_REEL_ATTRIBUTION,
    TRANSLATION_ATTRIBUTION,
    UNLOCKABLE_STICKER,
    VIDEO_CALL_ATTRIBUTION,
    WEARABLE_ATTRIBUTION,
    HORIZON_WORLDS_ATTRIBUTION,
    META_QUEST_ATTRIBUTION,
    SUPERLATIVE,
    PUBLISHED_SUPERLATIVE,
    STORIES_TEASER,
    EXPLORE_SHAREABLE_GRID,
    STORY_SNAPSHOT,
    PUBLIC_COLLECTION,
    ICONIC_ENTRYPOINTS,
    BARCELONA_SHARE,
    QUICKSNAP_RECAP;
    
    public static final Parcelable.Creator CREATOR = null;

    public final int describeContents() {
        return 0;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        0qQ.A0B(parcel, 0);
        parcel.writeString(name());
    }

    /* access modifiers changed from: public */
    static {
        ReelHeaderAttributionType[] reelHeaderAttributionTypeArr;
        A00 = 0oU.A00(reelHeaderAttributionTypeArr);
        CREATOR = new C376399Hv(41);
    }
}
